### ISSUE TITLE
Fix Viewer.destroy() exception after using DistanceMeasurementsPlugin

### ISSUE THREAD

**Issue by MathiasTribia** [xeokit/xeokit-sdk#1001]
**Describe the bug**
The viewer throws a null error when calling viewer.destroy if a measurement has been created while using the viewer. The measurement doesn't have to exist when the viewer is destroyed. Creating a measurement, then removing it, then destroying will still throw an error.

**To Reproduce**
1. Open up a viewer with the DistanceMeasurementsPlugin  added
2. Activate the measurement tool: DistanceMeasurementsPlugin.control.activate()
3. Click on two points to create a measurement
4. Deactivate the plugin controls: DistanceMeasurementsPlugin.control.deactivate()
5. Call the Viewer's destroy function
6. Exception is thrown

**Expected behavior**
Expected Viewer to gracefully destroy itself.

**Screenshots**
Screenshot is taken using the latest pull of xeokit-bim-viewer v2.4.8 with xeokit-sdk v2.3.1. But I've also tested this on a different setup which uses xeokit-sdk v2.3.9, and the error occurs on both. The _plugins[0] here is the DistanceMeasurementsPlugin I added in the BIMViewer.js constructor.

![image](https://user-images.githubusercontent.com/58598047/217569067-8537ca52-6cf1-415c-9b28-5beb55c8ee77.png)

![image](https://user-images.githubusercontent.com/58598047/217570811-613ea7ec-cb41-43ed-8f5e-6ee0b29f19ab.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome, Firefox]
 - Version [2.3.1, 2.3.9]

**Additional context**
I haven't investigated too deeply into the issue, but I noticed that the DistanceMeasurement object was still added to the viewer.scene._ownedComponents object even after being removed.

**Comment by xeolabs** [comment]
Thanks @MathiasTribia - issue was caused by measurement destructors assuming that the application-provided container element still existed 👍
