### ISSUE TITLE
Show names instead of IfcBuildingStorey with export from freecad

### ISSUE THREAD

**Issue by bewegende-Architektur** [xeokit/xeokit-sdk#1002]
Hey there :)

i am trying to host ifc-models exported from freecad. The goal is to use the TreeViewPlugin to organize the model in stories. The model is organized correctly but the name of each storey is "IfcBuildingStorey". I have also tried to change the hierarchy to containment or types:

```
    new TreeViewPlugin(viewer, {
        containerElement: document.getElementById("treeViewContainer"),
        autoExpandDepth: 4, // Initially expand the root tree node
        hierarchy: "stories"
    });
```
When taking a look at the example "TreeViewPlugin_Storeys", it looks like it is possible to show the name of the storey instead. What is the trick to do so? It would also be ok to split my model in containers. How does this organization in containers needs to be exported from freecad?

Thanks in advance!

Greetings,
Chris

**Comment by xeolabs** [comment]
Hi Chris,

The `TreeViewPlugin` should be just deriving the title from the `name` property belonging to the xeokit MetaObject that represents the IfcBuildingStorey.

So, if you're importing your IFC model by converting it to XKT using our CLI tools, then the XKT will contain a metaobject for each IfcBuildingStorey, which will have the name of that storey as given in the IFC. 

For example, when we convert the Duplex IFC test model to XKT, the XKT contains JSON metaobjects like this one:

````json
 {
      "CassiopAttr": "LOCAL 01-01-0115-01-0001",
      "CassiopOid": "129779903",
      "elevation": "3.10000000000038",
      "extid": "57c75e1d88d4ac141bdc2cd845b47569",
      "name": "Level 2",
      "type": "IfcBuildingStorey",
      "uuid": "1xS3BCk291UvhgP2dvNMQJ",
      "parent": "1xS3BCk291UvhgP2a6eflK",
      "id": "1xS3BCk291UvhgP2dvNMQJ"
    },
````
    
    Then when we load that using `XKTLoaderPlugin`, a `TreeViewPlugin` will be able to show the title for this IfcBuildingStorey's node as "Level 2".  

I'll close for now and re-open if you're still having an issue.
Cheers
