### ISSUE TITLE
 Measurement created on both left click and right click...possible to limit?

### ISSUE THREAD

**Issue by wbste** [xeokit/xeokit-sdk#1004]
Hi!

Currently have the `DistanceMeasurementsPlugin` working pretty well, but there seems to be an issue with the interactive bit (as shown in Example 2 [here](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsPlugin.js~DistanceMeasurementsPlugin.html).

When attempting to create a new measure, it will create on **both** left-click and right-click. This causes an issue when you enable a context menu.

Is it possible to define what button should be pressed on the mouse, such that a new measurement will only start (and end) on left click, for example?

---

**Comment by xeolabs** [comment]
Marking this one as a bug because the measurement plugins are only supposed to create measurements on left-click.

**Comment by xeolabs** [comment]
This is now fixed in the latest release.
