### ISSUE TITLE
On pick magnetism effect

### ISSUE THREAD

**Issue by assaad977** [xeokit/xeokit-sdk#1008]
**Describe the solution you'd like**
The solution that I'm imagining (or the feature), is that the user should be able when he is measuring a distance or an angle, to have a magnetism effect on the cursor, in such a way if the cursor gets close to the corners of the 3D object, it would automatically position the cursor in the closest corner.

**Additional context**
Xeokit-sdk is used by our company to provide to the user a simplified, easy to use 3D viewer.

**Comment by tmarti** [comment]
@assaad977: something like #1062? 🙂

**Comment by Kurtil** [comment]
I think this issue should be closed now :) @xeolabs
