### ISSUE TITLE
Error When Loading ifc files

### ISSUE THREAD

**Issue by sabermed** [xeokit/xeokit-sdk#1009]
**Describe the bug**
when upload some ifc files the model is not fully loaded it just appear and the loading animation still there so i can't interact with the model or do anything and i can see some errors in the console.

**Expected behavior**
atleast if some mesh are not support or i don't know why remove the loader so we can interact with the model.

**Desktop:**
 - OS: Windows 10 64-bit
 - Browser: Opera
 - Version: 96.0.4693.117

**Screenshots**
![Capture d’écran 2023-03-23 173232](https://user-images.githubusercontent.com/55387718/227274923-dd24f6ed-c6f1-4bc9-8f4e-8aa9f0cc8316.png)

**Comment by xeolabs** [comment]
Hi, closing for now, but will re-open if you find it's still happening with the latest release. If so, please also attach an IFC file we can reproduce the issue with. Thanks
