### ISSUE TITLE
Is there a reason to use the relative path instead of the node_module?

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1011]
**Describe the bug**
Is there a reason to use the relative path instead of the node_module path here https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/GLTFLoaderPlugin/GLTFVBOSceneModelLoader.js#L6 ?

On our fork, we use the src files and not the dist and the relative path is broken when xeokit is not the top-level package.
It works flawlessly when using 
```javascript
import {parse} from '@loaders.gl/core/dist/esm/index.js';
```

**Comment by xeolabs** [comment]
No that path shouldn't be like that. It should resolve to the package in the standard way - if you could make a PR, I'll merge that immediately.

**Comment by Amoki** [comment]
Fixed by https://github.com/xeokit/xeokit-sdk/pull/1015
