### ISSUE TITLE
XKTLoaderPlugin not override defaults types

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1023]
Have a IFC model converted to XKT and IfcPlate has opactity but not has in IFC file.
https://github.com/xeokit/xeokit-sdk/blob/02576b0be6dec9c4d8fc0f45bd408d4ffc05e449/src/plugins/XKTLoaderPlugin/parsers/ParserV10.js#L521-L531
It's because _**meshDefaults**_ in `utils.apply` must be in second place. There are several such places.
It's correct?
#659 maybe related.

**Comment by xeolabs** [comment]
Likely fixed by : https://github.com/xeokit/xeokit-sdk/issues/1154
I'll re-open if you're still experiencing this issue.
