### ISSUE TITLE
[💡DataTextures]: idea for smart deferred flags update

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#1033]
## Description: batched visibility updates today

In the context of `DataTextureSceneModel`, there is a mechanism that allows to do batched updates of all per-object attributes (flags, offsets, colors, ...).

This especially useful when applying dynamic filters to mid/big-size converted IFC files.

The mechanism works in this way today:

```js
// we want to batch-update the visible attributes for many objects
// this snippet makes sure 
{
    // here, we start a "batch transaction"
    dataTextureSceneModel.beginDeferredFlagsInAllLayers ();

    // and we update the visibility attributes/flags of a huge number of objects
    updateLotsOfObjectsAttributes();

    // finally, we commit in batched mode
    dataTextureSceneModel.commitDeferredFlagsInAllLayers()
}
```

## The problem

The problem with this mechanism, even tough it allows for really fast batch-updates, is that we must remember to call:

- `DataTextureSceneModel::beginDeferredFlagsInAllLayers`: before doing the updates
- `DataTextureSceneModel::commitDeferredFlagsInAllLayers`: after doing the updates

So, the responsibility to call the `begin` / `commit` methods is moved to the xeokit-sdk consuming side.

If we as xeokit-sdk users do the mass updates without invoking the `begin` / `commit` methods, the batched mechanism does not kick-in and this cancels any posibble benefit from batching updates, with a **big** peformance penalty.

## 💡 The proposed enhancement

The batched mechanism could behave in a smart way, in the `TrianglesDataTextureLayer` level.

- if there are less than N number of update operations in the current frame-number, do them directly
- if there are more than N number of update operations, let the batched-update mechanism kick-in automatically

(N could be some fixed number like 10 or 20)

This would allow to enjoy the benefit of batched updates in a totally transparent way to the xeokit-sdk consumer.

**Comment by tmarti** [comment]
@xeolabs you can assign this to me 🙂, as I'm interested that this one moves fast

**Comment by xeolabs** [comment]
@tmarti yip! Sounds good

**Comment by tmarti** [comment]
Solved by https://github.com/xeokit/xeokit-sdk/pull/1037
