### ISSUE TITLE
[question]: ¿isn't `SAO` really supported by Safari?

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#1034]
While working on `SAO` support for data-textures, noticed this line of code:

https://github.com/xeokit/xeokit-sdk/blob/f6bba419a2b450130fc545cc4ee8dab0c1907582/src/viewer/scene/postfx/SAO.js#L180-L182

This check disables `SAO` if the detected browser is Safari.

But, tried to ignore the check, and then tested with a recent version of Safari browser.

And, `SAO` seems to just work well!

Is there some historical reason for that check? Maybe Safari could now just be considered for `SAO` support as well as the rest of browsers?

**Comment by tmarti** [comment]
PS: since Apple realeased support for WebGL-v2 around 1 year ago, Safari seems to support quite well all those facy shaders I've played with in data-textures😍

**Comment by xeolabs** [comment]
Let's go ahead and remove that check for now - that was a workaround for an IoS problem some time back

**Comment by tmarti** [comment]
Solved by https://github.com/xeokit/xeokit-sdk/pull/1038
