### ISSUE TITLE
Handle IFC parsing errors in WebIFCLoaderPlugin 

### ISSUE THREAD

**Issue by PupoSDC** [xeokit/xeokit-sdk#1054]
**Describe the bug**

When loading incompatible IFC files some errors are not caught and dispatched to the `onSceneLoadError` handler.

**To Reproduce**

- load a incompatible / broken IFC. Example 

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION (('ArchiCAD 9.00 Release 1 generated IFC file.', 'Build Number of the Ifc 200 interface: 01038 (30-06-2004)\X\0A'), '2;1');
FILE_NAME ('0001.4211.situation.ifc', '2018-09-07T19:59:28', ('Architect'), ('Building Designer Office'), 'PreProc - IFC Toolbox Version 2.0 (99/07/01)', 'Macintosh System', 'The authorising person.');
FILE_SCHEMA (('IFC20_LONGFORM'));
ENDSEC;
DATA;
#2 = IFCDIRECTION ((0., 1., 0.));
#6 = IFCPERSON ('FamilyName', $, $, $, $, (), ());
#7 = IFCORGANIZATION ('OrganizationName', (), (), $);
#8 = IFCORGANIZATION ('Graphisoft', (), (), $);
#9 = IFCAPPLICATION ('ArchiCAD', 'ArchiCAD 8.0 (Graphisoft)', '8.0', #8);
#10 = IFCPERSONANDORGANIZATION (#6, #7, ());
#11 = IFCTRANSACTION (1536343158, #10, #9);
#12 = IFCAUDITTRAIL (1536343158, $, #10, $, #9, $, (#11));
#14 = IFCSIUNIT (*, .LENGTHUNIT., $, .METRE.);
#15 = IFCSIUNIT (*, .AREAUNIT., $, .SQUARE_METRE.);
#16 = IFCSIUNIT (*, .VOLUMEUNIT., $, .CUBIC_ME
```

- The error blows up in the console, without triggering `onSceneLoadError`

**Expected behavior**

The errors should be caught and dispatched via `onSceneLoadError`

**Additional context**

We fixed the problem by wrapping the entirety of the [_parseModel](https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/WebIFCLoaderPlugin/WebIFCLoaderPlugin.js#L645-L734) invocation in a try catch that calls ` sceneModel.fire("error", parsingError);` if an error is caught.

**Comment by xeolabs** [comment]
@PupoSDC your fix sounds like a good plan - could you make a PR?

**Comment by PupoSDC** [comment]
yes. I will try to do it this week still.
