### ISSUE TITLE
Initial camara when initializing the web and when selecting parts

### ISSUE THREAD

**Issue by Jongonzale** [xeokit/xeokit-sdk#1055]
When I charge an IFC file of the SDK examples, it initializes in a good way, but when I charge an IFC from other places, the intial camara startes so far, it only sees a little point in the viewer. How can I solve that?

Also, when I charge my IFC file, when I select a part of my complete piece in the treeview navigation, some of the pieces can't see because the camara zooms too much, and the camara passes the part or I can only see the middle part. I try to change that in the "nodeTitleClicked" part, changing the viewer.cameraFlisht.flyTo method, but if I change something the zoom doesn't work well. How can I do to do the same as now but only zooming a little bit less?

**Comment by xeolabs** [comment]
Sorry, can't understand what the issue here, must close until we have an issue that we can reproduce.

AFAIK CameraFlightAnimation.flyTo is working well for our users, but if you can reproduce a problem we need to fix, we'll get onto it.
