### ISSUE TITLE
The unShowNode method of the TreeViewPlugin

### ISSUE THREAD

**Issue by Jongonzale** [xeokit/xeokit-sdk#1061]
I'm trying to use that method with the treeviewplugin. When I select one part of the 3d object it works well, so the showNode method is working well, but when I select a second one, it select well in the treeview, but the first one chosen is not 'collapsed' in the tre view, so every time I pick a new one it opens in the treeview, without closing the previous ones, doing the treeview so large. How can i solve that?
I have used it like this: 
![image](https://github.com/xeokit/xeokit-sdk/assets/90178730/18cbdfdb-99b1-4726-8e10-6c005a1cf10e)

**Comment by xeolabs** [comment]
I think the most robust solution would be to call `treeView.collapse()` after calling `treeView.unshowNode()`.

If we were to make `unshowNode()` always collapse the target node, then for consistent tree state, that would need to have the same behaviour anyway.
