### ISSUE TITLE
Show measurements and annotations in snapshots

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#1064]
Add new `Viewer.getSnapshotWithPlugins()` method, which includes the HTML elements belonging to plugins in snapshots.

To include its HTML elements in one of these snapshots, a plugin must now have a `getContainerElement()` method that returns a single HTML element that contains all its HTML elements. 

Therefore, this update also adds a `getContainerElement()` to `DistanceMeasurementsPlugin`, `AngleMeasurementsPlugin`, and `AnnotationsMeasurementsPlugin`, to include them in snapshots. Note that we can make all plugins use the same container element, for simplicity. 

## Example

* [Run demo](https://xeokit.github.io/xeokit-sdk/examples/#screenshots_png_getSnapshot_withMeasurements)

[Screencast from 01.06.2023 01:26:15.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/7a95f326-4ed4-4eba-a09e-6b48ef6cc12b)

## Usage

````javascript
const viewer = new Viewer({
    canvasId: "myCanvas",
    transparent: true, // Default
    preserveDrawingBuffer: true // Default - needed true for canvas screenshots
});

//...

const distanceMeasurements = new DistanceMeasurementsPlugin(viewer, {
    container: document.getElementById("measurementsContainer")
});

//...

viewer.getSnapshotWithPlugins({
    format: "png",
    width: img.width * 2, // Upscale snapshot resolution 2x
    height: img.height * 2

}).then((imageData) => {
    const img = new Image();
    img.src = imageData;
    document.body.appendChild(img);
});
````

## Implementation Notes

Internally, this method works by capturing the pixels of the WebGL2 canvas to a separate HTMLCanvas  (using gl.readPixels), then using `html2canvas` to render the HTML container element of each installed `Viewer` plugin to that HTMLCanvas, which it then saves to a bitmap using `canvas2image`.

Using `gl.readPixels`, instead of just using `html2canvas` to grab everything (WebGL2 canvas + plugin containers) in one shot, enables us to properly control the resolution of the renderer's output when getting a custom-sized snapshot.

**Comment by Amoki** [comment]
https://github.com/niklasvh/html2canvas is great for this

**Comment by xeolabs** [comment]
Possible strategy:

- Extend `Viewer.getSnapshot`:
  - 1. For each plugin that is configurable with a container DIV, use `html2canvas` to render it to a canvas element
  - 2. Get snapshot of WebGL canvas
  - 3. Combine the snapshots of (1) and (2), and/or have option for `Viewer.getSnapshot()` to return them as separate bitmaps for caller to handle their combination/presentation
