### ISSUE TITLE
Rotate an GLTF after loading it.

### ISSUE THREAD

**Issue by antoniohof** [xeokit/xeokit-sdk#1067]
Hi, I'm trying to rotate an .gltf after loading it, but can't find the proper way to do it.

I can only load it using the  GLTFLoaderPlugin,
is there a way to get a Mesh when loading with GLTFLoaderPlugin?

When I try to load it using the parseGLTFIntoXKTModel, it gives out a texture error: "Basis Universal Supercompressed GPU Texture encoder Error"

Is this the right way?
```

`utils.loadArraybuffer(this.url, async (gltf) => {
        const xktModel = new XKTModel();

        parseGLTFIntoXKTModel({
          data: gltf,
          xktModel,
          log: (msg) => {
            console.log('log', msg);
          },
        }).then(
          () => {
            console.log('model loaded!', xktModel);
            xktModel.finalize();

            const buffer = writeXKTModelToArrayBuffer(xktModel);

            const xktLoader = new XKTLoaderPlugin(viewer);

            const modelNode = xktLoader.load({
              id: 'myModel',
              xkt: buffer,
            });
            modelNode.on('loaded', (loaded) => {
              console.log('xkt loaded', loaded);
              resolve(viewer.scene.models.myModel);
            });
          }
```

**Comment by xeolabs** [comment]
This feature is coming in the next release, but is now pre-released in the latest alpha release on npm.

We have some low-level examples here, where we update `position` and `rotation` properties on the `SceneModel`, which do what you need:

* https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#repositioning_vbo_instancing
* usage here: https://github.com/xeokit/xeokit-sdk/blob/master/examples/scenemodel/repositioning_vbo_instancing.html
