### ISSUE TITLE
Unload and reload a model makes the viewer laggy

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#107]
```
this.model.destroy();
this.model = this.gltfLoader.load({
    gltf: this.gltf,
    edges: true
});
// n times
```
Unloading and reloading the same model as above makes the viewer very laggy. The memory does not seem to be free.

<img width="773" alt="Screenshot 2019-07-11 at 10 26 02" src="https://user-images.githubusercontent.com/22523482/61034847-523b9780-a3c6-11e9-9092-7ba5055da8d0.png">

Attached, the chrome performance reccording when unload/reload model mutltiple times.

**Comment by xeolabs** [comment]
This one would be a priority fix, I'll get on it at the start of next week. Are you able to determine what memory is not being released?

**Comment by Kurtil** [comment]
I have no idea...

**Comment by Amoki** [comment]
@Kurtil, this bug is solved somehow, no?

**Comment by Kurtil** [comment]
@Amoki, It seems to be indeed.
