### ISSUE TITLE
Feature: Cursor snap-to-vertex and snap-to-edge

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#1070]
See PR: [WIP: [DataTextures]: snap-to-vertex functionality #1062](https://github.com/xeokit/xeokit-sdk/pull/1062)

## snap-to-vertex

https://github.com/xeokit/xeokit-sdk/assets/2405414/a66ed73d-d3fb-40eb-9fb3-9c3127a0ede7

## snap-to-edge

https://github.com/xeokit/xeokit-sdk/assets/2405414/d2556bbf-62b4-41be-97c2-0d16e92d4f03

**Comment by jenbuzz** [comment]
Hi, is this feature finalized yet?

I tried the latest alpha version locally and also the example you have online. It doesn't seem to work quite as I expected. It doesn't really snap at the correct positions. Zooming in seems to mke it worse or at least not better. I would expect zooming as a mechanism to help snap at the correct position.

I'm using Chrome btw.

**Comment by xeolabs** [comment]
Hi @jenbuzz this feature is still in development and is not released yet - these examples/screenshots are work-in-progress and we're expecting them to show bugs as we refine the algorithm.

**Comment by Kurtil** [comment]
I think this issue should be closed now :) @xeolabs
