### ISSUE TITLE
Question: Is possible to search the entity, knowking only the name/title of it?

### ISSUE THREAD

**Issue by Jongonzale** [xeokit/xeokit-sdk#1072]
Hi,

I'm trying to do a little menu with personalized names taken from an excel, where I only have the new name and the name/title of the pieces. It's possible in some way, only having the title, to take the entity it represents, so like that we can take the ObjectId and work with that for the visualization?

Thanks

**Comment by xeolabs** [comment]
No sorry. You can only look up the entity using its ID. What you could do though is maintain your own map of entity names, which you could rebuild whenever each model is loaded or unloaded, then use that search for them. Hope that helps.
