### ISSUE TITLE
the cdn links  not working anymore  if you tried to access them it will give you that it is not find 

### ISSUE THREAD

**Issue by khalidfathy1** [xeokit/xeokit-sdk#1073]
![image](https://github.com/xeokit/xeokit-sdk/assets/122186840/ad9d3b84-b7cf-43cf-ad02-bf252862df5f)

**Comment by Amoki** [comment]
The URL is not valid, you must either use https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk/dist/xeokit-sdk.min.es.js or https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk

If you want something else than ES, here is the full list of available files: 
web-ifc.wasm  xeokit-sdk.cjs.js  xeokit-sdk.es5.js  xeokit-sdk.es.js  xeokit-sdk.min.cjs.js  xeokit-sdk.min.es5.js  xeokit-sdk.min.es.js

**Comment by khalidfathy1** [comment]
first thank you for replying but  both are not working 
![image](https://github.com/xeokit/xeokit-sdk/assets/122186840/6ec8f3f4-0a8e-418a-8e52-c2290f73562e)
![image](https://github.com/xeokit/xeokit-sdk/assets/122186840/52d6638f-09be-48d7-9810-8da85ea966d0)

**Comment by Amoki** [comment]
Both links work on my side. Do you have access to https://cdn.jsdelivr.net ?

**Comment by khalidfathy1** [comment]
No, I can't access it anymore, although I was using it and it was working perfectly.

**Comment by khalidfathy1** [comment]
look when i try to browse from google this what i find
![image](https://github.com/xeokit/xeokit-sdk/assets/122186840/77427745-c572-429b-aad3-b432e7e46ead)

**Comment by khalidfathy1** [comment]
okay , thank you for replying

**Comment by xeolabs** [comment]
Just tried on my end as well - looks OK. Thanks for for reporting @khalidfathy1 !

**Comment by khalidfathy1** [comment]
Thank you for replying 🙏
