### ISSUE TITLE
Make picking (and camera navigation) faster by using a 1x1 viewport

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#1076]
Currently, our GPU-assisted picking renders the object pick colors and depths to a full-sized set of buffers, equal to the size of the canvas.

This is wasteful, and I think we would get a noticeable improvement in responsiveness if we instead render pick colors and depths to a 1x1 sized buffer, which would also involve using a custom projection, align the camera along the ray passing through the front plane at the clicked canvas coordinates etc.

 The 1x1 viewpoint technique is currently used in vertex snapping: https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/webgl/Renderer.js#L1358

**Comment by tmarti** [comment]
Check how the clip-space remapping is done in this PR:
- https://github.com/xeokit/xeokit-sdk/pull/1062

Pro-tip: try to avoid using a custom view/projection matrix 🙂, there is a distortion of perspective towards the sides of the camera frustum if you instead try to temporarily set the camera eye/look/up to get a ray algined with the canvas coordinate.

In the mentioned PR, I ended up implementing the clip-space remapping technique (so the shader does not suffer from that perspective distortion).

I'm attenting personal things those days, but in case you're interested I'm looking forward to write a small article about the technique in the PR in some days/weeks 🙂

**Comment by tmarti** [comment]
Further explanation of clip-space remapping: https://github.com/tmarti/graphics-research/blob/main/articles/webgl2-gpu-based-snapping.md#clip-space-remapping

**Comment by Kurtil** [comment]
1x1 picking viewport using clip-space remapping PR is merged. This issue can be closed.
