### ISSUE TITLE
Question: Is possible create a default texture for OBJ without mtl or textures?

### ISSUE THREAD

**Issue by georgy-alarcon** [xeokit/xeokit-sdk#1083]
Hi,

I'm try to use `OBJLoaderPlugin` to load `.obj` files.
But when i load a obj-file without materials this is rendered black, so i'm ask if is possible set default material with custom texture.

This is the current result
![image](https://github.com/xeokit/xeokit-sdk/assets/62250304/abfc998b-6cd5-42e6-b8a6-f07cb6e04209)

Desidered result
![image](https://github.com/xeokit/xeokit-sdk/assets/62250304/efa67258-e01a-475c-8b95-49912306b493)

**Comment by xeolabs** [comment]
Sorry, we don;t support this in the API currently. Will re-open if anyone has any ideas though.
