### ISSUE TITLE
[with solution]: Wrong check of duplicate entity in PerformanceModel class

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#109]
Following lines of code from `viewer/scene/PerformanceModel/PerformanceModel.js::createEntity` are checking that an entity with the same `id` does not exist:

https://github.com/xeokit/xeokit-sdk/blob/13dbc2956b0305d448499bc3f6e96b9c344be97d/src/viewer/scene/PerformanceModel/PerformanceModel.js#L554-L557

Going down the call tree so search for registration in the scene, lands us on `viewer/scene/PerformanceModel/lib/PerformanceNode.js::constructor`:

https://github.com/xeokit/xeokit-sdk/blob/13dbc2956b0305d448499bc3f6e96b9c344be97d/src/viewer/scene/PerformanceModel/lib/PerformanceNode.js#L51-L53

We can see that it's registering an `object` (is uses the `model.scene._registerObject` method), not a `Component`.

Hence, shouldn't be code on the first snippet more like the following...

```javascript
} else if (this.scene.objects[id]) {
    this.error("Scene already has an Object with this ID: " + id + " - will assign random ID");
    id = math.createUUID();
}
```

... instead of...

```javascript
} else if (this.scene.components[id]) {
    this.error("Scene already has a Component with this ID: " + id + " - will assign random ID");
    id = math.createUUID();
}
```
... in order to properly check for registered `objects` things intead of `components`?

**Comment by xeolabs** [comment]
Yes that would be neater. Note though that ````Component#id```` is unique among all components, and if you have an Entity registered in ````scene.objects```` it's also always going to be registered in ````scene.components````.  But it's worth changing things things to how you've described.

**Comment by xeolabs** [comment]
Actually I'm going to leave as is - the entity's object ID is always the same as its component ID, so the existing code is actually slightly more robust.
