### ISSUE TITLE
Extensible way to select SceneModel implementation for loaders

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#1101]
# Not so extensible

This is the current approach - this is not so extensible, because it couples ````XKTLoaderPlugin```` to ````DataTextureModel````:

````javascript
const sceneModel = xktLoader.load({
        id: "myModel",
        src: "myModel.xkt",
        useDataTextures: {
              // Configs specific to DataTextureSceneModel
        }
    });
````

In other words,  ````XKTLoaderPlugin```` should really be following the Liskov Substitution Principle and be agnostic of whatever ````SceneModel```` implementation it's loading, and whatever configs are specific to that implementation. Currently it needs to be aware of those configs and pass them through the `load()` method etc.

# More extensible

 *[LK] Personally I think (3) is cleanest, but (2) is the best compromise*

## (1) Inject a factory?

A Java blast-from-the past, a little clunky, but at least gives us more control:

````javascript
const myDataTextureSceneModelFactory = new DataTextureSceneModelFactory({
    //...configs we want for all DataTextureSceneModels
});

const myVBOSceneModelFactory = new VBOSceneModelFactory({
    //...configs we want for all VBOSceneModels
});

const sceneModel = xktLoader.load({
        id: "myModel",
        src: "myModel.xkt",
        sceneModelFactory: myVBOSceneModelFactory
    });
````

* Advantage is that we can control what special configs we set on `VBOSceneModels`, `DataTextureModels` etc that the `XKTLoaderPlugin` will create
* Easy to also use the factory to `CityJSONLoaderPlugin` etc

To preserve backwards-compatibility, loaders can fall back on `VBOSceneModel` as default:

````javascript
const sceneModel = xktLoader.load({
        id: "myModel",
        src: "myModel.xkt"
    });
````

## (2) Inject the SceneModel subtype?

We can just given `XKTLoaderPlugin` the `SceneModel` type we want it to instantiate:

````javascript
const sceneModel = xktLoader.load({
        id: "myModel",
        src: "myModel.xkt",
        sceneModelType: DataTextureSceneModel // or VBOSceneModel ...
    });
````

* Simpler than using a factory, however we lose the ability to configure special configs for `VBOSceneModels`, `DataTextureModels` etc that the `XKTLoaderPlugin` will create 
* Easy to also use with `CityJSONLoaderPlugin` etc

## (3) Externally manage SceneModel and MetaModel lifecycles

````javascript
const sceneModel = new DataTextureSceneModel(viewer.scene, {...});
const metaModel = new MetaModel(viewer.scene, {...});

xktLoader.load({
        id: "myModel",
        src: "myModel.xkt",
        sceneModel,
        metaModel
    }). then(()=> {

      sceneModel.finalize();
      metaModel.finalize();
});
````

* This is what we do in next-gen xeokit-sdk V3
* Advantage is complete control
* Disadvantage is big API changes and backward-compat breakages

**Comment by tmarti** [comment]
@xeolabs, what about this?

```js
const sceneModel = xktLoader.load({
    id: "myModel",
    src: "myModel.xkt",
    sceneModelType: DataTextureSceneModel // or VBOSceneModel ...,
    sceneModelOptions: {
        … // specific to the provided SceneModelType
     },
});
```

Because, this is probably what your factory in (1) would do, plus it solves the problem in (3) and keeps the simplicity of (2).

Then the implementation will probably:

```js
// …
… = new cfg.sceneModelType (
    …,
    cfg.sceneModelOptions
);
// …
```

If you want to attach pre-setup and pre-finalize callbacks as in (3), you could always allow to provide the corresponding callbacks as options in the `*loader.load` method. 🙂

**Comment by tmarti** [comment]
Maybe also:

```
const sceneModel = xktLoader.load({
    id: "myModel",
    src: "myModel.xkt",
    sceneModelType: // either a class derived from SceneModel, or a function returning an instance of SceneModel
});
```

More aligned with dynamically typed Js/Ts, and which allows the consuming side to either pass the class (with standard config options), or pass a function that will return the instanced class (then the specific options can be set in this function by the consumer before returning the instance).

**Comment by xeolabs** [comment]
Thanks @tmarti , will give this deep headscratches for a bit

**Comment by tmarti** [comment]
You're SOLIDly welcome @xeolabs  🥂
