### ISSUE TITLE
Ray picking precision

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#1105]
I'm developing a plugin to measure distances between objects.

![bbbf204df94bada3ce9e8e0efc994eb1](https://github.com/xeokit/xeokit-sdk/assets/22523482/d0614978-6137-4513-9a31-7852496ea00f)

However, ray picking is not precise enough to consider my plugin as usable.

**First**, it is not possible to ray picking precision surface with `matrix` instead of `origin` & `direction`. Indeed, `worldRayOrigin` & `worldRayDir` are not set if a matrix is provided in pick `params`. See [here](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/webgl/Renderer.js#L1038). Is this an oversight or it is intended to does not work with matrix ?

**Second**, I used picking with matrix because it seems to be more precise. Indeed, the [matrix ray picking example](https://xeokit.github.io/xeokit-sdk/examples/#picking_ray_matrix) seems way more *stable* than the [surface ray picking example](https://xeokit.github.io/xeokit-sdk/examples/#picking_ray_surface). Comparing the code of both examples and the code on the Renderer.js, I saw that the only difference to go from `origin` & `direction` to `matrix` is [this part](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/webgl/Renderer.js#L971-L976):

```js
randomVec3[0] = Math.random();
randomVec3[1] = Math.random();
randomVec3[2] = Math.random();

math.normalizeVec3(randomVec3);
math.cross3Vec3(worldRayDir, randomVec3, up);
```

Maybe these lines are responsible for the lack of precision when picking with `origin` & `direction`...

Measuring the Duplex roof is a good place to show the ray picking limitations:

**No Precision**
- `origin` & `direction`:
![8b0b929e0155c8a0ac031f874d734d71](https://github.com/xeokit/xeokit-sdk/assets/22523482/eabc8f61-8fb2-460d-a6f0-2b5698ddd470)
- `matrix`:
![6776d57f2d08e712a143fd823ea901bf](https://github.com/xeokit/xeokit-sdk/assets/22523482/bf51577e-e888-4c61-9e74-f7c9458a3af7)

I seems better with matrix but in both no precision cases, the measure stops like 10cm before the wall...

For this kind of plugin, precision is key, precision picking needs to be enabled.

**Precision**
- `origin` & `direction`:
![6d5ef8a03f0ccf49040f49786d1a6044](https://github.com/xeokit/xeokit-sdk/assets/22523482/e409bcfb-24ff-4ce6-a1da-746c50f6fd97)

It hardly catches the other wall :/

I did not manage to get a fix for this. Maybe the provided example code below can be used as a sandbox to improve the precision of the ray picking. In the example, there is two checkboxes as the top of the document to quickly enable precision ray picking and switching between `matrix` or `origin` & `direction`.

The following zip file is the measurements_distance_modelWithMeasurements example updated with the spacing measurement plugin.

[measurements_distance_modelWithMeasurements.html.zip](https://github.com/xeokit/xeokit-sdk/files/12129256/measurements_distance_modelWithMeasurements.html.zip)

**Comment by xeolabs** [comment]
Won;t be able to look at this until perhaps next week, unfortunately

**Comment by Kurtil** [comment]
> Won;t be able to look at this until perhaps next week, unfortunately

No problem. I updated the entire issue content as it was not really relevant.

**Comment by tmarti** [comment]
@Kurtil @xeolabs I've been doing an experiment on top of DTX (data-textures) as the memory layout does not have precision loss in normals due to octencoding.


https://github.com/xeokit/xeokit-sdk/assets/2405414/e652ace2-ca7b-469d-8f9f-e3cf0b389f4c

The measurement is 100% stable and its precision **only** bounded by the quantization error during XKT compression, which in many models just means sub-mm error 🥂.

I need to debug and profile this a bit more before pushing the code, so please have pacience 🍿

**Comment by Kurtil** [comment]
Fixed by [this commit](https://github.com/xeokit/xeokit-sdk/pull/1168/commits/e9549ca02df787e444831ed1d2f5e2722ac887c9) on the 1 x 1 picking viewport PR #1168 and the 32 bit picking normal PR #1172.
