### ISSUE TITLE
Convert 3D coordinates to 2D coordinate to project it on a 2D map (SVG)

### ISSUE THREAD

**Issue by Aka-Dev** [xeokit/xeokit-sdk#1108]
Hello, I'm working to convert 3D coordinates (xeokit) to 2D coordinates to project an annotation or element on a 2D map (storeys in SVG 2D), I'm wondering if xeokit has an API to do that or not, if not how I can do it, knowing that the coordinates aren't in px,  thanks

**Comment by xeolabs** [comment]
We don't currently store the vertex coordinates in memory (for a low memory footprint), but for annotations you could just get the World-space 3D position of those and project them onto a 2D plane.
