### ISSUE TITLE
resetView( ) is not fully implemented

### ISSUE THREAD

**Issue by chloesun** [xeokit/xeokit-sdk#111]
Hello Lindsay,

I tried to use this method `resetView( )` and noticed this is not fully implemented, not working...
https://xeokit.github.io/xeokit-sdk/docs/file/src/viewer/Viewer.js.html#lineNumber241

**Comment by chloesun** [comment]
Reset the camera
```
resetView(eye, look, up) {
this.scene.camera.eye = eye;
this.scene.camera.look= look;
this.scene.camera.up=up;
}
```

**Comment by xeolabs** [comment]
Hi Chloe, try these memento-helper classes instead:

* https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/mementos/CameraMemento.js~CameraMemento.html
* https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/mementos/ObjectsMemento.js~ObjectsMemento.html
