### ISSUE TITLE
How can I determine the Object Oriented Bounding Box of an entity

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1110]
Currently, I only see the Axis Aligned Bounding Box (aabb) in the `Entity` object, I'd like to get the oriented bounding box. 

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/7acc250a-380b-4ff8-b63a-b2d102bb1a85)

I tried to get the entity's points' positions to calculate it manually, but I couldn't find the Mesh's `geometry`.

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/150534b5-f6f9-400f-a904-1264dbb35ca5)

Any help would be appreciated

**Comment by xeolabs** [comment]
Currently we only track the axis-aligned boundaries - for a low memory footprint, we don't currently store all the positions information in memory, so it's not currently possible to calculate the OBB, unfortunately.
