### ISSUE TITLE
Some сolors not relevant

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1122]
**Describe the bug**
Green parts with some transparency look more like gray and almost completely transparent.

**To Reproduce**
````js
const viewer = new Viewer({
    canvasId: "model-canvas",
})
const ifcLoader = new XKTLoaderPlugin(viewer, {})
const sceneModel = ifcLoader.load({
    id: "myModel",
    src: '...',
    loadMetadata: true,
    excludeTypes: ["IfcSpace"],
    edges: true,
});
````
Ifc and xkt loaders give the same result.

**Screenshots**
1 Xeokit viewer
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/74b93d54-18bd-40bf-a7ae-e69eb9b00e45)
2. Programs like BimVision, Trimble Connect and IFC.js [live example](https://ifcjs.github.io/hello-world/examples/web-ifc-three/helloworld/)
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/673001ff-2e53-41f1-b448-5afabd9c8c16)
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/ad557af8-59b1-400d-88ad-743732299706)
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/97d50b23-463a-43d3-b080-9a11d21942b0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 116

**Additional context**
[Model_Full_wrong_color.zip](https://github.com/xeokit/xeokit-sdk/files/12386731/Model_Full_wrong_color.zip)
Example details ids: 2QtixrV35ClxZwwX2HIYjo, 2PO4udnUH8P84Bns3dnRsc

**Comment by xeolabs** [comment]
This is likely to be fixed by https://github.com/xeokit/xeokit-sdk/issues/1154 - we were applying color+opacity overrides to certain IFC element types by default (including IfcWindow, IfcSpace and IfcPlate) and have now removed those overrides.

Try again with the latest version of @xeokit/xeokit-sdk
