### ISSUE TITLE
Determine pick is edge or vertex

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1123]
I want to create custom measurements plugin, for this I need to know when click (red on screenshot) on surface is edge, vertex or other. It's possible? Need some help.
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/2d67cb68-0504-4d17-9ce5-b90d022d2686)

**Comment by xeolabs** [comment]
I'm still preparing the release for this in this branch: https://github.com/xeokit/xeokit-sdk/tree/scenemodel-refactoring-next

It's not possible yet, but I'll add something like a  ````snapMode: "vertex" | "edge"```` to the result returned by the snap pick function.

We'll have this release out in a few days, though not sure what day exactly. Consider snapping an "alpha" feature for now, until that release.

**Comment by xeolabs** [comment]
Actually, [CameraControl.snapMode](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/CameraControl/CameraControl.js~CameraControl.html#instance-set-snapMode) indicates whether snapping is currently edge or vertex.
