### ISSUE TITLE
Console is spammed with a lot of logs

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1140]
**Describe the bug**
![image](https://github.com/xeokit/xeokit-sdk/assets/1349751/597cc895-0766-4c69-919e-977c70b98009)

There is a lot of new `console.log()`. We can either remove them or use `console.info()` so they're not shown by default. @xeolabs what do you prefer?
I can submit a PR if needed.

**Comment by xeolabs** [comment]
Oh yes, console.info() is a good idea, PR welcome. I want to keep these logs for a little bit, until we're sure data texture rendering is stable on enough devices.
