### ISSUE TITLE
How to load the obj model properly, thanks!

### ISSUE THREAD

**Issue by zhuhuanzi** [xeokit/xeokit-sdk#1146]
**Describe the bug**
I made an example of loading a model according to the documentation，Example code repository address： https://github.com/zhuhuanzi/xeokit-obj-demo

> git clone https://github.com/zhuhuanzi/xeokit-obj-demo.git
> yarn install 
> yarn start

![image](https://github.com/xeokit/xeokit-sdk/assets/26531688/95ee3ab9-4e03-4d31-9c56-9213fc8885bf)

I don't know why this model can't be loaded and how should I troubleshoot this problem，thank you。

- The correct example is shown below：
![a138cb9f9eec13da1d667cbdd003c50](https://github.com/xeokit/xeokit-sdk/assets/26531688/d05d0c6b-f282-4ab7-85fa-e92f80de3809)

**Comment by xeolabs** [comment]
xeokit-bim-viewer is build to load XKT files, and we don't support OBJ files at this time. If possible, convert the file to XKT using convert2xkt, but no guarantees on results.
Sorry about that. Will need to close this issue since it's out of scope.
