### ISSUE TITLE
3DXML

### ISSUE THREAD

**Issue by Mike-yangdaichun** [xeokit/xeokit-sdk#115]
3XDML do not support SchemaVersion4.3.

**Comment by Mike-yangdaichun** [comment]
XML3DLoader.js   only support SchemaVersion4.2. I tried to use toSchemaVersion4.3 but failed.

**Comment by Mike-yangdaichun** [comment]
[JG.zip](https://github.com/xeokit/xeokit-sdk/files/3419536/JG.zip)
I want to use this 3DXML but failed.

**Comment by gyuannnn** [comment]
> [JG.zip](https://github.com/xeokit/xeokit-sdk/files/3419536/JG.zip)
> I want to use this 3DXML but failed.

Me too

**Comment by xeolabs** [comment]
Hi @Mike-yangdaichun, @gyuannnn, if you represent commercial users who wish to buy licenses, then I can put Schema Version 4.3 on the near-term road map.

**Comment by atinytudou** [comment]
> Hi @Mike-yangdaichun, @gyuannnn, if you represent commercial users who wish to buy licenses, then I can put Schema Version 4.3 on the near-term road map.

I will buy it if i can stand the price,so how much the licenses is? waiting for your  reply day and night!

**Comment by xeolabs** [comment]
Hi @atinytudou , unfortunately we've decided to remove 3DXML support because it's no longer out focus for xeokit-sdk. Sorry about that - will close ticket.
