### ISSUE TITLE
Freeze at first camera move and WebGL warnings in console when using dtx

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1155]
**Describe the bug**
![image](https://github.com/xeokit/xeokit-sdk/assets/1349751/73459456-df09-4752-8ea2-8fbfb2b2ff36)

When loading a model with dtx, there are 2 WebGL warnings twice.
At the first camera move (pivot, zoom, etc.), there is a lag of 2 to 3 seconds then another round of 2 WebGL warnings. There is no more lag after that.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 118

**Comment by xeolabs** [comment]
This initial lag is likely partially due to picking shaders and their data textures (used for camera navigation) being lazy-created only as soon as we first use them.

The texture warnings are a separate issue, but if I pre-initialize those shaders I'm guessing we'll reduce that initial lag.

**Comment by xeolabs** [comment]
Fixed in @xeokit/xeokit-sdk 2.4.0-alpha-89
