### ISSUE TITLE
Question: How to dynamically enable or disable textures for a model?

### ISSUE THREAD

**Issue by phxd88** [xeokit/xeokit-sdk#1164]
Hi!,
Would be a way to include a ON/OFF switch for Performance Texture related to a gltf file?
The main purposes is to turn on / off texture of the model. 

I tried with this but nothing happened: 

`     $('#toggle').on('click', function(){
      if (viewer.scene.PerformanceModel) {
          viewer.scene.PerformanceModel = false;
        } 
      else {
          viewer.scene.PerformanceModel = true;
           }
         });`

Thank You

**Comment by xeolabs** [comment]
Hi - try this:

````javascript
myModel.colorTextureEnabled = false;
````

or 

````javascript
myScene.colorTextureEnabled = false;
````

**Comment by phxd88** [comment]
Hi Lindsay,
Thank you for your quick response. But seems not to be working.
I evoked 3d gltf model in that way:

`      const gltfLoader = new GLTFLoaderPlugin(viewer);

    const sceneModel = gltfLoader.load({
        id: "myModel",
        src: "./assets/models/untitled.gltf",
		performance: false,
		});`


Should I add `SceneModelcolorTextureEnabled: true,` after the gltf location?

Thank you for your time

**Comment by xeolabs** [comment]
No prob - try the following - this assumes that the model has textures. Also, note that the `performance` flag on the `load` call was removed several versions back, you might be using an old version.

````javascript

viewer.scene.colorTextureEnabled = true;

const gltfLoader = new GLTFLoaderPlugin(viewer); 

const sceneModel = gltfLoader.load({ id: "myModel", src: "./assets/models/untitled.gltf" });

sceneMode.colorTextureEnabled = true;

// Then to disable textures for the model:
sceneMode.colorTextureEnabled = false;

````

**Comment by phxd88** [comment]
Thank you Lindsay! 

I downloaded latest SDK and now it works! 

I used this for the model loading:

` viewer.scene.colorTextureEnabled = true;
     const gltfLoader = new GLTFLoaderPlugin(viewer); 
     const sceneModel = gltfLoader.load({ 
	 id: "myModel", 
	 src: "./assets/models/untitled.gltf"
	 });`

And this for the switch: 

` $('#toggle').on('click', function(){
      if (viewer.scene.colorTextureEnabled) {
          viewer.scene.colorTextureEnabled = false;
        } 
      else {
          viewer.scene.colorTextureEnabled = true;
           }
         });`

Thanks again! :)
