### ISSUE TITLE
[FEATURE SUGGESTION] DirLights dynamic slider

### ISSUE THREAD

**Issue by phxd88** [xeokit/xeokit-sdk#1171]
would be possible of implementing the viewer with a dynamic slider for controlling directional lights in real-time (Height/Azimut)?
Thanks in advance

**Comment by xeolabs** [comment]
Yes, that would be possible - the `pos` and `dir` properties on the light source components can be dynamically updated. Such a feature would be best done as an example page, with the UI components belonging to that example. If anyone has time to contribute such an example, w'd be happy to merge a PR,
