### ISSUE TITLE
type <--> name swapped on metaScene.metaObjects

### ISSUE THREAD

**Issue by cvillagrasa** [xeokit/xeokit-sdk#1185]
**Describe the bug**
Hi! I'm a new user of xeokit, and I'm trying to include it on Jupyter Notebooks cells so as to provide visualizations for IfcOpenShell-generated models in Python. Reference: https://github.com/IfcOpenShell/ifcopenshell-binder/issues/1#issuecomment-1770327024

I'm using a custom data source (the IFC models in memory themselves), and a `WebIFCLoaderPlugin`. The issue I'm having appears when querying `metaObjects`. The type key refers to the Name, and the name key sometimes refers to the IFC class, and sometimes to a seemingly random value, depending on the lib version being used.

**To Reproduce**
`console.log(viewer.metaScene.metaObjects);`

I've tried with xeokit-sdk@2.3.9, as well as with 2.4.0-alpha-90. In the Colab from the link above there's the full JavaScript, but it's mainly what I explained: custom data source from a string + `WebIFCLoaderPlugin`, and there's something strange triggering this swap. When using `web-ifc` from `WebIFCLoaderPlugin._ifcAPI`, `GetLine` returns the properties as expected.

**Expected behavior**
type <--> name the other way around

**Screenshots**
![wall_name_type](https://github.com/xeokit/xeokit-sdk/assets/57069798/2bc7c896-2613-4e22-892f-4472db25043a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 as local, and Ubuntu 22.04.2 as cloud (Google Colab)
 - Browser: Chrome
 - Version: 118.0.5993.70

Thanks in advance!

**Comment by cvillagrasa** [comment]
Mmm so the little bug fix makes the name appear on the name, but the type is still behaving weirdly with the minimized version of the lib from a CDN:

![wall_type_bug](https://github.com/xeokit/xeokit-sdk/assets/57069798/17502a55-6db9-41fb-a9d0-19826672d7dd)


The screenshot corresponds to using `WebIFCLoaderPlugin()._ifcAPI.GetLine` on `2.4.0-alpha-99/dist/xeokit-sdk.es.min.js`.

The non-minimized version `xeokit-sdk.es.js` works ok and returns the expected "IfcWall" for constructor.name. The last stable 2.3.9 version also works ok in its minimized form, so it should be something between `web-ifc` 0.0.34 and 0.0.41 making rollup unhappy.

The `web-ifc` built-in GetNameFromTypeCode does work on both minimized and non-minimized versions, but as shown, returns the IFC class uppercase, which is not ideal.

In any case, I'll bundle it and avoid the problem, so feel free to close the issue if deemed not super important.

**Comment by xeolabs** [comment]
Oops I may have forgotten to deploy the minified build - will do this
evening/tomorrow ✌️

**Comment by cvillagrasa** [comment]
Type is still "Hr" on alpha-100 minified.

**Comment by xeolabs** [comment]
I think to track this bug/fix properly, would you be able to provide a standalone HTML page that loads the file and shows the problem?

**Comment by cvillagrasa** [comment]
So in the notebook from the following link, you just need to press Play on the highlighted four cells:

https://colab.research.google.com/drive/1wVjX4H3w-NFqFa_FVnefP14bDqzHTbjX?usp=sharing

![image](https://github.com/xeokit/xeokit-sdk/assets/57069798/2b620a98-4d0f-4bd2-8aa1-e0ff94005593)

And will see the following output on the console:

![image](https://github.com/xeokit/xeokit-sdk/assets/57069798/f10f019f-b1bf-452d-803c-fa71201f666b)

Then, if you unfold the "Setup of xeokit" tab, you'll see some boilerplate on the first two cells, the JS on the third, the CSS on the fourth, and the HTML on the fifth.

On that third cell with the JS, this function near the end is what's outputting that intriguing "Hr" to the console:

![image](https://github.com/xeokit/xeokit-sdk/assets/57069798/46f5fab2-8e15-4bfe-84c3-d9f57d91439b)

At the top, you may easily comment / uncomment the minified / non-minified versions:

![image](https://github.com/xeokit/xeokit-sdk/assets/57069798/d8d5bb9a-8f0e-4b2e-8f6f-caf3c7443040)

After changing the JS, just run that third cell, then the fifth (HTML) and lastly the "Model viz with xeokit" at the end (so press play in those three cells). That allows to live edit the code, and will output the new results to the console.

You'll see that with the non-minified, everything works as expected:

![image](https://github.com/xeokit/xeokit-sdk/assets/57069798/e78684a4-b9ea-428b-b7e9-21856fdae048)

Intriguing!

**Comment by paireks** [comment]
Hello Carlos!

First of all - great notebook :)

It looks like minimizing JS files with default settings changes class names to make them shorter, so the class name were renamed to Hr, therefore later after use of constructor.name it probably returns minimized version. Generally constructor.name should't be used client-side because of that, however one of the solutions on a Xeokit side might be probably changing terser options to keep original class names (keep_classnames: true). But it's up to @xeolabs to decide if such change in configuration is necessary and justified.

**Comment by cvillagrasa** [comment]
Hey @paireks ! nice to see you around here ;) I need to find some time to work on [this repo](https://github.com/IfcOpenShell/ifcopenshell-jupyter) and finally have a nice ifcopenshell + xeokit pip-installable package for notebooks.

Good research! Maybe the best global solution is that `GetNameFromTypeCode` from web-ifc API returned the IFC class in PascalCase, instead of UPPERCASE, which is ultimately destructive. But they've had it like this for so long, and it's a breaking change...

**Comment by xeolabs** [comment]
AFAIK this is fixed with the PR mentioned above - will re-open if not.
