### ISSUE TITLE
Fix NavCubePlugin Left/Right color Configuration

### ISSUE THREAD

**Issue by AXONE-IO** [xeokit/xeokit-sdk#1194]
**Describe the bug**
The rightColor property of a NavCubePlugin configuration updates the color of the left face. 
The leftColor property of a NavCubePlugin configuration updates the color of the right face. 

**To Reproduce**
1. Declare a NavCubePlugin with the following configuration
 `    new NavCubePlugin(viewer, {
        canvasId: "myNavCubeCanvas",
        visible: true,
        rightColor: "purple",
        leftColor: "yellow"
    });`

**Expected behavior**
I guess the two properties are reversed.

**Screenshots**
![image](https://github.com/xeokit/xeokit-sdk/assets/129860932/bf17de27-4923-48db-9d76-b55cc513df82)
![image](https://github.com/xeokit/xeokit-sdk/assets/129860932/f421fa01-d98a-4c15-afce-e8ea7612fc9f)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professionnel v22H2
 - Browser Chrome v118.0.5993.89 (64 bits)

**Comment by xeolabs** [comment]
Fixed in @xeokit/xeokit-sdk 2.4.0-alpha-101
