### ISSUE TITLE
[bug]: WIP Problem with edge-indices re-bucketting in DTX

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#1204]
## Context

This thread continues the research on this issue...

- https://github.com/xeokit/xeokit-sdk/issues/1162

... for the concrete case of this example:

```
examples/scenemodel/snapToVertex_dtx_instancing_triangles.html
```

## Description

When porting the code from the original DTX PR, some refactors happened and e.g. the `rebucketPositions` function in following file...

https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/model/dtx/triangles/rebucketPositions.js

... seems to have some refactor-related bugs.

For example, the code here...

https://github.com/xeokit/xeokit-sdk/blob/095e9a22705b71071e3ebbaece123af7108d3261/src/viewer/scene/model/dtx/triangles/rebucketPositions.js#L219-L244

... seems to mix processing logic between regular `indices` and `edge-indices`.

This is indeed what causes the trouble in `snapToVertex_dtx_instancing_triangles.html` missing some edges when using @Kurtil's snap-buffer debugger technique in https://github.com/xeokit/xeokit-sdk/issues/1162.

## Implications

Today, the current implementation of rebucketting has undefined behaviour when managing `edge-indices`.

## Next steps

The problem is now located, I would suggest:

1. compare side-by-side:

  - the rebucketting code from the original DTX PR
  - the rebucketting code in main branch

2. make them equivalent again

**Comment by xeolabs** [comment]
Good catch, thanks @tmarti

**Comment by xeolabs** [comment]
@tmarti I just pushed a temporary patch release of xeokit-sdk 2.4.0-beta-3 and xeokit-bim-viewer 2.4.9-beta-3 that disables rebucketing until this is fixed. I took a brief look but didn't spot anything so far, will take a closer look next week.

**Comment by xeolabs** [comment]
PS. I'll also include the shader debugger from kurtil in a patch tomorrow.

**Comment by tmarti** [comment]
@xeolabs; the error is, very probably already there in the `rebucket-positions` code of my original PR some months back 😉.

Will keep debugging the code 👍

**Comment by tmarti** [comment]
@xeolabs this one is solved with https://github.com/xeokit/xeokit-sdk/pull/1207

Took me a while to notice welding was disabled here even in case of having bucketing enabled 🙈
