### ISSUE TITLE
3D model URL from GDrive or Mega

### ISSUE THREAD

**Issue by phxd88** [xeokit/xeokit-sdk#1208]
Hi! 
I am trying to embed a 3D model (gltf-glb) from gdrive or mega, but with no positive results.
I followed instruction for hosting and sharing correctly files, but probably I missed something. 

I tried `src` and also `href` in the loader code: 

` const gltfLoader = new GLTFLoaderPlugin(viewer); const sceneModel = gltfLoader.load({ 
   id: "myModel", 
   src: "https://drive.google.com/uc?export=view&id=GDRIVE_FILE_ENCRYPTED_CODE",
   useDataTextures: true,`

Could someone help me?
thank you

**Comment by phxd88** [comment]
Thank you. 
However, I tried to put the the download link but nothing.

**Comment by Amoki** [comment]
Is your file accessible from an unauthenticated user with the URL?

Or maybe you can't use GDrive at all for this

**Comment by phxd88** [comment]
Thank you Amoki for your time,

Yes, files are available also for other users. I tried GDrive and Mega with free access via shared link but nothing. I also used download link, but the viewer goes into an infinite loader loop (3D models are about 40-80MB).
