### ISSUE TITLE
Change Typing of MetaScene::metaObjectsByType

### ISSUE THREAD

**Issue by assaad977** [xeokit/xeokit-sdk#1223]
**Describe the bug**
the bug (or error) is on the definition of MetaScene::metaObjectsByType. It is defined as follows : 

`metaObjectsByType: {[key: string]: MetaObject}`

where in reality it should be : `metaObjectsByType: {[key: string]: { [key: string] : MetaObject } }

i loaded an xkt model using xeokit and when i console.log viewer.metaScene.metaObjectsByType, i get the data shown in the screen

![image](https://github.com/xeokit/xeokit-sdk/assets/83342805/bce52b8d-71a4-4fa2-aa37-78e3fecefb1c)

edit : it can be resolved if we cast metaObjectsByType, as follows 

`viewer.metaScene.metaObjectsByType["IfcBuildingStorey"] as unknown as { [key: string]: MetaObject}`

xeokit-sdk v2.3.2

**Comment by mlankamp** [comment]
Can you create a PR to fix the typings?

**Comment by assaad977** [comment]
@mlankamp Done
