### ISSUE TITLE
NavCuve Resolution/Interaction

### ISSUE THREAD

**Issue by AXONE-IO** [xeokit/xeokit-sdk#1231]
**Describe the bug**
If you modify the resolution of the canvas associated with the NavCube, the interactions are not detected in the correct locations.

**To Reproduce**
1. Set nav cube canvas resolution to 2.
`this.navCube["_navCubeScene"]["canvas"].resolutionScale = 2;
`
2. Hover over the cube and try to interact with it.

**Desktop :**
 - OS: Windows
 - Browser Chrome
 - Version 119.0.6045.124 (Build officiel) (64 bits)

**Additional context**

**Comment by xeolabs** [comment]
Resolution scaling of the NavCube's canvas is not a use case we currently support in the xeokit API. We would consider a PR if this is critical to your app, however.
