### ISSUE TITLE
Navcube loading bug

### ISSUE THREAD

**Issue by TitouanGisle** [xeokit/xeokit-sdk#1246]
The viewer is embedded in a **VueJS app**, and the navcube fails to load properly under some conditions. Its textures are missing, and it cannot be interacted with. It still moves in accordance with the model in the viewer.

![image](https://github.com/xeokit/xeokit-sdk/assets/47686081/1815c51b-95b5-4ea7-bef2-e1e58e00efb7)

The bug occurs when **leaving the viewer** to go to another part of the VueJS app, **then returning** to the viewer.

The bug doesn't occur when accessing the viewer component for the first time, or when reloading the page.

The bug was reproduced on Firefox and Edge.

**Additional context**
The VueJS app also makes use of "vue-router".

**Comment by xeolabs** [comment]
This one is a mystery to me also. Sounds like it's caused by a side-effect specific to VueJS or `vue-router` and unfortunately I have no experience with either of these. 

Comments welcome from any VueJS users!

**Comment by Amoki** [comment]
The reason is probably because you do not destroy xeokit properly when your vue Component is destroyed. the WebGL context is not released and when opening the viewer many times, you reach the max contexts number and this glitch appears. You should have a WebGL warning in the console when it appends.

**Comment by TitouanGisle** [comment]
Oh ! You're absolutely right ! 

```
WebGL warning: uniform setter: `location` is from a different (or lost) WebGL context.
```

I'm gonna try to destroy Xeokit (nothing personal).

**Comment by TitouanGisle** [comment]
It works !

I called `viewer.destroy()`, `navCube.destroy()`, and multiple other destroys on my component's `beforeDestroy()`, and all's well.

Thanks a bunch !
