### ISSUE TITLE
Duplicate object ids on loading same XKT to scene multiple times

### ISSUE THREAD

**Issue by intrida-dev** [xeokit/xeokit-sdk#1262]
We are using **xeokit-sdk** with version number '2.4.1'. We want to load single XKT model multiple times in scene. For that we are referring your example: https://xeokit.notion.site/Viewing-Multiple-Models-71b73627d97840f7887275ea6ac4ed4a

We have already created XKT files and trying to load them using **XKTLoaderPlugin**. 

When we load same XKT multiple times to scene the ids against each entity get duplicated and it becomes difficult to identify each entity individually (for highlight, xray, select etc.). 

How can we avoid having duplicate entity ids when same XKT model is loaded twice?

**Comment by xeolabs** [comment]
Try the `XKTLoader's globalizeObjectIds` option: https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/XKTLoaderPlugin/XKTLoaderPlugin.js~XKTLoaderPlugin.html#instance-get-globalizeObjectIds

**Comment by intrida-dev** [comment]
This helped us. Thanks :-)
