### ISSUE TITLE
Vertex picking

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#128]
We need this for measurement tools, to enable the cursor to snap to vertices when measuring.

More info on implementation here when released.

**Comment by Amoki** [comment]
That would imply to freeze the camera to avoid a rerender of the 2D canvas, no? Or the 2D canvas could be generated without much overweight?

**Comment by xeolabs** [comment]
Nope, won't be a problem. When xeokit does its existing pick operations, it renders to a **hidden** framebuffer, which we then read pixels from, which does not disrupt normal rendering in any way. This will just be building on that general technique.

We now have distance measurement, and soon we'll have angle measurement. This snapping will be the final touch that makes measurement ready for practical use. 

https://xeokit.github.io/xeokit-sdk/examples/#measurements_distance_modelWithMeasurements
https://xeokit.github.io/xeokit-sdk/examples/#measurements_distance_createWithMouse

**Comment by raffdp** [comment]
Has snapping been added to measurement or still in the pipeline? It would be really nice to get accurate measurement.

**Comment by pbruehwiler** [comment]
Any news on this regarding snap-in? This would be a nice and necessary feature to use the measurement in practice.

**Comment by pbbr** [comment]
Are there any plans to integrate this feature to use the measurement tools in practice? I thinks this would be a game changer.

**Comment by Kurtil** [comment]
@xeolabs this issue should be closed now ;)
