### ISSUE TITLE
Updating a model's position makes the aabb wrong

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1284]
**Describe the bug**
In xeokit build 2.4.2-beta-31, changing a model's position makes the aabb positions wrong

**To Reproduce**
1. [Go to Duplex model](https://xeokit.github.io/xeokit-sdk/examples/buildings/#xkt_vbo_Duplex)
2. Check the main model's `aabb` and calculate the `Xmax - Xmin`
```js
viewer.scene.models.myModel.aabb
// => [
    -1.2004623413085938,
    -9.725000381469727,
    -0.24150000512599945,
    9.041500091552734,
    6.608947230820357,
    18.041500091552734
]
viewer.scene.models.myModel.aabb[3] - viewer.scene.models.myModel.aabb[0]
// => 10.241962432861328
```
3. Change the position
```js
viewer.scene.models.myModel.position = [11, 0, 0]
```
4. Check that difference again
This is the output of the aabb and `Xmax - Xmin`

```js
viewer.scene.models.myModel.aabb
// => [
    -0.24150000512599945,
    -9.725000381469727,
    -0.24150000512599945,
    16.80899986924487,
    6.608947230820357,
    18.041500091552734
]
viewer.scene.models.myModel.aabb[3] - viewer.scene.models.myModel.aabb[0]
// => 17.05049987437087
```

**Expected behavior**
Since we only changed the X axis by 11 (no rotation), we should see Xmin and Xmax increased by 11, and the difference should not change

**Screenshots**

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/cebb0c40-3413-4829-907b-804958b04600)

Thanks for checking 🙏

**Comment by xeolabs** [comment]
Fixed in #1291
Published in @xeokit/xeokit-sdk 2.4.2-beta-35
