### ISSUE TITLE
FIX: Entities missing on distance and angle measurements

### ISSUE THREAD

**Issue by ksinb** [xeokit/xeokit-sdk#1287]
## Describe the bug
- In xeokit SDK `2.4.2-beta-29`, `entity` property is missing when creating Distance Measurement.

## To Reproduce
- Checkout [xeokit-bim-viewer](https://github.com/xeokit/xeokit-bim-viewer).
- Add below code at [src/toolbar/MeasurementDistanceTool](https://github.com/xeokit/xeokit-bim-viewer/blob/7d4695ba6c03df6495c1cc3292c0f120a7abab63/src/toolbar/MeasureDistanceTool.js#L53-L55).
```js
this._distanceMeasurementsPlugin.on('measurementEnd', (data) =>
  console.log(data)
);
``` 
- Run local server
- Check `console.log` output.

## Expected behavior (xeokit SDK `2.4.0-alpha-53`)
- `console.log` outputs entities
- `data.origin.entity` and `data.target.entity` are not `undefined`.
<img width="434" alt="スクリーンショット 2023-12-08 13 53 04" src="https://github.com/xeokit/xeokit-sdk/assets/61133806/ca27969c-897e-47a7-8c76-f3a249b75b57">

## Current behavior (xeokit SDK `2.4.2-beta-29`)
- `console.log` outputs `undefined`.
- `data.origin.entity` and `data.target.entity` are `undefined`.
<img width="434" alt="スクリーンショット 2023-12-08 13 51 13" src="https://github.com/xeokit/xeokit-sdk/assets/61133806/7273c196-a909-458f-8ea7-6cd5d0746889">

## Desktop (please complete the following information):
 - OS: MacOS 14.1.2
 - Browser: Chrome
 - Version: 119.0.6045.199

**Comment by xeolabs** [comment]
Fixed in 

* @xeokit/xeokit-sdk 2.4.2-beta-41
* @xeokit/xeokit-bim-viewer 2.4.30
