### ISSUE TITLE
Picking broken for geometry batching

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#13]
In example that uses BIMServerLoaderPlugin to load the [Schependomlaan model](https://xeokit.github.io/xeokit-sdk/examples/#BIMServer_Schependomlaan), mousing over some objects, like the roof, highlights the wrong objects.

However, the problem does not exist with the equivalent [glTF model loaded with GLTFLoaderPlugin](https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_Schependomlaan).

But this bug can be reproduced using the [geometry batching bemchmark](https://xeokit.github.io/xeokit-sdk/examples/#sceneRepresentation_PerformanceModel_batching_benchmark), where some objects appear to be unpickable. This might be due to running out of picking color range for large numbers of objects.

**Comment by xeolabs** [comment]
In the [geometry batching benchmark](https://xeokit.github.io/xeokit-sdk/examples/#sceneRepresentation_PerformanceModel_batching_benchmark) it appears as if objects are selected, but their highlighted representations are positioned incorrectly. In theis screenshot, the mouse is actually over the center of the block of objects, yet the highlighted representation is over on the left (see yellow object).

![screenshot from 2019-03-06 15-07-21](https://user-images.githubusercontent.com/83100/53887056-bec21680-4021-11e9-9722-02386bb17f2b.png)

**Comment by sha-N** [comment]
Looks like this is resolved in the latest release. Before this some elements were not even pick-able or was highlighting wrong element, now it is selecting elements correctly.

**Comment by xeolabs** [comment]
In this particular issue it appears that the highlighted representation of each entity (for when geometry batching is used for rendering) is appearing far away from the picked entity, for this particular example. So probably not related to picking, more like a renderer bug of some sort.

But yes, the latest release has fixed an issue with picking when using instancing for reused geometries, where the wrong objects were getting picked. Not related to this though.
