### ISSUE TITLE
Issue in Zoom in/out

### ISSUE THREAD

**Issue by alabrazi** [xeokit/xeokit-sdk#130]
Zoom in/out work only when the course is not on the annotations otherwise the viewer scroll up and down instead.

![Aug-17-2019 18-46-23](https://user-images.githubusercontent.com/7549404/63214360-f03a2480-c11f-11e9-9a66-579973b91323.gif)

**Comment by xeolabs** [comment]
You'll need to find a CSS rule for the annotation marker elements that will disable mouse wheel events for that element.
