### ISSUE TITLE
Feature request: extend distance measurement to support touch input with snapping

### ISSUE THREAD

**Issue by ksinb** [xeokit/xeokit-sdk#1306]
## Describe the bug
- In xeokit SDK `2.5.1-beta`, creating Distance Measurements not working at mobile devices. 

## To Reproduce
- Checkout [xeokit-bim-viewer](https://github.com/xeokit/xeokit-bim-viewer).
- Run local server
- Open `xeokit-bim-viewer` by mobile devices
- Try to create Distance Measurements

## Expected behavior
- Distance Measurements can be created on mobile devices.

## Current behavior (xeokit SDK `2.5.1-beta`)
- Distance Measurements can be created only with mouse events, not with touch events on mobile devices.

## Smartphone (please complete the following information)
 - Device: iPhone 14 Pro Max
 - OS: iOS16.0
 - Browser: Safari
 - Version: 16.0 

## Additional context
- Current SDK version(`2.5.1-beta`), there is only a [mouse control implementation](https://github.com/xeokit/xeokit-sdk/blob/9fa6cab8163ca92772338120674e35ccc412ae56/src/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsMouseControl.js) and no touch control implementation
- Has the current version dropped creating Distance Measurements on touch events?

**Comment by xeolabs** [comment]
> Has the current version dropped creating Distance Measurements on touch events?

These are coming in a release soon, we just wanted to evaluate a few UX options first.

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeokit/xeokit-sdk/releases/tag/v2.6.0-beta-15
