### ISSUE TITLE
Strange feedback from viewer when zooming in

### ISSUE THREAD

**Issue by AlABarazi** [xeokit/xeokit-sdk#131]
When zooming in too much the model start to jump

 in all directions. Does this feedback from the viewer mean that it is not possible to zoom in more? Or is this an issue that require an attention?

![Aug-18-2019 12-39-34](https://user-images.githubusercontent.com/7549404/63222921-b0724c00-c1b6-11e9-884f-6a2eab7b7aae.gif)

**Comment by xeolabs** [comment]
This happens when the distance between Camera eye and look becomes too short, and CameraControl clamps the distance, unfortunately with some jankiness. So that would be something that needs fixing in CameraControl.

**Comment by simplylogicninjas** [comment]
This is still a problem in the current viewer with "followPointer" set to false
