### ISSUE TITLE
GLB file does not display properly

### ISSUE THREAD

**Issue by ksinb** [xeokit/xeokit-sdk#1313]
**Describe the bug**
- GLB files do not display properly when the SDK version is `v2.4.0-alpha-73`  or later versions

**To Reproduce**
- Open below sample GLB file with `GLTFLoader`
- [sample GLB file](https://github.com/ksinb/xeokit-bim-viewer/blob/944c116d036d4564c3eb159a3ad50d6c92564136/app/data/projects/GLBSample/public-use-sample-apartment.glb)

**Expected behavior**
- GLB files display properly

**Screenshots**
| v2.4.0-alpha-54 | v2.4.0-alpha-73 or later |
| -- | -- | 
| <img width="482" alt="スクリーンショット 2023-12-25 10 49 09" src="https://github.com/xeokit/xeokit-sdk/assets/61133806/f85ba7b0-a73a-4aa6-b246-03b190050ba3"> | <img width="482" alt="スクリーンショット 2023-12-25 10 48 03" src="https://github.com/xeokit/xeokit-sdk/assets/61133806/0365483c-d6cc-4210-af1d-b6d5792b5434"> |

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.2
 - Browser: Chrome
 - Version: 120.0.6099.129

**Comment by xeolabs** [comment]
`convert2xkt` is running out of memory while attempting to convert this ````.glb```` file - see below. Perhaps a better option is to load it directly using ````GLTFLoaderPlugin````, or to try converting a ````.gltf```` version with textures and geometries as externals attachments.

````
node --max-old-space-size=18076 convert2xkt.js  -t -c convert2xkt.conf.json -s public-use-sample-apartment.glb -o geometry.xkt                         -l 
[convert2xkt] Running convert2xkt v1.1.15-beta-4...
[convert2xkt] Using JSON configs file: convert2xkt.conf.json
[convert2xkt] Converting single input file public-use-sample-apartment.glb...
[convert2xkt] Reading input file: public-use-sample-apartment.glb
[convert2xkt] Input file size: 16178.78 kB
[convert2xkt] Not embedding metadata in XKT
[convert2xkt] [ERROR]: [parseGLTFIntoXKTModel] Error: maxMemoryUsageInMB limit exceeded by at least 225MB
````

**Comment by xeolabs** [comment]
This `.glb` file loads successfully, almost instantly, using `GLTFLoaderPlugin` - I would recommend using that technique:

![Screenshot from 2024-02-26 09-42-56](https://github.com/xeokit/xeokit-sdk/assets/83100/16b35644-a6a1-4e73-a00e-dd125906c798)

**Comment by xeolabs** [comment]
Also, for completeness, `convert2xkt` is running out of memory while attempting to convert this ````.glb```` file - see below.

So indeed the best option for this file is to load it directly using ````GLTFLoaderPlugin````.

````
node --max-old-space-size=18076 convert2xkt.js  -t -c convert2xkt.conf.json -s public-use-sample-apartment.glb -o geometry.xkt                         -l 
[convert2xkt] Running convert2xkt v1.1.15-beta-4...
[convert2xkt] Using JSON configs file: convert2xkt.conf.json
[convert2xkt] Converting single input file public-use-sample-apartment.glb...
[convert2xkt] Reading input file: public-use-sample-apartment.glb
[convert2xkt] Input file size: 16178.78 kB
[convert2xkt] Not embedding metadata in XKT
[convert2xkt] [ERROR]: [parseGLTFIntoXKTModel] Error: maxMemoryUsageInMB limit exceeded by at least 225MB
````
