### ISSUE TITLE
After rotating a model, I get the wrong aabb values

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1316]
**Describe the bug**
Rotating a model makes its aabb wrong

**To Reproduce**
1. Open the https://xeokit.github.io/xeokit-sdk/examples/buildings/#xkt_vbo_Duplex example
2. Rotate the model by 40° in Y axis
`viewer.scene.models.myModel.rotation = [0, 40, 0]`
4. check its abb, you get the wrong values

**Expected behavior**
The aabb is still right after rotation

**Screenshots**

I made a script that draws a transparent cube given an aabb for testing:

```js
const makeBox = (aabb) => {
  new Mesh(viewer.scene, {
    geometry: new ReadableGeometry(
      viewer.scene,
      buildBoxGeometry({
        center: [
          (aabb[3] + aabb[0]) / 2,
          (aabb[4] + aabb[1]) / 2,
          (aabb[5] + aabb[2]) / 2,
        ],
        xSize: (aabb[3] - aabb[0]) / 2, // Half-size on each axis
        ySize: (aabb[4] - aabb[1]) / 2,
        zSize: (aabb[5] - aabb[2]) / 2,
      })
    ),
    material: new PhongMaterial(viewer.scene, {
      // diffuseMap: new Texture(viewer.scene, {
      //   src: "textures/diffuse/uvGrid2.jpg",
      // }),
      backfaces: true,
      alpha: 0.2,
    }),
  });
};
```
It is correct initially before rotation

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/e5abd114-12f7-4c9d-9190-69835f8e0725)

But after rotating:

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/08fb4a4b-94e1-4159-8864-1c9cdd0921e0)

**Desktop (please complete the following information):**
 - Device: Laptop HP Zbook
 - OS: Windows 64bit
 - Browser: Chrome
 - Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by paireks** [comment]
My observation after looking at it for a while, is that after the rotation (e.g. changing position doesn't seem to have a problem) the size of aabb seems probably fine, but its the position of aabb which is wrong.
I can't find out however why wrong aabb is actually calculated.
SceneModelEntity during get aabb() do this += this.origin of the aabb, so maybe there is something with this origin. But it's difficult to spot how this origin is being calculated and when.

**Comment by paireks** [comment]
Few additional observations:
- It looks like setting a quaternion instead of rotation also ends up with wrongly positioned AABB.
- Setting position ends up with correct AABB.
- In fact every SceneModelMesh has wrongly positioned AABB (but with the right size).
- In web-ifc example every SceneModelMesh has this.origin = [0,0,0], while in xkt every SceneModelMesh has this.origin is [4.4000000432133675, 2.542399935674667, 8.900000043213367]

**Comment by intrida-dev** [comment]
Has this been fixed? [#1379](https://github.com/xeokit/xeokit-sdk/issues/1379)  this seems to be closed.

**Comment by xeolabs** [comment]
@intrida-dev It has not been fixed. For distantly-placed models, I have not been able to make individual object rotations on objects work within xeokit's RTC tiles coordinate system. I'm not sure of a solution for that at this stage. Only translations currently work for all models.

**Comment by intrida-dev** [comment]
@xeolabs Ok. We will try applying translations until this gets fixed. Thanks

**Comment by paireks** [comment]
It looks there is something wrong with aabb and origins that I cannot figure out (it is probably not related to rotations though).
![image](https://github.com/user-attachments/assets/71d1ece9-c930-489f-a84c-14e16ac9a2ee)
Here is this code: https://github.com/paireks/xeokit-sdk/blob/develop/RotationCalculation/examples/scenegraph/error_AABB.html
Depending if I comment or uncomment this console.log line here: https://github.com/paireks/xeokit-sdk/blob/develop/RotationCalculation/examples/scenegraph/error_AABB.html#L70 
I get either left or right.

**Comment by paireks** [comment]
Here is an example with .xkt file loaded: https://github.com/paireks/xeokit-sdk/blob/develop/RotationCalculation/examples/scenegraph/error_AABB_xkt.html


![2024-09-12_22h00_09](https://github.com/user-attachments/assets/f8e1c935-f8de-4c49-a935-8be8c42d4888)
