### ISSUE TITLE
PointerLens require dtxEnabled ?

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#1323]
**Describe the bug**
when using pointerLens error occur is dtxEnabled is not set to true on viewerConfig.

**To Reproduce**
1. init viewer instance (without setting dtxEnabled to true)
2. init loader and load model
3. init measurement Tool (andle or distance) with a pointerLens
4. activate measurement tool.
5. see error on first loading page.

**Expected behavior**
i don't know if dtxEnabled is required for pointerLens to function, if its the case it should be mentioned in the docs that it is imperative to enable it, if its not the case well pointerLens should work.

**Screenshots**
![image](https://github.com/xeokit/xeokit-sdk/assets/50522164/68f1c6a7-421c-4f02-a3b4-524495e4f48d)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome v120.0.6099.200
 - xeokit v2.5.1-beta
 - node v18.6.0

**Comment by assaad97** [comment]
this is a repo to reproduce the error https://github.com/assaad97/xeokitBugs

**Comment by xeolabs** [comment]
I just tried the reproduction repo (thanks for that, ideal for reproducing issues) and it seems OK with @xeokit/xeokit-sdk 2.5.2-beta-4 (Ubuntu / Chrome)
Try upgrading to that version, and if it works OK, we'll just close this issue and keep an eye open for this happening again. I must have broken and fixed something inadvertently. 

PointerLens has no dependency on dtxEnabled BTW

[Screencast from 11.01.2024 18:11:18.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/850e6610-0f59-40b7-af63-c4466e30710b)

**Comment by assaad97** [comment]
@xeolabs works with version 2.5.2-beta-4, thanks for the response.
