### ISSUE TITLE
[FEATURE]:Enable external render functions for treeview

### ISSUE THREAD

**Issue by mlankamp** [xeokit/xeokit-sdk#1325]
In the TreeViewPlugin move the functions:
- _createNodeElement
- _expandSwitchElement
- _collapseNode
- _collapseSwitchElement

to the constructor and allow these functions to be overwritten via the constructor configuration.

This allows users to create their own styling. 

Alternative solution:
Create a render service, which can be passed via the constructor (same as the localeService).

**Comment by mlankamp** [comment]
I created a PR to support this scenario #1329

**Comment by xeolabs** [comment]
Looks good, thanks @mlankamp. Could we please also get an HTML example page to demo it? Maybe just base it off this one: https://github.com/xeokit/xeokit-sdk/blob/master/examples/navigation/TreeViewPlugin_Containment.html

**Comment by mlankamp** [comment]
Yes, I will create an example! Will include the x-rayed style as well.

**Comment by mlankamp** [comment]
Done, see PR #1331

**Comment by mlankamp** [comment]
@xeolabs is it possible to create a new beta? Will upgrade my typescript based solution and can check if the typings are ok

**Comment by xeolabs** [comment]
@mlankamp yip, done - 2.5.2-beta-5

**Comment by mlankamp** [comment]
Nice, with the latest merge the example works: https://xeokit.github.io/xeokit-sdk/examples/navigation/#TreeViewPlugin_options_renderService

**Comment by xeolabs** [comment]
Could it be extended to create IFC element icons on the tree nodes, do you think? Maybe extend the callback to take a MetaObject, then add class names to node elements to style them with the corresponding icon?

**Comment by mlankamp** [comment]
That should be possible, will try tomorrow

**Comment by mlankamp** [comment]
The MetaObject contains the type, which I can use to render an icon in the treeview. I came up with this example:
![image](https://github.com/xeokit/xeokit-sdk/assets/8513556/c4213f05-969c-4f1d-86ad-149a18bf93d5)

We could a helper class, which maps a ifc type to a specific icon (font-awesome and material design icons). Or even better, is there a defined icon set?

**Comment by mlankamp** [comment]
Found this: https://aecgeeks.github.io/ifc-icons/ (source: https://github.com/AECgeeks/ifc-icons)

**Comment by xeolabs** [comment]
> Found this: https://aecgeeks.github.io/ifc-icons/ (source: https://github.com/AECgeeks/ifc-icons)

Yip that's the one I had in mind!

**Comment by mlankamp** [comment]
This uses the google Material Icons, I've created my example based on the material design icons library.
