### ISSUE TITLE
Measurements always have null entity

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1337]
**Describe the bug**
Listening to measurementEnd always yields a null entity on both `origin` and `target`

**To Reproduce**
1. Go to https://xeokit.github.io/xeokit-sdk/examples/measurement/#distance_createWithMouse_snapping
2. Listen to `measurementEnd`

```
distanceMeasurementsPlugin.on("measurementEnd", (measurement) => {
    console.log("origin", measurement.origin.entity);
    console.log("target", measurement.target.entity);
});

```

4. Log entity in `origin` and `target`
5. They're null

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/959fdae5-08fd-4a12-8c02-0624b0fb3f6a)

**Expected behavior**
They're the correct entities

**Comment by paireks** [comment]
If I understand correctly the behaviour - attaching Entity to a specific Marker is optional, so it can be null.

**Comment by hamza-hajji** [comment]
@paireks yeah they can be null, but since the marker's position is correct, shouldn't the entity not be null?

**Comment by paireks** [comment]
It looks to me, that it's not always null.
When you try to create a dimensions while the mouse pointer is red (e.g. in the middle of the wall) the Entity will be attached automatically.
However there are some other errors showing off in the console, I will take a look.

**Comment by paireks** [comment]
Ok, so it seems to me that it works once you draw dimensions on a specific Entity - then it will attach the Entity.

**Comment by hamza-hajji** [comment]
@paireks you're right, the issue only occurs when you snap (pointer is green)

**Comment by hamza-hajji** [comment]
@paireks @xeolabs I'd like to fix the issue locally and create a PR, but the build scripts doesn't work for me locally

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/97e05a3a-98bf-4bcd-95b1-4ffb6b08b683)

**Comment by paireks** [comment]
I personally can't help you with build, as I haven't run npm run build myself, only change the js files and test the changes
