### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by mlankamp** [xeokit/xeokit-sdk#1341]
For people wanting to start with xeokit and typescript, I made an example site

**source**
https://github.com/mlankamp/vue-xeokit

main file: https://github.com/mlankamp/vue-xeokit/blob/main/src/App.vue

**output**
https://mlankamp.github.io/vue-xeokit/

**Comment by xeolabs** [comment]
Woa thanks @mlankamp - I'll check this out later tonight!
