### ISSUE TITLE
.d.ts files creation

### ISSUE THREAD

**Issue by paireks** [xeokit/xeokit-sdk#1345]
During a struggle to properly update SceneModel.d.ts I've found out, that some content between .js and .d.ts are different, meaning:
- there are different params for .d.ts and .js files for the same methods
- there are different comments for some parameters or methods

which makes me wonder if that is on purpose - then the question would be why there are such differences. Or if it's by mistake: then maybe there could be a better way to keep both worlds the same, such as code generation.

**Comment by xeolabs** [comment]
Yeah those are different - When there is a difference, the .js comments and parameters should be considered the correct ones. 

I'm not aware of any automatic tools to generate the .d.ts files, but would be interested if you happen to find any.

PS. Although several months off from being production ready, xeokit V3 will be natively TypeScript, so we won't have this problem then: https://github.com/xeokit/sdk

**Comment by xeolabs** [comment]
PPS. off-topic but V3 will [support dotbim]( https://xeokit.github.io/sdk/docs/modules/_xeokit_dotbim.html)

**Comment by paireks** [comment]
@xeolabs Great!
Is it possible to locally build version V3 to experiment / contribute right now, or such option will be possible after the release?

**Comment by joshcomley** [comment]
Hello! How far away is V3? Is there a way to locally build and dev against it, now? I tried using the V2 library but the `.d.ts` files have issues (duplicate properties, invalid imports etc.) and the compilation fails. Thank you!
