### ISSUE TITLE
Wrong position of the measurement pointer

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1348]
**Describe the bug**

Positioning the canvas to the right makes the measurement pointer's position wrong

**To Reproduce**
1. Go to https://xeokit.github.io/xeokit-sdk/examples/measurement/#distance_createWithMouse_snapping
2. Give the canvas half the size + move it to the right, in pageStyle.css

```
#myCanvas {
  width: 50%;
  height: 100%;
  position: absolute;
  top: 0;
  right: 0;
  background: lightblue;
  background-image: linear-gradient(lightblue, white);
}
```

Hovering with the mouse gives an offset of the measurement pointer.

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/5c03bb0c-ad3c-4558-a632-c7b928368fd0)

**Expected behavior**

The measurement pointer is in the correct position.

**Comment by xeolabs** [comment]
Fixed in v2.5.2-beta-8
