### ISSUE TITLE
Obj files with multiples textures files

### ISSUE THREAD

**Issue by SoftwareMechanic** [xeokit/xeokit-sdk#1355]
Hello,
I Found that I can load obj files with textures using the SceneModel class.
It works nice, but I am trying to figure out if is possible to have more tiled textures of the same type for one mesh.

i.e.
let's suppose I have one object which is tiled, I could have one obj file with 16 color textures, would be possible to load it ?

**Comment by xeolabs** [comment]
I'm not sure what you mean by tiled, but we only support one texture of each type per mesh. 

Internally, we use loaders.gl to parse OBJ - perhaps take a look at the docs over there for more insights on what's possible with OBJ: https://loaders.gl/docs/modules/obj/api-reference/obj-loader
