### ISSUE TITLE
WebGL error deleting annotation

### ISSUE THREAD

**Issue by iagoandreii** [xeokit/xeokit-sdk#137]
256[.WebGL-0x3310e20ca800]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0

**Comment by Kurtil** [comment]
Indeed, both clear and destroyAnnotation methods of the AnnotationsPlugin lead to this warning in the console.
Also, when deleting annotations, this warning is logged repetitively.

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeokit/xeokit-sdk/commit/13c75988acf8b1d69e98c4879896f89321e57a13
