### ISSUE TITLE
Creating multiple viewers and loading models clears out the old viewers.

### ISSUE THREAD

**Issue by intrida-dev** [xeokit/xeokit-sdk#1370]
**Describe the bug**
In Our application, we create multiple viewers and load models into them. One viewer is shown at a time while others are hidden. When we have axis triad(AxisGizmoPlugin) and nav cube(NavCubePlugin) and then we load 6 models, the first viewer is cleared out(it goes white and there is nothing in the viewer). When we have only one active (either axis triad or nav cube), this issue occurs on loading 9th model. When we don't have both, then it works well (I could load upto 12 models). 

On debug console, we get an error 'Invalid framebuffer'.

We have checked this issue with different versions of xeokit sdk: 2.4.2-beta-31, 2.5.2-beta-8, 2.5.2-beta-13, 2.5.2-beta-22

I have attached a zip file with a sample code to reproduce an issue and a video explaining the issue. Please have a look at it.
[New folder.zip](https://github.com/xeokit/xeokit-sdk/files/14276001/New.folder.zip)

**To Reproduce**
1. Click on 'Load Model' button from top right corner to create and load a model.
2. Create and load 6 models
3. After loading 6th model, select the viewer with index 1 from combo box at top left corner.
4. You will see busy spinner spinning. The viewer background is changed to white and there is no model in viewer. Also there are no axis triad and nav cube.

**Screenshots**
![image](https://github.com/xeokit/xeokit-sdk/assets/73640257/27583a85-bb41-4e73-b9ef-ed6f19258c41)

**Comment by xeolabs** [comment]
Sorry for the lateness on this.

I found the reason - not a xeokit bug, rather that WebGL is not allowing us to have that many WebGL contexts.

It seems that, at least on Chrome/Ubuntu, we're not allowed to have that many WebGL contexts (ie. WebGL canvases) in the DOM at a time.

From the JS console:

![Screenshot from 2024-04-20 15-48-52](https://github.com/xeokit/xeokit-sdk/assets/83100/806ceee5-ab62-499b-8790-05e1a116911f)
