### ISSUE TITLE
"getShapshot" appends canvas elements to the body

### ISSUE THREAD

**Issue by Trufinol** [xeokit/xeokit-sdk#1377]
**Describe the bug**
Whenever "viewer.getShapshot" is called - it creates a snapshot successfully but also adds a canvas element of that snapshot to the body.
The method is also followed by the warning log in the browser's console:
`#1 217ms Unable to clone WebGL context as it has preserveDrawingBuffer=false <canvas id=​"nav-cube-canvas" width=​"140" height=​"140" style=​"visibility:​ visible;​">​`
The complete browser's warning log file is attached
[localhost-1708504159624.log](https://github.com/xeokit/xeokit-sdk/files/14356535/localhost-1708504159624.log)

**To Reproduce**
1. run `viewer.getSnapshot({ format: 'png' })`
2. Check out the canvas element that is appended to the body.

**Expected behavior**
It should not append a canvas element to the body, or the canvas should be removed after the method is complete.

**Screenshots**
![image](https://github.com/xeokit/xeokit-sdk/assets/17147676/4c49ea91-ef78-4168-9770-8ea0299bf8da)
![image](https://github.com/xeokit/xeokit-sdk/assets/17147676/63bf9e03-6191-4677-ba6e-99ee4a72658c)

**Desktop (please complete the following information):**
 - OS: Windows 11, MacOS 14
 - Browser: Mozilla Firefox 122, Chrome 121
 - @xeokit/sdk 2.4.1, also reproducible in 2.4.2

**Comment by paireks** [comment]
Hey :)

I'm trying to reproduce it, but it seems I miss something in the process. I tried to paste viewer.getSnapshot({ format: 'png' }) in a few different examples, but I can't see additional canvases created, and can't see your warning log.
Also if creating snapshots would work that way, I believe all example files from "snapshots" folder would create a warning and append canvas, but they looks fine to me. Or am I missing something? :)

**Comment by xeolabs** [comment]
Not seeing it here either - after running various test examples on my end (like [this one](https://xeokit.github.io/xeokit-sdk/examples/snapshots/getSnapshot_png.html)), I'm not seeing any canvas elements being appended to the DOM. 

We'll re-open if this can be reproduced.
