### ISSUE TITLE
WebIFCLoaderPlugin causes the bundle size to double

### ISSUE THREAD

**Issue by mlankamp** [xeokit/xeokit-sdk#1381]
**Describe the bug**
The size of the SDK is doubled from version 2.3.9 to 2.5.*

**To Reproduce**
Compare:
https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.3.9?activeTab=code
https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.5.2-beta-23?activeTab=code

The file `xeokit-sdk.min.es.js` changed from 2.19 MB to 4.7MB

Why is so much larger?

**Comment by mlankamp** [comment]
Version 2.3.9:
![image](https://github.com/xeokit/xeokit-sdk/assets/8513556/aeeab475-47f1-49a9-8a30-ea9fc78365d8)

Version 2.5.2-beta-23:
![image](https://github.com/xeokit/xeokit-sdk/assets/8513556/4c67db76-2c72-4a7e-ab2a-a72d65666351)

**Comment by xeolabs** [comment]
The `html2canvas`dependency also seems to add many lines of JS. 

I think it would be ideal to move WebIFCLoaderPlugin out to a new package, or even to convert the repository into a monorepo, perhaps using turborepo, with each plugin being it's own package.

**Comment by mlankamp** [comment]
Every plugin as a separate package would be ideal! 

Or maybe for now mark web-ifc as external, so it's not in the bundle (add `external: ['web-ifc']` to rollup) and if you want to use webifc you have to include the dependency yourself?

**Comment by xeolabs** [comment]
Yes that would be a good compromise - we'd need to ensure the live examples for WebIFCLoaderPlugin are updated as well though.

**Comment by mlankamp** [comment]
I will try and if it works I will create a PR (and update the examples where web-ifc is used)

**Comment by xeolabs** [comment]
It's a significant task, to convert xeokit-sdk to a monorepo. I tried a couple of times but kept needing to shelve it as other tasks came up. If you feel up to it, here's a tutorial.. https://turbo.build/repo/docs/handbook 

We also have @xeokit/sdk, the next generation version of xeokit, set up as a monorepo, using the techniques described in that link: https://github.com/xeokit/sdk

That version of xeokit has a different API BTW and is not yet ready to use.

**Comment by mlankamp** [comment]
Or maybe for now only move the webifc to a separate package? As that seems to add an enormous bundle size increase.

Do we have any insights into how many people use the web-ifc plugin (I guess most ifc files are to large to process in the browser anyway)?

**Comment by xeolabs** [comment]
What we could do is make the WebIFC object, from the web-ifc library, a pluggable strategy for WebIFCLoaderPlugin.

Currently the WebIFCLoaderPlugin instantiates WebIFC inside the constructor, ie. 

````javascript
class WebIFCLoaderPlugin extends Plugin {

    constructor(viewer, cfg = {}) {

        super("ifcLoader", viewer, cfg);

        //...
        
       this._ifcAPI = new WebIFC.IfcAPI();

        if (cfg.wasmPath) {
            this._ifcAPI.SetWasmPath(cfg.wasmPath);
        }

        this._ifcAPI.Init().then(() => {
            this.fire("initialized", true, false); // Don't forget the event
        }).catch((e) => {
            this.error(e);
        })
    }
````

but we could instead rely on the user to instantiate it themselves, and pass it into the plugin, ie.

````javascript
class WebIFCLoaderPlugin extends Plugin {

    constructor(viewer, cfg) {

        super("ifcLoader", viewer, cfg);

       // Assume the WebIFC is pre-initialized, with WASM path already set etc

        this._ifcAPI = cfg.webIFC;
    }
````

This way, the user would be responsible for loading the web-ifc library themselves. The WebIFC example pages would need to be updated accordingly as well. They could just load web-ifc from a CDN.

This is actually how we handle the web-ifc dependency in @xeokit/sdk - see this test, where the `loadWebIFC` function accepts the web-ifc API as an argument: https://github.com/xeokit/sdk/blob/develop/packages/webifc/tests/loadWebIFC.test.ts

**Comment by mlankamp** [comment]
I like that solution

**Comment by xeolabs** [comment]
See: https://github.com/xeokit/xeokit-sdk/pull/1401
