### ISSUE TITLE
Floor of my xkt file model isn't displayed correctly

### ISSUE THREAD

**Issue by Layak-Ali** [xeokit/xeokit-sdk#1398]
![Screenshot (46)](https://github.com/xeokit/xeokit-sdk/assets/93964740/f25deb30-a400-451f-8d39-8ef799400064)

The floor of my file isnt displayed correctly. It works fine in gltf and ifc format in other viewers but not in xkt format. Is there any error in my code?

**Comment by xeolabs** [comment]
We would need more information to verify if this is a bug in xeokit:

- the IFC file,
- which conversion tools you used to convert IFC->XKT, and their versions
- the version of xeokit-sdk you're using

thanks

**Comment by xeolabs** [comment]
Closing because not enough info provided to investigate

**Comment by Layak-Ali** [comment]
Unfortunately i cant give send you the ifc file. 
- i tested the ifc file in ifc.js/thatopen.
- convert2xkt, xeokit-metadata and ifcconvert (latest)
- latest
