### ISSUE TITLE
[with solution]: reduce peak memory and reduce 20%~30% execution time for internal method _loadDataIntoModel of XKTLoaderPlugin

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#140]
# Intro 

Both `XKTLoaderPlugin` and `batchingLayer` make extensive use of `array.slice` method to generate sub-views of geometry arrays in their way to GPU-buffers.

Using `array.slice`, as it is used both on `XKTLoaderPlugin` and `batchingLayer` in a cumulative way, has the effect that the peak memory used during `XKT` file loads is 3x of the really needed memory:
- one for the decompressed geometry
- one during `XKTLoaderPlugin` processing
- one during `batchingLayer` processing

One could argue that maybe copy-on-write (COW) semantics in the JS engine could alleviate this effect, but timing bencharks (shown below) suggest that this is not happening on the most advanced JS engine (Chrome on PC), so COW does not seem to enter into action here.

The idea is to replace all occurrences of `array.slice` with `array.subarray` in those files.

Simply a text replace `slice` => `subarray` does the trick.

# One thing to take into account

If complete `slice` => `subarray` replacemenet is used, only one additional ajustment needs to be done.

The following lines of code...

https://github.com/xeokit/xeokit-sdk/blob/5d73c3a60c98abb1f80964568f9aa79f33751667/src/plugins/XKTLoaderPlugin/XKTLoaderPlugin.js#L588-L603

... should be replaced with:

```javascript
 _inflateData(deflatedData) { 
     return { 
         positions: new Uint16Array(pako.inflate(deflatedData.positions).buffer), 
         normals: new Int8Array(pako.inflate(deflatedData.normals).buffer), 
         indices: new Uint32Array(pako.inflate(deflatedData.indices).buffer), 
         edgeIndices: new Uint32Array(pako.inflate(deflatedData.edgeIndices).buffer), 
         meshPositions: new Uint32Array(pako.inflate(deflatedData.meshPositions).buffer), 
         meshIndices: new Uint32Array(pako.inflate(deflatedData.meshIndices).buffer), 
         meshEdgesIndices: new Uint32Array(pako.inflate(deflatedData.meshEdgesIndices).buffer), 
         meshColors: new Uint8Array(pako.inflate(deflatedData.meshColors).buffer), 
         entityIDs: pako.inflate(deflatedData.entityIDs, {to: 'string'}), 
         entityMeshes: new Uint32Array(pako.inflate(deflatedData.entityMeshes).buffer), 
         entityIsObjects: new Uint8Array(pako.inflate(deflatedData.entityIsObjects).buffer), 
         positionsDecodeMatrix: new Float32Array(pako.inflate(deflatedData.positionsDecodeMatrix).buffer) 
     }; 
 } 
```

This prevents the decompressor to see the backing `ArrayBuffer` of the _subarrayed_ data (which is the complete _non-subarrayed_ buffer) and instead see the proper sub-view of the array.

# Some benchmarks

I tested this idea with two `XKT` models, testing the speed improvement by comparing the average of 10 execution times on `XKTLoaderPlugin._loadDataIntoModel` after a warm-up phase of 3 loads:
- model with 3.3M polygons: internal method time reduced to 74% of the original time
- model with 1.7M polygons: internal method time reduced to 80% of the orignal time

Those timing optimitzations effectively suggest that COW mechanism is not used at al by the browser (and could indicate, although I've not measured it, that effectively 3x of the needed CPU-RAM is used during model load), as the point of it is to create a mapped readonly memory region that triggers a copy of itself during a write, and the buffers are not overwritten at all, so the reduced time must account for internal memory copy operations.

**Comment by xeolabs** [comment]
Nice, I just committed this optimization to xeokit master :)

**Comment by tmarti** [comment]
Great!

Byw, I have devised another nice GPU-RAM usage optimization, and will try to create another issue for that one (possibly at the beginning of next week).

That one will not include complete solution as some of your @xeolabs help will be needed to implement it, but will include the explanation of the idea 😉.
