### ISSUE TITLE
Need to load different MTL loading the same .obj with ObjLoaderPlugin

### ISSUE THREAD

**Issue by erikwski** [xeokit/xeokit-sdk#1403]
**Is your feature request related to a problem? Please describe.**
I load an xkt model and need to append the same obj model multiple time. 
If i do that and my .mtl file use the keyword newmtl for create new Material, i will get an error for same material id on PhongMaterial.

**Describe the solution you'd like**
I would like to doesn't need to make manual changes loading different .mtl or use diffent id. Maybe the id of the Material can become `id=${newMtlId}-${objId}`.

**Describe alternatives you've considered**
Load different .mtl, one using newmtl, and the second time use the file with usemtl and retrieve PhongMaterial instance and set to it

**Comment by xeolabs** [comment]
If I understand correctly:

- you load an XKT file
- then load the same OBJ file multiple times
- find there are ID clashes between the PhongMaterials created for the OBJ models

Unfortunately we don't currently support this use case, where we don't support loading multiple copies of the same OBJ model.

If anyone wants to extend OBJLoaderPlugin to enable the PhongMaterials to get non-clashing IDs for this case, we'd consider a PR.

I hope this helps..
