### ISSUE TITLE
Backfaces on GLTF loader makes no difference

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1411]
**Describe the bug**
Setting backfaces=false/true in GLTFLoaderPlugin#load makes no difference whether the backfaces are shown or not

**To Reproduce**
1. Load this example locally https://xeokit.github.io/xeokit-sdk/examples/buildings/#glTF_Duplex_transform
2. Set the backfaces to false on the loader, (it is false by default, but setting it to true made no difference)
3. Zoom into the upper room
4. You can see the backfaces of the room (see screenast)

**Expected behavior**
Loading it into a [GLTF viewer](https://gltf-viewer.donmccurdy.com/) and zooming into the upper room, you can see the backfaces are transparent (see screenshot)

I'm not sure if this is the param to do this, because that's how it's described in the docs:

>When true, allows visible backfaces, wherever specified in the glTF. When false, ignores backfaces

**Screencasts**

![zoomintoroof](https://github.com/xeokit/xeokit-sdk/assets/26790341/c6c61a79-94d9-484d-b91f-88ad6ef997f9)

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/b60059e3-f424-4299-811d-5d1346ea65c6)

**Comment by xeolabs** [comment]
Fixed by modifying the behaviour of the `backfaces` option:

- Make the `backfaces` option `true` by default 
- When true, always show backfaces, even on objects for which the glTF material is single-sided
- When false, only show backfaces on geometries whenever the glTF material is double-sided.

**Comment by xeolabs** [comment]
Hi could you please provide the glb model so we can debug?

> Seems like backfaces was true.

Could you please clarify here - do you mean in the code or in the model?
 
thanks

**Comment by tgranie** [comment]
Please find an example here (glb zipped) :
[02_07_2024.zip](https://github.com/user-attachments/files/16069847/02_07_2024.zip)

Basically we would like the backfaces to be transparent :

![image](https://github.com/xeokit/xeokit-sdk/assets/105110014/2608e14b-be7c-4cd0-960f-af3da6c27570)

**Comment by tgranie** [comment]
@xeolabs Does it clarify the issue ?
