### ISSUE TITLE
Geometry Distortion in Model after IFC to XKT Conversion

### ISSUE THREAD

**Issue by rafaeldemiranda95** [xeokit/xeokit-sdk#1415]
Hello, Xeokit team,

I'm encountering an issue where the geometry of a model appears distorted in the xeokit viewer. This issue emerges after converting an IFC file to XKT through a multi-step process - specifically, converting from IFC to DAE, then DAE to glTF, and finally glTF to XKT using version 1.4.0 of the bimspot/xeokit-converter.

**Conversion Process:**

The IFC file is first converted to DAE.
The DAE file is then converted to glTF.
Finally, the glTF file is converted to XKT.
Upon loading the XKT file into the xeokit viewer, the geometry of the model displays incorrectly.

**Expected Result:**
The expectation is for the model to display with its geometry intact, accurately representing the original IFC file's structure.

**Actual Result:**
Instead, the model's geometry in the viewer is broken or distorted, which compromises the visual integrity of the model.
![screencast-newtab-2024 03 14-10_34_28-_online-video-cutter com_](https://github.com/xeokit/xeokit-sdk/assets/37124918/973b5b92-4a4f-4e42-a1c2-dfda31576cde)

This distortion seems specific to this model and conversion process. Other models converted in a similar manner did not show this issue, which suggests a possible issue with the conversion process or this particular model.

I would greatly appreciate your guidance on resolving this geometry distortion or any insights into potential conversion errors that might be contributing to this problem.

Best regards,
Rafael de Miranda

**Comment by paireks** [comment]
Hello Rafael

This jittering looks like precision issue to me at first glance. Is it possible for you to share the problematic XKT file?

Also if you are one of the enterprise users: please log this issue with our Jira.

**Comment by paireks** [comment]
Ok, thank you :)

Just for internal conversation - I could recreate it (using FastNavPlugin_HolterTower example). Model is far from origin:
![image](https://github.com/xeokit/xeokit-sdk/assets/47977819/fffe1972-8203-4f12-b3dd-2970c733b911)

**Comment by xeolabs** [comment]
@rafaeldemiranda95 try these conversion pipelines:

* Open source tools: https://www.notion.so/xeokit/Converting-IFC-Models-to-XKT-using-Open-Source-Tools-A-Simpler-Pipeline-02d45ba457eb4f808f63bcacb71a4fb3

* Using proprietary `ifc2gltf`, which @paireks mentioned: https://www.notion.so/xeokit/Converting-IFC-to-XKT-using-ifc2gltfcxconverter-a2e0005d00dc4f22b648f1237bc3245d

Note that we never use the COLLADA2GLTF tool anymore in the open source connversion pipeline, because:

- `IfcConvert` can convert IFC->glTF/glb, and `convert2xkt` can convert that to XKT
- `COLLADA2GLTF` introduces some rounding error in its matrix math for big transforms

**Comment by xeolabs** [comment]
If you use the proprietary `ifc2gltf` pipeline, this page is also useful for understanding its options: https://xeokit.github.io/xeokit-model-conversion-tests/ifc-tests.html

Basically, we're always able to avoid jittering in models these days, so it should be a matter of getting the right conversion pipeline working.

**Comment by rafaeldemiranda95** [comment]
Thanks, @xeolabs and @paireks. I’ll explore the recommended conversion methods and review additional settings. Appreciate both of your help.
