### ISSUE TITLE
BCF camera up

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#142]
I've noticed something interesting while working on https://github.com/xeokit/xeokit-sdk/issues/139.

If we take a look at the source code for the BCFPlugin's `setViewpoint` method, [specifically where it sets the camera properties](https://xeokit.github.io/xeokit-sdk/docs/file/src/plugins/BCFViewpointsPlugin/BCFViewpointsPlugin.js.html#lineNumber354), it seems that you're not applying the values for the `up` property.

- in line 358, `up` is initialised, its value at this point is `undefined`
- line 365 (or 374 for ortho), `camera.up` is given the value from the BCF viewpoint; note that this value is set directly on `camera.up` instead of `up` that was previously initialised
- in line 379, `camera.up` is set to the value of `up`, which is... well... still undefined

[Passing `undefined` (or any falsey value for that matter) to `camera.up` will restore the default value, which is: `[0, 1, 0]`.](https://xeokit.github.io/xeokit-sdk/docs/file/src/viewer/scene/camera/Camera.js.html#lineNumber485)

I'm afraid I don't know enough on the subject of properly converting and setting BCF viewpoints, so I'm not sure if the `camera.up` values need to remain the default or they should be set to the values received from the BCF viewpoint.

But what happens in the highlighted segment does seem a bit counterintuitive to me, nonetheless.

Would you please have a look and weigh in when you get the chance?

Cheers

**Comment by xeolabs** [comment]
Thanks @barnabasmolnar - I just pushed a fix: https://github.com/xeokit/xeokit-sdk/commit/8ed86834df0faf3a4effc566ec57826fab2b1f68

**Comment by barnabasmolnar** [comment]
Looks good, thank you!
