### ISSUE TITLE
How to add properties section?

### ISSUE THREAD

**Issue by Layak-Ali** [xeokit/xeokit-sdk#1420]
I couldnt find properties section in xeokit docs. I tried but its not working correctly. Where to find the code for properties?
![Screenshot (48)](https://github.com/xeokit/xeokit-sdk/assets/93964740/9136a58a-b424-4419-95e8-4ab15fac3aa7)

**Comment by xeolabs** [comment]
PropertySets are extracted from the IFC only using our proprietary IFC conversion tool, `ifc2gltfcxconverter`.

The third-party `xeokit-metadata` tool from BIMData does not support property set extraction from IFC.

Usage of `ifc2gltfcxconverter` is described here: https://xeokit.github.io/xeokit-model-conversion-tests/ifc-tests.html

Please contact [here](https://xeokit.io/for-business) if you would like to evaluate this tool.

**Comment by Layak-Ali** [comment]
@xeolabs is there a way i can add properties section for free?

**Comment by xeolabs** [comment]
@Layak-Ali you could extend the xeokit-metadata tool to extract the property sets from the IFC - https://github.com/bimspot/xeokit-metadata
