### ISSUE TITLE
How to disable right mouse drag in first person mode

### ISSUE THREAD

**Issue by Candy-u** [xeokit/xeokit-sdk#1432]
`cameraControl.navMode = 'firstPerson'` 
hi~,when I set it to 'firstPerson' and I want to disable right clicking to drag a model, how should I set it

**Comment by xeolabs** [comment]
Hi, there is currently no way to disable right-licking dragging in first-person mode, it's intentional that we are still able to do that.
Could you describe your reason for needing to disable it?
thanks

**Comment by Candy-u** [comment]
Thank you for your reply. The reason for disabling is that:I want to contrast it with the panorama and at the same time, the position of the camera didn't allow to move.

---Original---
From: "Lindsay ***@***.***&gt;
Date: Tue, Apr 9, 2024 19:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xeokit/xeokit-sdk] How to disable right mouse drag in firstperson mode (Issue #1432)




 
Hi, there is currently no way to disable right-licking dragging in first-person mode, it's intentional that we are still able to do that.
 Could you describe your reason for needing to disable it?
 thanks

**Comment by xeolabs** [comment]
> contrast it with the panorama and at the same time, the position of the camera didn't allow to move

I'm not quite following what you mean here - perhaps a diagram?

**Comment by Candy-u** [comment]
Sorry about that.&nbsp;
What I want to do is set up a comparison between a 3D panoramic image and a model, with both presented in first-person perspective. The catch is, for the model part, I need to lock the viewpoint so it doesn't change, which is exactly why I'd like to disable dragging functionality – to maintain a fixed perspective throughout the comparison.




---Original---
From: "Lindsay ***@***.***&gt;
Date: Tue, Apr 9, 2024 21:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xeokit/xeokit-sdk] How to disable right mouse drag in firstperson mode (Issue #1432)




  
contrast it with the panorama and at the same time, the position of the camera didn't allow to move
  
I'm not quite following what you mean here - perhaps a diagram?
