### ISSUE TITLE
I want to show wireframe,not show edge

### ISSUE THREAD

**Issue by atlas1119** [xeokit/xeokit-sdk#1435]
I want to show wireframe,not show edge.
How?

**Comment by xeolabs** [comment]
https://xeokit.github.io/xeokit-sdk/examples/scenemodel/#dtx_instancing_geometries

![Screenshot from 2024-04-13 07-18-16](https://github.com/xeokit/xeokit-sdk/assets/83100/09faa8bd-c30a-4b8a-b4c9-39c6d6e7407f)
