### ISSUE TITLE
Question: Determine world position to entity type.

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1439]
It's possible to determine world position is surafce, edge or vertex like `viewer.scene.pick({canvasPos: [...]})` but use `worldPos` instead of `canvasPos` ? So if I have world position I want to now what is it.

**Comment by xeolabs** [comment]
Maybe ray-picking is what you need: https://xeokit.github.io/xeokit-sdk/examples/picking/#pick_ray_surface

**Comment by g-rodigy** [comment]
Ray-picking not contain this info, can get only entity and some other, not about edge or surface.
