### ISSUE TITLE
Impossible to move plane in Section Plane plugin on z axis

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#144]
When a section plane is just created, it is impossible to move it on the z axis (for me it is the red arrow) because this function (https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/SectionPlanesPlugin/Control.js#L947) return a planeNormal like this : [NaN, NaN, NaN].
In the case of the z axis, the worldAxis is [1,0,0,0] and the cross vector of twice the same vector return [0,0,0] (https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/SectionPlanesPlugin/Control.js#L954).

Maybe the error is due to the if/else above that do not track correctly this use case...

**Comment by Amoki** [comment]
On line https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/SectionPlanesPlugin/Control.js#L950, `worldAxis` is used as an object with x, y and z properties. On line https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/SectionPlanesPlugin/Control.js#L973, `worldAxis` is an array. 
Therefore, in `getTranslationPlane()` the check `if (absX > Math.abs(worldAxis.y) && absX > Math.abs(worldAxis.z)) {` is always false (`worldAxis.y` in undefined) and the bug may come from here

**Comment by xeolabs** [comment]
@Kurtil @Amoki I just pushed a fix for the bug @Amoki just mentioned.
