### ISSUE TITLE
[FIX] SceneModelTransform: parentTransformId parameter doesn't work

### ISSUE THREAD

**Issue by lzoia-bc** [xeokit/xeokit-sdk#1441]
**Describe the bug**

The `parentTransformId` parameter in the `createTransform` method of a `SceneModel` is ignored due to the following error in the code
```
if (this.parentTransformId) {
    parentTransform = this._transforms[cfg.parentTransformId];
    if (!parentTransform) {
        this.error("[createTransform] SceneModel.createTransform() config missing: id");
        return;
    }
}
```
Here the code should check `cfg.parentTransformId` instead of `this.parentTransformId`.

**To Reproduce**

1. Create a SceneModel
2. Create the base [SceneModelTransform](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/model/SceneModelTransform.js~SceneModelTransform.html)
3. Create a new [SceneModelTransform](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/model/SceneModelTransform.js~SceneModelTransform.html) specifying the previous one as parent
4. Create a new [SceneModelMesh](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/model/SceneModelMesh.js~SceneModelMesh.html) using the latest transform id

**Expected behavior**
The create mesh should be transformed according to the composition of ParentTransform and Transform

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 2.5.2-beta-32

**Additional context**
This error should fixed in a new release of the 2.5 version

**Comment by lzoia-bc** [comment]
I tried the latest version `2.6.0` and the `parentTransformId` doesn't work still.
I suppose the error now is inside `SceneModel.createTransform` when the transform is created. I see that the parent transform is sent to the `SceneModelTransform` constructor using the parameter `parentTransform`, while the `SceneModelTransform` constructor code is reading `cfg.parent`. 
I think this bug is still present since is not possible to use the parentTransformId feature yet

**Comment by xeolabs** [comment]
I haven't made a test yet, but seemed an obvious thing to patch - try: https://github.com/xeokit/xeokit-sdk/releases/tag/v2.6.1

**Comment by lzoia-bc** [comment]
I just tried and I'm getting the following error
```
TypeError: childTransform._setWorldMatrixDirty is not a function
    at SceneModelTransform._addChildTransform (xeokit-sdk.es.js:80390:1)
    at new SceneModelTransform (xeokit-sdk.es.js:80383:1)
    at SceneModel.createTransform (xeokit-sdk.es.js:83363:1)
```

**Comment by lzoia-bc** [comment]
I just tried with `2.6.2` and I'm getting the following error

```
TypeError: childTransform._setAABBDirty is not a function
    at SceneModelTransform._addChildTransform (xeokit-sdk.es.js:80391:1)
    at new SceneModelTransform (xeokit-sdk.es.js:80383:1)
    at SceneModel.createTransform (xeokit-sdk.es.js:83363:1)
```

**Comment by lzoia-bc** [comment]
I modified locally `childTransform._setAABBDirty();` with `childTransform._setSubtreeAABBsDirty(this);` and it seems to work fine against my code

**Comment by lzoia-bc** [comment]
I created this PR with the above change https://github.com/xeokit/xeokit-sdk/pull/1469

**Comment by lzoia-bc** [comment]
Re-opened PR https://github.com/xeokit/xeokit-sdk/pull/1471
