### ISSUE TITLE
Restrict gestures to having effect only inside the canvas, not in the outer html elements

### ISSUE THREAD

**Issue by vaziliybober** [xeokit/xeokit-sdk#1442]
I'm having issue with zooming in and out with pinch gesture on macbook trackpad. This gesture both zooms in/out the model inside the canvas and the whole website page as well. Also when I use scrolling on the canvas in order to zoom in/out the model gets zoomed in/out but also the outer element gets scrolled in/out.

Please help me understand how to restrict gestures of zooming the model to only the canvas itself. How can I prevent the zooming and scrolling of the outer page?

1. Go to any example of xeokit. For instance: https://xeokit.github.io/xeokit-sdk/examples/buildings/#glTF_VianneyHouse
2. Zoom in/out with pinch gesture on your trackpad or with ctrl/command + mouse wheel up/down
3. See that the whole page gets zoomed in/out, not only the model

Expected behavior:

Only the model is zoomed. For example on this page https://sbcode.net/react-three-fiber/event-propagation/ you can scroll down to "Using stopPropagation to Stop Events from Going Behind" header and try to zoom/scroll the model there and see that the rest of the page stays unchanged. Only the model is affected

**Comment by g-rodigy** [comment]
I had similar issue, but I use viewer on fullscreen. It can be help.
````js
document.getElementById(canvasElement).addEventListener("wheel",
  function(e) {
	  e.preventDefault()
	  return false
  },
  {passive: false}
)
````

**Comment by vaziliybober** [comment]
@g-rodigy, wow that did help! Both with scrolling and pinching. Thank you
