### ISSUE TITLE
Does XKT support points metadata?

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1446]
We're exploring the possibility of showing points metadata (classification, 8-bit values per point, etc).
Does XKT support this kind of data? Can we show/hide points with filters on these values?

**Comment by xeolabs** [comment]
Not currently - this is our current metadata schema: https://github.com/xeokit/xeokit-convert/blob/main/specs/xkt_v10_metadata.schema.json

However, we would be very interested in any ideas you have for support for point metadata, and cases for filtering.

Regarding filtering, do filter on intensity, however - see this demo: https://xeokit.github.io/xeokit-sdk/examples/lidar/#laz_NallsPumpkinHill
