### ISSUE TITLE
Fix SectionPlanesPlugin overview for orthographic projection

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#145]
When changing from perspective to ortho, the section plane overview seems to be broken and the planes move very slowly :
Perspective :
![Screenshot 2019-09-09 at 17 38 36](https://user-images.githubusercontent.com/22523482/64545497-2175d100-d329-11e9-800b-10863d25f3c7.png)
Ortho : 
![Screenshot 2019-09-09 at 17 38 50](https://user-images.githubusercontent.com/22523482/64545507-26d31b80-d329-11e9-8d1d-833df046aa37.png)

**Comment by Kishanpparmar** [comment]
facing the same issue.
this happens because of camera.ortho.near and far.

Still finding a solution.
