### ISSUE TITLE
GLTFSceneModelLoader - backfaces option throw `undefined` if material in primitive.material is missing

### ISSUE THREAD

**Issue by vsigno** [xeokit/xeokit-sdk#1458]
**Describe the bug**
In #1449 if GLTF material is undefined in [line 523](https://github.com/xeokit/xeokit-sdk/blob/1a927e9858855da7605c4cac46eb5457bb3a6b7b/src/plugins/GLTFLoaderPlugin/GLTFSceneModelLoader.js#L523), `const backfaces` in [line 537](https://github.com/xeokit/xeokit-sdk/blob/1a927e9858855da7605c4cac46eb5457bb3a6b7b/src/plugins/GLTFLoaderPlugin/GLTFSceneModelLoader.js#L535) throw an `undefined` TypeError when it tries to access `doubleSided`.

**To Reproduce**
It’s possible that the GLTF model I’m using has a missing material, however, it was loaded correctly using [2.6.0-beta13](https://github.com/xeokit/xeokit-sdk/tree/v2.6.0-beta-13) 

**Current fix**
Setting `param.backfaces` explicitly to `true` when loading the GLTF model in `GLTFLoader.load` avoids the error. Even if `true` should be the default value for `ctx.backfaces`.

**Comment by xeolabs** [comment]
Fixe now in https://github.com/xeokit/xeokit-sdk/releases/tag/v2.6.2
