### ISSUE TITLE
How can I disable logging in console of the library

### ISSUE THREAD

**Issue by vaziliybober** [xeokit/xeokit-sdk#1465]
Hello. How can I disable messages in console like "Creating VBOInstancingTrianglesLayer" or "[xeokit plugin XKTLoader]: Loading .xkt V10"?

Thank you!

**Comment by paireks** [comment]
Hello @vaziliybober :) maybe I'm missing something, but I cannot see a way to disable all console.logs coming from sdk. I can see there are hacky ways to e.g. disable all console.logs, but I think they shouldn't been used. Can we ask you what is the reason for such request?

**Comment by vaziliybober** [comment]
@xeolabs any progress on this?
