### ISSUE TITLE
AngleMeasurementsPlugin red dot is not at the position of the mouse pointer

### ISSUE THREAD

**Issue by Trufinol** [xeokit/xeokit-sdk#1479]
**Is this bug fix critical for your commercial enterprise?**
no

**Describe the bug**
When a viewer is mounted inside a modal window, the red dot position of a AngleMeasurementsPlugin or DistanceMeasurementsPlugin does not match the cursor position.

**To Reproduce**
1. Mount a model inside of a modal window with some margin around the viewport.
2. Enable the AngleMeasurementsPlugin or or DistanceMeasurementsPlugin.
4. See that the red dot is not under the mouse cursor.

**Expected behavior**
Red dot should be positioned on the mouse cursor.

**Screenshots**
![image](https://github.com/xeokit/xeokit-sdk/assets/17147676/ce932b15-28d5-482e-a808-714304e04509)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 124.0.6367.119 (Official Build) (arm64)

**Comment by xeolabs** [comment]
Getting the red dot to appear at the right position has been a weirdly difficult thing to make work robustly for all page layouts.

All we want to do is transform a 2D position from canvas coordinates to page coordinates, but it seems that no matter what we've tried so far, there's always some layout for which our built-in function doesn't work correctly.

Therefore, I made that canvas->page 2D transformation user-configurable via a callback on the measurements plugins.

Could you see if you can implement this callback to do the transformation yourself - see this example: https://github.com/xeokit/xeokit-sdk/blob/master/examples/measurement/angle_createWithMouse_snapping_canvasToPagePos.html#L194

Then, if you find something that works, that might give us a clue on how to more correctly implement the mapping internally.

Thanks

**Comment by Trufinol** [comment]
Thank you for the hint. 
In my case, applying `canvasPos` to `pagePos` fixed the issue. 
However, in the typescript definition the `canvasToPagePos` is missing at both DistanceMeasurementsMouseControl and AngleMeasurementsMouseControl.

https://github.com/xeokit/xeokit-sdk/blob/master/types/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsMouseControl.d.ts
https://github.com/xeokit/xeokit-sdk/blob/master/types/plugins/AngleMeasurementsPlugin/AngleMeasurementsMouseControl.d.ts
 Is it possible to include it in the next minor release or do you need any participation on this?

**Comment by xeolabs** [comment]
> Thank you for the hint. In my case, applying `canvasPos` to `pagePos` fixed the issue. However, in the typescript definition the `canvasToPagePos` is missing at both DistanceMeasurementsMouseControl and AngleMeasurementsMouseControl.
> 
> https://github.com/xeokit/xeokit-sdk/blob/master/types/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsMouseControl.d.ts https://github.com/xeokit/xeokit-sdk/blob/master/types/plugins/AngleMeasurementsPlugin/AngleMeasurementsMouseControl.d.ts Is it possible to include it in the next minor release or do you need any participation on this?

Oops I'll fix that tonight - https://github.com/xeokit/xeokit-sdk/issues/1481
