### ISSUE TITLE
Width of cross-section lines

### ISSUE THREAD

**Issue by paireks** [xeokit/xeokit-sdk#1483]
Question is if we can somehow add width to the "lines" of cross-sections.

As these are not lines, but colored pixels on a triangle, it's hard for me to figure out if it is possible to add some thickness to these colored triangles.

Such feature would be helpful once someone look at the cross-section from the same point as the clipping plane (which is the most popular option for looking at cross-sections), cause it could make it much more visible, once someone would increase the "line width".

**Comment by xeolabs** [comment]
Just a note: WebGL on Windows AFAIK still has a limitation where lines can only be one pixel wide, because their WebGL is built on DirectX, which has this limitation.
