### ISSUE TITLE
Can't load Las, Laz models from Electron app

### ISSUE THREAD

**Issue by intrida-dev** [xeokit/xeokit-sdk#1485]
We have an application which is built only to run in ElectronJS. Recently we implemented Las/Laz loading capability and found that it doesn't work in ElectronJS App. We get following error:
![image](https://github.com/xeokit/xeokit-sdk/assets/73640257/8d346b5e-3a54-4d33-a234-c33e3b85c2e4)

But we can load the same model with same code when it is viewed in browser. I have attached a video explaining this issue.

https://github.com/xeokit/xeokit-sdk/assets/73640257/75ae3087-cfd5-45bd-b228-2e128592690f

We debugged a little and found an issue in _canParseWithWorker_ function. If statement at line number 108996 evaluates to true, when it is from Electron.
![image](https://github.com/xeokit/xeokit-sdk/assets/73640257/145ae717-b6a1-4890-8d0e-62d59e06c015)

Also I have attached a sample code in zip.
[sample.zip](https://github.com/xeokit/xeokit-sdk/files/15257651/sample.zip)

**To Reproduce**
1. First place '_autzen.laz_' sample model in models directory
2. Open the attached sample code in VS code and go to terminal
3. Execute '_npm install electron_'
4. Run command '_npm start_' to launch electronjs app.
5. See error on console

**Comment by xeolabs** [comment]
This looks like an issue with the 3rd-party library, [loaders.gl](https://loaders.gl/docs/modules/las/api-reference/las-loader), which we use for loading LAS/LAZ. 

We've never developed any xeokit applications on Electron unfortunately, so I'm not sure what to suggest, but I recommend logging the issue with the [loaders.gl](project).

**Comment by intrida-dev** [comment]
Sure, I am going to report this to them. Thanks :-)
