### ISSUE TITLE
model.opacity  error

### ISSUE THREAD

**Issue by atlas1119** [xeokit/xeokit-sdk#1486]
gltfLoader
model.opacity = 0.3
![image](https://github.com/xeokit/xeokit-sdk/assets/9478646/13593530-cde9-4e2f-bccf-2cce847e21fa)

why?

**Comment by xeolabs** [comment]
This is a problem with your model, where the vertices in its geometry have an irregular vertex winding order. Not all triangles have their vertices specified in the same order, causing some to be interpreted as front faces, and others interpreted as back faces. The front faces are rendered, and the back faces are culled. You need to fix your model.

**Comment by paireks** [comment]
Just to add: you can use Blender (free and open-source) to fix such model problems. E.g. have a look here: https://www.youtube.com/watch?v=p4yDKp2MtlI
