### ISSUE TITLE
Annotation: pins are missplaced if the canvas is not at the top left of the page.

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#149]
![image](https://user-images.githubusercontent.com/1349751/64852899-93e0fc80-d61a-11e9-826f-8f1760c880cd.png)

@xeolabs, you fixed a similar issue in our xeogl version here https://github.com/bimdata/viewer.js/commit/8d321f7322dc9e3bc6a08a158cf5196ffd8a6c6b
(Sorry for others, the repo is not public)

**Comment by xeolabs** [comment]
Maybe this fixes things - I've not documented it yet, but we can supply a container element for the annotations like this:

````javascript
const annotationsPlugin = new AnnotationsPlugin(this.viewer, {
        container: document.getElementById(cfg.containerId),
//...
});
````

**Comment by Kurtil** [comment]
Elements inside canvas are considered [alternative content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#Alternative_content). They will be rendered only as fallback. I manage to use the container option like this : 
```
container: document.getElementById(cfg.containerId).parentElement
```
But be aware that padding on the canvas may move annotation out of their corresponding spot...
