### ISSUE TITLE
BIMServerLoaderPlugin not rendering geometries properly

### ISSUE THREAD

**Issue by sha-N** [xeokit/xeokit-sdk#15]
Hi, I was checking out this SDK as a replacement for BIMSURFER, Great Job 👍. 

But Im facing an issue, the plugin loads structural IFC files properly, but for IFC files containing pipes or those type of geometries, the objects look pixelated and shake while moving the camera. 

Does this has anything to do with the plugin being based on PerformanceModel.

Is this being worked on?
![capture](https://user-images.githubusercontent.com/12491622/52964118-9cd65c00-33b2-11e9-8950-97796dbe9fef.PNG)

_Originally posted by @sha-N in https://github.com/xeokit/xeokit-sdk/issues/5#issuecomment-464797607_

**Comment by sha-N** [comment]
Side note

BIMSURFER2 which is based on SceneJS renders the above model as follows

![image](https://user-images.githubusercontent.com/12491622/52970845-5db20600-33c6-11e9-9b08-ccab8139b353.png)

and in BIMSURFER3 when quantization is disabled, it also behaves in a similar fashion.

**Comment by sha-N** [comment]
@xeolabs can you provide some pointers on where to start for resolving this, I just got started on this whole bimserver stuff a week back, trying to catch up on what is available and how is it done.

**Comment by xeolabs** [comment]
This is a quantization accuracy error, which is not an error within xeokit as such. It is caused by your floating-point geometry losing accuracy when xeokit internally quantizes it to integers. Two things you can try:

- increasing or decreasing the scale of your model
- ensuring that your model is centered at ````[0,0,0]````

For example:

````javascript
var model = bimServerLoader.load({
    //..
    scale: [0.5, 0.5, 0.5],    
    position: [-90, 0, 0] 
});
````

**Comment by sha-N** [comment]
Thank you for the reply, I had tried changing scaling with no luck.

can internal quantization be disabled once, *** Download quantized geometry from BIMServer - in progress** is done

**Comment by xeolabs** [comment]
No, quantization ican't be disabled. Are you able to share your IFC file, or any IFC file that reproduces this issue for you? Then I can investigate ways to make quantization more robust.

**Comment by sha-N** [comment]
Yes, I will send you the link in mail, shall i send to this id lindsay.kay@xeolabs.com ?

Please check of a solution as this SDK is kind of a perfect solution for the problem Im trying to solve.

**Comment by xeolabs** [comment]
Yes, please send to that email, thanks.

**Comment by sha-N** [comment]
Hi, were you able to reproduce the issue

**Comment by sha-N** [comment]
Hi, Solved the issue as per your comment by setting the `position:` parameter.

Right now it is kind of a workaround, 
- loading the model without position
- get initial camera position
- use inverse of these coordinates on next load with position.

One question though, why xeogl is not recognizing the coordinates on its own.

**Comment by xeolabs** [comment]
@sha-N yes I'll add an option to BIMServerLoader - see https://github.com/xeokit/xeokit-sdk/issues/22
