### ISSUE TITLE
[with solution]: reduce the time it takes to set flags, flags2 and colors arrays during model load

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#150]
According to this post...

https://stackoverflow.com/questions/16462517/bufferdata-usage-parameter-differences

... following lines of code...

https://github.com/xeokit/xeokit-sdk/blob/6cf15138b78169be8c0552d528b3aef5d16a8dc7/src/viewer/scene/PerformanceModel/lib/batching/batchingLayer.js#L378

https://github.com/xeokit/xeokit-sdk/blob/6cf15138b78169be8c0552d528b3aef5d16a8dc7/src/viewer/scene/PerformanceModel/lib/batching/batchingLayer.js#L382-L383

https://github.com/xeokit/xeokit-sdk/blob/6cf15138b78169be8c0552d528b3aef5d16a8dc7/src/viewer/scene/PerformanceModel/lib/instancing/instancingLayer.js#L331

https://github.com/xeokit/xeokit-sdk/blob/6cf15138b78169be8c0552d528b3aef5d16a8dc7/src/viewer/scene/PerformanceModel/lib/instancing/instancingLayer.js#L336-L337

... should have its array type changed from `gl.STATIC_DRAW` to `gl.DYNAMIC_DRAW`, as the colors and flags(2) arrays values are not fixed upon creation, but they will be set from time to time due to end-user API usage and (most important) they will be massively set during model initialization.

In the case of `XKTLoaderPlugin`, those very simple changes reduce the time it takes to execute the internal `_loadDataIntoModel` function to about 92% of the original time.

**Comment by xeolabs** [comment]
Nice. I'd actually assumed those directives weren't that important on WebGL, but the numbers don't lie, so I'll patch this in.
