### ISSUE TITLE
Implementation with Vue.js

### ISSUE THREAD

**Issue by yearmfew** [xeokit/xeokit-sdk#1503]
Hi, I am trying to use xeokit with vue.js. I need to use IFC file for my application. I am using the codes in npm documentation but I have timeout error. 

`Uncaught RuntimeError: memory access out of bounds
    at web-ifc.wasm:0xb495
    at web-ifc.wasm:0x37929
    at web-ifc.wasm:0xcf0c8
    at web-ifc.wasm:0xc5d69
    at Proxy.OpenModel (eval at newFunc (web-ifc.js?t=1716452265981&v=98734fb6:6132:31), <anonymous>:9:10)
    at Proxy.OpenModel (web-ifc.js?t=1716452265981&v=98734fb6:65374:34)
    at WebIFCLoaderPlugin._parseModel (@xeokit_xeokit-sdk.js?t=1716452265981&v=98734fb6:106204:34)
    at @xeokit_xeokit-sdk.js?t=1716452265981&v=98734fb6:106174:14
    at request.onreadystatechange (@xeokit_xeokit-sdk.js?t=1716452265981&v=98734fb6:105894:13)`

How can I solve it? Or is it even possible to use web-ifc with vue.js?

**Comment by xeolabs** [comment]
Does this happen for you with this example, without Vue? 
https://xeokit.github.io/xeokit-sdk/examples/buildings/#web-ifc_vbo_Duplex

**Comment by yearmfew** [comment]
Yes. It works without vue.js

**Comment by xeolabs** [comment]
This sounds like a Vuew-related peculiarity relating to [web-ifc](https://github.com/ThatOpen/engine_web-ifc) rather than to xeokit - I'd recommend seeing in the web-ifc project if there are any Vue-related issues. Not sure what we can do on the xeokit end unfortunately.

**Comment by paireks** [comment]
Also just to add, maybe have a look here: https://github.com/ThatOpen/engine_web-ifc/issues?q=memory+access+out+of+bounds

Cause it looks like such exception happens from time to time there, so maybe it's somehow related to your case :)
