### ISSUE TITLE
Entities are not registered for models loaded using GLTFLoaderPlugin

### ISSUE THREAD

**Issue by jbenhardus** [xeokit/xeokit-sdk#1504]
**Is this bug fix critical for your commercial enterprise?**
We have potential workarounds, but this affects required functionality for our application

**Describe the bug**
When loading a model in `.glb` or `.gltf` format, `scene. objects` is empty. This prevents the use of methods and properties such as `scene.objectIds` and `scene.setObjectsVisible` to show or isolate objects in the scene.

**To Reproduce**
1. Load a model using `GLTFLoaderPlugin`, providing urls for `src` and `metaModelSrc`
2. Inspect `viewer.scene.objects` using a breakpoint or console log statement
3. `viewer.scene.objects` is empty and `scene.setObjectsVisible` does not change visibility of objects

**Expected behavior**
`viewer.scene.objects` should be populated, and `scene.setObjectsVisible` should update the visibility of objects

**Screenshots**

https://github.com/xeokit/xeokit-sdk/assets/12035748/c72ce901-4615-4653-9630-f9dfb046288f

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1
 - Browser: Chrome
 - Version: 125.0.6422.61

**Additional context**
It appears the issue arises because the `loadNode` function in `GLTFSceneModelLoader` calls `sceneModel.createEntity` without specifying the `isObject` property in the config object (example [here](https://github.com/xeokit/xeokit-sdk/blob/0d3bc436e920b24bc180159dde8e6fa6e8bd530a/src/plugins/GLTFLoaderPlugin/GLTFSceneModelLoader.js#L631-L638)). Adding `isObject: true` to the config fixes the issue I am experiencing

**Comment by xeolabs** [comment]
This should be OK now in the latest xeokit-sdk release - please try that and close this issue if it looks good.

**Comment by jbenhardus** [comment]
Thanks! This seems to be working as expected now.
