### ISSUE TITLE
GLTFLoader does not support fully PBR

### ISSUE THREAD

**Issue by tgranie** [xeokit/xeokit-sdk#1507]
**Describe the bug**

- Following https://github.com/xeokit/xeokit-sdk/issues/1506, Same code
- Load the glb file attached using the code
- Load the glb file attached in https://3dviewer.net

**Expected behavior**

The glb should be rendered

**Screenshots**

_xeokit with pbr enabled_

![image](https://github.com/xeokit/xeokit-sdk/assets/105110014/41a1dcf0-abbf-47f5-85d2-6d8525ed5bc8)

_3dviewer_ 

![image](https://github.com/xeokit/xeokit-sdk/assets/105110014/d2f41e0c-811a-419a-a9d3-02164bb51055)

**Comment by xeolabs** [comment]
Note that the microfacet BRDF needs a reflection map to show the roughness aspect. The roughness channel works by perturbing the reflection from the reflection map - see this example:

https://github.com/xeokit/xeokit-sdk/blob/master/examples/navigation/TreeViewPlugin_Containment_3DXML.html#L306

**Comment by xeolabs** [comment]
However, what we are missing in glTF/GLB support so far is the bump mapping.

**Comment by tgranie** [comment]
@xeolabs Thanks for you answer : is there any plan to support this ?

**Comment by xeolabs** [comment]
We don't have it on the roadmap at present, but please contact management at Creoox if it's vital for your enterprise and we can discuss. We only handle basic materials at this stage, as required for AECO apps. Thanks
