### ISSUE TITLE
Consider renaming metrics.js - It is getting blocked by ublock plugin

### ISSUE THREAD

**Issue by TheLaughableCoder** [xeokit/xeokit-sdk#151]
I had an error trying to load models, and it was because my ublock extension through that this file was tracking me.

Consider renaming.

**Comment by barnabasmolnar** [comment]
A +1 on this. I've since disabled uBlock specifically for the xeokit site but I'd imagine others might run into this issue too and may be left thinking that the examples are just straight up broken.

**Comment by xeolabs** [comment]
Yeah sounds like it's necessary, I'll rename. I need to think up a new name though, so if you guys have any suggestions, that'd be appreciated.

The [Metrics](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/metrics/Metrics.js~Metrics.html) component "Configures its Scene's measurement unit and mapping between the Real-space and World-space 3D Cartesian coordinate systems."

There's probably a more appropriate name for this component anyway..

**Comment by xeolabs** [comment]
Fixed - https://github.com/xeokit/xeokit-sdk/commit/4de23f059a57be878409b5dd4f4fe47deb6b5f38
