### ISSUE TITLE
SnapPick don't work without canvasPos?

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1537]
**Describe the bug**
Hello. Has error when try get `viewer.scene.pick()` with params `origin`,  `direction` and `snapToEdge: true`. Got error 
>Cannot read properties of undefined (reading '0') at ...

reading '0' is canvasPos[0]
https://github.com/xeokit/xeokit-sdk/blob/160b384c1ee5063a0a5fbe4e899f2e744b67d23d/src/viewer/scene/webgl/Renderer.js#L1319-L1322

**To Reproduce**
````js
viewer.scene.pick({
   origin,
   direction,
   pickSurface: true,
   pickSurfaceNormal: true,
   pickSurfacePrecision: true,
   snapToEdge: true,
   snapToVertex: false,
})
````

**Expected behavior**
If found entity get nearest edge like work with `canvasPos`.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 126

**Additional context**
xeokit-sdk v2.6.9

**Comment by xeolabs** [comment]
Yes, `Scene.snapPick()` only works with `canvasPos` - I've updated the docs accordingly.

BTW do you represent one of our enterprise users? If so, please get in touch and we can prioritize support via our Jira:  https://creoox.com/en/contact/
