### ISSUE TITLE
UI freeze on large model load

### ISSUE THREAD

**Issue by vaziliybober** [xeokit/xeokit-sdk#1547]
Hey! With large models it takes a few seconds to load them, and it freezes UI of the whole page. I'm using XKTLoaderPlugin for loading. Is there a way to prevent that somehow? Maybe via service workers? Thanks!

**Comment by xeolabs** [comment]
You could try loading multi-XKT models via a manifest, as described here: https://xeokit.github.io/xeokit-model-conversion-tests/ifc-tests.html
