### ISSUE TITLE
DistanceMeasurementsPlugin typescript definitions is not up to date

### ISSUE THREAD

**Issue by Trufinol** [xeokit/xeokit-sdk#1572]
I'm not sure if it's a bug or a missing feature...

**Describe the bug**
Typescript definition of DistanceMeasurementsPlugin is not up to date with the documentation.
For instance, `setAxisVisible` method is not defined in the typescript definitions
https://github.com/xeokit/xeokit-sdk/blob/master/types/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsPlugin.d.ts
 even though it is present in the documentation
https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/DistanceMeasurementsPlugin/DistanceMeasurement.js~DistanceMeasurement.html

**Comment by xeolabs** [comment]
This should be fixed in the latest release, will reopen if it persists.
