### ISSUE TITLE
Remove zipping compression from XKT format

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#1580]
Create a new XKT format, v11. 

In this format, remove zip compression. 

* removing the zipping that's done in `xeokit-convert` - [see here](https://github.com/xeokit/xeokit-convert/blob/main/src/XKTModel/writeXKTModelToArrayBuffer.js)
* make `xeokit-convert` mark each new XKT it creates as version 11
* Create a new `ParserV11.js` parsing strategy for [`XKTLoaderPlugin`](https://github.com/xeokit/xeokit-sdk/tree/master/src/plugins/XKTLoaderPlugin), identical to `ParserV10.js`, but with unzipping removed.
* be sure to register the new parser strategy with the plugin - [see here](https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/XKTLoaderPlugin/XKTLoaderPlugin.js#L31) 

This will create larger XKT files, but they will load faster into the Viewer, since it won't have to unzip their data. It will also consume less memory in the browser while loading.

## Caveat

Let's start by removing Zipping for everything except for the ID strings. 

It may make sense to keep zipping in place for the ID strings in the XKT format though. 

Or, we may want to pack the strings into an arraybuffer, unzipped, or something like that.

Also we may want to just to use numbers for the IDs of the meshes and geometries, and only use strings for the model object IDs. The IDs meshes and geometries are only local to the model, so it's kind of wasteful to make those strings.

**Comment by Amoki** [comment]
gzip widely used in the web will compensate for the unzipped part of the xkt anyway :)

**Comment by xeolabs** [comment]
I really got stuck on this one, so would welcome a PR if anyone has the time!

I just couldn't get the buffers for each array packing and unpacking right in the XKT ArrayBuffer.

**Comment by xeolabs** [comment]
Completed - see https://github.com/xeokit/xeokit-sdk/pull/1635
