### ISSUE TITLE
Cachebuster doesn't work with data urls

### ISSUE THREAD

**Issue by schlundus** [xeokit/xeokit-sdk#1590]
**Describe the bug**
Cachebuster introduced in v2.6.18 doesn't seem to work with blob urls

**To Reproduce**
Have an blob with valid content... try to load it with cachebuster enabled using xktloader
![image](https://github.com/user-attachments/assets/765caddf-5768-456b-92c5-29bfaa129f81)
this modies the blob's data url 
to something like blob:http://localhost:11000/47eec4c9-c66a-4da1-9bc1-86fee1609eec?_=1721378727455
and the resulting url is no longer valid  for loading  a blob...
![image](https://github.com/user-attachments/assets/61477690-ab02-4256-9cbf-c7f21246bc87)

If i disable cachebuster the data url is not modified and it works

**Expected behavior**
data urls should not be modified

**Comment by xeolabs** [comment]
Hi, do this to disable cache busting:

````
xktLoader.dataSource.cacheBuster = false;
````
