### ISSUE TITLE
gltfLoad model， I want to see all the information on the back，backfaces ，It doesn't work？

### ISSUE THREAD

**Issue by atlas1119** [xeokit/xeokit-sdk#1592]
![image](https://github.com/user-attachments/assets/7aba77ff-1b57-409b-ae37-5d8e67f00da3)
![image](https://github.com/user-attachments/assets/4b12ac1e-0e4e-44d5-b791-9c8a2633e104)

From this perspective, you can see 2 circles, but if you look at it from another angle, you won't be able to see 2 circles. Why?
I want to see from any angle, what should I do?

**Comment by xeolabs** [comment]
Rendering of transparent objects is unfortunately dependent on the order  in which they are rendered, where farthest objects need to be rendered first, closest last, for correct alpha blending. This is an inherant limitation of WebGL / OpenGL, for which order-independent transparency algorithms exist, but are not implemented in xeokit for performace reasons. For the purpose of rendering buildings, this is not a problem for our users ordinarily. However is unfortunately a problem for your model. Not much we can do unfortunately.
