### ISSUE TITLE
Some material is white

### ISSUE THREAD

**Issue by amirandaspace** [xeokit/xeokit-sdk#1593]
Some concrete material is always in white color. 
My opinion, the code is not getting the correct parameter from material in some cases. Why so white?

![Captura de tela 2024-07-24 180931](https://github.com/user-attachments/assets/0fd995ae-87bf-4cf5-af6e-37fdb8ac2a19)

**Comment by xeolabs** [comment]
For us to reproduce and investigate this issue, could you please provide us with the IFC model, and details of how you convert and load it into xeokit. 
thanks

**Comment by amirandaspace** [comment]
You can download here: https://1drv.ms/u/s!AjdDvfmGmjP6nZcKxkCqACBzV8UOBw?e=DHYWxV
Command to convert: node .\convert2xkt.js -s 'file.ifc' -o 'file.xkt' -l

**Comment by xeolabs** [comment]
We won't fix this at this time, however if this is critical for your enterprise application, please get in touch here and we can prioritise a fix: https://creoox.com/en/contact/

If you do happen to have time to fix this issue we are also happy to accept a PR on xeokit-convert.

If this is critical to your enterprise, we recommend using the `ifc2gltfcxconverter`, which is entirely maintained by us and gives better results. This particular conversion option uses the third-party `web-ifc` library, which sometimes gives mixed results.

Thanks
