### ISSUE TITLE
Control camera panning out of view.

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1598]
Can control and stop pan when model located outside camera/canvas view?
I not found any params for this and no events fired when pan.

**Comment by xeolabs** [comment]
I'm not sure what you mean, could you please clarify?

**Comment by g-rodigy** [comment]
![image](https://github.com/user-attachments/assets/54f2e36a-f876-4ef5-9deb-997221c13ef7)
When move model (up on screenshot) by right mouse button restrict this move when model reach the border (perimeter red line) or cross border on half for example.
Prevent the model from going out of sight.

**Comment by xeolabs** [comment]
No, that's not currently implemented. Please log a request with our service desk if this is critical to your enterprise. Thanks
