### ISSUE TITLE
Delay on pick entity

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#160]
What is this timer for ?
https://github.com/xeokit/xeokit-sdk/blob/0c2ede0593787373e311e5cc7e5333bf1ce2a4ff/src/viewer/scene/camera/CameraControl.js#L1477-L1497
It leads to some delay when picking entity. I removed it and it seems to work correctly (tested on a track pad).

**Comment by Kurtil** [comment]
Ok I get it it is for the double click... But maybe the "dblclick" event could be more appropriate ?

**Comment by Kurtil** [comment]
My bad... I thought that in 2019 we could distinguish between simple and double click but after some research, it appears that we can't. Sorry for the noise.

**Comment by Kurtil** [comment]
For info : 
```
viewer.cameraControl.doublePickFlyTo = false
```
will not add the timeout on simple click ! 👍 ❤️

**Comment by xeolabs** [comment]
Yes that timeout is to differentiate between single and double click/tap. We wait to see if there is a second click/tap before firing any event to indicate single-click/tap. I'm not too happy with it. 

When I need a fast single-click pick, I've been doing this sort of thing:

````javascript
                const lastCoords = math.vec2();

                this._onMousedown = this.viewer.scene.input.on("mousedown", (coords) => {
                    lastCoords[0] = coords[0];
                    lastCoords[1] = coords[1];
                });

                this._onMouseup = this.viewer.scene.input.on("mouseup", (coords) => {
                    if (entity) {
                        if (!closeEnough(lastCoords, coords)) {
                            entity = null;
                            return;
                        }
                        entity.visible = false;
                        entity.highlighted = false;
                        entity = null;
                    }
                });
````
