### ISSUE TITLE
Cannot remove treeView from DOM

### ISSUE THREAD

**Issue by Nxito** [xeokit/xeokit-sdk#1606]
# Objective

Im trying to clean the scene, the treeviewPlugins and the annotations.
I dont know if is there an easy way but....

# The bug

In the code i just see that the nodes inside the tree are recreating when i try to remove them

```js
   .......
  removeModel(modelId) {
    if (!this._containerElement) {
      return;
    }
    const metaModel = this._metaModels[modelId];
    if (!metaModel) {
      return;
    }
    if (this._rootNames[modelId]) {
      delete this._rootNames[modelId];
    }
    delete this._metaModels[modelId];
    this._createNodes();
  }
.........
```

![image](https://github.com/user-attachments/assets/35316ef9-5ee4-4683-88a0-0fc20f5289f4)

Note: I try to remove the ul directrly on the HTML but when i try to load a new model i got the error : 
`TypeError: Cannot read properties of null (reading 'removeChild')` 
inside *_createNodes()* function

## Depenencies  :
"@xeokit/xeokit-sdk": "2.6.28",
"vite": "^5.3.1",
"web-ifc": "0.0.55"

**Comment by xeolabs** [comment]
Yeah possibly this is a bug where a TreeViewPlugin that's configured to automatically rebuild itself when a new model is loaded will not allow you to remove the model manually. 

See what happens when you configure the TreeViewPlugin with autoAddModels and add/remove models manually.

**Comment by Nxito** [comment]
Sorry for not updating this.
In the end what I did was delete the trees and then the model and metamodels from the scene. All  in this order :

```js

function removeTrees() {
  viewer._plugins
    .filter((e) => e.id == "TreeViewPlugin")
    .forEach((tree) => {
      Object.keys(viewer.scene.models).map((k) => {
        tree.removeModel(k);
      });

      tree._rootElement?.remove();
      tree._rootElement = null;
    });
}

function removeModels(params) {
  Object.keys(viewer.scene.models).map(k=>{ 
    viewer.metaScene.destroyMetaModel(k)
    return  viewer.scene.models[k].destroy()
   })
}

function cleanScene() {
  removeTrees()
  removeModels() 
}

```
For my part, this is no longer a problem.
