### ISSUE TITLE
Cannot remove AngleMeasurementPlugin 'pointer dot' when deactivating control

### ISSUE THREAD

**Issue by vaziliybober** [xeokit/xeokit-sdk#1610]
With AngleMeasurementPlugin, there is a dot that is visible near your mouse pointer. The problem is that this dot does not disappear once the control is deactivated. It stays wherever your mouse last was at the time of deactivation.

Steps to reproduce:

```
const angleMeasurementsPlugin = new AngleMeasurementsPlugin(viewer);
const startMeasurement = () => {
  angleMeasurementsPlugin.control.activate();
};
const endMeasurement = () => {
  // This leaves the 'pointer dot' at the location of your mouse at the time of calling this function.
  // But it should not leave that dot
  angleMeasurementsPlugin.control.deactivate();
};
```

You can also see this bug in xeokit examples, for example here: https://xeokit.io/demo.html?projectId=RAC

Just make sure the angle measurement tool is over some object, turn on the tool, see the dot, click on the tool again to deactivate it.

Expected result: the dot is no longer visible
Actual result: the dot remains near the angle measurement tool toggle button and just stays there.
<img width="372" alt="image" src="https://github.com/user-attachments/assets/32c500bc-a791-4b17-a990-b8037742b067">

**Comment by MichalDybizbanskiCreoox** [comment]
Hi @vaziliybober , thank you for the report.
What xeokit-sdk release are you using?

**Comment by MichalDybizbanskiCreoox** [comment]
Thank you @vaziliybober , we've identified the issue and prepared a fix. It'll be merged to the master branch, and will end up in next release.

**Comment by MichalDybizbanskiCreoox** [comment]
Hi @vaziliybober , the fix has been merged to the master branch.

**Comment by MichalDybizbanskiCreoox** [comment]
The fix is included by the latest release https://github.com/xeokit/xeokit-sdk/releases/tag/v2.6.35
