### ISSUE TITLE
Screen recording breaks DistanceMeasurementsPlugin

### ISSUE THREAD

**Issue by RCRJ** [xeokit/xeokit-sdk#1611]
**Is this bug fix critical for your commercial enterprise?**
- Not critical

**Describe the bug**
- Starting a screen recording causes the [DistanceMeasurementsPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsPlugin.js~DistanceMeasurementsPlugin.html) to work incorrectly
- The updated cursor UI is still showing where a measurement would start, however the click events behave as if the user is rotating / panning the model
- The example below is using the DistanceMeasurementsPlugin [Example 2: Create distance measurements with mouse](https://xeokit.github.io/xeokit-sdk/examples/measurement/#distance_createWithMouse_snapping)
  - In this example, I created one measurement before starting a recording software, and you can see my mouse trying to create a second measurement afterwards

https://github.com/user-attachments/assets/9fe75bfd-2ae7-4c7a-b796-8db02eac1a93

**To Reproduce**
1. Go to the DistanceMeasurementsPlugin demo: [Example 2: Create distance measurements with mouse](https://xeokit.github.io/xeokit-sdk/examples/measurement/#distance_createWithMouse_snapping)
2. Validate that you can create a measurement
3. Start a screen recording software
4. Again try to create a measurement

**Expected behavior**
Measurements should work after starting a screen recording

**Desktop (please complete the following information):**
 - OS: MacOS 14.5 (23F79) Sonoma
 - Browser: Chrome
 - Version: 127.0.6533.89 (Official Build) (arm64)
 - Recording software: MacOS builtin recording tool

**Comment by xeolabs** [comment]
I'm not sure this is anything we can fix - it sounds like interference between recording software and browser, not specific to xeokit AFAIK. Does it happen with any other web frameworks or applications?

**Comment by RCRJ** [comment]
Great suggestion:
- Firefox: No Issue
- Safari: Same Issue
- Other recording software: No issues

So I think that narrows down the problem to using MacOS's builtin Quicktime recorder on Chrome and Safari.
