### ISSUE TITLE
IFC loader fails

### ISSUE THREAD

**Issue by jameshickman** [xeokit/xeokit-sdk#1645]
I am the creator of a Drupal integration for XeoKit, https://github.com/jameshickman/drupal_xeokit

I just did a fresh install for my module running `npm i @xeokit/SDK`, and now my front-end script is giving me `Uncaught Parameter expected: WebIFC' when it creates the WebIFCLoaderPlugin object. I have not changed my code, but I had not reinstalled Xeokit in several months, so something has changed in the SDK, or so it appears.

See line 57 of viewer.js

Thank you.

**Comment by xeolabs** [comment]
Hi, this is the breaking change that is likely affecting you: https://github.com/xeokit/xeokit-sdk/pull/1401

BTW we now have a changelog - keep an eye open for anything labeled "breaking": https://github.com/xeokit/xeokit-sdk/blob/master/CHANGELOG.md

**Comment by jameshickman** [comment]
Got it. Thank you.
