### ISSUE TITLE
XTKLoaderPlugin broken

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#166]
Please see my comment here: https://github.com/xeokit/xeokit-sdk/pull/164#issuecomment-535938839

@xeolabs, would you please fix it? I'd rather not go through the whole PR process for one missing `}` :smile:

**Comment by Amoki** [comment]
A fix has just been merged! https://github.com/xeokit/xeokit-sdk/pull/165

**Comment by barnabasmolnar** [comment]
Thanks. Closing this issue as soon as my build runs.
