### ISSUE TITLE
object.numPrimitives and numTriangles are NaN

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1671]
**Describe the bug**
`object.numPrimitives`  and `object.numTriangles` are NaN for all objects with VBO loaded from xkt (didn't try with other loads).

**To Reproduce**
1. Open https://xeokit.github.io/xeokit-sdk/examples/buildings/xkt_vbo_RACHouse.html
2. in console: `viewer.scene.objects['1bOeIks4fCNAuMrZZw4irh'].numPrimitives` or `viewer.scene.objects['1bOeIks4fCNAuMrZZw4irh'].numTriangle`
3. Response is `NaN`

**Expected behavior**
Be able to retrieve the number of primitives

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser: Firefox & Chrome
 - Version: latest

**Comment by Amoki** [comment]
Thanks!

**Comment by MichalDybizbanskiCreoox** [comment]
Hi @Amoki, you're welcome!
Please mind that although the fix has been merged to the `master` branch, it hasn't been released yet.
Best,
  Michał
