### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by eriadam** [xeokit/xeokit-sdk#168]
We would love to have the automated build process for every commit in order to check for syntax errors, eslint issues, and run unit tests later on, etc. Every pull request then would have to pass these checks before merging.

If OK with you, I would go ahead and add the pipeline.

**Comment by xeolabs** [comment]
Definitely, if you could get Travis hooked up that would be awesome.

**Comment by eriadam** [comment]
Hi @xeolabs , 
as discussed, I am mostly done with the [travis integration](https://github.com/bimspot/xeokit-sdk/blob/ci/.travis.yml).

I would need one input from you regarding the release notes. I have a pretty simple script that takes all commit messages since the last tag and makes a list out of them.

I can filter this list based on any requirements you have.
- Only commits with a certain word in there
- Commits referencing tickets
- Etc.

Please let me know then I can send the pull request.

Cheers,
Adam
