### ISSUE TITLE
Euler angles in model rotation does not work as expected

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1690]
**Describe the bug**

Changing rotation coordinates does not work as expected, this visualization describes how euler angles work

https://danceswithcode.net/engineeringnotes/rotations_in_3d/demo3D/rotations_in_3d_tool.html

If I try the same thing in xeokit, I get very different results

**To Reproduce**
1. Go to an example model https://xeokit.github.io/xeokit-sdk/examples/buildings/#xkt_vbo_Duplex
2. change the x and y coordinates 

```js
const model = viewer.scene.models.myModel
// [pitch, yaw, roll]
model.rotation = [30, 90, 0]
```
![image](https://github.com/user-attachments/assets/bd901801-89d8-4452-98ac-e6f0481f27c5)

Notice how the x and y rotations are always local to the object's axes

**Expected behavior**

I expect the rotation to work like this visualization of euler angles (yaw being y axis, x being pitch)

![image](https://github.com/user-attachments/assets/0c18ee91-4632-4258-9376-bcd6bf9e1a01)

I'm not sure how xeokit calculates rotation, if anyone can provide me with a way to make the object's rotation global instead of local that would be appreciated

Thank you

**Comment by paireks** [comment]
Hello @hamza-hajji,

first thing to remember is that Xeokit has a different coordinate system than the one in this website presented.

IMO in Xeokit it's like this (green one):
![image](https://github.com/user-attachments/assets/253eb9c7-1f9e-4c81-855a-536cfd47447c)

second thing to remember is that Euler angle itself doesn't specify the order in which you should rotate. On this website they rotate in order ZYX, but respectively to their coordinate system.

I'd advise to check the rotations e.g. in Blender where you can specify the order of rotations for Euler angles. Here is some tutorial there that explains the differences: https://www.youtube.com/watch?v=mcDHDfK2pXs

This way you can make sure if everything looks ok.

**Comment by paireks** [comment]
Also please check this example, click on the question mark at the top right and manipulate rotations by sliders to see how it works in Xeokit: https://xeokit.github.io/xeokit-sdk/examples/lidar/#xkt_MAP_alignPointCloud

**Comment by hamza-hajji** [comment]
@paireks thanks for your response, it seems in the rotation setter, you use an XYZ order when setting the quaternion

```js
// Mesh.js
set rotation(value) {
    this._rotation.set(value || [0, 0, 0]);
    math.eulerToQuaternion(this._rotation, "XYZ", this._quaternion);
    this._setLocalMatrixDirty();
    this._setAABBDirty();
    this.glRedraw();
    this.fire("rotation", this._rotation);
}
```

Is it possible to override the XYZ order in this code (either by doing computation on my side or throught modifying the library)? Do the rotation angles care about the order you pass to quaternion setter or it's just in xeokit that you do only one order?

Thanks for taking the time to respond 🙏

**Comment by MichalDybizbanskiCreoox** [comment]
Hi @hamza-hajji , there's an alternative way to control a `Mesh`'s rotation through the `Mesh::quaternion` setter, as defined at
https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/mesh/Mesh.js#L481-L494

This way you can transform a local euler angle with a local order to a quaternion, and have it assigned to the `Mesh`, e.g.:
`model.quaternion = math.eulerToQuaternion([30, 90, 0], "ZYX");`

Hope this helps!

**Comment by MichalDybizbanskiCreoox** [comment]
@hamza-hajji 
Both `Mesh::quaternion` and `Mesh::rotation` setters modify "private" `Mesh::_quaternion` and `Mesh::_rotation` properties, which are kept in sync.
The difference is a type of an input value either of the setters take.

**Comment by hamza-hajji** [comment]
@MichalDybizbanskiCreoox excuse me but if I do

```js
model.quaternion = math.eulerToQuaternion([30, 90, 0], "ZYX");
``` 

the quaternion setter will override the rotation value with a XYZ rotation based on my quaternion, so they will be out of sync, no?

```js
math.quaternionToEuler(this._quaternion, "XYZ", this._rotation);
```

since `math.quaternionToEuler()` does set `this._rotation`

**Comment by MichalDybizbanskiCreoox** [comment]
@hamza-hajji right, if that's what you mean then it's correct - `Mesh::rotation`'s value, which is defined in the "XYZ" order, might not be the same as your `math.eulerToQuaternion`'s argument if applied with the "ZYX" order.

If you wanted to get an arbitrarily ordered euler angle value from a `Mesh`, you could use a symmetrical call:
```js
const euler = math.quaternionToEuler(model.quaternion, "ZYX");
```

Please keep in mind however, that `euler` value might not be what was initially used as the `math.eulerToQuaternion` argument, because 
`quaternionToEuler(eulerToQuaternion(E, O), O)` does not necessarily equal `E`.

**Comment by hamza-hajji** [comment]
> @hamza-hajji right, if that's what you mean then it's correct - `Mesh::rotation`'s value, which is defined in the "XYZ" order, might not be the same as your `math.eulerToQuaternion`'s argument if applied with the "ZYX" order.
> 
> If you wanted to get an arbitrarily ordered euler angle value from a `Mesh`, you could use a symmetrical call:
> 
> ```js
> const euler = math.quaternionToEuler(model.quaternion, "ZYX");
> ```
> 
> Please keep in mind however, that `euler` value might not be what was initially used as the `math.eulerToQuaternion` argument, because `quaternionToEuler(eulerToQuaternion(E, O), O)` does not necessarily equal `E`.

@MichalDybizbanskiCreoox wouldn't it be simpler if instead of hardcofing the XYZ, there's a Mesh#eulerOrder that I can set like

```js
model.eulerOrder = "ZYX";
model.quaternion = [x, y, z, w];
```
