### ISSUE TITLE
[Regression] metaModel is no longer available in metaObjects

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1705]
**Describe the bug**
Meta model is no longer available in meta objects

**To Reproduce**

Render the example XKT model

```js
const viewer = new Viewer({
  canvasId: "myCanvas",
  transparent: true,
  saoEnabled: false,
});

viewer.scene.camera.eye = [
  14.915582703146043, 14.396781491179095, 5.431098754133695,
];
viewer.scene.camera.look = [
  6.599999999999998, 8.34099990051474, -4.159999575600315,
];
viewer.scene.camera.up = [
  -0.2820584034861215, 0.9025563895259413, -0.3253229483893775,
];

const xktLoader = new XKTLoaderPlugin(viewer);

const sceneModel = xktLoader.load({
  id: "myModel",
  src: "./models/Duplex_A_20110505.glTFEmbedded.xkt",
  saoEnabled: false,
  edges: true,
  dtxEnabled: true,
});

```

Try to log any metaObject `viewer.metaScene.metaObjects['06uoIsbYr35x9JXU7VZ77u']`, its metaModel is `null`

**Expected behavior**
The meta model is there

**Screenshots**

![image](https://github.com/user-attachments/assets/cbef265e-60aa-48b0-83ac-8c2384346876)

**Comment by hamza-hajji** [comment]
Hello @xeolabs is there any update on this issue?

**Comment by xeolabs** [comment]
See https://github.com/xeokit/xeokit-sdk/pull/1753
