### ISSUE TITLE
[Regression] Treeview plugin, rootnode renders `na` instead of rootName

### ISSUE THREAD

**Issue by mlankamp** [xeokit/xeokit-sdk#1706]
**Describe the bug**
The treeview plugin allows to specify the rootName for a model, but since version `2.6.48` it renders `na` instead of the rootName

**To Reproduce**
Add a model manually using:
```
    treeviewPlugin.addModel(modelId, {
      rootName: `expected rootname`
    });
```

**Expected behavior**
The rootnode should use the rootname (if specified)

**Comment by xeolabs** [comment]
Hi @paireks , I think this might be related to https://github.com/xeokit/xeokit-sdk/commit/958195481d37538793a13cd8072470b9ac61e723

**Comment by paireks** [comment]
Hey @mlankamp, could you please check this with master branch? Cause there were at least 2 fixes:
1. https://github.com/xeokit/xeokit-sdk/pull/1700
2. https://github.com/xeokit/xeokit-sdk/pull/1702

**Comment by mlankamp** [comment]
Yes, I just checked the master branch and that is working! No new package available with this fix.

**Comment by xeolabs** [comment]
> Yes, I just checked the master branch and that is working! No new package available with this fix.

Done - https://github.com/xeokit/xeokit-sdk/releases/tag/v2.6.51
