### ISSUE TITLE
API documentation is unavailable

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1734]
**Describe the bug**
API documentation page gives a 404 Error

**To Reproduce**
1. Go to https://xeokit.github.io/xeokit-sdk/docs/
2. or click the "API reference link" here https://xeokit.notion.site/xeokit-Documentation-4598591fcedb4889bf8896750651f74e

![image](https://github.com/user-attachments/assets/24413f70-0b77-4c6e-bf75-0402a6270ba6)

**Comment by xeolabs** [comment]
Fixed, hanks
