### ISSUE TITLE
error of using PerformanceModel to load model

### ISSUE THREAD

**Issue by tornado96** [xeokit/xeokit-sdk#179]
I try to use PerformanceModel to load a model, but the display of the model is wrong.

display result:
![1](https://user-images.githubusercontent.com/12689279/66735197-49ac9e80-ee98-11e9-8fa2-77965c64cd80.png)
while the correct is:
![2](https://user-images.githubusercontent.com/12689279/66735261-795ba680-ee98-11e9-915b-f14481408048.png)
model:
[test1.zip](https://github.com/xeokit/xeokit-sdk/files/3723387/test1.zip)
my code:
```js
import { Viewer } from "../../xeokit/src/viewer/Viewer.js";
import { PerformanceModel } from "../../xeokit/src/viewer/scene/PerformanceModel/PerformanceModel.js";
export default class {
  constructor(canvasId) {
    this.viewer = new Viewer({
      canvasId: canvasId,
      transparent: true
    });
  }
  load(mesh) {
    const viewer = this.viewer;
    const performanceModel = new PerformanceModel(viewer.scene, {
      id: "table",
      isModel: true, // <--- Registers PerformanceModel in viewer.scene.models
      position: [0, 0, 0],
      scale: [0.01, 0.01, 0.01],
      rotation: [-90, 0, 0]
    });
    performanceModel.createGeometry({
      id: mesh.Id,
      primitive: 'triangles',
      positions: mesh.Positions,
      normals: mesh.Normals,
      indices: mesh.Indices
    });
    performanceModel.createMesh({
      id: 'm' + mesh.Id,
      geometryId: mesh.Id,
      matrix: [
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1
      ],
      color: [0.3, 0.3, 0.3]
    });
    performanceModel.createEntity({
      id: 'ety' + mesh.Id,
      meshIds: ['m' + mesh.Id],
      isObject: true
    });
    performanceModel.finalize();

    const model = viewer.scene.models["table"];
    viewer.cameraFlight.flyTo(model);
  }
}
``` ```

**Comment by xeolabs** [comment]
Does changing the size of the geometry positions make any difference? Sometimes this is an accuracy issue when xeokit internally quantizes floating point geometry into integers. Note that i mean changing the positions array data, not changing the ````scale```` property on the ````PerformanceModel```` constructor. 

Can you supply the geometry data in your example?
