### ISSUE TITLE
Keep object under mouse while drag-panning

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#192]
Use the standard "unprojection technique" in which we find the mouse start and drag positions on the View-space projection plane, transform the delta to World-space, and translate camera by that amount.

In case the panning is not sensitive enough, some workarounds in the meantime:

- Scale your model down as you load it - see source code of [this example](https://xeokit.github.io/xeokit-sdk/examples/#loading_XKT_Duplex_transform)
- Tweak (hack) the mouse pan sensitivity within the source of [CameraControl](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/camera/CameraControl.js#L533)

**Comment by zachlite** [comment]
@xeolabs, I'm happy to work on this.

Can you clarify: 
In the case where where the pan starts, but there's no model underneath the cursor, should I use the near clipping plane as my world-space reference?

**Comment by xeolabs** [comment]
@zachlite great - yes, that would work fine I think.

**Comment by zachlite** [comment]
Hey @xeolabs, here's an update:

I want to make sure I understand expected functionality before I spend time poking around in an unfamiliar codebase, so I whipped up a stand-alone unprojected panning experiment on stackblitz.  It's messy but I wanted to turn something around to get feedback.

You can take a look at it here: https://stackblitz.com/edit/js-nybl1a
The interesting bits happen from Line 98 to Line 156

As expected, if you click and drag on a cube, the cube stays under the cursor 😄 
If you click and drag anywhere else, the near clipping plane isn't providing enough depth for the pan to be meaningful.  

If nothing is picked, do you have an aversion to just using a constant that feels natural, or is there a more "scientific" approach?

**Comment by xeolabs** [comment]
That looks great @zachlite - yeah I think a natural constant panning rate, when not clicking on an object, is the way to go. I can't think of a better option.
