### ISSUE TITLE
Publish xeokit to npm

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#203]
We need to publish xeokit to npm. However I'm not clear on certain things:

- xeokit has an examples directory that contains a lot of test data - that shouldn't be on npm
- xeokit is comprised of many individual EC6 modules - since developers import only whichever of those they need, how would that work with npm? 

@Amoki , @eriadam, @tmarti would you guys have any tips on how to proceed?

**Comment by Amoki** [comment]
npm easily allows us to select which files we want on the repository (https://docs.npmjs.com/files/package.json#files), this won't be an issue.

Loading each file independantly is very inefficient: https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_glTF_Duplex does about 100 HTTP queries.

For a release, I think doing something like https://github.com/caolan/async/blob/master/lib/index.js is a good idea.
Then using `rollup` to build a single file to import in browsers and keep the current file structure for projects that use webpack or bundlers.

**Comment by xeolabs** [comment]
@Amoki sounds good, thanks.

Since many of the JS files within ````./src```` are optional extras (for example ````src/viewer/scene/geometry/builders/buildPlaneGeometry.js````), then I assume that ````index.js```` should not include imports for those - would that be a correct assumption?

**Comment by xeolabs** [comment]
Hopefully this works: https://www.npmjs.com/package/@xeokit/xeokit-sdk

I left ````index.js```` empty for now.
