### ISSUE TITLE
How to make certain entities unclickable(unpickable)?

### ISSUE THREAD

**Issue by chloesun** [xeokit/xeokit-sdk#204]
For example, how to make certain entities of this model unpickable, so when you hover over, nothing happens? https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_glTF_Duplex

**Comment by xeolabs** [comment]
Hi Chloe - like this:

````JavaScript 
myEntity.pickable = false;
````

See: https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/Entity.js~Entity.html#instance-set-pickable

**Comment by chloesun** [comment]
so I tried to add an attribute when you load the model like this:
```
 const model = gltfLoader.load({
        id: "myModel",
        src: "./models/gltf/duplex/scene.gltf",
        metaModelSrc: "./metaModels/duplex/metaModel.json", // Creates a MetaObject instances in scene.metaScene.metaObjects
        edges: true, 
        pickable: false
    });
```
^^This didn't work, I assume I need to import the viewer, so something like `viewer.scene.models[entityId].pickable = false`?
