### ISSUE TITLE
Is it possible to import glb files?

### ISSUE THREAD

**Issue by opikalo** [xeokit/xeokit-sdk#205]
It does not appear that glb format is properly recognized in GLTFLoader, unless I'm doing something wrong. Is GLB format supported?

**Comment by xeolabs** [comment]
Hi @opikalo, glb is not supported by GLTFLoaderPlugin yet, but I will add that capability as soon as licensees require it. 

PRs are always welcome, if anyone else has time to add it.

If you need fast loading of big models without textures, the [XKTLoaderPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/XKTLoaderPlugin/XKTLoaderPlugin.js~XKTLoaderPlugin.html) may do the trick.
