### ISSUE TITLE
Question: how to make annotations attached to certain entities

### ISSUE THREAD

**Issue by chloesun** [xeokit/xeokit-sdk#206]
Without using a marker, how to make sure the annotation labels are attached to certain entities?
Do I need to specify the `worldPos` and `canvasPos` ?

**Comment by xeolabs** [comment]
The Annotation class extends the Marker class, so they'll always be Markers.

You can associate a Marker with an Entity by setting the Annotation's ````entity```` property to reference that Entity. 

However, that doesn't actually do anything yet - what I need to do next is make the Marker/Annotation synchronize its visibility with the Entity (thats pretty much the reason that Marker/Annotation can be associated with an Entity).

**Comment by ESiham** [comment]
> Without using a marker, how to make sure the annotation labels are attached to certain entities?
> Do I need to specify the `worldPos` and `canvasPos` ?

hello @chloesun , I have the same issue that yours, I want to create some annotations but based on the entities guid and not the worldPos, did you succeed to do this?
