### ISSUE TITLE
Why use bimserverplugin to display only wireframes?

### ISSUE THREAD

**Issue by chaogao** [xeokit/xeokit-sdk#217]
Figure 1 is a model rendered using xeosdk. Some structures only have wireframes.

![2181575985240_ pic_hd](https://user-images.githubusercontent.com/3032192/70534771-b7263400-1b96-11ea-981d-a694337834dd.png)

Figure 2 is the model rendered after uploading the ifc file in bimserver, which can be displayed correctly、

![WechatIMG219 (1)](https://user-images.githubusercontent.com/3032192/70534791-c1483280-1b96-11ea-8653-14c24611b96d.png)

**Comment by xeolabs** [comment]
Any errors in the JavaScript console?

**Comment by chaogao** [comment]
> Any errors in the JavaScript console?

no errors
