### ISSUE TITLE
Annotation z-index very large

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#218]
In annotation plugin, annotation z-index is set very large as inline style with 90005 magic number :
https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/AnnotationsPlugin/Annotation.js#L196-L201

What does represent this number? Is there any logic behind it like a z-index table? Could it be changed by configuration?

**Comment by xeolabs** [comment]
Yip that's a dirty magic number. I'll need to make that configurable somehow.
