### ISSUE TITLE
Merging and filtering XKT elements

### ISSUE THREAD

**Issue by BalintBende** [xeokit/xeokit-sdk#230]
Hey Lindsay,

I am wondering that is it possible to filtering elements from different `xkt` files and merging into a new one? I would like to explore the possibilities of that. I can see some example on the website about copy elements in a file or merging two files into. In case of multiple models geometry files might be stored as well. After filtering by GUIDs, from the stored `xkt` files elements and meshes would be collected and added to a newly created `xkt` file.

Do you have a specification about how to build up an `xkt` file from another one or from zero?
Another aspect is to do the filtering and merging on glTF files, then use converter.

Thank you for your kind answer in advance.

Cheers, Balint

**Comment by xeolabs** [comment]
Hey @BalintBende that's a very interesting use case - I'll be away for the next couple of days, but I'll give it some thought and I'll be in touch.

**Comment by xeolabs** [comment]
This may be useful: we can now parse multiple IFC models (via glTF) into the same ````xkt```` file, using tools in [````xeokit-xkt-utils````](https://github.com/xeokit/xeokit-xkt-utils), specifically the [loadGLTFIntoXKTModel](https://github.com/xeokit/xeokit-xkt-utils#loading-gltf-into-an-xktmodel).
