### ISSUE TITLE
XKTLoaderPlugin & GLTFLoaderPlugin not using original IFC colors correctly

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#233]
To make ````XKTLoaderPlugin```` use the colors from the original IFC file, we configure ````XKTLoaderPlugin```` to **not** use the per-IFC-type colors specified in ````objectDefaults````.

However, those colors don't look so good, because the ````xeokit-gltf-to-xkt```` pipeline tool seems to be parsing the glTF colors incorrectly. 

An example is the windows on the Duplex model, which should be transparent:

![Screenshot from 2020-01-22 09-24-29](https://user-images.githubusercontent.com/83100/72877342-095f8680-3cf9-11ea-8ed9-40cea4a499a0.png)

## Cause

WIP

**Comment by Amoki** [comment]
I don't think there is a problem with the windows there. The gray comes from spaces.
Windows are 100% transparent, but spaces are gray without transparency.
![Screenshot from 2020-01-22 10-09-22](https://user-images.githubusercontent.com/1349751/72880608-82fa7300-3cff-11ea-9197-219c602c9e47.png)
And without spaces:
![Screenshot from 2020-01-22 10-09-29](https://user-images.githubusercontent.com/1349751/72880637-8857bd80-3cff-11ea-90e3-ada10969d87e.png)

**Comment by xeolabs** [comment]
Good catch - I just confirmed that the pipeline is actually handling colors OK, and XKT is loading them OK as well.

**Comment by xeolabs** [comment]
So, XKTLoaderPlugin & GLTFLoaderPlugin are using original IFC colors correctly, it's just that the IfcSpace elements were making it look like there was a colors bug. 

By configuring ````objectDefaults```` to make ````IfcSpace```` elements 0.2 opacity (or just invisible), we see the original IFC colors coming through:

````javascript
const xktLoader = new XKTLoaderPlugin(viewer, {
    objectDefaults: {
        IfcSpace: {
            pickable: false,
            opacity: 0.2
        }
    }
});
````

where Duplex seems to show all colors parsed correctly (within the IFC->COLLADA->glTF->XKT pipeline) - see screenshot.

![Screenshot from 2020-01-22 10-23-56](https://user-images.githubusercontent.com/83100/72882153-63187e80-3d02-11ea-9525-f40fa804d16c.png)

**Comment by xeolabs** [comment]
Not an issue, all works nicely - verified by: https://github.com/xeokit/xeokit-sdk/commit/50dacbcd6180a2eaeae3948d7c61b13eeff27876

Live example: https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_XKT_Duplex_originalIFCColors
