### ISSUE TITLE
Colorize should replace existing color, not blend with it

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#235]
### Problem

When colorizing an Entity, the ````colorize```` value is currently multiplied by the Entity's rendered pixel colors.

This is a problem when either the color or ````colorize```` is dark.

A ````colorize```` that's yellow would be weird, if for example, color was red, in which case the result would appear yellow.

### Fix

Fix by making ````colorize```` **replace** color in the shader, when given. When ````colorize```` is then set null or undefined, original color would be restored again.

**Comment by Hanan88** [comment]
hello, 
I am using xeokit in react app and I want to 
1- change the color of STL-model 
2- change the transparency(opacity) of STL-model
Thank you
