### ISSUE TITLE
Scalable Ambient Obscurance

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#247]
In progress, close to completion. Tracking in this issue for process visibility.

* [Live demo](https://xeokit.github.io/xeokit-sdk/examples/#postEffects_SAO_OTCConferenceCenter)
* [API docs](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/postfx/SAO.js~SAO.html)
* [Original paper on SAO](https://research.nvidia.com/sites/default/files/pubs/2012-06_Scalable-Ambient-Obscurance/McGuire12SAO.pdf)

## Remaining tasks

- [x] Acceptable blur effect
- [x] Preserve enhanced edges
- [ ] Option to only enable while camera not moving
- [ ] More documentation on optimal configurations, or some auto-magic to match SAO configs to camera configs (they are dependent)

**Comment by Amoki** [comment]
While SAO seems very great on your screenshots, it doesn't feel the same on little, small-windowed buildings:

![Capture d’écran de 2020-02-03 10-28-50](https://user-images.githubusercontent.com/1349751/73641532-73204e80-4670-11ea-888e-74b7f2edaa52.png)
![Capture d’écran de 2020-02-03 10-29-47](https://user-images.githubusercontent.com/1349751/73641537-74ea1200-4670-11ea-96b3-79e56dbe3a31.png)

I tried to randomly play with the values in the config (I don't really know what they mean) without success.

Did I miss something, are example values not optimized or I'm way too early to really test this feature?

**Comment by xeolabs** [comment]
SAO is ready to use, but needs to be configured just right - it seems very dependent on the distance between camera near and far clipping planes. 

What I'd like to do next:

- Find a sensible default value for the ````far```` clip plane distance for perspective and orthographic projections,
- Set default configs for SAO to values that would work (more or less) out-of-the-box for that ````far```` value.

I propose to follow THREE.js' default value of ````2000.0```` for the ````far```` plane. Then I'd tweak SAO accordingly. 

Also, I think we should try to scale models to use as much of the region between ````near```` and ````far```` as possible, while somehow constraining the camera to not move too far away from the model, so as to not cause it to be clipped by ````far````.

Does a value of ````2000```` for ````far```` work OK for you? 

I think all of this is what Forge does to ensure that SAO works out-of-the-box.

**Comment by xeolabs** [comment]
BTW, I'm guessing that if you were to reduce ````intensity```` and/or increase ````scale````, you'd probably get better results for your model.
