### ISSUE TITLE
StreamBIM-Style Distance Measurement Plugin

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#25]
This specification is work-in-progress.

This is a measurement tool inspired by the StreamBIM measurement plugin, shown here:

 * https://www.youtube.com/watch?v=iAKBmkm83lk

## Mode 1: Quick Measure

TODO

## Mode 2: With measurement plane

1. Activate plugin
2. Click an object
3. Plugin creates a plane-aligned a cross-section plane on the clicked object face
4. Click a second object
5. Plugin finds the distance between the centers of the first and second cross-sections

**Comment by Amoki** [comment]
Hi Lindsay,

We worked on a UX draft for the measure tool.
The StreamBIM example looks nice but is very specialized. A simpler tool seems to be enough for a lot of people.

After activation of the plugin:

Click on an edge or a face with magnetism on edges.

If we’re over an edge the cursor is: 
![Screenshot from 2019-07-09 17-11-49](https://user-images.githubusercontent.com/1349751/60900700-e8f44100-a26c-11e9-8b55-426e11e4d5b1.png)

If we’re over a face, the cursor is :
![Screenshot from 2019-07-09 17-11-55](https://user-images.githubusercontent.com/1349751/60900708-eb569b00-a26c-11e9-8b98-0ec7f66d80a6.png)

Until we click a second time, we see in real-time a line between the first dot and the cursor with the distance:
![Screenshot from 2019-07-09 17-12-05](https://user-images.githubusercontent.com/1349751/60900712-ed205e80-a26c-11e9-9b34-877ef0079c3e.png)



On second click, freeze the line between the two points (with their icons).

If the points are on different faces, is it possible to show the length of each face?
![Screenshot from 2019-07-09 17-12-16](https://user-images.githubusercontent.com/1349751/60900720-f0b3e580-a26c-11e9-934c-912f1a9bf785.png)


When clicking again: 
If it’s far from any point, start a new measure
If it’s close to an existing point, update it.


What do you think?

**Comment by xeolabs** [comment]
Hi Hugo,

There are some limitations with the high-detail representation loaded by GLTFLoaderPlugin, XKTLoaderPlugin and BIMServerLoaderPlugin, which affect this UX:

1) Geometry for high-detail models is resident in GPU memory only, meaning that the geometry cannot be read from browser memory, meaning that it's not possible to measure the faces for large models.
2) We don't yet have the capability to pick lines, so we can't yet snap to them.

(1) is possible if we load models using GLTFLoaderPlugin with ````performance: false````, in which case geometry is retained in memory. However that's not an option for huge models, which won't fit in browser memory anyway.
(2) is something I'm planning to add support for, as well as vertex picking BTW (which will enable snap-to-vertex).

So I think everything in this UX is possible (once I've implemented edge picking) except for the face measurement part, unfortunately.
