### ISSUE TITLE
Colors not displayed correctly on Ubuntu 19.10 using Firefox

### ISSUE THREAD

**Issue by Wesley-DST** [xeokit/xeokit-sdk#251]
On a freshly installed Ubuntu 19.10 the colors aren't appearing correctly and changing the angle sometimes affects the colors.

Firefox version used: 72.0.2 (64-bit)
System information:
![Screenshot from 2020-02-03 13-39-50](https://user-images.githubusercontent.com/51397927/73654165-488fbf00-468b-11ea-8032-8aa31c769cc0.png)
Color issue:
![Screenshot from 2020-02-03 13-43-57](https://user-images.githubusercontent.com/51397927/73654166-488fbf00-468b-11ea-9eae-9798e6012b38.png)
![Screenshot from 2020-02-03 13-46-26](https://user-images.githubusercontent.com/51397927/73654310-a6240b80-468b-11ea-8b41-edf2e4f95371.png)

**Comment by Amoki** [comment]
We have the same problem, only on Firefox with any version on Linux.

Transparency over a colored object seems to trigger the bug. Transparency over transparency does fancy stuff too!

**Comment by xeolabs** [comment]
Fixed in: https://github.com/xeokit/xeokit-sdk/commit/b4b2e9afe3a1850445a0236f46883fd9f935ecd2
