### ISSUE TITLE
Background color bleed into highlightMaterial color 

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#260]
The scene.highlightMaterial.[fillColor/fillAlpha] change accordingly to the background color.

```js
viewer.scene.highlightMaterial.fillColor = new Float32Array([
    47 / 255,
    55 / 255,
    74 / 255
]);
viewer.scene.highlightMaterial.fillAlpha = 0.7;
```

![Screenshot 2020-02-07 at 14 37 08](https://user-images.githubusercontent.com/22523482/74033871-59a43d00-49b7-11ea-96a6-36a3b9337611.png)
![Screenshot 2020-02-07 at 14 36 25](https://user-images.githubusercontent.com/22523482/74033875-5ad56a00-49b7-11ea-83be-51a6e52deddd.png)

**Comment by xeolabs** [comment]
This will require some careful combination of WebGL blend funcs, more experimentation needed. Priority item - should have done in first part of next week.

**Comment by xeolabs** [comment]
Modified blend functions in this commit: https://github.com/xeokit/xeokit-sdk/commit/75f892b9f7e2de12abaecd8b12546b7de54c3e53

* https://xeokit.github.io/xeokit-sdk/examples/picking_canvas_mesh_highlight_transparent.html
* https://xeokit.github.io/xeokit-sdk/examples/picking_canvas_mesh_select_transparent.html
