### ISSUE TITLE
MetaScene createMetaModel shoud trigger model re-render

### ISSUE THREAD

**Issue by Kurtil** [xeokit/xeokit-sdk#264]
If we create a meta-model (like IfcSpace visible: false) after loading a model, this should impact the model without the need of reloading it.

Use case: data about types are fetched and available after the xkt loads. The meta-model is created afterward. But nothing happens. The model needs to be reloaded to take into account the meta-model.

**Comment by xeolabs** [comment]
@Kurtil  to confirm your use case, is this your flow:

1. Use XKTLoaderPlugin to load model "foo", without metadata
2. Use MetaScene#createMetaModel to create MetaModel for model "foo"
3. Then the entities in the model should get appearances set according to XKTLoaderPlugin#objectDefaults and the IFC types in the MetaModel

**Comment by xeolabs** [comment]
@Kurtil BTW why is metadata only available after the geometry loads?

The contract of ````XKTLoaderPlugin#load()```` is to load both ````.XKT```` geometry and JSON metadata as a unit, together at the same time in the ````load()```` call - they're not currently designed to be loaded separately. 

Note that you can do this: 

````javascript
myXKTLoader.load({
    xkt: myArraybuffer,
    metaModelData: myMetaModelJSON
});
````

I'm not sure if that helps, but is there a chance that you can pre-load that arraybuffer, then load the metadata JSON, then do a call to ````load()```` with both of those, when you have them both?

Or is it that you want to be able to dynamically reassign model metadata to the same model geometry? 

Or perhaps dynamically switch between different ````[IfcObjectDefaults````](https://xeokit.github.io/xeokit-sdk/docs/variable/index.html#static-variable-IFCObjectDefaults) for a model?

**Comment by Kurtil** [comment]
The flow you described above is correct.

The feature that I am looking for is to dynamically switch between different [IfcObjectDefaults] to hide IfcSpace in some conditions.
