### ISSUE TITLE
[with solution]: problem with transparent objects

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#267]
## The problem

In the following code...

https://github.com/xeokit/xeokit-sdk/blob/9c7819aae888d3f6519abf94578055b6b10a4f43/src/viewer/scene/webgl/Renderer.js#L599-L614

... seems that this if...

```js
if (!transparentDepthMask) {
    gl.depthMask(false);
}
```

... has the wrong `!` in front of it.

## The semantic bug

- `transparentDepthMask == true` should mean that it won't update Z-Buffer (it's transparent for Z-Buffer updates)

## The practical bug

- due to `const transparentDepthMask = true;`, the code will never enter the `if`, and this will cause transparent objects to update the Z-Buffer, leading to strange artifacts when 2 transparent objects overlap

## The solution

Just change this code...

```js
if (!transparentDepthMask) {
    gl.depthMask(false);
}
```

... to...

```js
if (transparentDepthMask) {
    gl.depthMask(false);
}
```

(notice the removed `!`)

And, of course, remember to invoke...

```js
gl.depthMask(true)
```

... at the end of the `if` statement:

https://github.com/xeokit/xeokit-sdk/blob/9c7819aae888d3f6519abf94578055b6b10a4f43/src/viewer/scene/webgl/Renderer.js#L599-L638

**Comment by xeolabs** [comment]
Fixed in 4b85198cbee8b087341e39a26abb124e3b76f9a4
