### ISSUE TITLE
StoreyViewsPlugin#gotoStoreyCamera() positions camera incorrectly

### ISSUE THREAD

**Issue by heshamhossam** [xeokit/xeokit-sdk#269]
Hi Lindsay,

there is an issue while picking/navigating using a storey map.
to reproduce:
1. go to https://xeokit.github.io/xeokit-sdk/examples/#storeyViews_StoreyViewsPlugin_pickStoreyMap
2. click anywhere over the storey map
3. it navigates deeply down even under the building itself

Thanks.

**Comment by xeolabs** [comment]
@heshamhossam Aha yes. That's due to the camera position when making the snapshot image - the camera's "up" vector is pointing the wrong way (I think ````[0,0,-1]```` when it should be ````[0,0,1]````). So the storey map is basically upside down. Upping the priority on this one. Thanks!

**Comment by heshamhossam** [comment]
Thanks in advance and waiting for the fix.

**Comment by xeolabs** [comment]
Now fixed in master and npm @xeokit/xeokit-sdk 0.9.3
