### ISSUE TITLE
Fix StoreyViewsPlugin#createStoreyMap() snapshot size for huge models

### ISSUE THREAD

**Issue by heshamhossam** [xeokit/xeokit-sdk#271]
Hi Lindsay,

While using createStoreyMap in StoreyViewsPlugin to generate a png image of a relatively big model, image src is not generated at all.
with same tracing I found that aspect ratio reaches 2000+ and I guess that's the reason.

steps to reproduce:
- loading a model normally
- call storeyViewsPlugin.createStoreyMap({
        format: "png",
        width: 200,
        useObjectStates: true
      })

Thanks.

**Comment by xeolabs** [comment]
Not sure I follow this one - I just modified this example to use your parameters: https://xeokit.github.io/xeokit-sdk/examples/#storeyViews_StoreyViewsPlugin_recipe2

Like so:

````javascript
const storeyMap = storeyViewsPlugin.createStoreyMap("2SWZMQPyD9pfT9q87pgXa1", {
      format: "png",
      width: 200,
      useObjectStates: true
});
````

And I get an image src OK.

In your code snippet you're missing the ID of the IFCBuildingStorey - could that be the issue?

**Comment by xeolabs** [comment]
Hi @heshamhossam could you email me the XKT and metadata files for your model?

**Comment by xeolabs** [comment]
More info:  this happens when using a relatively big model (dimensions) and the aspect ratio is getting calculated based on the model to a number over 2000+ and then no png data is returned.

**Comment by xeolabs** [comment]
My theory is is that:

- each plan view PNG is generated to be the extents of the entire model
- if one storey fills a large portion of the model extents, but another storey fills only a small part, the plan view for the second storey may not look so good.

That's just a theory though - I'd need the model to verify that. Solution would be to fit each PNG to the extents of each storey.

If so, then I'd see if I can make the StoreyViewsPlugin adapt to that case better.

See the Schependomlaan model example below - note how the PNGs are the same size,  but the second storey occupies a small region of its PNG. That may be the issue.

![storey1](https://user-images.githubusercontent.com/83100/77539871-5818d080-6ea2-11ea-9de7-3471c396ee9c.png)

![storey2](https://user-images.githubusercontent.com/83100/77539883-5d761b00-6ea2-11ea-846a-5e51a2c63114.png)

**Comment by xeolabs** [comment]
@heshamhossam try upgrading to V0.0.3  of xeokit-gltf-to-xkt - the accuracy fixes in that tool allow the StoreyViewsPlugin to create an accurate snapshot - 

 ![planRadar_plan1](https://user-images.githubusercontent.com/83100/77620301-5d295e80-6f3a-11ea-8d80-a993ce208891.png)
