### ISSUE TITLE
It seems like it needs a DoubleClick instead of a Click to trigger the two mentioned actions.

### ISSUE THREAD

**Issue by PixelPartner** [xeokit/xeokit-sdk#272]
https://github.com/xeokit/xeokit-sdk/blob/15f1465bcd904ffb9f8e236c152eef80c00db7e8/examples/storeyViews_StoreyViewsPlugin_recipe1.html#L39

**Comment by xeolabs** [comment]
Hi - not seeing it on my end - what's your OS and browser?

**Comment by PixelPartner** [comment]
Win10 Newest Firefox
