### ISSUE TITLE
Shortcuts 1 to 6 to move the camera to predefined positions are bugged

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#277]
Our models are Y up, I don't know if it may have an impact.
The model appears very far, sometimes upside down.

![Screenshot from 2020-03-11 10-52-29](https://user-images.githubusercontent.com/1349751/76404364-a00a0480-6386-11ea-8458-9539b414153a.png)

**Comment by xeolabs** [comment]
@Amoki could you try again with the latest npm or master? Might be fixed now.

**Comment by Amoki** [comment]
It is fixed, thanks!
