### ISSUE TITLE
[with solution]: wrong linear interpolation of "up" destination for "flyTo" method

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#278]
## How the problem was found

Experimenting with some culling logic, it has been seen that the `camera up` vector is not properly updated during a `camera flight`.

## The idea for the solution

In the following piece of code...

https://github.com/xeokit/xeokit-sdk/blob/8b35b6e8fe822908d9c3382179fceedf593d343d/src/viewer/scene/camera/CameraFlightAnimation.js#L483-L488

.. the `camera flight` has its `up` vector linearly interpolated.

To show you why this not accurate, let's show the following picture:

![imagen](https://user-images.githubusercontent.com/2405414/76432554-6ac7db80-63b3-11ea-8cbb-6b7303e428bf.png)

In this orthogonal case, the `camera eye=>up` vector would need to always remain orthogonal to the `camera eye=>look` vector, and ensuring orthogonality of those vectors is not achieved by linearly interpolating both `look`, `eye` and `up` vectors, we need a cross product for that, and this implicitly implies some kind of `sin` / `cos` calculation.

The idea of the solution, instead of linearly interpolating the `up` vector, is the following:

Following the example of the picture, when starting the flight, the dot product of...

- inital `eye => look` unit vector
- destination `eye => look` unit vector

... is 0.

When arriving destination the dot product of the...

- interpolated `eye => look` unit vector
- destination `eye => look` unit vector

... will be 1.

So the idea is that instead of interpolating the `up` vector accodring to a linear `tFlight` weight, do interpolate based on the dot product of:

- interpolated `eye => look` unit vector
- destination `eye => look` unit vector

## An idea for the solution code

The following code also takes into account that initial `eye=>look` vector might not be orthogonal with destination `eye=>look` vector .

1) In this line...
  https://github.com/xeokit/xeokit-sdk/blob/8b35b6e8fe822908d9c3382179fceedf593d343d/src/viewer/scene/camera/CameraFlightAnimation.js#L310
  ... add following code:
  ```js
if (this._flyEyeLookUp)
{
    var currentEyeLookDir = math.normalizeVec3 (
        math.subVec3 (
            this._look1,
            this._eye1,
            [ 0, 0, 0 ]
        ),
        [ 0, 0, 0 ]
    );

    this._destEyeLookDir = math.normalizeVec3 (
        math.subVec3 (
            this._look2,
            this._eye2,
            [ 0, 0, 0 ]
        ),
        [ 0, 0, 0 ]
    );

    this._eyeLookDirRange = [
        math.dotVec3 (
            currentEyeLookDir,
            this._destEyeLookDir
        ),
        1
    ];
}
```

2) replace following line...
  https://github.com/xeokit/xeokit-sdk/blob/8b35b6e8fe822908d9c3382179fceedf593d343d/src/viewer/scene/camera/CameraFlightAnimation.js#L487
  ... with...
  ```js
  var eyeLookDir = math.normalizeVec3 (
    math.subVec3 (
        camera.look,
        camera.eye,
        [ 0, 0, 0 ]
    ),
    [ 0, 0, 0 ]
);

  camera.up = math.lerpVec3(
    math.dotVec3 (
        this._destEyeLookDir,
        eyeLookDir
    ),
    this._eyeLookDirRange [0],
    this._eyeLookDirRange [1],
    this._up1,
    this._up2,
    newUp
);

With this solution, the `up` vector seems to be properly interpolated.

**Comment by xeolabs** [comment]
Thanks @tmarti 

I tried this out, but when using this logic with the ````NavCubePlugin````, encountered a case where there seemed to be a numeric error - the case was that when we've clicked the top of the NavCube and have a downward-looking view, then clicking the top of the NavCube again blanked the canvas, which probably mean a numeric error in the Camera (eye, look, up) state and the resultant view matrix. 

I need to shelve this for now, but I'll share a gist of the CameraFlightAnimation.js that I modified with your suggestion in the meantime: https://gist.github.com/xeolabs/5a8a91a4abe906f62625731e6930f6c1

**Comment by tmarti** [comment]
Could is possible that in this case the `initial dot product` is `<0`, and the linear interpolator is expecting the starting weight to be always `>=0`? 😃
