### ISSUE TITLE
IfcBuildingStorey Id not matching storey Id expected by StoreyViewsPlugin

### ISSUE THREAD

**Issue by julianopita** [xeokit/xeokit-sdk#280]
Hi. I`ve been working on an online IFC viewer for models stored on a BIMServer and Xeokit for visualisation.
I`ve been trying to implementing the storey views as described in recipe 3 of the plugin https://github.com/xeokit/xeokit-sdk/blob/master/examples/storeyViews_StoreyViewsPlugin_recipe3.html
and adapting it to load a model from BimServer. Everything works fine until it tries to use the Id of the IfcStoreys, which drops an error saying that the IfcBuidingStorey is not found with the id:

            Plugin.js:92 [xeokit plugin StoreyViews]: IfcBuildingStorey not found with this ID:         
            0B5gfVFyr9cw1sh0d960Pz

Thing is, I`m getting the Ids directly from the scene using
 
            viewer.metaScene.getObjectIDsByType("IfcBuildingStorey");

it returns me an array of Ids:

["0B5gfVFyr9cw1sh0d962Cn", "0B5gfVFyr9cw1sh0d962W4", "0B5gfVFyr9cw1sh0d962vO", "0B5gfVFyr9cw1sh0d96Zrl", "0B5gfVFyr9cw1sh0d96Zxk", "0B5gfVFyr9cw1sh0d961jX", "0B5gfVFyr9cw1sh0d960Pz"]

what I`m doing wrong? Or there is a mismatch between the BimServer Ids and other model loaders?

Thanks!

**Comment by ajaxjiang96** [comment]
In my case I called `storeyViewsPlugin.showStoreyObjects` before the storey was actually loaded. I'd suggest placing the function call inside the onstorey callback
```js
storeyViewsPlugin.on('storeys', () => {
  /* your stuff here */
});
```
