### ISSUE TITLE
Cannot be loaded

### ISSUE THREAD

**Issue by simonasdmd** [xeokit/xeokit-sdk#286]
hi~
I have a copy of 3D XML data exported by CATIA. But I couldn't load it. Can you help me test it?

[test.zip](https://github.com/xeokit/xeokit-sdk/files/4449751/test.zip)

**Comment by xeolabs** [comment]
Hi, can't help with testing your model unfortunately, but note that XML3DLoaderPlugin only supports 3DXML V4.2 (I just updated the docs to indicate that). Try exporting that version and see how it goes.
