### ISSUE TITLE
setObjectsColorized colors only one face

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#291]
When using `scene.setObjectsColorized(ids, color);`, only one face is colored:
![5bf428c2fcb421db6f547e961ff4551a](https://user-images.githubusercontent.com/1349751/80361721-b78f4500-8881-11ea-8d72-bf9a276fe004.gif)

We can also see a gradient color around to colored face:
![Screenshot 2020-04-27 at 10 32 22](https://user-images.githubusercontent.com/1349751/80361799-cf66c900-8881-11ea-8cda-9c6477d9e08f.png)

We're using the v0.9.96. Do you have any idea @xeolabs?

**Comment by xeolabs** [comment]
@Amoki looks like a breakage from recent optimizations. I'll fix ASAP.

**Comment by xeolabs** [comment]
@Amoki fixed in https://github.com/xeokit/xeokit-sdk/commit/8b0054651d116345cec4628a706739f68191bbc7

**Comment by Amoki** [comment]
Thanks!
