### ISSUE TITLE
Error when destroying Viewer instance.

### ISSUE THREAD

**Issue by Wesley-DST** [xeokit/xeokit-sdk#308]
When destroying an Instance of Viewer an error is thrown. This error occurs when destroy is called in MouseMiscHandler.
![image](https://user-images.githubusercontent.com/51397927/81572890-12598e00-93a4-11ea-8a36-27cf410620f1.png)

The error can be reproduced in this example:
https://xeokit.github.io/xeokit-sdk/examples/#viewer_createDestroyRepeat

**Comment by xeolabs** [comment]
Now fixed in npm @xeokit/xeokit-sdk 1.0.0

GitHub can take a little while update the live examples though, but the fix in in npm.
