### ISSUE TITLE
IfcConvert alternatives?

### ISSUE THREAD

**Issue by chloesun** [xeokit/xeokit-sdk#309]
Hello, this might be super related to xeokit-sdk itself.. I was following [this wiki](https://github.com/xeokit/xeokit-sdk/wiki/Creating-Files-for-Offline-BIM) to convert IFC to glTF.

1. [IfcConvert](http://ifcopenshell.org/ifcconvert) (v0.6.0 or later) to convert IFC files to DAE
2. COLLADA2GLTF to convert DAE to glTF

I downloaded the 0.6.0 IfcConvert 64bit Windows, and can't install it. 
![bugg](https://user-images.githubusercontent.com/13730281/81984948-8d6caf80-9603-11ea-84a3-8ed9cb32e45b.PNG)

I already reported this to their [page](https://github.com/IfcOpenShell/IfcOpenShell/issues/850), hope to get some input from the community for this tool or other CLI tools alternatives, thank you!

**Comment by Amoki** [comment]
The log says you're using IfcConvert 0.5.0-rc1 which is a very old version instead of 0.6.0. It may be the problem

**Comment by chloesun** [comment]
@Amoki  installing 0.6.0 is the same issue.
![0 6 0](https://user-images.githubusercontent.com/13730281/82365256-6c7ad480-99de-11ea-90fd-e81d9c99a6b4.PNG)
