### ISSUE TITLE
Repository has "duplicate" case sensitive file names in the same directory

### ISSUE THREAD

**Issue by lasselaakkonen** [xeokit/xeokit-sdk#316]
At least these folders and their subfolders:
- https://github.com/xeokit/xeokit-sdk/tree/e4b350a/docs/ast/source/viewer/scene/PerformanceModel/lib/instancing 
- https://github.com/xeokit/xeokit-sdk/tree/e4b350a/docs/ast/source/viewer/scene/PerformanceModel/lib/batching

Have "duplicate" files with case sensitive names, eg:
- https://github.com/xeokit/xeokit-sdk/blob/e4b350a/docs/ast/source/viewer/scene/PerformanceModel/lib/instancing/InstancingLayer.js.json
- https://github.com/xeokit/xeokit-sdk/blob/e4b350a/docs/ast/source/viewer/scene/PerformanceModel/lib/instancing/instancingLayer.js.json

This causes issues default macOS setups, which have a case insensitive filesystem.

**Comment by xeolabs** [comment]
This will only be in the ````docs```` directory - I fixed by deleting then regenerating them.
