### ISSUE TITLE
Add PerformanceModel#entityList

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#320]
Expose ````PerformanceModel```` private property ````_nodeList```` as a public property named ````entityList````.

Then we can access ````Entity````s like this:

````javascript
const entity99 = performanceModel.entityList[99];
````

**Comment by barnabasmolnar** [comment]
Hey there,

This seems to have been removed in https://github.com/xeokit/xeokit-sdk/pull/355/files#diff-cb82542ca477e9971e19cb2c44134c58L732

I'm assuming by mistake.

Would you please add it back in?

**Comment by xeolabs** [comment]
Oops merge mistake. Restored in 1.3.52
