### ISSUE TITLE
View Culling

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#322]
# ViewCullPlugin

See PR https://github.com/xeokit/xeokit-sdk/pull/355

Create ````ViewCullPlugin````, which uses [frustum culling](https://en.wikipedia.org/wiki/Viewing_frustum) to accelerate rendering performance.

````ViewCullPlugin```` works by automatically marking every ````Entity```` *culled* whenever it falls outside our current view. 

Since xeokit's renderer does not process culled ````Entity````s, this plugin can be used to avoid wasting GPU on objects that we're not looking at.

Use ````ViewCullPlugin```` by simply adding it to your ````Viewer````. 

````javascript
const viewer = new Viewer({
    canvasId: "myCanvas",
    transparent: true
});
    
const viewCullPlugin = new ViewCullPlugin(viewer, {
    maxTreeDepth: 20
});

const xktLoader = new XKTLoaderPlugin(viewer);

const model = xktLoader.load({
    id: "myModel",
    src: "./models/xkt/OTCConferenceCenter/OTCConferenceCenter.xkt",
    metaModelSrc: "./metaModels/OTCConferenceCenter/metaModel.json"
});
````

**Comment by xeolabs** [comment]
\ping @tmarti

**Comment by xeolabs** [comment]
Added in 1.3.51

**Comment by barnabasmolnar** [comment]
Hi,

I'm getting the following error when trying to destroy the viewer:

`objectCullStates._destroy is not a function`

Pointing to the `ObjectCullStates.js` file and the following piece of code:

```js
scene.on("destroyed", () => {
    delete sceneObjectCullStates[sceneId];
    objectCullStates._destroy();
});
```

Could you please look into it? Thanks.
