### ISSUE TITLE
Navigation on touch screens is too sensitive

### ISSUE THREAD

**Issue by eriadam** [xeokit/xeokit-sdk#325]
Hello Lindsay, 
This one is maybe connected to #313 .

We see a huge difference in the sensitivity among different devices. We determined the following sensitivity settings that work best for them:
- laptop with a mouse`sensitivity=360`
- iPad `sensitivity=200`
- Cisco Board `sensitivity=1`

It shouldn’t matter which input device the user is using. Is it maybe detectable using the viewport and adjusted internally by xeokit?

**Comment by xeolabs** [comment]
I'll see if I can fix this in master for Monday, then include in next week's release. I think #313  should be a sufficient fix, then if not I'll add an automatic scaling derived from viewport size.

**Comment by eriadam** [comment]
awesome, thanks!

**Comment by eriadam** [comment]
Hi @xeolabs , It works much better now, thanks for the fixes.

Would it be possible to account for the acceleration of the cursor/finger as well? Slow scroll fine movements, fast scroll larger distances?
