### ISSUE TITLE
Extend BCFViewPointsPlugin to save & load object colors & opacities

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#328]
Currently, the BCF plugin doesn't handle the "color" part.
I'll submit a PR the handle them in `setViewpoint` but I have some trouble implementing `getViewpoint`.

We should define "colors" only for objects that have seen their color changed in the current scene. Is there a way to get all the objects with a changed color?

**Comment by xeolabs** [comment]
@Amoki it should be possible to get the IDs of ````Entity```` instances that have had their ````colorize```` properties modified like this this:

````javascript
const colorizedObjectIds = myViewer.scene.colorizedObjectIds;
````

**Comment by Amoki** [comment]
Thanks, I could develop the coloring part.
I can't find an equivalent for opacity. I tried to loop on objects and check their opacity but I get all windows and transparent doors. Is there a way to retrieve objects that had an opacity change?
