### ISSUE TITLE
Ignore clicks on disabled ContextMenu items

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#331]
If the getEnabled method of a context menu item returns "false", the html attribute "disabled" is set on that list entry, but the doAction call is still executed on click. This is unexpected and looks like a bug to me.

https://github.com/xeokit/xeokit-sdk/blob/master/src/extras/ContextMenu/ContextMenu.js#L243

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeokit/xeokit-sdk/commit/20e857fa54d868c63c4d1cd1a33a0c573522e7a9
