### ISSUE TITLE
inconsistent documentation

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#332]
the documentation claims there is a "mouseRightClick" event, but "rightClicked" is then shown in the example code event name. While the actual event name is "rightClick" as of version 1.3.2

https://github.com/xeokit/xeokit-sdk/blob/baea53e382e67c3aa70a8ae9596738fd0c17727b/src/viewer/scene/CameraControl/CameraControl.js#L409

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeokit/xeokit-sdk/commit/f7b8bbef2b4fb150c93b5ee5ba8e1589da5dc531
