### ISSUE TITLE
picked event is delayed by almost 300ms which causes wrong entity picks

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#333]
compared to the old mouseclicked event on viewer.scene.input the new "picked" event of the viewer.cameraControl is delayed and can therefore cause weird behaviour on picking the entity. 

![image](https://user-images.githubusercontent.com/29466624/84039907-378cec80-a9a2-11ea-8ba1-a6c8daa913cb.png)

A click and mouse move within the delay will not pick the desired 3d entity in the viewer, but the currently hovered entity at the time of the event firing.

**Comment by Amoki** [comment]
This probably comes from the DoubleClick. The code has to wait to see if there is a second click or not.
If you don't use any DoubleClick feature, you can disable it with
```
cameraControl.doublePickFlyTo = false;
cameraControl.panRightClick = false;
```

**Comment by xeolabs** [comment]
The problem is that when a user double-clicks, it's only on the second click that CameraControl knows that it's handling a double-click and not a single-click, hence needing to wait. If anyone has a technique that allows CameraControl to signal both single-click and double-click events without needing to wait, I'm all ears!

**Comment by devjta** [comment]
Well, the viewer.scene.input.on and mousedown and dblclick are working like your first idea, which I dont like at all..

It would be better to give an attribute/property to the method, if we want this behavior or not. I dont mind waiting 300ms, before firing the mousdown event.

**Comment by blickfeld7** [comment]
I'm currently using viewer.scene.input.on, but as i understood they're going to be private and we should use the events implemented on the viewer's CameraControl object.
As of 1.3.42 the event is still fired with delay, but the hit entity is the one at click time, not the one which you're hovering at the time of event firing.

So to me this issue is solved. The delay is not nice for the user experience, but i can live with it.

**Comment by devjta** [comment]
Oh, you are right it also works with "picked" at cameraControl.. I find it kinda strange that there is no warning.. Also the examples are also still using the scene.input.

At least the new listener has no double-click/tap issue anymore! So thanks for your answer :)

**Comment by devjta** [comment]
Great.. with the newest verison this hoovering error is fixed, but for whatever reasons at a PixelC tablet the "picked" get triggered TWICE.
Same codebasis at the desktop (also Chrome) works without any problem -> 1 click = 1 picked event...

**Comment by blickfeld7** [comment]
as of 1.4.1 this got worse. Now the delay is also applied with `cameraControl.doublePickFlyTo = false;` might pick the wrong element stated in my last comment now https://github.com/xeokit/xeokit-sdk/issues/333#issuecomment-644824232

**Comment by Amoki** [comment]
May it be the ray cast that takes ~300ms on a slow computer so the "picked" event is emitted later than expected?
