### ISSUE TITLE
CameraControl fires "hover" events when moving mouse while button down

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#335]
The "hover" and "hoverEnter" event should either not be fired during a camera navigation (panning/rotating) or a flag should be available in the event arguments, which allows to programmatically allow for different behaviour on hover during navigation.

**Comment by xeolabs** [comment]
Fixed in 5986a29

**Comment by blickfeld7** [comment]
The commit solved the bug for 3D camera rotation, but not for panning. The following video is showing behaviour in xeokit 1.3.42

![Screen Recording 2020-06-16 at 16 30 16](https://user-images.githubusercontent.com/29466624/84788879-f030dc80-afef-11ea-8085-ab5bce3a4634.gif)

**Comment by xeolabs** [comment]
@blickfeld7 this should now be fixed in 1.3.43
