### ISSUE TITLE
CameraControl should only fire "picked" events on left click

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#336]
The documentation describes the "picked" event to be fired on a left-click, however it gets also fired on right click (may be used for context menu) and can therefore lead to undesired behaviour.

Please either add a flag to the event arguments, which allows for programmatically change the behavior in the event handler or disable the firing of the "picked" events on all other mouse button clicks, than lmb.

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeokit/xeokit-sdk/commit/4e6b103eb063215dc0aeda8bb01eb64cb34ac2d5
