### ISSUE TITLE
ContextMenu dynamic item titles

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#338]
Currently the title is hardcoded on the contextMenu. It would be nice to be able to set the text for the contextMenu programmatically in a method called e.g. **setTitle**, which receives a context object (like **getEnabled** and **doAction**)

https://github.com/xeokit/xeokit-sdk/blob/master/src/extras/ContextMenu/ContextMenu.js#L54

**Comment by xeolabs** [comment]
Added in https://github.com/xeokit/xeokit-sdk/commit/85769100d722f8f63d83b1dd5dc9330457a34834
