### ISSUE TITLE
adding objects to an existing xkt file

### ISSUE THREAD

**Issue by ESiham** [xeokit/xeokit-sdk#346]
Hello, everyone, I have an issue I  used xeokit-sdk to convert my IFC file of a building to an xkt file and now I would like to insert some objects like chairs into my existing xkt file but I don't know if this is possible or not, and if possible how to do it. please does anyone have information?

**Comment by xeolabs** [comment]
Hi, unfortunately XKT is not designed for editing - you'll need to edit the IFC or the glTF then reconvert to XKT.

**Comment by ESiham** [comment]
Okay, do you know a tool to edit glTF ?

**Comment by xeolabs** [comment]
Not that I'm aware of, no.
