### ISSUE TITLE
CameraControl zoom bugged until pivotPoint timeout

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#349]
The pivot point stays for one second after a pivot. Meanwhile, if we try to zoom in ou out, the camera starts to move then comes back to its original position.

![BimData platform](https://user-images.githubusercontent.com/32667664/84632807-baa4ca00-aeef-11ea-978e-903a6e7e26e7.gif)

**Comment by Amoki** [comment]
Oh, I just was your commits to fix this issue. Unfortunately, the bug is still here.

The bug is even more visible on mobile:
When we want to pinch to zoom, a finger is detected before the other, starts a pivot, and locks the zoom until the 1 ou 2 seconds of pivot timeout.

**Comment by Amoki** [comment]
The bug doesn't seem to directly come from the pivot point.
When we move, the model takes 1 sec to totally stop (like a smooth scroll). During the smooth pivot, any other order to move the camera (zoom, pan) bug. 
Is there a way to disable the smooth pivot?

**Comment by xeolabs** [comment]
@Amoki try 

````myViewer.cameraControl.dollyInertia = 0;````

Also, this bug seems to be fixed in master - can you confirm [this example](https://xeokit.github.io/xeokit-sdk/examples/#CameraControl_orbit_Duplex) works as expected?

**Comment by Amoki** [comment]
The example has the same problem :disappointed: 

![output](https://user-images.githubusercontent.com/1349751/89990362-8dbc2b80-dc82-11ea-85c6-71680e940b13.gif)

I'll try on my projet with `dollyInertia=0` today or tomorrow

**Comment by Amoki** [comment]
I don't see any difference with dollyInertia = 0. There is still inertia on pivot

**Comment by xeolabs** [comment]
@Amoki I made a tweak to master - try the example now

**Comment by Amoki** [comment]
It's a bit better.
While the pivot point is active, the zoom is very slowed down but we don't have the rollback effect anymore

**Comment by xeolabs** [comment]
Yes I see what you mean with the pivot slowing the zooming/dollying. I'll see if I can fix that. For now, you can work around it by setting ````rotationInertia = 0````. (which is maybe better UX anyway?)

**Comment by Amoki** [comment]
That what I was looking for! It fixes the problem, it's a better UX and feels less laggy on big models/slow computers. Thanks!
