### ISSUE TITLE
Performance Model add VectorTextGeometry

### ISSUE THREAD

**Issue by vs1785** [xeokit/xeokit-sdk#351]
How to add a VectorTextGeometry to Performance Model?

I have tried creating a new geometry using buildVectorTextGeometry and then assigned positions and indices from that geometry to Performance Model using createGeometry.

It renders text but i see extra lines in between text.

**Comment by xeolabs** [comment]
Currently PerformanceModel only supports triangle meshes, while VectorTextGeometry creates VBOGeometry and ReadableGeometry components, which do support line segments. 

Therefore, there's unfortunately no way to currently (correctly) generate vector text within a PerformanceModel.
