### ISSUE TITLE
"Moveable PerformanceNodes" causes a huge performance degradation

### ISSUE THREAD

**Issue by lasselaakkonen** [xeokit/xeokit-sdk#359]
This commit 3530856d causes a huge performance degradation.

# Reproducing

Using a model I happen to have, with 10 000s objects. Using xeokit with almost minimal initialization configs. Calculating the FPS with the stats plugin and doing a scientific "wave the model around and see what the FPS is"-analysis.

Using a MacBookPro, macOS 10.13.6, Chrome 83.0.4103.97 ..

.. using the discrete Radeon Pro 455 GPU:

> Display Adapter Vendor: ATI Technologies Inc.
> Display Adapter: AMD Radeon Pro 455 OpenGL Engine
> Supported OpenGL Version: 2.1 ATI-1.68.20

- Load a model with 10 000s objects and edges enabled
- Checkout commit 5118d4dc
- Rotating the view around, FPS is around 51-52
- Checkout commit 3530856d
- Rotating the view around, **FPS goes down to around 23**

.. using the integrated Intel HD 530 GPU:

> Display Adapter Vendor: Intel Inc.
> Display Adapter: Intel(R) HD Graphics 530
> Supported OpenGL Version: 2.1 INTEL-10.36.19

- Load a model with 10 000s objects and edges enabled
- Checkout commit 5118d4dc
- Rotating the view around, FPS is around 21-22
- Checkout commit 3530856d
- Rotating the view around, **FPS stays around 18-19**, there is a small but consistent degradation

Using a Samsung S10e and a iPad Pro A1701 I also could not reproduce the performance degradation. Their FPS was obviously lower, but the offset calculations did not seem to affect them like with the Radeon GPU.

Edit: Added more specific Reproducing section. Changed the FPS numbers a bit, so they are a bit more accurate.

Edit: Added more details about the GPUs.

**Comment by lasselaakkonen** [comment]
Is there a way to disable all of the "Moveable PerformanceNode"-features? So that we could use the latest version, but without the "Moveable PerformanceNode"-features, which do not need.

**Comment by lasselaakkonen** [comment]
At least calculations such as this https://github.com/xeokit/xeokit-sdk/blob/3530856d6ec473f8b217273f3b079e845f75a06d/src/viewer/scene/PerformanceModel/lib/batching/draw/batchingDrawShaderSource.js#L96 seem to affect the rendering speed significantly.

**Comment by Amoki** [comment]
I can't see any significant difference on my laptop (Linux, Intel graphic card).

Can you try with `src.push("worldPosition.xyz += offset;");`? There may be a small compiler optimisation there

**Comment by lasselaakkonen** [comment]
`src.push("worldPosition.xyz += offset;");` did not seem to make a difference.

I updated the original message with more detailed info. It seems the issue can be reproduced with a Radeon GPU, but not with an Intel GPU.

I have also reproduced the issue using the latest xeokit sources with the offset calculations VS with the offset calculations commented out.

**Comment by xeolabs** [comment]
Hopefully we haven't hit some edge case that low-end GPUs like Intel HD are failing to optimize correctly for. 

Could you also try setting this line in CameraUpdater.js: https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/CameraControl/lib/CameraUpdater.js#L3

to:

````javascript
const SCALE_DOLLY_EACH_FRAME = 2000; 
````

This will cause the "follow pointer" behavior to stop working, would be interesting to see if it makes a difference.

**Comment by lasselaakkonen-congrid** [comment]
> Hopefully we haven't hit some edge case that low-end GPUs like Intel HD are failing to optimize correctly for.

It is actually the Radeon that is performing poorly / failing to optimize stuff. The MBP has a "less powerful Intel GPU" and a "more powerful Radeon GPU", so the Intel GPU will have a lower FPS, but the offset calculations do not seem to affect it. The Radeon GPU has performed fine/consistently, until 3530856.

> `const SCALE_DOLLY_EACH_FRAME = 2000; `
There didn't seem to be a noticeable difference. I'm just moving the mouse around, looking at a FPS counter and the computer doing other random stuff in the background, so the measurements are not that accurate.

Using 3530856 and `SCALE_DOLLY_EACH_FRAME=2`.
- MBP, Radeon Pro 455: 25-27fps
- MBP, Intel HD 530: 21-23fps

Using 3530856 and `SCALE_DOLLY_EACH_FRAME=2000`.
- MBP, Radeon Pro 455: 24-28fps
- MBP, Intel HD 530: 21-23fps

**Comment by xeolabs** [comment]
@lasselaakkonen-congrid could you try this branch and see if you get the performance regression: https://github.com/xeokit/xeokit-sdk/tree/disable-offsets

In that branch, I just disabled the offsets in the shaders.

**Comment by lasselaakkonen** [comment]
Using a model I happen to have, a MacBookPro, macOS 10.13.6, Chrome 83.0.4103.97 ..

Using 49fa5a06 from `master`:
- Radeon Pro 455: 26-27fps
- Intel HD 530: 26-27fps

Using 53712e42 from `disable-offsets`:
- Radeon Pro 455: 50-51fps
- Intel HD 530: 29-31fps

@xeolabs I had done some very similar experimentation of commenting out stuff related to offsets and I got very similar results then as well -- the offsets were what caused the performance issues on the Radeon GPU.
