### ISSUE TITLE
Fix CameraControl "doublePickedNothing" event arguments

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#365]
the doublePickedNothing event args **returns a boolean value 'true'**  instead of the event argument object, containing the canvasPos as promised in the documentation: 

https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/CameraControl/CameraControl.js~CameraControl.html#---pickednothing---

tested on chrome with npm 1.3.52

**Comment by xeolabs** [comment]
Fixed in @xeokit/xeokit-sdk 1.3.6
