### ISSUE TITLE
Zoom should use native pinch-to-zoom

### ISSUE THREAD

**Issue by eriadam** [xeokit/xeokit-sdk#368]
When using the pinch-to-zoom gesture on a touch device, the whole web view is zoomed into, not the model. It seems the canvas/application does not respond to the gesture.

<img width="1108" alt="Screenshot 2020-06-26 at 22 09 01" src="https://user-images.githubusercontent.com/2480660/85896960-b0d96b80-b7f9-11ea-87b9-94f25cb14e10.png">

Version 1.3.52

**Comment by eriadam** [comment]
UPDATE: I cannot reproduce this on the iPad at the moment, will look into this a bit more on Monday.

**Comment by raffdp** [comment]
Did you get a resolution to this? 
I have been looking to resolve this too. It looks like you might have to disable the native browser pinch zoom and navigation gestures as the browser is intercepting the gestures before they get to the canvas. Haven't found the the solution yet though.

**Comment by raffdp** [comment]
Resolved by adding
body {
    touch-action: none;
}
Tested on Windows Surface
