### ISSUE TITLE
Meshes are not selectable on touch devices

### ISSUE THREAD

**Issue by eriadam** [xeokit/xeokit-sdk#369]
Version 1.3.52

Picking meshes not working on touch devices.

**Comment by xeolabs** [comment]
Could be related to https://github.com/xeokit/xeokit-sdk/issues/386

**Comment by xeolabs** [comment]
@eriadam is this issue about inability to (touch) pick a 3D position on the surface of a ````Mesh```` that has a  ````VBOGeometry```` ?. 

If so, to work around this issue for now, I recommend replacing your ````VBOGeometry```` components with ````ReadableGeometry````. The latter geometry type supports surface picking. ````VBOGeometry```` just doesn't have that code path implemented yet.
