### ISSUE TITLE
[ViewCulling] Visual bug on some elements

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#371]
Some faces aren't shown when they should be.

![culling problem](https://user-images.githubusercontent.com/1349751/86231072-40807080-bb92-11ea-8a00-ea6a01be32f3.gif)

**Comment by xeolabs** [comment]
Could I get that model to debug with?

**Comment by Amoki** [comment]
Sent in private!

**Comment by xeolabs** [comment]
I haven't been able to reproduce this bug, at least using this viewer setup:   https://gist.github.com/xeolabs/8047d833b2699098ff251868053a556c

Could you post a minimal HTML page that shows this issue?

**Comment by Amoki** [comment]
I just retried on commit (https://github.com/xeokit/xeokit-sdk/commit/cbde67749e34242259d046d02e8a43eac51794d1) with the following code and the bug is still here:
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
</head>
<body>
    <div>
        <canvas id="app" style="height: 100vh;width: 100vw"></canvas>
    </div>
    <script type="module">
        import { Viewer } from "./node_modules/@xeokit/xeokit-sdk/src/viewer/Viewer.js";
        import {ViewCullPlugin} from "./node_modules/@xeokit/xeokit-sdk/src/plugins/ViewCullPlugin/ViewCullPlugin.js";
        import { XKTLoaderPlugin } from "./node_modules/@xeokit/xeokit-sdk/src/plugins/XKTLoaderPlugin/XKTLoaderPlugin.js";

        const viewer = new Viewer({
            canvasId: "app",
            transparent: true
        });
        new ViewCullPlugin(viewer, {
            maxTreeDepth: 20
        });
        const xktLoader = new XKTLoaderPlugin(viewer);

        const model = xktLoader.load({
            src: "./model.xkt",
            edges: true,
        });
        model.once("loaded", () => viewer.cameraFlight.flyTo(model));
    </script>
</body>
</html>
```

**Comment by xeolabs** [comment]
I found the reason :-

- for efficiency, xeokit does not render backfaces for XKT models, and 
- this model's triangles contain inconsistent vertex winding directions, meaning that some triangles have their vertices listed in the wrong order, causing them to be treated as backfaces when they would be front-facing.

After hacking the renderer to disabler backface culling, the faces appear:

![Screenshot from 2020-12-20 14-39-01](https://user-images.githubusercontent.com/83100/102714862-e73c0300-42d1-11eb-8f43-dfba8c8d165e.png)

We don't want to enable backfaces to work around these kinds of meshes - it would reduce rendering performance too much.
