### ISSUE TITLE
Component confusion in loading gltf model

### ISSUE THREAD

**Issue by ZBrave77** [xeokit/xeokit-sdk#372]
Using the latest version of gltf loader to load the model will lead to component confusion. I looked at the example on the official website and found a similar problem. https://xeokit.github.io/xeokit-sdk/examples/#loading_glTF_Duplex_transform

![微信图片_20200701231324](https://user-images.githubusercontent.com/55724830/86261049-a7347700-bbf0-11ea-8263-3892ba50100c.png)

**Comment by Amoki** [comment]
Duplicate of https://github.com/xeokit/xeokit-sdk/issues/370

**Comment by xeolabs** [comment]
Now fixed in xeokit-sdk 1.3.53 on npm
