### ISSUE TITLE
Can this sdk be used for ground plane?

### ISSUE THREAD

**Issue by marcusx2** [xeokit/xeokit-sdk#373]
Can I use this sdk to place objects on the ground, move, rotate, and scale them? See [vuforia's ground plane](https://www.youtube.com/watch?v=oTgc9ozukyY).

**Comment by Amoki** [comment]
You can, but it may not be the best. There are no animations nor shadows. xeokit's strength is to be able to show hundreds of thousand objects in the same scene which you probably don't need in your use case.

**Comment by marcusx2** [comment]
I need to place the object on the ground, then navigate inside it. I see I can use this library to navigate inside 3D objects. Is there an example of placing an object on the ground with it? I don't need animations or shadows. Just placement(rotate, scale, and move)

**Comment by Amoki** [comment]
What do you mean by "place the object on the ground"?
You would need to define the "ground" yourself, there is no such thing in xeokit.
As long as you know the coordinate to place the object, you're good!

**Comment by xeolabs** [comment]
The ````ImagePlane```` component in ````v1.3.6```` may be what you need - example: https://xeokit.github.io/xeokit-sdk/examples/#ImagePlane_groundPlane
