### ISSUE TITLE
Xeokit doesn't render Model loaded from OpenBIMServer

### ISSUE THREAD

**Issue by McFege** [xeokit/xeokit-sdk#376]
Hi,

I've been trying to load models uploaded to the openbimserver instance running on my local server and had no luck with the process. I've been trying with the exact template issued on the documentations, only changing the bimServerAddress, credentials, and poid.
Since the example (hosted on cleverapps) is no longer online, I can't confirm if the connection itself is the problem and after a few days of trying to bugfix it by step-for-step compiling the code, I am on the brink of insanity ;)

The connection succeeds and it creates the download-link complete with cleanup POST's, the outcome is still a never-ending loading canvas...

Can anyone please help or tell me sth I need to change or adapt to make it work?

10x,
Fege

Template code I use: [https://github.com/xeokit/xeokit-sdk/blob/master/examples/BIMServer_Schependomlaan.html](url)

**Comment by TitouanGisle** [comment]
Hi ! I have the same issue !

I have infinite loading when using the version 1.5.182 of BIMserver, bimserverclient.js seems to get stuck at the "Getting model data..." step.

A version 1.5.162 of BIMserver works though (to a certain extent anyway : many objects are not rendered)

**Comment by xeolabs** [comment]
Does this issue still occur in the current release?
