### ISSUE TITLE
After explosion, the entity and wire frame are separated

### ISSUE THREAD

**Issue by ZBrave77** [xeokit/xeokit-sdk#382]
Hello, I would like to ask how to solve the problem of leaving the wireframe in place after I offset the object?
![MU{@$(ZGAQDXXR@BJZOQ(3W](https://user-images.githubusercontent.com/55724830/87624411-4d888c80-c75a-11ea-91c3-d5180b4489ba.png)

**Comment by xeolabs** [comment]
Hi, is this a bug where the solid part of the objects is moving, but the wireframe edges do not move?

Are there any messages in the JavaScript console?
What OS and browser are you using?

**Comment by xeolabs** [comment]
PS. If you can publish an HTML page that demonstrates the bug, that would be ideal.

**Comment by ZBrave77** [comment]
> 嗨，这是一个错误，对象的实体部分正在移动，而线框边缘却不移动吗？
> 
> JavaScript控制台中是否有任何消息？
> 您正在使用什么操作系统和浏览器？

The JavaScript console does not have any error messages. I use Google browser and the operating system of win 10.

**Comment by ZBrave77** [comment]
> PS. If you can publish an HTML page that demonstrates the bug, that would be ideal.

![image](https://user-images.githubusercontent.com/55724830/87650348-18912f80-c784-11ea-9d5b-2be932654769.png)

**Comment by Amoki** [comment]
You're using an "old" version (the "true" in logs have been removed on 25 May) https://github.com/xeokit/xeokit-sdk/commit/5e8e4ac2003a58f78859ebfaf1701ea31b65fe92), can you try with the latest version?

**Comment by ZBrave77** [comment]
> You're using an "old" version (the "true" in logs have been removed on 25 May) [5e8e4ac](https://github.com/xeokit/xeokit-sdk/commit/5e8e4ac2003a58f78859ebfaf1701ea31b65fe92)), can you try with the latest version?

So, you don't know which file the line and entity separation offset is written in,?

**Comment by ZBrave77** [comment]
> You're using an "old" version (the "true" in logs have been removed on 25 May [5e8e4ac](https://github.com/xeokit/xeokit-sdk/commit/5e8e4ac2003a58f78859ebfaf1701ea31b65fe92)), can you try with the latest version?

Hello, I want to ask again if there is an explosion for 3DXML format

**Comment by xeolabs** [comment]
Hi, no explosion support for 3DXML yet, but it is planned.

Would you be able to deploy your example so it can be loaded in a browser? Maybe make a small github project and publish it to the web as gh-pages?

**Comment by ZBrave77** [comment]
> Hi, no explosion support for 3DXML yet, but it is planned.
> 
> Would you be able to deploy your example so it can be loaded in a browser? Maybe make a small github project and publish it to the web as gh-pages?

Hi, I've used the new version to solve the wireframe problem. Now, how can the explosion function be restored to its original state?

**Comment by xeolabs** [comment]
Retore the explosion by supplying a zero length vector to Entity#setExplosionOffset().

**Comment by ZBrave77** [comment]
Excuse me, which JS folder is setexplosionoffset() in?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xeokit/xeokit-sdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 晚上6:45
收件人:&nbsp;"xeokit/xeokit-sdk"<xeokit-sdk@noreply.github.com&gt;;
抄送:&nbsp;"温祖儿"<892375155@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xeokit/xeokit-sdk] After explosion, the entity and wire frame are separated (#382)





 
Retore the explosion by supplying a zero length vector to Entity#setExplosionOffset().

**Comment by ZBrave77** [comment]
> Retore the explosion by supplying a zero length vector to Entity#setExplosionOffset().

Sorry, I can't find the function you mentioned. Can you tell me which JS file setexplosionoffset() is in?

**Comment by xeolabs** [comment]
Oops, I mean use this method here: https://github.com/xeokit/xeokit-sdk/blob/master/examples/BIMOffline_XKT_metadata_moveStoreys.html#L172

This will restore the objects to their unexploded positions:
myScene.setObjectsOffset(["myObject", "myObject2"...], [0,0,0]);
