### ISSUE TITLE
GLTFLoader Performance Mode - Follow Pointer

### ISSUE THREAD

**Issue by raffdp** [xeokit/xeokit-sdk#386]
The cameraControl.followPointer=true does not seem to work for the GLTFLoader when performance=false. It always has the pivot point at the centre of the scene and not the last selected point on the model. It does work when performance=true;

**Comment by xeolabs** [comment]
Reason for this is that ````GLTFLoaderPlugin```` with ````performance:false```` creates ````Mesh```` components, which hold their geometry in  ````VBOGeometry```` components. 

````VBOGeometry```` intentionally does not support surface-picking. 

However, the new ````CameraControl```` relies on surface picking for ````followPointer```` behaviour, therefore that's not working for ````GLTFLoaderPlugin```` with ````performance:false````.

Solution is to implement surface-picking for ````VBOGeometry````.

**Comment by xeolabs** [comment]
For dev purposes, issue can be reproduced using this code: https://gist.github.com/xeolabs/c2eb4d437b484f4896111442036465d0
