### ISSUE TITLE
Rotation direction needs to be aware of upside down model

### ISSUE THREAD

**Issue by raffdp** [xeokit/xeokit-sdk#388]
When you rotate a model upside down, rotation left and right follows the same axis direction, so the rotation is in the opposite direction relative to where you are dragging the rotation.
![RotationNeedsToReverse](https://user-images.githubusercontent.com/1573230/87778839-b4be4380-c823-11ea-991c-0bc4f47e6b5a.gif)

**Comment by xeolabs** [comment]
Any clues on how to do this robustly are most welcome!
