### ISSUE TITLE
Entity rotation issue

### ISSUE THREAD

**Issue by ESiham** [xeokit/xeokit-sdk#389]
Hello, I have an existing model of a house, and I would like to build  a virtual tour inside the apartment, and I like during the tour rotating the doors entity about 90 degrees, I tried to use the rotateX() or rotateY() functions but seems not working I get the following issue, Uncaught TypeError: entity.rotateY is not a function
Can anyone help me

**Comment by Amoki** [comment]
These functions are only accessible if the gltf to rotate is loaded with `performance: false`.
```js
gltfLoader.load({
  src: "my/path",
  performance: false
});
```

It does not work for xkt models.

**Comment by ESiham** [comment]
I tried with gltf file and with performance: false but still not working.

**Comment by xeolabs** [comment]
Closing because not enough information to reproduce this issue.

**Comment by antoniohof** [comment]
I also could not rotate a .gltf after it was loaded. I can position it using offset but I can't rotate it. Even with performance: false.
