### ISSUE TITLE
Fix broken emphasis fill effect

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#394]
Hello there,

I've noticed some issues with rendering when picking elements.

This is what I get on my Macbook Pro 13":

<img width="1440" alt="mac" src="https://user-images.githubusercontent.com/38168628/89178150-4dc3bd00-d58d-11ea-90a3-fa7cf3df2c51.png">

And this is what I get on my PC:

![pc](https://user-images.githubusercontent.com/38168628/89178179-5a481580-d58d-11ea-9af3-325741737c72.png)

FYI:

Same result across all major modern browsers so that doesn't seem to make a difference.

The Mac is an older model (2017 I believe) and has some shitty integrated GPU I'm guessing.

I have a GTX 1070 8GB in my PC. For what it's worth @tothatt81 has a significantly lower powered GPU (GT 1030 2GB) and it works fine for him as well.

The expected result would be what you can see on the PC screenshot.

Could you please look into it? Thank you.

**Comment by xeolabs** [comment]
Hi, any errors or warnings in the JS console?

**Comment by barnabasmolnar** [comment]
Yep:

`[.WebGL-0x7f8d29062e00]GL ERROR :GL_INVALID_OPERATION : glDrawElementsInstancedANGLE: attempt to access out of range vertices in attribute 5`

**Comment by xeolabs** [comment]
Fixed in @xeokit/xeokit-sdk 1.3.7
