### ISSUE TITLE
 model is too large ，results too long loading time

### ISSUE THREAD

**Issue by xiaokai199010** [xeokit/xeokit-sdk#399]
The gltf model is too large, which results in too long loading time. However, after using Draco compression model, I don't know whether it can support it

**Comment by xeolabs** [comment]
GLTFLoaderPlugin does not support Draco yet. If you don't need textures,  I'd recommend converting your glTF to XKT for fast loading: https://github.com/xeokit/xeokit-sdk/wiki/Creating-Files-for-Offline-BIM

**Comment by xiaokai199010** [comment]
OK, thank you. I'll try it

**Comment by xiaokai199010** [comment]
Do you have plans to support Draco or use gltf-pipeline to compress and decompress gltf models？

**Comment by xeolabs** [comment]
We don't have plans to use Draco at the moment, since xeokit's native XKT format does what we need so far, at least for BIM. 

However, if you do happen to have time to add GLB / Draco to xeokit, you'd be most welcome, it would still be great to have!
