### ISSUE TITLE
[Discussion] PickedNothing behavior

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#414]
Currently, when picking miss, the usually use [0,0,0] as a default point to dolly/pan/rotate.

Some models are far from [0,0,0] and pivot, in this case, behave weirdy. (and it will be worst with xkt v6)

What do you think about using the center of the scene instead?

**Comment by xeolabs** [comment]
@Amoki possible this update fixes this behaviour: #503

**Comment by Amoki** [comment]
Currently, the user shouldn't click outside the model. We're trying not to lose users when they do this rather than providing a smart behavior when clicking outside the model.

After some discussions, we'd like to try some stuff, but we don't have enough math skills to try it ourselves.

![pivot](https://user-images.githubusercontent.com/1349751/102763527-1908a480-437a-11eb-807f-45f632fc0dbe.jpeg)

We draw a virtual sphere between the center of the model and the camera.
If the user clicks on the model, the pivot point is where they clicked (the current behavior). (2.)
If the user clicks outside the model, the intersection between the ray and the sphere is used as the pivot point. If we click outside the model on the right, the behavior is different if we click outside the model on the left. (1.)

What do you think?

**Comment by xeolabs** [comment]
I like it - I think this would work well

**Comment by Amoki** [comment]
How do you want to proceed?

We know how to generate an invisible geometry but we may don't want to create one. And we don't know how to compute the intersection between the sphere and the ray.

**Comment by xeolabs** [comment]
I can handle this one, but won't be for a couple of weeks or so. 

I wouldn't use an invisible sphere geometry - I think this would involve simply setting the pivot point at a position on the Camera's (eye->look) vector, set at a distance equivalent to radius of the virtual sphere, so no intersection calculations needed.

**Comment by Amoki** [comment]
Not on the `eye -> look` vector, more the `eye -> cursor` vector, no ?

**Comment by xeolabs** [comment]
````eye -> cursor````, yes

**Comment by Amoki** [comment]
If you tell me how to retrieve this vector, I may be able to try it after all! It seems simpler than I thought

**Comment by Amoki** [comment]
Closed by https://github.com/xeokit/xeokit-sdk/pull/534
