### ISSUE TITLE
XKT file hide over the canvas

### ISSUE THREAD

**Issue by Kishanpparmar** [xeokit/xeokit-sdk#420]
Hello,
when I load the XKT file it will hide by the canvas after zoom it will show but at the time 360 degree rotating it will hide some portion check the att
![Image1](https://user-images.githubusercontent.com/69810471/91286089-a0b71b80-e7ab-11ea-968b-648b268a1c11.png)
![Image2](https://user-images.githubusercontent.com/69810471/91286100-a3b20c00-e7ab-11ea-883d-b6da4f69dc7c.png)

ached Images.

**Comment by xeolabs** [comment]
Looks like WebGL's far clipping plane is slicing part of your model.

To fix, either reduce the scale of your model (recommended), or increase the distance to far clipping plane like this:

````javascript
myViewer.scene.camera.perspective.far = 10000.0;
myViewer.scene.camera.ortho.far = 10000.0;
````

**Comment by Kishanpparmar** [comment]
Hello,
Thanks for your help. 
after applying  camera.perspective.far and camera.ortho.far my problem is resolved 
but facing issue in Annotation,
**_Annotation are not display on object.
I also apply annotations.surfaceOffset = 10000.0_**
still facing issue.
