### ISSUE TITLE
BCFViewPointsPlugin is not loading SectionPlanes

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#421]
**Describe the bug**
````BCFViewPointsPlugin```` ````loadViewPoint```` is not loading ````SectionPlanes````.

**To Reproduce**
Run demo: https://xeokit.github.io/xeokit-sdk/examples/#BCF_LoadViewpoint

**Expected behavior**
Front of model should be sliced off by a ````SectionPlane```` loaded by the example's ````BCFViewpointsPlugin````.

**Comment by Amoki** [comment]
The clipping plane is actually loaded:
![Capture d’écran de 2020-08-27 08-35-55](https://user-images.githubusercontent.com/1349751/91400697-63509d80-e840-11ea-8cfe-463d3e077eed.png)
