### ISSUE TITLE
Problem with sectioning tool

### ISSUE THREAD

**Issue by lyluojy** [xeokit/xeokit-sdk#422]
When using the sectioning tool in gltf format, the section plane of the model is not aligned with the actual section plane, or the section plane cannot be cut by dragging the section plane.
![微信图片_20200829162820](https://user-images.githubusercontent.com/43317137/91632538-0c9bbd00-ea14-11ea-8b2d-fc091dc3b379.png)

**Comment by xeolabs** [comment]
Fixed by #481
