### ISSUE TITLE
Documentation for creating Meshes with different primitives

### ISSUE THREAD

**Issue by MaximilianFranz** [xeokit/xeokit-sdk#423]
I've been trying to generate geometry in xeokit from our own internal format. We have lines, points, polygons, etc.. I've been able to generate Meshes within xeokit with ease, using the ReadableGeometry as such: 

```javascript 

    new Mesh(this.viewer.scene, {
        geometry: new ReadableGeometry(this.viewer.scene, 
          {
            positions: [0.0, 3, 0.0, -3, -3, 0.0, 3, -3, 0.0], 
            indices: [0, 1, 2],
            uv: [0.0, 0.0, 0.5, 1.0, 1.0, 0.0],
          
          }),
        material: new PhongMaterial(this.viewer.scene, {
            ambient: [0.9, 0.3, 0.9],
            shininess: 30,
            backfaces: true // otherwise only one side is visible
        })
    });


``` 
However, I have not been able to find any useful documentation on how to handle primtives like points, lines and line-loops that are [described here. ](https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/geometry/ReadableGeometry.js~ReadableGeometry.html)

**Describe the solution you'd like**

- A short example of how to use primitives other than triangles would be useful. 
- A more precise documentation of ReadableGeometry would  be desirable. 

I can be of help writing the documentation, once a minimal viable example has been given. I guess I'll be able to figure out how the internals work from there, but guessing at how to use indices and positions for points, lines, etc. isn't going to be very effective.

**Comment by Amoki** [comment]
This may be related to (but not a duplicate) https://github.com/xeokit/xeokit-sdk/issues/364.
