### ISSUE TITLE
objectDefaults overrides actual IFC color with BIMServerLoaderPlugin

### ISSUE THREAD

**Issue by TitouanGisle** [xeokit/xeokit-sdk#424]
The default object colorization of a BIMServerLoaderPlugin (whether the one by default in IFCObjectDefaults.js, or one provided in its constructor) actually overrides the color of the IFC.

With a forced empty objectDefaults, we get the correct colors, defined in the IFC :
```javascript
new BIMServerLoaderPlugin(viewer, {
    bimServerClient: client,
    objectDefaults : {}
 });
```
![image](https://user-images.githubusercontent.com/47686081/91965105-50423f80-ed10-11ea-93a0-654dad280ae6.png)
(as proved by the same model on BIM Vision)
![image](https://user-images.githubusercontent.com/47686081/91965213-79fb6680-ed10-11ea-8c05-feafda497efc.png)

However, if we set a default color for IFCRoofs, for example, it completely overrides the IFC colors :
```javascript
new BIMServerLoaderPlugin(viewer, {
    bimServerClient: client,
    objectDefaults : {
         IfcRoof: {
            colorize: [1, 0, 1] //very pink
         }, 
     }
 });
```
![image](https://user-images.githubusercontent.com/47686081/91965706-2d645b00-ed11-11ea-9845-5cc8cf51a9b3.png)

I didn't test with the XKTLoaderPlugin, so it might actually be the intended behavior, but to me, a default colorization should only be applied if the color of the element can't be retrieved from the metadata.

**Comment by juho-ylikyla** [comment]
This issue is also present in the XKTLoader (ParserVX.js)

At least there the problem is that this the defaults actually do overwrite the colors in the actual IFC color:

```
performanceModel.createMesh(utils.apply(meshDefaults, {
                    id: meshId,
                    color: color,
                    opacity: opacity,
                    matrix: entityMatrix,
                    geometryId: geometryId,
}));
```
This is the utils.apply which overwrites the second parameter with the first one

```
/** Add properties of o to o2, overwriting them on o2 if already there
 */
function apply(o, o2) {
    for (const name in o) {
        if (o.hasOwnProperty(name)) {
            o2[name] = o[name];
        }
    }
    return o2;
}
```
