### ISSUE TITLE
Ability to disable Viewer anti aliasing

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#427]
Support disabling of WebGL antialiasing for a ````Viewer````:

````javascript
const viewer = new Viewer({
    antialiasing: false
});
````

**Comment by Amoki** [comment]
Open question:
Could it be possible to disable the anti-aliasing dynamically? Like https://xeokit.github.io/xeokit-sdk/examples/#techniques_nonInteractiveQuality

**Comment by xeolabs** [comment]
Unfortunately antialiasing is only configurable when we instantiate the WebGL context - can't be set dynamically. Would be nice indeed.

**Comment by xeolabs** [comment]
Crazy idea: temporarily reducing the resolution of the canvas (ie via CSS) while the camera is moving?

**Comment by Amoki** [comment]
If it doesn't flicker, it may be a good idea!
