### ISSUE TITLE
How to Get Title description form Id

### ISSUE THREAD

**Issue by Kishanpparmar** [xeokit/xeokit-sdk#432]
I want Title to form the selected object.
when I get the information from Id like 
         viewer.scene.objects["object Id"]
but I did not get the object title form that.

**Comment by Kishanpparmar** [comment]
Dear Team,
any help for the above!!!

**Comment by Amoki** [comment]
The scene has only geometric information.
For IfcType, Name, and stuff like that, you can use https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/metadata/MetaModel.js~MetaModel.html
These data aren't in the gltf/xkt file
