### ISSUE TITLE
Continuous orbit around selection

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#433]
I'd like the camera to orbit around a selection.
Is there a method the retrieve the center of all selected object to set it as the `pivotPos`?

To orbit, the code uses 
* `updates.rotateDeltaY`. I can update it with `cameraControl._updates.rotateDeltaY += 5` but the `_` tells me I shouldn't.
* `orbitYaw()`, but it doesn't let me chose the orbit center.

**Comment by xeolabs** [comment]
Hey @Amoki , try this:

````javascript
const selectedObjectIds = viewer.scene.selectedObjectIds;
const aabb = viewer.scene.getAABB(selectedObjectIds);
````

Then from here, you could do:

````javascript
viewer.cameraFlight.flyTo(aabb);
````

Or perhaps: 

````javascript
const center = math.getAABB3Center(aabb);
viewer.scene.camera.eye = center;
````

**Comment by xeolabs** [comment]
But of course, that moves the camera to look at the center, which implicitely sets that as the pivot pos. 

Maybe I missed something?

**Comment by Amoki** [comment]
Thanks!
It's not excatly what I was thinking but I'll go with it.
I was thinking about pivoting the model so the camera would be free to move but it may be way more complexe to implement.
