### ISSUE TITLE
Section planes and gltf model

### ISSUE THREAD

**Issue by Stalso** [xeokit/xeokit-sdk#445]
Hello. You have an example, how to place section planes control in custom place using mouse. I mean [this one](https://xeokit.github.io/xeokit-sdk/examples/#gizmos_SectionPlanesPlugin_createWithMouse). Here you use `xkt` model. When I try to use `gltf` model with `performance = false`, my `pickResult.worldPos` and  `pickResult.worldNormal` in `mouseclicked` event handler have null values. So I can not choose right position for section planes. How can I overcome this problem? 

**EDIT** This issue is reproduced when we use `GLTFLoaderPlugin` with `performance = false` option. If we load model with `performance = false` everything works

**EDIT** Also found, that if you try to implement object context menu in model, loaded using  `GLTFLoaderPlugin` with `performance = false` option, you will get following exception:

    Uncaught TypeError: Cannot convert undefined or null to object
        at Float32Array.set (<anonymous>)
        at HTMLCanvasElement.MousePanRotateDollyHandler.canvas.addEventListener._mouseDownHandler 
    (MousePanRotateDollyHandler.js:174)
    MousePanRotateDollyHandler.canvas.addEventListener._mouseDownHandler @ MousePanRotateDollyHandler.js:174 

And if we dive into source code of sdk, we can see that exception is thrown in following line: 

    pickedWorldPos.set(pickController.pickResult.worldPos);

So we can see, that this is bug. `pickResult.worldPos` is not calculated for models, loaded using  `GLTFLoaderPlugin` with `performance = false` option, but library itself needs this.

**Comment by xeolabs** [comment]
Can you try again with the latest release?
