### ISSUE TITLE
Fix PickResult#worldPos for arbitrary ray picking

### ISSUE THREAD

**Issue by lasselaakkonen** [xeokit/xeokit-sdk#447]
**Describe the bug**
Calling `hit = pick()` with `origin[]` and `direction[]` parameters returns incorrect values for `hit.worldPos[]`.

**To Reproduce**
1. Open https://xeokit.github.io/xeokit-sdk/examples/#picking_ray_surface
2. Witness the "red pick target" fly around in the world

**Expected behavior**
The "red pick target" should be rendered at the point where the ray intersects with the first object it hits.

**Screenshots**
![xeokit-pickresult](https://user-images.githubusercontent.com/6214096/95881400-366d3100-0d81-11eb-91ef-45c6c7678741.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version v85.0.4183.121

**Comment by xeolabs** [comment]
![Peek 2020-10-28 14-53](https://user-images.githubusercontent.com/83100/97445279-6265e600-192d-11eb-9a22-9cc2d0ba5f19.gif)
