### ISSUE TITLE
Using rotation params property in XKTLoader breaks scene.pick(origin: [...], direction: [...])

### ISSUE THREAD

**Issue by juho-ylikyla** [xeokit/xeokit-sdk#448]
**Describe the bug**
When loading an XKT model, there is the possibility to rotate the model. If you give any rotation parameter to the load function, eg: ` rotation: [0, 0, 0]` 

the scene.pick with origin and direction breaks.

```
window.viewer.scene.pick({
              pickSurface: true,
              origin: [somewhere],
              direction: [0, 0, 10]
```

It will give a randomly picked entity, seemingly depending on the current camera position.

**To Reproduce**
1. Go to https://xeokit.github.io/xeokit-sdk/examples/#picking_ray_surface
2. Edit the loading function https://github.com/xeokit/xeokit-sdk/blob/master/examples/picking_ray_surface.html#L57 by adding there `rotation: [0,0,0]`
3. Load the model
4. See that the selected entity is fixed.

**Screen recording**
![issue](https://user-images.githubusercontent.com/62982612/95985658-8275af80-0e2d-11eb-9f53-2d4d343d7cd9.gif)

**Comment by xeolabs** [comment]
Fixed by https://github.com/xeokit/xeokit-sdk/issues/494
