### ISSUE TITLE
Section planes solid view 

### ISSUE THREAD

**Issue by KrishDunn** [xeokit/xeokit-sdk#449]
![Section](https://user-images.githubusercontent.com/72904809/96081320-accf7780-0ed6-11eb-8a2c-f3b52dba4779.png)

In the above Snapshot after use section, it is showing a very thin surface of the object. it should be solid.
is there any option to do Solid View?

**Comment by KrishDunn** [comment]
Hello Team,
any solutions or suggestions.

**Comment by xeolabs** [comment]
Currently xeokit has no option to make solid cross-sections with SectionPlanes.

We can extend xeokit with this option in future.

It is possible to extend xeokit to robustly approximate solid cross-sections when only one SectionPlane is active. This would work by coloring interior surfaces with a uniform non-shaded color. However, it only works well for a single SectionPlane.

The alternative, to work with multiple SectionPlanes, is to use the standard stencil buffer technique.

Some info on those techniques here: http://shrekshao.github.io/2016/08/27/BioDigital-Intern-Review-3-Cross-Section/

**Comment by vs1785** [comment]
Having single SectionPlane active works for me time being. However, i am not sure where do i start to extend Xeokit to implement it.

Can you give some guidance here?
