### ISSUE TITLE
XRay Issue

### ISSUE THREAD

**Issue by KrishDunn** [xeokit/xeokit-sdk#450]
![round](https://user-images.githubusercontent.com/72904809/96115009-f97d7780-0f03-11eb-9672-8fa511afc556.png)
![round_xray](https://user-images.githubusercontent.com/72904809/96115022-fc786800-0f03-11eb-9805-29f7a6943860.png)

Round object load with multiple edges.
showing unwanted edges(vertical lines) after the x-ray feature.

**Comment by xeolabs** [comment]
The edges are an intentional part of the x-ray effect, but you can disable them.

Try this:

````javascript
myViewer.scene.xrayMaterial.edges = false;
````
