### ISSUE TITLE
BCFPlugin: Colors are incorrect

### ISSUE THREAD

**Issue by kelyamany** [xeokit/xeokit-sdk#451]
https://github.com/xeokit/xeokit-sdk/blob/9697518d43f8fc0d0b1fc0d71823f16585e6bd97/src/plugins/BCFViewpointsPlugin/BCFViewpointsPlugin.js#L394

I think the exported/imported bcf colors are incorrect as Solibri for example couldn't read the viewpoint at all until I removed the coloring node from the file.

Even exporting getting a viewpoint from xeokit and then setting it again would change the coloring of the elements even though it shouldn't

Probably swapping the color and alpha will solve the issue but I'm not sure
`color = color + alpha;`

**Comment by Amoki** [comment]
Hi,
Is the bug still there with v1.4.6? A color fix has been pushed.

BCF colors are encoded as ARGB (https://github.com/buildingSMART/BCF-api#optimization-rules-1) even if the most common format is RGBA.

**Comment by kelyamany** [comment]
Aha, in this case let me check as we are still using v 1.4.1

**Comment by xeolabs** [comment]
Actually @Amoki could you take a look at: https://github.com/xeokit/xeokit-sdk/blob/9697518d43f8fc0d0b1fc0d71823f16585e6bd97/src/plugins/BCFViewpointsPlugin/BCFViewpointsPlugin.js#L394

Looks like I missed that line in my PR review a while back..seems to be attempting to add a scalar to a vector there.

**Comment by Amoki** [comment]
Both are strings.
color comes from `colorizeToRGB()` which returns a string and alpha is a string too.

**Comment by xeolabs** [comment]
Ah of course, cool.

**Comment by kelyamany** [comment]
yap the colors are correct in v1.4.6. at least exporting and importing from and to xeokit

Solibri is still unable to read the files whenever the "coloring" tag exists but I assume it's a problem from Solibri's side. I'll try to check that also later.

Thanks guys for the quick feedback

**Comment by Amoki** [comment]
BCFplugin exports viewpoints in BCF-API format. It's quite far from a complete BCF-XML file. What do you use to convert the viewpoint into a complete BCF file?

**Comment by kelyamany** [comment]
We created a converter to bidirectionaly convert between the 2 formats and it works quite well so far. I'm unaware if such a standard conversion way or library exists so far!

We just had to exclude the "Coloring" tag for now as it wasn't parsable using Solibri although it was parsable with ArchiCAD and other software. It didn't affect the core functionality of the BCF file anyway
