### ISSUE TITLE
Fix BCFViewpointsPlugin visibility update for composite elements 

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#452]
When loading BCF, xeokit is only setting the visibility of objects that have geometry in the 3D scene. 

Suppose we load a model, with a metadata JSON containing an ````IfcElementAssembly````, which does not have geometry of its own in the 3D scene.

Let's now load a BCF viewpoint that declares a visibility exception for that element, to set it visible.

Unfortunately, even though our ````IfcElementAssembly```` has child ````IfcWalls```` that do have geometry, ````BCFViewpointsPlugin```` will simply ignore it and not trying to set its visibility, because our ````IfcElementAssembly```` has no corresponding geometry to set visibility of.

The fix is to make that happen recursively, so that if an object in the BCF does not have geometry of its own, then we recursively visit its children, and whenever a child has geometry, set that child's visibility.

**Comment by xeolabs** [comment]
Ouch true, this fix assumes that users are loading metadata for the model. I need to make it robust for when there is no metadata.

**Comment by Amoki** [comment]
If I like the idea, I don't see anything about this in the BCF documentation. Do I miss something?

**Comment by Amoki** [comment]
I asked https://github.com/buildingSMART/BCF-XML/issues/226

**Comment by Amoki** [comment]
https://github.com/buildingSMART/BCF-XML/issues/226#issuecomment-717242800
This behavior is not in the BCF standard. If someone wants to have this behavior, they should do it themself and shouldn't be part of the BCF plugin imho.
