### ISSUE TITLE
Vue

### ISSUE THREAD

**Issue by Calvin66** [xeokit/xeokit-sdk#453]
How to use it in Vue project

**Comment by xeolabs** [comment]
https://vuejs.org/

**Comment by Calvin66** [comment]
> https://vuejs.org/

no,i mean how to use xeokit-sdk in Vue project,Because I am npm it ,[xeokit plugin GLTFLoader]: load(): Failed to load model metadata for model 'myModel from  '/metaModels/duplex/metaModel.json'
