### ISSUE TITLE
SectionPlans is not synchronized with the previous model

### ISSUE THREAD

**Issue by ZBrave77** [xeokit/xeokit-sdk#461]
![image](https://user-images.githubusercontent.com/55724830/98086500-d5390900-1eb9-11eb-8c4d-a33082d985cf.png)

There will be such a situation, and I would like to ask you, click the lower right corner of the cut plane model perspective will become very close, how to solve this problem? I think the perspective of the model will not change when I click the cut plane in the lower right corner.

**Comment by djamel2288** [comment]
Fix SectionPlane failure to clip certain objects #481
