### ISSUE TITLE
The model is not synchronized with the SectionPlans 

### ISSUE THREAD

**Issue by ZBrave77** [xeokit/xeokit-sdk#463]
![image](https://user-images.githubusercontent.com/55724830/98248608-24f9fc00-1fb0-11eb-8542-f6bb923aa4b4.png)

![image](https://user-images.githubusercontent.com/55724830/98248664-34794500-1fb0-11eb-87ca-fe938b027546.png)

I will parse the model of step format into gltf format. The application of this function will lead to the same situation as you. How can you synchronize the two?

**Comment by xeolabs** [comment]
Sorry, I don't understand this issue. Possibly fixed by #481?
