### ISSUE TITLE
Is it possible to Load the tree view plugin without the model?

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#477]
Is it possible to load the tree view plugin without the model?

**Comment by xeolabs** [comment]
Hi, no, the TreeViewPlugin populates itself from models as they're loaded, so it's dependent on models.

**Comment by vadimt2** [comment]
I need to load the structure without the model, i can take the source code of the viewer and make a wrapper without install the npm viewer gltf. and take the viewer from my own JS wrapper,
My question is: Where in the code can i change the behavior of the GTLF plugin?

const grlf = server_response_data:
if(!grlf){ // i know that i have no GLTF file.
- inside the wrapper i wiil copy paste the code from Node models GLTFLoaderPlugin and make my own GLTFLoaderPlugin
and inside my own GLTFLoaderPlugin with the copied code from the GLTFLoaderPlugin where can i change the code if the 
gtlf is null still show the tree view models:
_objectNodes: 
_rootMetaObject:
of the metadata json
}

**Comment by vadimt2** [comment]
I'm trying to use the method of addModel
but i can't get the viewer.metaScene.metaModels OBserver showing empty array .
I'm using vue js and only after it's mounted i can see viewer.metaScene.metaModels
what can i do to see the data with the promise ?

**Comment by imadBelaroussi** [comment]
you can tell me on which OS you are running your application ??

**Comment by vadimt2** [comment]
i'm using vue js

**Comment by imadBelaroussi** [comment]
Linux  or Windows ??

**Comment by vadimt2** [comment]
Windows
