### ISSUE TITLE
Fix size of SectionPlane editing control

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#480]
**Describe the bug**
Section plane controls are huge:
![Capture d’écran de 2020-11-24 16-35-26](https://user-images.githubusercontent.com/1349751/100115685-19914680-2e73-11eb-8b1b-1d4f20a63f4d.png)

And sometimes even bigger:
![Capture d’écran de 2020-11-24 16-40-24](https://user-images.githubusercontent.com/1349751/100116254-cff52b80-2e73-11eb-8961-5c0f8115d52f.png)

I updated to 1.5.13, the problem persists (with and without xkt v6).

**To Reproduce**
Open our demo model (MarcAntoinePetit.ifc)
Create a section on an axis

```javascript
sectionPlanesPlugin.createSectionPlane({
  dir: camera.worldRight.map(val => -val),
  pos: math.getAABB3Center(scene.getAABB())
});
```

**Expected behavior**
The best behavior may be a constant size of section controls, regardless of zoom.
Just not huge controls are very OK.

**Desktop (please complete the following information):**
Tried on Linux, latest Firefox and Chromium.

**Comment by Amoki** [comment]
@xeolabs Do you have any clue? It breaks our section tool :/

**Comment by xeolabs** [comment]
@Amoki currently the tool sizes itself to the entire model boundary. I'll fix in the next version by sizing it to the view frustum, or something like that.

**Comment by Amoki** [comment]
Just did a bisect: it works in 1.4.7, it's way too big since 1.4.8 (the merge of RTC-coords).

A fix to just bring back the old size is enough for us if doing a dynamic size is hard.

**Comment by Amoki** [comment]
Hi @xeolabs, It's been 6 weeks since this bug is here, do you have any info about this?

**Comment by xeolabs** [comment]
@Amoki it's on the list for this week's release
