### ISSUE TITLE
Fix CameraControl zoom for ortho mode when followPointer false

### ISSUE THREAD

**Issue by KrishDunn** [xeokit/xeokit-sdk#484]
Hello Team,
Ortho view zoom functionality is not working with Mouse wheel event and it is also not working with camera.zoom(5);

**Comment by KrishDunn** [comment]
Mouse wheel Zoom functionality also not working in the xeokit example library.
https://xeokit.github.io/xeokit-sdk/examples/#BCF_SaveViewpoint_ortho

**Comment by xeolabs** [comment]
Do this as workaround for now:

````javascript
viewer.cameraControl.followPointer = true;
````

**Comment by KrishDunn** [comment]
Ok. Thank you. 
viewer.cameraControl.followPointer = true;
is working mouse wheel and pad zoom in Ortho view

But followPointer with navMode="orbit is difficult to manage big object
and also camera.zoom(5); function is not working.

**Comment by kingwangwang** [comment]
viewer.scene.camera.zoom(5); function is also not working.

**Comment by ohadgilboa888** [comment]
viewer.scene.camera.zoom(5); function is also not working for me also on `ortho`

**Comment by ohadgilboa888** [comment]
if someone needs it, what solved it for me was:
`viewer.scene.camera.ortho.scale = viewer.scene.camera.ortho.scale + dollyDeltaForDist;`
`viewer.scene.camera.zoom(dollyDeltaForDist);`
