### ISSUE TITLE
Ability to load multiple copies of same IFC model without object ID clashes

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#485]
This feature extends xeokit with the capability to load two or more instances of the same IFC model into a ````Viewer````, without having clashes between the ````Entity#id````s of the equivalent objects in the model instances.

See #495 for details.

**Comment by xeolabs** [comment]
\ping @Amoki

**Comment by Amoki** [comment]
That seems really nice :D

The BCF has 2 values for saving GUIDs(https://github.com/buildingSMART/BCF-XML/tree/release_2_1/Documentation#component): 
`IfcGuid`, which must be the GUID without the model ID
`AuthoringToolId`, an optional custom identifier for the tool which created the BCF topic.

It could make sense to use `AuthoringToolId` to save `myModel2#0BTBFw6f90Nfh9rP1dlXrb`. The `setViewpoint` method could check for `AuthoringToolId` first, check if it looks like `loadedModelID#GUID` and backup to `IfcGuid` if not (at least one of them MUST be defined). 
`getViewpoint` would define both values. One for xeokit, the other for exports and BCF sharing with other tools.
