### ISSUE TITLE
bug in create EntityIDs in Linux and not in Windows

### ISSUE THREAD

**Issue by imadBelaroussi** [xeokit/xeokit-sdk#486]
https://github.com/xeokit/xeokit-sdk/blob/17eee17889ccfdc0e2db5beccaa3ca94dd6b737c/src/plugins/XKTLoaderPlugin/parsers/ParserV3.js#L38

error on the EntityIDs retrieval, it retrieves "product -..., product -..." which does not exist on my IFC, suddenly the metaObject list will be empty. (this bug is on Linux that's all)

**Comment by xeolabs** [comment]
Need more clarification on this bug - could you provide the IFC file?

**Comment by imadBelaroussi** [comment]
I have an angular / spring application which does the conversion of the IFC and which uses the xkt to display it to the viewer, locally (windows 10) works normally, but the server (linux ubento) cannot fill in the metaObject. when i check where the problem is, then it is the EntityIDs list does not match the mockup items


EntityIDs in windows:
 ![CaptureB](https://user-images.githubusercontent.com/52861298/100984417-01908580-354b-11eb-9b10-02d94515cef1.PNG)


EntityIDs in linux:
 ![CaptureA](https://user-images.githubusercontent.com/52861298/100984350-ecb3f200-354a-11eb-88c5-32abc5e45840.PNG)


viewer in windows: 
![CaptureC](https://user-images.githubusercontent.com/52861298/100984834-81b6eb00-354b-11eb-9fcf-73c4b2444857.PNG)

viewer in linux: 
![CaptureD](https://user-images.githubusercontent.com/52861298/100985097-d9555680-354b-11eb-87e3-e4648cc82c63.PNG)

**Comment by xeolabs** [comment]
I'm not able to reproduce this bug given the information provided.

**Comment by djamel2288** [comment]
i have the same problem, any solution please ?
