### ISSUE TITLE
Spinner percentage 

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#488]
How can i show Spinner percentage loading during the model is loading ?

**Comment by xeolabs** [comment]
Oh we would love to have that, but so far I've found it very difficult to implement, so it's not a feature, at least not yet.

The main problem I had was DOM interactivity while loading, where an HTTP request (ie. XMLHttpRequest, and perhaps xeokit's parsing logic), seems to completely block DOM repaints until finished.

Hopefully we can come back to this. I'll leave this ticket open.
