### ISSUE TITLE
deactivate or clear measurment doesn't work

### ISSUE THREAD

**Issue by djamel2288** [xeokit/xeokit-sdk#491]
creating measurment with mouse work fine, but when i use the deactivate() function  doesn't work
distanceMeasurements.control.deactivate();

**Comment by xeolabs** [comment]
This is actually correct behaviour - once we have completed creating a ````DistanceMeasurement```` using the ````DistanceMeasurementsControl````, then calling ````DistanceMeasurementsControl#deactivate()```` will not destroy that ````DistanceMeasurement````, because it is complete. ````DistanceMeasurementsControl#deactivate()```` will only destroy a ````DistanceMeasurement```` that is still be created.

**Comment by djamel2288** [comment]
thank you sir, there is a way to clear created measurement?
thank you again

**Comment by xeolabs** [comment]
Either:

````javascript
myDistanceMeasurementsPlugin.clear();
````

or 

````javascript
myDistanceMeasurementsplugin.measurements["myMeasurement"].destroy();
````

**Comment by djamel2288** [comment]
thanks sir it's work fin :D

**Comment by djamel2288** [comment]
this a simple code I made to help me enabling/disabling measurements
`/* variable for toggling between enable/disable the measurement function  */
let enableMeasurement = true;

/* button for enabling/disabling measurement function */
document.getElementById("measures").onclick = function () {
  measurement(enableMeasurement);
  enableMeasurement = !enableMeasurement;
}

let distanceMeasurements = new DistanceMeasurementsPlugin(viewer);

function measurement(bool) {

  if (bool) {
    
    /* activate DistanceMeasurementsPlugin */
    distanceMeasurements.control.activate();
  } else {
    
    /* clear measurements */
    distanceMeasurements.clear();
    
    /* destroy  DistanceMeasurementsPlugin*/
    distanceMeasurements.control.destroy();
    
    distanceMeasurements = new DistanceMeasurementsPlugin(viewer);
  }
}

`

**Comment by phxd88** [comment]
> this a simple code I made to help me enabling/disabling measurements
> 
> /* variable for toggling between enable/disable the measurement function */
> let enableMeasurement = true;
> 
> /* button for enabling/disabling measurement function */
> document.getElementById("measures").onclick = function () {
> measurement(enableMeasurement);
> enableMeasurement = !enableMeasurement;
> }
> 
> let distanceMeasurements = new DistanceMeasurementsPlugin(viewer);
> 
> function measurement(bool) {
> 
> if (bool) {
> 
> ```
> /* activate DistanceMeasurementsPlugin */
> distanceMeasurements.control.activate();
> ```
> 
> } else {
> 
> ```
> /* clear measurements */
> distanceMeasurements.clear();
> 
> /* destroy  DistanceMeasurementsPlugin*/
> distanceMeasurements.control.destroy();
> 
> distanceMeasurements = new DistanceMeasurementsPlugin(viewer);
> ```
> 
> }
> }

Sorry Sir, 
I was unable to use your code, could you help me?

**Comment by djamel2288** [comment]
hi,
of course, if I can why not

**Comment by phxd88** [comment]
Thanks, 
I am not very familiar with codes. I insered your code after the default xeokit measurements tool code (https://github.com/xeokit/xeokit-sdk/blob/master/examples/measurements_distance_createWithMouse.html) but nothing changed. How can I implement it correctly?

**Comment by djamel2288** [comment]
you would like to deactivate or clear measurment right?

**Comment by djamel2288** [comment]
please, xeokit code works for you?

**Comment by phxd88** [comment]
Yes, I would like to easy deactivate measurement just taken, 
xeokit default code works fine with my model.

**Comment by djamel2288** [comment]
so, what i did is simply create a button to toggle between two stat (toggle a bool variable), 
then puting this line of code:
`let distanceMeasurements = new DistanceMeasurementsPlugin(viewer);`

after that the function that checks the stat of the variable, for example, if bool == false, that means you are already making some measurement, and so on...

so if bool == true just activate it
`/* activate DistanceMeasurementsPlugin */
distanceMeasurements.control.activate();`

else
`/* clear measurements */
distanceMeasurements.clear();

/* destroy  DistanceMeasurementsPlugin*/
distanceMeasurements.control.destroy();

/* here you are just making a new instance */ 
distanceMeasurements = new DistanceMeasurementsPlugin(viewer);`

like this it worked fine for me

**Comment by phxd88** [comment]
thanks for the code, 
however it does not work, I probably pasted this code incorrectly.

**Comment by phxd88** [comment]
Update: it works! I have written some words wrong. 
Thank you! :)

**Comment by djamel2288** [comment]
nice, happy for you , good luck bro

**Comment by phxd88** [comment]
hi @djamel2288 I'm trying to apply your code (you shared above) also for quick enable/disable annotationsPlugin by using a proper button. In addition I would like to customize picked annotations with JavaScript. dat.GUI menu as reported here: http://xeogl.org/examples/#annotations_tronTank

Could you (or whoever is reading) help me?
thank you
