### ISSUE TITLE
Add support for IFC properties and property sets to metadata JSON

### ISSUE THREAD

**Issue by cemunds** [xeokit/xeokit-sdk#498]
**Is this feature critical for your commercial enterprise?**
I am not using xeokit commercially, but for a research project at my institution.

**Is your feature request related to a problem? Please describe.**
I am creating a custom viewer for IFC models and want to display information about an object's properties. However, the metadata JSON file created by the xeokit-metadata tool doesn't extract properties and property sets from the IFC file and the support for properties in the metadata JSON schema expected by xeokit is somewhat limited. I am aware that MetaObjects have a properties field for arbitrary metadata. However, since property sets in an IFC file can be shared among multiple objects, adding a copy of the JSON object representing a shared property set to every MetaObject would significantly bloat the JSON metadata file.

**Describe the solution you'd like**
I would suggest an extension of the metadata JSON schema to include property and property set definitions, so that MetaObjects can link to them. I suppose it could look something like this:

````json
{
  "id": "schependomlaan Nijmegen",
  "projectId": "3lUedKGIrD1P6ias9DdoKR",
  "author": "",
  "createdAt": "",
  "schema": "IFC2X3",
  "creatingApplication": "",
  "metaObjects": [
    {
      "id": "3lUedKGIrD1P6ias9DdoKR",
      "name": "schependomlaan Nijmegen",
      "type": "IfcProject",
      "parent": null
    },
    {
      "id": "3YJ06nMiDAexeyGFzzxgR9",
      "name": "Undefined",
      "type": "IfcSite",
      "parent": "3lUedKGIrD1P6ias9DdoKR"
    },
    {
      "id": "1N_cUz3E56iumYBFH281Eh",
      "name": "Undefined",
      "type": "IfcBuilding",
      "parent": "3YJ06nMiDAexeyGFzzxgR9"
    },
    {
      "id": "1LJ6oI00EDWJ4qCp4mE3Op",
      "name": "DOOR",
      "type": "IfcPlate",
      "parent": "3lUedKGIrD1P6ias9DdoKR",
      "propertySets": ["propertySetId1"]
    }
  ],
  "propertySets": [
    {
      "id": "propertySetId1",
      "name": "",
      "description": "",
      "properties": ["propertyId1", "propertyId2", "propertyId3"]
    }
  ],
  "properties": {
    "singleValues": [
      {
        "id": "propertyId1",
        "name": "",
        "description": "",
        "nominalValue": "",
        "unit": ""
      }
    ],
    "enumeratedValues": [
      {
        "id": "propertyId2",
        "name": "",
        "description": "",
        "enumerationValues": [],
        "enumerationReference": ""
      }
    ],
    "boundedValues": [
      {
        "id": "propertyId3",
        "name": "",
        "description": "",
        "upperBoundValue": "",
        "lowerBoundValue": "",
        "unit": ""
      }
    ],
    "tableValues": [
      {
        "id": "",
        "name": "",
        "description": "",
        "definingValues": "",
        "definedValues": "",
        "expression": "",
        "definingUnit": "",
        "definedUnit": ""
      }
    ],
    "listValues": [
      {
        "id": "",
        "name": "",
        "description": "",
        "listValues": [],
        "unit": ""
      }
    ]
  }
}
````
I deliberately left out the _IfcPropertyReferenceValue_ for now, because this might become somewhat of a rabbit hole, pulling too many nested dependencies into the file. And you could even think about removing the _enumerationReference_ field from enumeratedValues, as this would also require to pull in IfcPropertyEnumerations.

**Describe alternatives you've considered**
Like mentioned above, a straightforward alternative would be to have every MetaObject contain a copy of its own properties in the _properties_ field. However, this would bloat the JSON file with redundant information and also make modifying a property a lot harder, as it would have to be modified in every object that contains it.

**Additional context**
N/A

**Comment by xeolabs** [comment]
Thanks @cemunds, I like this - simple and efficient.

In xeokit it's intended that users implement their own data service for fetching arbitrary property sets for element IDs, but I think it makes sense to also be able to generate metadata JSONs containing properties for the particular aspect we're visualizing.

I'm going to transfer this issue to https://github.com/bimspot/xeokit-metadata, as a feature request.

**Comment by xeolabs** [comment]
Can't transfer this issue - @cemunds could you also create a ticket for this issue at https://github.com/bimspot/xeokit-metadata?
Thanks

**Comment by cemunds** [comment]
Thank you for your quick reply. I created an issue in the xeokit-metadata repo.

I am somewhat new to IFC and by no means an expert, so if you have any idea for a better structure, feel free to correct my proposal. Maybe there's a way to simplify the _properties_ field, so we don't need to distinguish between singleValues, enumeratedValues, etc. like the way I did above, but I couldn't come up with a better solution which at the same time ensures that the JSON schema is well-defined.

Once the JSON schema is decided, I can also gladly support you in adding the feature to xeokit.

**Comment by cemunds** [comment]
I closed this issue now since the related issue in the xeokit-metadata repo was also closed. My use case is probably rather narrow and after further investigation I agree with the maintainers of xeokit-metadata that this would not be feasible for real world projects.
