### ISSUE TITLE
Fix Entity#offset for PerformanceModel instancing

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#505]
**Describe the bug**
![Capture d’écran de 2020-12-21 18-26-56](https://user-images.githubusercontent.com/1349751/102804747-76244a80-43ba-11eb-8d10-efd5825f6410.png)

**To Reproduce**
https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_XKT_metadata_moveStoreys

**Expected behavior**
Move all objects of the example

**Comment by xeolabs** [comment]
Fixed in 38b276d, to release in 1.5.3 this week
