### ISSUE TITLE
TreeViewPlugin 

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#515]
I need to add some logic to TreeViewPlugin.
When do i know the TreeViewPlugin is loaded?
model.on("loaded", () is not a good option for me because the model can be loaded before then the TreeViewPlugin with all the
tree nodes

**Comment by samouray69** [comment]
I have a problem with TreeViewPlugin , when i deloyed my application on Ubuntu system , the metadata are not visible , could you help me please ?

**Comment by djamel2288** [comment]
Hi, me too I have the same problem

**Comment by xeolabs** [comment]
Are there any error messages in the JS console?

**Comment by djamel2288** [comment]
thank you for responding me, 
if I use this...
`let model = xktLoader.load({ id: idModel, xkt: xktFile, metaModelData: metaModel, edges: true, saoEnabled: true, excludeUnclassifiedObjects: false, });`
locally it works fine, but on the server the model display  but the treeView stay empty without error.

if  I use this...
`const blob: any = new Blob([data], { type: 'application/*; charset=utf-8' }); const url = window.URL.createObjectURL(blob); xktFileBlobUrl = url;`
locally work fine too, but on ubunto docker image (not on server) I have ( Content-Security-Policy) error.

I don't know what's wrong, and what is the best way to get xkt / metamodel from my server and desplay it

Thank you again.

**Comment by djamel2288** [comment]
hi, it seems that the problem is the metaObject

**Comment by vadimt2** [comment]
I did the same use u:
const blob: any = new Blob([data], { type: 'application/*; charset=utf-8' }); const url = window.URL.createObjectURL(blob); xktFileBlobUrl = url;
and i've got this issue:
Uncaught incorrect header check

**Comment by djamel2288** [comment]
hi,I solved my problem with the blob solution by adding those in my index header, also in my backend's header configuration.

`default-src *  data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval' 'unsafe-dynamic'; script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src * data: blob: 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src * data: blob: ; style-src * data: blob: 'unsafe-inline';font-src * data: blob: 'unsafe-inline'`

nb: if you add this, you will allow types of access.

now my problem is, my metaObject on server gives wrong IDs for entities a don't know why, since it's the same code on localhost and every thing work fin.

**Comment by vadimt2** [comment]
how do you add header to blob in js ?
`
axios.get("./models/xkt/duplex/duplex.xkt").then(response => {
   const blob = new Blob([response.data], { type: 'application/*; charset=utf-8' }); 
const url = window.URL.createObjectURL(blob);
let  xktFileBlobUrl = url;
`

- metaObject  - i have generated the metaObject from ifc file with xeokit-metadata tool
and it worked.

**Comment by djamel2288** [comment]
I use angular with spring-boot, so for the blob I use this function to create xktFileBlobUrl and metaModelBlobUrl
`const blob: any = new Blob([data], { type: 'application/*; charset=utf-8' });
 const url = window.URL.createObjectURL(blob); xktFileBlobUrl = url;`

and then I use the URL like this...
`let model = xktLoader.load({ 
   id: idModel,
   src: xktFileBlobUrl, 
   metaModelSrc: metaModelBlobUrl, 
   edges: true, 
   saoEnabled: true, 
   excludeUnclassifiedObjects: false,
 });`

**Comment by djamel2288** [comment]
and for the metaObject when I run my project locally ( windows ) it works well, but if I try to run it on docker Or server ( I use ubuntu for both ),  I can't show the TreeView and I can't understand where is the problem.

and I found that for example when I click over un element console tel me that metaobject is undefined, and when I compare element ID's I found that is wrong for example it should give $0sdsd5ds, but it gives me some thing like this ( product -....-body)

**Comment by vadimt2** [comment]
I did the same thing as you:
`
axios.get("./models/xkt/duplex/duplex.xkt").then((response) => {
      const blob = new Blob([response.data], {
        type: "application/*; charset=utf-8",
      });
      const url = window.URL.createObjectURL(blob);
      let xktFileBlobUrl = url;
        let mechanical = xktLoader.load({
          id: index + "",
          src: xktFileBlobUrl,
          metaModelSrc: element.metaModelSrc,
          edges: true,
          saoEnabled: true,
          excludeUnclassifiedObjects: false,
        });
`
and i have this error:
Uncaught incorrect header check

**Comment by djamel2288** [comment]
i don't know , but metaModelSrc must be JSON

**Comment by vadimt2** [comment]
This is working great:
`
          src: "./models/xkt/duplex/duplex.xkt",
          metaModelSrc: "./metaModels/duplex/metaModel.json",
`
and here i'm getting the error:
`
axios.get("./models/xkt/duplex/duplex.xkt").then((response) => {
      const blob = new Blob([response.data], {
        type: "application/*; charset=utf-8",
      });
      const url = window.URL.createObjectURL(blob);
        let mechanical = xktLoader.load({
          id: index + "",
          src: url,
          metaModelSrc: "./metaModels/duplex/metaModel.json",
          edges: true,
          saoEnabled: true,
          exclude
        });

`

**Comment by djamel2288** [comment]
for metaModelSrc try to add JSON.stringify to your response data.

**Comment by djamel2288** [comment]
@xeolabs, @Amoki can you help me please?

**Comment by Amoki** [comment]
`axios.get("./models/xkt/duplex/duplex.xkt")`

You can't load local files from JS for security reasons (you don't want any web page to be able to access your local files).

XMLHttpRequest replaces automatically `./models/xkt/duplex/duplex.xkt` by `${current_url}/models/xkt/duplex/duplex.xkt`, so it kinda works if `${current_url}/models/xkt/duplex/duplex.xkt` is a valid path.

Axios does not do that so you must give it a valid URL: `axios.get("https://domain.tld/models/xkt/duplex/duplex.xkt")`


Disabling browser security is a big mistake.

**Comment by vadimt2** [comment]
I got here: https://github.com/xeokit/xeokit-sdk/issues/557
I have already solved it, tnx)
