### ISSUE TITLE
On Using PerformanceModel class, stats doesn't update

### ISSUE THREAD

**Issue by Thornton-developer** [xeokit/xeokit-sdk#519]
I am working on optimizing my Obj model, I have used stats.js for displaying performance. while using performanceModel class, I am able to load the model, but the stats are not getting updated.

**To Reproduce**
I wrote below code for using performancemodel class:
const performanceModel = new PerformanceModel(viewer.scene, {
        id: 'MyModel',
        isModel: true,
        position: [0, 0, 0],
        scale: [1, 1, 1],
        rotation: [0, 0, 0],
        edges: true
    });
    performanceModel.createGeometry({
        id: "myGeometry",
        primitive: "triangles",
        positions: geometry.positions,
        normals: geometry.normals,
        indices: geometry.indices,
        isObject: true
    });
    performanceModel.createMesh({
        id: "mymesh",
        geometryId: "myGeometry",
        material: new PhongMaterial(viewer.scene, {
            ambient: [0.9, 0.3, 0.9],
            shininess: 30,
        })
    });

     id: "performmesh",
        meshIds: ["mymesh"],
        isObject: true // <---- Registers Entity by ID on viewer.scene.objects
    });
    performanceModel.finalize();

But this doesn't update the stats.

**Expected behavior**
Stats should be updated on using Performance model

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [chrome,FireFox]

**Comment by Thornton-developer** [comment]
Do we have an update on this please ?

**Comment by xeolabs** [comment]
Not yet. When complete, a note will be added to this ticket with information. Please note that the last few days have been holidays for us. If you need a commercial agreement for priority support, [please get in touch](http://xeokit.io/index.html?foo=3#contact).
