### ISSUE TITLE
Section planes are not parallel to the clicked surface 

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#523]
```javascript
var pickResult = viewer.scene.pick({
  canvasPos: coords,
  pickSurface: true  // <<------ This causes picking to find the intersection point on the entity
});
if (pickResult) {
  const sectionPlane = sectionPlanes.createSectionPlane({
    pos: pickResult.worldPos,
    dir: math.mulVec3Scalar(pickResult.worldNormal, -1)
  });
}
```
If the picked surface is not axis-aligned, the section place is not parallel to the surface.

![Capture d’écran de 2021-01-07 17-44-52](https://user-images.githubusercontent.com/1349751/103919205-1515aa00-5110-11eb-820d-a917fed858a1.png)

On ortho from above, it's easier to see:
![Capture d’écran de 2021-01-08 12-52-52](https://user-images.githubusercontent.com/1349751/104012644-78571900-51b0-11eb-8077-3ebba5bf2938.png)

**To Reproduce**
It also appears on xeokit's example https://xeokit.github.io/xeokit-sdk/examples/#gizmos_SectionPlanesPlugin_createWithMouse
![Capture d’écran de 2021-01-07 17-45-54](https://user-images.githubusercontent.com/1349751/103919392-42faee80-5110-11eb-934a-20d9b0b8329b.png)

It was hard to find a non-axis-aligned surface on this model. The section is on the railing.

The problem is the same withe xkt v6 and xkt v3

**Expected behavior**
The section to be strictly parallel to the picked surface

**Comment by Kurtil** [comment]
@xeolabs, the 32 bits normal encoding merged PR fixed this issue.
