### ISSUE TITLE
Zooming on section planes arrows on XKT v6 make the model disappear 

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#528]
**Describe the bug**
![output](https://user-images.githubusercontent.com/1349751/104213814-ffb5be00-5436-11eb-9fa2-fd92a4a17003.gif)

**To Reproduce**
1. open an xkt v6 model
2. create a section plane
3. Zoom on an axis arrow 
4. See the model disappear

**Expected behavior**
The model stays

**Comment by Amoki** [comment]
I just tried these commits and the problem is still there :/

**Comment by xeolabs** [comment]
This fix didn't make it into the 1.6.0 release - will be in the next one. Check the change log to see what's in each release: https://github.com/xeokit/xeokit-sdk/blob/master/CHANGE_LOG.md

**Comment by Amoki** [comment]
I tried directly by pulling these commits, not by using v1.6.0.
It was just FWI
