### ISSUE TITLE
How to automatically fit camera far clipping plane to model size

### ISSUE THREAD

**Issue by raffdp** [xeokit/xeokit-sdk#540]
The view planes / frustum is not being adjusted to fit the bounding box of the whole scene for a loaded GLTF model.

a) When I load the model (which contains multiple nodes and meshes), the scene is zoomed in close
b) When I then zoom out, meshes are being clipped by the frustum planes and I can't see the whole model

Here is the code I am using to load the model.

const loader = new GLTFLoaderPlugin(viewer);
const model = loader.load({
	id: "myModel",
	src: "TC017-006A.ASM.gltf",
	edges: true,
	edgeThreshold : 45,
	performance: false,
});
		
model.on("loaded", () => {
	//cameraFlight.flyTo(model);
        camera.flyTo(scene.getAABB({}));
})

What do I need to do to properly fit the scene to the model?

What I see when I load:
![image](https://user-images.githubusercontent.com/1573230/105157868-4ecdb400-5b05-11eb-8a77-413f65940abb.png)

What I should see:
![image](https://user-images.githubusercontent.com/1573230/105158205-a10ed500-5b05-11eb-86f0-bc62cdc252f3.png)

**Comment by xeolabs** [comment]
Looks like you're getting clipped by the far clipping plane - try setting the far clipping plane further back, eg:

````javascript
myViewer.scene.camera.perspective.far = 10000;
````

**Comment by raffdp** [comment]
That worked, but I had to increase it up to 100000. I have models dimensionally larger that this too. Is there a way to determine what the far plane distance should be based on the model loaded?

![image](https://user-images.githubusercontent.com/1573230/105161982-ed5c1400-5b09-11eb-8d6c-ae996c06cd44.png)

Also, it looks like the mouse wheel zoom needs to adjust at the same time to compensate for the far plane distance as wheel zoom increments seem to be very small.

**Comment by xeolabs** [comment]
You could fit the far plane using the model's World-space bounding box, something roughly like this (untested):

````javascript
model.on("loaded", ()=> {
    const aabb = model.aabb;
    const diag = math.getAABB3Diag(aabb);
    myViewer.scene.camera.perspective.far = diag*2;  
});
````

If you get rendering accuracy issues with the distant far plane, you could try enabling the logarithmic depth buffer - see example: https://xeokit.github.io/xeokit-sdk/examples/#logDepthBuf_XKT_Lyon

````javascript
   const viewer = new Viewer({
        canvasId: "myCanvas",
        logarithmicDepthBufferEnabled: true 
    });
````

Note there may be a performance impact when that's enabled.

For wheel zoom movements, enable ````CameraControl#followPointer````:

````javascript
myViewer.cameraControl.followPointer = true;
````

Now when you use mousewheel while mouse is over an object, you're rate of movement will adjust for the distance from that object.

Also possibly adjust the mouse wheel dolly rate, to move faster when moused over nothing:

````javascript
myViewer.cameraControl.mouseWheelDollyRate = 150.0;
````
