### ISSUE TITLE
Fix lighting for PerformanceModel with instanced geometry

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#545]
## Problem

As shown in the screenshot below, lighting calculations are incorrect for ````PerformanceModel```` with instanced geometries (the table model at right-back).

![Screenshot from 2021-01-26 13-22-48](https://user-images.githubusercontent.com/83100/105844613-cd30c700-5fd9-11eb-80d6-41026b112e44.png)

This is caused by the wrong order of terms in this shader expression:

````glsl
vec3 viewNormal = normalize(vec4(worldNormal * viewNormalMatrix).xyz);
````

## Solution

Simply reverse the order of the terms:

````glsl
vec3 viewNormal = normalize(vec4(viewNormalMatrix * worldNormal).xyz);
````

**Comment by Amoki** [comment]
Before this commit, XKT colors were wrong, but glTF colors were good. Now both are wrong. 
In https://github.com/xeokit/xeokit-sdk/issues/511, BIMData logo should be blue and yellow, it is now black and orange for both XKT and glTF

**Comment by Amoki** [comment]
This message may be totally out of scope.

The behavior didn't change.
It was not glTF/XKT difference, it was performance mode true/false difference and it just wasn't fixed by this commit.

**Comment by xeolabs** [comment]
Hmm. maybe the order of those terms in the shader was actually the correct order. Could I get the BIMData logo to test with?

**Comment by Amoki** [comment]
The glTF is available at https://github.com/xeokit/xeokit-sdk/issues/511.
The expected result is the quality mode
