### ISSUE TITLE
Picking doesn't work on big models on chrome

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#546]
**Describe the bug**
On Chrome (it works on Firefox), picking doesn't work on big models.
If a load just Lyon2, it works. If I load the full city, I can't pick anymore and zoom is really slow (picked nothing, so zoom speed is set to the default I guess)

**To Reproduce**
1. Load all models of Lyon
2. Zoom or pick a building, it doesn't work

**Expected behavior**
Be able to pick or zoom

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 88

It works on firefox.

**Additional context**
config:

```Javascript
const viewer = new Viewer({
  canvasId: this.engine3dCanvasId,
  enableOffsets: false,
  logDepthBufferEnabled: true,
});

viewer.cameraControl.doublePickFlyTo = false;
viewer.cameraControl.panRightClick = false;

viewer.cameraControl.followPointer = true;
viewer.cameraControl.smartPivot = true;

viewer.camera.perspective.near = 0.1;
viewer.camera.perspective.far = 1e27; // I tried with a 1 000 000, same result
viewer.camera.ortho.near = 0.1;
viewer.camera.ortho.far = 1e27;

new ViewCullPlugin(viewer, {
  maxTreeDepth: 20,
});
```

**Comment by xeolabs** [comment]
Reason for this is that the massive far clipping plane distance of ````1e27```` screws up picking.

Everything works fine with a distance of ````100000```` or ````1000000````, which is still 100km or 1000km.

So not really a bug, just exceeding accuracy limitations.

**Comment by xeolabs** [comment]
I've updated the examples in an upcoming PR.

**Comment by Amoki** [comment]
I have the same problem with `far = 1000000` and `far = 100000`;

Picking works with `1e27` on smaller models.

**Comment by xeolabs** [comment]
How about making the near plane ````1.0````? As a general rule, that improves the projection accuracy that picking relies on - see if that helps.

**Comment by Amoki** [comment]
It doesn't work with `near = 1.0`.
As it works on Firefox, I'm not sure it's a configuration problem.

**Comment by xeolabs** [comment]
Does this work? 

https://xeokit.github.io/xeokit-sdk/examples/#CameraControl_orbit_Lyon

Works for me on Ubuntu/Chrome, Android and IOS 14.2

**Comment by Amoki** [comment]
Hmmm, It works on your example...
I'll investigate.

(Enabling SmartPivot on the example doesn't work)

**Comment by xeolabs** [comment]
SmartPivot seems to work for me in that example:

![Peek 2021-01-28 12-14](https://user-images.githubusercontent.com/83100/106131074-7e626900-6162-11eb-8ccf-8fd41a91cc73.gif)

**Comment by Amoki** [comment]
My bad.
We use the pivot sphere since smart pivot is out and in my mind, smart pivot == pivot sphere, which is wrong.

But this is nice :D
![Capture d’écran de 2021-01-28 12-17-09](https://user-images.githubusercontent.com/1349751/106132488-4c520680-6164-11eb-8763-2c17feb980bd.png)

**Comment by Amoki** [comment]
Ok, I got it.

I missed https://github.com/xeokit/xeokit-sdk/commit/a0205c3061cc87dae5a94918ed163a8b01739496 and was still using `Viewer.logarithmicDepthBufferSupported`.

If I set `viewer.camera.perspective.far = 10000000;` and `logarithmicDepthBuffer` is not supported (iOS Safari), what happens?

**Comment by xeolabs** [comment]
Results will vary, depending on the geometry. 

If you use a linear depth buffer, then when viewing tightly-packed geometry from a distance may result in Z-fighting. Log depth buffer may give the precision required for the Z-test to properly layer the geometries.

For the Lyon model, the geometries are distinct enough that log depth buff doesn't make much difference.

A couple of examples to try:

https://xeokit.github.io/xeokit-sdk/examples/#logDepthBuf_PerformanceModel_batching_RTC
https://xeokit.github.io/xeokit-sdk/examples/#logDepthBuf_PerformanceModel_batching_RTC_logDepthBufDisabled
