### ISSUE TITLE
CameraControl pinch-dolly refinements

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#553]
Pinch-dolly is sketchy. Some refinements needed:

1. Don't pan while pinching
2. When doing proximity-scaled dolly speed, ray-pick **between** the two touch coordinates to find the nearest object, not at the first touch coordinate
3. Increase overall minimum dolly speed for touch input

Another possibility:

4. Make dolly speed proportional to pinch rate.

Could remove (2) and just have (4), or have a combo of (2) and (4).

**Comment by NeluQi** [comment]
Please add it faster

**Comment by xeolabs** [comment]
This is actually a zombie ticket, no longer active. We're currently happy with the camera behaviour. If you have any preferences for how you would like it modified, you're welcome to define them in a ticket, or make a PR with your proposed changes.

**Comment by NeluQi** [comment]
> This is actually a zombie ticket, no longer active. We're currently happy with the camera behaviour. If you have any preferences for how you would like it modified, you're welcome to define them in a ticket, or make a PR with your proposed changes.

how to change pan speed for first Person (which is on the right mouse button)?

and how to disable changing the pan speed for the first Person when pan for the model object and for the void?


Now when I paranomy from the PC (with the mouse - right click):
1) When I take a canvas (not an object), the movement occurs at normal speed
2) When I take an object, the movement is very slow (camera speed)

How to fix point 2?
