### ISSUE TITLE
glTF loadder generate geometries with some wrong points

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#556]
**Describe the bug**
Some geometries are wrong with glTF loader, good with XKT loader:

![Capture d’écran de 2021-01-29 13-56-34](https://user-images.githubusercontent.com/1349751/106277768-e59f1c80-6239-11eb-941b-0ce4a6ff9b29.png)
![Capture d’écran de 2021-01-29 13-57-02](https://user-images.githubusercontent.com/1349751/106277774-e768e000-6239-11eb-92eb-f635de0e45ed.png)

The point at the bottom is wrong.

XKT is good:
![Capture d’écran de 2021-01-29 13-58-00](https://user-images.githubusercontent.com/1349751/106277862-09faf900-623a-11eb-979b-aee991b1ae64.png)

Same with another model:
![Capture d’écran de 2021-01-29 14-02-35](https://user-images.githubusercontent.com/1349751/106278243-b0df9500-623a-11eb-9194-accfdba23f0d.png)

![Capture d’écran de 2021-01-29 14-02-43](https://user-images.githubusercontent.com/1349751/106278261-b937d000-623a-11eb-8224-7321381df027.png)

These models were generated from Blender, not IfcConvert.

**Additional context**
This is a non-critical bug for us, we mostly only load XKT files but I think it worth an issue for later.

**Comment by Amoki** [comment]
The issue has disappeared, I'm closing the issue

**Comment by xeolabs** [comment]
Cool - this one was likely fixed by #609.
