### ISSUE TITLE
Investigate supporting backfaces on certain objects

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#562]
So far, the only use case for backfaces is on plants, which tend to rely on double-sides faces.

The xeokit renderer culls backfaces by default, in order to reduce GPU load.

This would impact both the XKT format and the xeokit-sdk renderer.

Possibly not even needed, but an evaluation of effort is worth it.

**Comment by Francois-Thierry** [comment]
Hello Lindsay,
I was just going to make an issue about this very specific problem !
Apart from the plants that exhibit artifacts from backface culling :
![Screenshot from 2021-02-03 17-17-01](https://user-images.githubusercontent.com/7921372/106775735-aad72300-6643-11eb-944c-bc3adb57cff3.png)
We also had some feedback about the "transparency" of terrains (mainly IfcSites) viewed from below as everything is backface-culled for performances. Some have the normals pointing to the wrong direction making them only visible from below :
![Screenshot from 2021-02-03 17-14-21](https://user-images.githubusercontent.com/7921372/106775361-559b1180-6643-11eb-9931-824dd6734dff.png)
![Screenshot from 2021-02-03 17-15-05](https://user-images.githubusercontent.com/7921372/106775442-6b103b80-6643-11eb-9a40-ea8f95f5f1a0.png)
There is also the problem of geometries generated from CityGML in LOD3 :
![Screenshot from 2021-02-03 17-18-30](https://user-images.githubusercontent.com/7921372/106775948-e540c000-6643-11eb-9fe0-ced8ce726a84.png)

**Comment by xeolabs** [comment]
Hi Francois, thanks for that, I can see now that we do need to be able to deactivate backface culling.

I've found that it's usually best to do as much data correction in the pipeline as possible, rather than make the 3D renderer adapt to incorrect data, which leads to slow-downs, but possibly backfaces are a special case, where it's sometimes impossible to fix them.

A couple of options I see:

1. A global Viewer config to switch culling on or off for everything
2. Extend XKT format with a per-object flag to enable or disable culling, which would also require extensions to the renderer to organize objects into cullable vs non-cullable render bins (bins == batches of many objects drawn in one draw call)

(1) is doable in short-term, but possibly has a performance hit, so worth measuring. We could do an experimental branch in which culling is hacked disabled, and see how that performs.
(2) for this to work, authoring tools will need to be able to specify that culling flag for the individual objects - is that possible in your pipeline?

**Comment by Francois-Thierry** [comment]
Hello,
I think that measuring the performance loss from (1) would be interesting, it might be not so detrimental as the performances are already great (with xkt related optimizations, viewport culling etc..). This would already be an nice fix regarding this issue for us.
Regarding (2), yes of course it is possible but I think it will be best if this can be automated directly in xeokit.
I performed some exploratory testing and found that edges adjacency is a nice criterion to identify geometries that need to have the backface culling disabled.
If there are edges that are only connected to a single triangle, then the geometry will likely be a surface and we can disable the backface culling :)
I tested it on 
[IfcOpenHouse.txt](https://github.com/xeokit/xeokit-sdk/files/5926525/IfcOpenHouse.txt)
and successfully identified the terrain :)

**Comment by xeolabs** [comment]
Nice, that's really useful.

I made a first attempt at a little function, that uses your edge adjacency heuristic to determine if a triangle mesh is solid: 
 https://gist.github.com/xeolabs/66aa8433f0a74c35bec5600d33bd9ef4
 
Next, I'll use this within xeokit, to organize surface (non-solid) meshes into their own render bin, for which backface culling is exclusively enabled.

This can be added within PerformanceModel, so will be quite transparent. Also, even if it falsely classifies lots of meshes as surfaces, that's cool, not a big performance impact to do some extra culling.

**Comment by xeolabs** [comment]
Actually, I found a few obvious flaws in that function - next version in progress.

**Comment by algusaem** [comment]
I don't think this issue has ever been adressed besides putting it on a milestone back in 2021. I'd like to know if there's a way to disable backface culling and if there isn't  (which seems to be the case) I'd like to ask for a way to disable it on future releases.

Have a nice day!
