### ISSUE TITLE
XeoKit engine distorts the geometry

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#568]
Hello, For some reason this GLTF File is working on a few different gltf viewers and on xeo kit it showing a wrong triangles.
The engine distorts the geometry.
You can download this file here: [https://easyupload.io/r8f39j](url)
![babylon](https://user-images.githubusercontent.com/42798926/107352351-caa39680-6adc-11eb-82a7-be71175824c3.PNG)
![cesium](https://user-images.githubusercontent.com/42798926/107352357-cb3c2d00-6adc-11eb-9d23-a829feed0f4b.PNG)
![filament](https://user-images.githubusercontent.com/42798926/107352360-cbd4c380-6adc-11eb-915f-952d1891f61c.PNG)
XeoKit:
![xeokit](https://user-images.githubusercontent.com/42798926/107352363-cbd4c380-6adc-11eb-86b4-ad081386a351.PNG)
XeoKit:
![xeokit2](https://user-images.githubusercontent.com/42798926/107352365-cc6d5a00-6adc-11eb-8b29-1dbcda51289d.PNG)

How can we work around this issue?

**Comment by Amoki** [comment]
Similar to https://github.com/xeokit/xeokit-sdk/issues/556?

**Comment by xeolabs** [comment]
Could I please get that file again?
