### ISSUE TITLE
Support point clouds and line segments in PerformanceModel

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#569]

**Comment by Francois-Thierry** [comment]
Hello Lindsay,
I am really interested about this feature, I can provide you with some test files if you need it, let me know.
Also this issue might be related to #364, feel free to close it when you are done !
Thanks for the amazing work

**Comment by xeolabs** [comment]
Hi Francois!

Yes please, some test files would be great.

Ideally, glTF files with points and lines, because I don't think ````IfcConvert```` supports IFC 4x2 at this point.
