### ISSUE TITLE
RTC coordinates for all geometries

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#570]
**Is this feature critical for your commercial enterprise?**
Without RTC coordinates for all objects, we can't load small and movable geometries near the loaded model.
Loading a technical object from a non-IFC source and place it in the model is common.
We can't do it anymore since see use RTC coordinates for models (Which is a very good feature). 

**Describe the solution you'd like**
Be able to load a glTF with big coordinates and use QualityModels (movable, resizable) alongside the model.
This implies being able to set a very big `position` when dynamically moving on an object.

**Describe alternatives you've considered**
I didn't find any solution.

**Comment by xeolabs** [comment]
This should be fixed now in 2.2.1-beta.1.

* [Demo](https://xeokit.github.io/xeokit-sdk/examples/positioningModels_GLTFLoaderPlugin_animateOriginAndRotation.html)
* [Source code](https://github.com/xeokit/xeokit-sdk/blob/master/examples/positioningModels_GLTFLoaderPlugin_animateOriginAndRotation.html)

With this fix, we can animate the ````origin```` property of all classes that implement the ````Entity```` abstract class. Those classes include ````PerformanceModel````, which loaded by ````XKTLoaderPlugin```` and ````GLTFLoaderPlugin```` (when configured performance: true), and the ````Node```` and ````Mesh```` classes, which compose the scene graphs loaded by ````GLTFLoaderPlugin```` (when configured performance: false).

````origin```` is an alias for ````rtcCenter````, which is the dynamically-updatable double-precision RTC center for the ````Entity````.

If the ````Entity```` is a ````PerformanceModel````, then ````origin```` is the RTC center that the RTC centers for all the contained ````PerformanceNode````s will be considered relative to. ````PerformanceNode```` does not expose an ````origin```` property - those are private and immutable.

If the ````Entity```` is a ````Node````, then the ````origin```` is the RTC center that the ````origin```` of all child ````Node```` and ````Mesh```` components will be considered relative to.

So, we effectively have a dynamically-updatible hierarchy of RTC centers, accessible via ````Entity#origin````. 
 These are cheap to animate, and only cost a redraw.

When we load a glTF, we can animate ````PerformanceModel#origin```` or ````Node#origin```` on the model (depending on which scene representation we loaded) to move the model around the double-precision World coordinate system. We can also animate ````Entity#scale```` and ````Entity#rotation````.
