### ISSUE TITLE
Problem with Npm Versioning

### ISSUE THREAD

**Issue by K01603779** [xeokit/xeokit-sdk#576]
**Describe the bug**
It is possible to install version 1.9.9.1 of the xeokit-sdk package with npm. But according to the npm page the current version should be 1.7.0-alpha.3. So I wanted to ask if  there is some versioning problem with the npm registry.

**To Reproduce**
1 `npm install @xeokit/xeokit-sdk@1.9.91`
2 `npm outdated`
Output 
Package             Current  Wanted         Latest        
@xeokit/xeokit-sdk   1.9.91  1.9.91  1.7.0-alpha.3

**Comment by Amoki** [comment]
According to npm, those packages are deprecated: https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/1.9.91

@xeolabs, you may want to unpublish them. Nobody is using them anymore imho.
