### ISSUE TITLE
Versioning + publish to npm

### ISSUE THREAD

**Issue by clemsos** [xeokit/xeokit-sdk#58]
Hi there, 

I am trying out `xeokit-sdk` and thinking it will be of great help to have it avail on npm registry. 

For now I have checked the git repo in my dependencies with a [commit number](https://docs.npmjs.com/files/package.json#github-urls), but then there is still the question of versioning. I saw the github tags in the repo but the `package.json` file still have default version number 1.0.0 

Will be neat to have a npm dep with proper version number if possible.

FWIW I have used [release-it](https://www.npmjs.com/package/release-it) to solve similar issues in previous projects and found it quite handy.

**Comment by xeolabs** [comment]
Good idea. Possible approach would be to have the [core viewer bits](https://github.com/xeokit/xeokit-sdk/tree/master/src/viewer) aggregated into one "xeokit-sdk" package, with each plugin being its own package. 

That ````package.json```` version number is not matched correctly, yes, we'll need to set that to ````0.2.1````.

**Comment by Amoki** [comment]
Using npm peerDependencies may be a good option for plugins.
It would imply create a package per plugin, dissociates plugins and viewer but opens the door for an API to build custom plugins while using the standard viewer.

**Comment by xeolabs** [comment]
xeokit is now available via npm: https://www.npmjs.com/package/@xeokit/xeokit-sdk
