### ISSUE TITLE
45 degree pipe bend mission on ifc parsing

### ISSUE THREAD

**Issue by vuicBABS** [xeokit/xeokit-sdk#593]
On the IFCOPENSHELL there was a issue (#1269). The problem is that the bend elements were not represented. The issue has been solved and must probably be in xeokit integrated.
Because for that time we don't have the visualization of these elements (look at the picture)

![image](https://user-images.githubusercontent.com/40517234/112527479-634b5880-8da3-11eb-8194-e43274bc9bd6.png)

**Comment by xeolabs** [comment]
@vuicBABS thanks for the heads-up!
