### ISSUE TITLE
TypeError: _xeokit_xeokit_sdk__WEBPACK_IMPORTED_MODULE_2___default.a is not a constructor

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#622]
hello, im trying to make a react app to implement a bim viewer, using the xeokit sdk, while coding the app, i wanted to call the viewer constructor, to see how it works in react, the code used is the following : 
`
class App extends React.Component {
    constructor(props) {
        super(props);
        const viewer = new Viewer({
            canvasId: "myCanvas",
            transparent: true
        });
    }
....
}
`

l'erreur retourné est la suivante : 
TypeError: _xeokit_xeokit_sdk__WEBPACK_IMPORTED_MODULE_2___default.a is not a constructor

**Comment by xeolabs** [comment]
Hi we can't offer support developing applications without a business support agreement - please get in contact if you need such support: http://xeokit.io/index.html#pricing
