### ISSUE TITLE
Fix sticky CameraControl rotation after dragging with left & right mouse buttons

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#623]
When you click right & left-click the model is turning around with the mouse
even if you don't press on the mouse

[https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_XKT_WaterLock](https://xeokit.github.io/xeokit-sdk/examples/#BIMOffline_XKT_WaterLock)

**Comment by xeolabs** [comment]
I can't reproduce this - what OS/Browser does this happen iin?

**Comment by Amoki** [comment]
I can with Firefox

**Comment by xeolabs** [comment]
Are there any special steps to follow? 

Opening that page and following those instructions works fine for me on FF and Chrome.

**Comment by vadimt2** [comment]
Chrome

**Comment by vadimt2** [comment]
Press both right and left click at the same time

**Comment by Amoki** [comment]
Open the page, press left, press right, release left, release right, move the mouse

**Comment by Amoki** [comment]
The fix partially broke the pan.
If we press shift before the left click, the pan doesn't work. If we press the left button before pressing shift, the pan works.

**Comment by xeolabs** [comment]
Should be fixed now.
