### ISSUE TITLE
Ability to configure which quality rendering effects are enabled by FastNavPlugin

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#625]
**Describe the bug**
FastNavPlugin enables pbr, sao and edges even if their not enabled.
After the first pivot, the 3 options are enabled anyways.
It comes from https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/FastNavPlugin/FastNavPlugin.js#L81which doesn't check the previous config.

**Comment by Amoki** [comment]
The solution only works for static configuration.
If edges are dynamically set to off at runtime, the plugin will restore them because edges were on at startup.

**Comment by xeolabs** [comment]
Yes this is how I intend it to work - the contract is that once instantiated, FastNavPlugin will be the only thing that should enable/disable PBR, SAO and edges.

**Comment by xeolabs** [comment]
I just updated it to support dynamic configuration: https://github.com/xeokit/xeokit-sdk/commit/1c0a69cf8367c3f0bde2b46311a837091471b391
