### ISSUE TITLE
How can i change cube language ?

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#626]
[https://xeokit.github.io/xeokit-sdk/examples/#gizmos_NavCubePlugin](https://xeokit.github.io/xeokit-sdk/examples/#gizmos_NavCubePlugin
)
How can i change cube language ?

**Comment by xeolabs** [comment]
Not supported yet. First step would be integrating some sort of internationalized string lookup map into xeokit, that various components like NavCubePlugin can source their strings from. Needs a bit of R&D.

**Comment by xeolabs** [comment]
Will be supported by #671
