### ISSUE TITLE
DrawRenderer.js?0f5a:177 WebGL: INVALID_OPERATION: uniform4f: location not for current program

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#636]
I'm using Vue JS and when you select a project and scene is loaded everything is ok.
I click on Annotations and every is working great.
When i go back to projects and selecting a new project and i'm loading a new scene and click on Annotations
I receive this error:
```
DrawRenderer.js?0f5a:177 WebGL: INVALID_OPERATION: uniform4f: location not for current program
```
// mounted
const xeoKitLoader = new XKTLoaderPlugin(viewer);

```
beforeUnmount() {
if (this.models.length > 0)
        this.models.forEach(model => {
          debugger
          model.destroy();
        });
 this.xeoKitLoader.destroy();
 this.xeoKitLoader.viewer.scene.destroy();
 }
```

**Comment by Amoki** [comment]
You must destroy the Viewer, not just the scene.

We use vue2 and this is what we do:
```javascript
this.viewer = new Viewer({...});

beforeDestroy() {
  this.viewer.destroy();
}
```

@xeolabs Do we need to destroy plugins too (loaders, BCF, navCube, ViewCullPlugin, etc) ?

**Comment by vadimt2** [comment]
Great it solved my issue:
```
 this.viewer.destroy();
```

I thought i will destroy the xeoKitLoader.destroy(); and it will kill everything.

"@xeolabs Do we need to destroy plugins too (loaders, BCF, navCube, ViewCullPlugin, etc) ?"

It means that i have to destroy  oneeach of them ?

**Comment by Amoki** [comment]
I don't know, that's why I'm asking

**Comment by xeolabs** [comment]
I just verified that Viewer#destroy will call Plugin#destroy on each installed plugin: https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/Viewer.js#L359
