### ISSUE TITLE
Fix transparency bug revealed by IfcOpenShell simple_wall.ifc model

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#641]
**Describe the bug**
This single object file fails to render correctly (glTF and xkt). The object is transparent instead of white.
Object is xeokit:
![Capture d’écran de 2021-05-03 18-13-44](https://user-images.githubusercontent.com/1349751/116902661-b4b8f400-ac3b-11eb-99db-ed7afd987c7b.png)
Selected object in xeokit:
![Capture d’écran de 2021-05-03 18-15-40](https://user-images.githubusercontent.com/1349751/116902675-b84c7b00-ac3b-11eb-9134-f54dccf48c63.png)
Object in threeJS:
![Capture d’écran de 2021-05-03 18-13-48](https://user-images.githubusercontent.com/1349751/116902729-c8645a80-ac3b-11eb-8b01-c05e7414b79f.png)

[simple_wall.gltf.txt](https://github.com/xeokit/xeokit-sdk/files/6416115/simple_wall.gltf.txt)
[simple_wall.ifc.txt](https://github.com/xeokit/xeokit-sdk/files/6416107/simple_wall.ifc.txt)

It worked with xeokit 1.4.9 (and maybe later), but not anymore.

**Expected behavior**
A white colored object

**Comment by xeolabs** [comment]
Fixed - objects were getting wrongly flagged as transparent as they were loaded.

This issue even gets the delux treatment, with it's own visual regression test page: https://xeokit.github.io/xeokit-sdk/tests/loading_XKT_SimpleWall.html

**Comment by xeolabs** [comment]
Thanks to the minimal attached model files, and snapshots, this bug was super easy to fix and translated directly into a regression test - the ideal issue ticket IMO.
