### ISSUE TITLE
Working on Single Page Application 

### ISSUE THREAD

**Issue by suryakumara** [xeokit/xeokit-sdk#660]
Load to the first page with xeokit canvas everything is going well. but when I went to the other page, and go back again to the canvas, there were some items missing and got a warning like this.

WebGL: INVALID_OPERATION: uniformMatrix4fv: location is not from current program

![Screen Shot 2021-05-21 at 2 22 30 PM](https://user-images.githubusercontent.com/51102773/119092074-8cedcc80-ba40-11eb-93c9-d5bd0fa027e2.png)
![Screen Shot 2021-05-21 at 2 22 41 PM](https://user-images.githubusercontent.com/51102773/119092084-8eb79000-ba40-11eb-8f1c-2ee683292ee1.png)
![Screen Shot 2021-05-21 at 2 22 57 PM](https://user-images.githubusercontent.com/51102773/119092098-924b1700-ba40-11eb-96c1-d9e1325be8da.png)

**Comment by fanfafafanfan** [comment]
hello, I also have this poblem, how did you fixed it ?

**Comment by suryakumara** [comment]
You have to destroy the viewer and all plugin.
