### ISSUE TITLE
Xeo kit making overflow to body

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#662]
Hi, i can see that your body overflow is hidden:
https://github.com/xeokit/xeokit-sdk/blob/master/examples/css/style.css
You are hidding 
```
<!--StartFragment-->body {    font-family: 'Roboto', sans-serif;    font-size: 15px;    line-height: 1.50;    color: white;    background-color: black;    text-decoration: none;    word-spacing: normal;    text-align: left;    letter-spacing: 0;    -webkit-font-smoothing: antialiased;    overflow-y: hidden;    overflow-x: hidden;    margin: 0;    touch-action: none;}<!--EndFragment-->

```
I can do the same in my app.
My body overflow set to auto.

and when i'm loading xeo kit model your canvas making huge x & y over to my body element.

* The issue is because the annotations.

**Comment by xeolabs** [comment]
Sorry, I don't understand this issue. If you can post a live example (JSFiddle etc) that reproduces the issue, we'll reopen and take a look. Thanks
