### ISSUE TITLE
Uploading Image Plane from Cloud

### ISSUE THREAD

**Issue by suryakumara** [xeokit/xeokit-sdk#663]
const imagePlane = new ImagePlane(viewer.scene, {
      id: "Plane",
      isModel: true,
      src: "https://firebasestorage.googleapis.com/vt.com/o/images%2Fmap.png?alt=media&token=xcxxxxx=-20e7-4763-9729-079fds2d3b4c32",
      size: 190,
      position: [0, 0, 0],
      rotation: [0, 90, 0], 
      opacity: 1.0,
      collidable: false,
      gridVisible: true,
      pickable: false,
    });

Trying to use image from cloud (dynamic imagePlane) and got this ERROR: 

Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.
    at Na.setImage (http://localhost:3000/static/js/vendors~main.chunk.js:98692:14)
    at Va.set image [as image] (http://localhost:3000/static/js/vendors~main.chunk.js:98832:85)
    at Image.e.onload (http://localhost:3000/static/js/vendors~main.chunk.js:109866:29)

![Screen Shot 2021-05-26 at 3 01 12 PM](https://user-images.githubusercontent.com/51102773/119616584-5a264880-be33-11eb-8675-045abf77b539.png)

**Comment by Amoki** [comment]
Hello,

I'm facing the same problem. How did you solve this?

**Comment by Amoki** [comment]
The solution is to use the `image` field instead of `src` and set the `crossOrigin` to `anonymous`.

```javascript
const img = new Image();
img.src = "THE_URL";
img.crossOrigin = "anonymous";
img.onload = () => {
  new ImagePlane(viewer.scene, {
    image: img,
    ...
  };
}
```
