### ISSUE TITLE
CORS issue trying to use outside resource

### ISSUE THREAD

**Issue by suryakumara** [xeokit/xeokit-sdk#666]
I was planning to use an image from an server source and got a cross error. for testing only I use NPM serve so that it can be accessed.  (https://www.npmjs.com/package/serve)

This is the error : 
Access to image at 'http://localhost:5000/cit.png' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

     ` const img = new Image();
      img.crossOrigin = "Anynomous";
      img.src = "http://localhost:5000/cit.png";

      const imagePlane = new ImagePlane(viewer.scene, {
        id: "Plane",
        isModel: true,
        src: img,
        size: 190,
        position: [0, 0, 0],
        rotation: [0, 90, 0], // X, Y and Z
        opacity: 1.0,
        collidable: false,
        gridVisible: true,
        pickable: false,
      });`

**Comment by Amoki** [comment]
CORS are delivered from http://localhost:5000 in your use case. You must serve CORS headers from your server running on port 5000.

**Comment by suryakumara** [comment]
I got it. Thank for your response
