### ISSUE TITLE
Unable to Destroy ImagePlane

### ISSUE THREAD

**Issue by suryakumara** [xeokit/xeokit-sdk#668]
When loading xkt files everything runs smoothly as well as when using viewer.destroy(). 
But got this error when I added ImagePlane. by the way I use React.

destroy() {
    this.viewer.destroy();
  }

![Screen Shot 2021-06-07 at 6 16 42 PM](https://user-images.githubusercontent.com/51102773/121000348-b175d280-c7bc-11eb-9f52-4654b4fd7f39.png)

**Comment by steven11329** [comment]
The Problem is
```
ImagePlane.js:553 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at ImagePlane.destroy (ImagePlane.js:553)
    at Scene.destroy (Component.js:887)
    at Scene.destroy (Scene.js:2406)
    at Viewer.destroy (Viewer.js:368)
```
And I found the code
```js
destroy() {
    this._state.destroy();
    super.destroy();
}
```

_state is undefined

**Comment by MaxGeldner** [comment]
Have the same issue.
I don't see a variable `_state` in the code for the ImagePlane, as well as in the code of Component. So does` _state` even exist?

Maybe its a leftover from an earlier version?
