### ISSUE TITLE
Regex for testing userAgent fails in WKWebViews on iOS

### ISSUE THREAD

**Issue by indianscout** [xeokit/xeokit-sdk#669]
**Describe the bug**
Loading xeokit-bim-viewer in an iOS WKWebview fails (shows blank page) with the following error in the console:
![image](https://user-images.githubusercontent.com/7571099/121296590-36620880-c8f1-11eb-9374-988e369ae14f.png)

The reason for this is in xeokit-sdk: https://github.com/xeokit/xeokit-sdk/blob/f2a481cd6971535569c5de028d9a89a1f4f866bd/src/viewer/scene/postfx/SAO.js#L179

The userAgent in WKWebview on iOS 14.5.1 looks like:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)
```

**To Reproduce**
1. Open xeokit-bim-viewer that uses xeokit-sdk in a iOS WKWebView

**Expected behavior**
The 3D model should be displayed like loading it in Safari.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone8/12
 - OS: iOS 14.5.1
 - Browser WKWebView
 - Version -

**Additional context**
WKWebView userAgent do not contain the keyword "safari" like the Safari browser on iOS. The regex here: https://github.com/xeokit/xeokit-sdk/blob/f2a481cd6971535569c5de028d9a89a1f4f866bd/src/viewer/scene/postfx/SAO.js#L179 retuns **null** and i[1] of null causes the app to crash.

**Comment by xeolabs** [comment]
Fixed by: https://github.com/xeokit/xeokit-sdk/pull/681
