### ISSUE TITLE
Angle Measurement bug

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#670]
im usign the Angle Measurment plugin, and im using it in a button component via onClik event, now the goal of the button is to activate and desactivate the plugin, which i implemented in the code below : 

`
function HandleAngleMesure(viewer, btnState, setBtnState) {
    let AnglePlug = new AngleMeasurementsPlugin(viewer);
    if(btnState === true) {
        console.log("test true")
        AnglePlug.control.activate();
    } else {
        console.log("test false")
        AnglePlug.clear();
        AnglePlug.destroy();
        AnglePlug.control.deactivate();
    }
    setBtnState(!btnState)
}
`

now in the console i can see that the function switches between the true and false state, but in the view i can still use the plugin
![Capture](https://user-images.githubusercontent.com/50522164/121506611-28d97b00-c9e4-11eb-9f7f-45b39a32276d.JPG)

thanks for your help in advance @xeolabs

**Comment by xeolabs** [comment]
Hi we can't offer support developing applications without a business support agreement - please get in contact if you need such support: http://xeokit.io/index.html#pricing
