### ISSUE TITLE
logarithmicDepthBufferEnabled breaks ortho projection

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#677]
**Describe the bug**
When logarithmicDepthBufferEnabled is true, the ortho project is very glitchy.

**To Reproduce**
1. set `logarithmicDepthBufferEnabled: true`
2. set projection mode to ortho

**Expected behavior**
Ortho projection work with logarithmicDepthBufferEnabled

**Screenshots**
![Capture d’écran de 2021-06-25 18-38-07](https://user-images.githubusercontent.com/1349751/123457778-91c81200-d5e4-11eb-9497-fd0b67d23c27.png)

**Comment by xeolabs** [comment]
Looking around to see how other WebGL renderers handle this, I noted that THREE actually disables log depth buf for ortho:  https://github.com/mrdoob/three.js/commit/8d00c49c4d32c323839da05012f9a126180b9535#diff-5e6741c88cfdbeaa621f557a003c9bd5e3b8e524991e3aebf904422cc2aa0427

**Comment by Amoki** [comment]
I don't think anyone wants to see a city in ortho mode, it seems to be a good workaround
