### ISSUE TITLE
Xeokit converter is not working please help me asap - gltf to xkt

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#689]
[test (1).zip](https://github.com/xeokit/xeokit-sdk/files/6786165/test.1.zip)
I can't convert gltf to xkt and I having this issue:
```
Reading glTF file: test.gltf
Converting to XKT format v7
Something went wrong: Parameter expected: params.primitiveType
```
https://github.com/xeokit/xeokit-gltf-to-xkt/issues/39

I'm using the lastest converter

**Comment by xeolabs** [comment]
Hi, 

it's a ````xkt2gltf```` bug, where ````xkt2gltf```` is expecting a "mode" property on each glTF primitive (see spec: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/mesh.primitive.schema.json#L25).

That property should be optional, and xeokit should be defaulting to ````4```` (triangles).

I'll fix in the next release, but in the meantime if you could reexport your glTF somehow with that property included, that would be a workaround I think.

**Comment by vadimt2** [comment]
Tnx, i will you version 0.6 for now
