### ISSUE TITLE
Layout issue with auto-generated annotation elements

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#695]
Hi, i can see that on your demo:
http://xeokit.io/demo.html?projectId=RevitSamples&tab=models
You have headed
```
body {
    overflow: hidden;
}
```

In the project that I'm working on, I can't do it.
And when I run xeo kit, I have overflow x and y.
and it's messing up the application UI.

The reason for it that annotation-marker and annotation-label are outside of the canvas.
Can you fix it please and make it inside the canvas?

**Comment by satyajitghana** [comment]
I found a workaround

create the marker and the label manually and give their IDs to the createAnnotation function

```javascript
bimModel?.annotationsPlugin.createAnnotation({
...
  markerElementId: markerElementCustom.id
  labelElementId: labelElementCustom.id
...
})
```
