### ISSUE TITLE
Usdz support?

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#706]
Does supporting the Usdz format align with xeokit and its ````.xkt```` format?

Discussion welcome!

https://graphics.pixar.com/usd/docs/Usdz-File-Format-Specification.html

**Comment by simplylogicninjas** [comment]
With the advertising of Apple RoomPlan, I think it is.

https://developer.apple.com/augmented-reality/roomplan/

Any idea's how to convert it to XKT for the near future?

**Comment by xeolabs** [comment]
We have no immediate plan to support USDZ, but would welcome PRs on this one.

Two options:

1. Within xeokit-sdk, create a USDZLoaderPlugin, that loads directly into the Viewer
2. Within xeokit-convert, create a parseUSDZIntoXKTModel.js function and integrate it into convert2xkt, to use when parsing files with the ".usdz" extension.

Resources:

* https://github.com/autodesk-forks/USD/tree/gh-pages/usd_for_web_demos
