### ISSUE TITLE
Select and hover on an object

### ISSUE THREAD

**Issue by NeluQi** [xeokit/xeokit-sdk#718]
I created my xkt model, but to hover over the object I need to hover to the side. (Red dot in the photo). How to fix it? And what could it be connected with?

![image](https://user-images.githubusercontent.com/16963395/131555938-6ee35d7c-18d7-497f-9afc-a9176216e271.png)

**Comment by xeolabs** [comment]
If you can post a live example (JSFiddle etc) that reproduces the issue, we'll reopen and take a look. Thanks

**Comment by NeluQi** [comment]
The problem went away after updating the package
