### ISSUE TITLE
Unable to extends the class DistanceMeasurement and DistanceMeasurementsControl

### ISSUE THREAD

**Issue by zhy1440** [xeokit/xeokit-sdk#721]
Hi Experts,

**Describe the bug**
I want to costmize the behavior of DistanceMeasurement but was unable to extends the class DistanceMeasurement and DistanceMeasurementsControl.

**To Reproduce**
`Uncaught TypeError: _xeokit_xeokit_sdk_dist_xeokit_sdk_es_js__WEBPACK_IMPORTED_MODULE_4__.DistanceMeasurementsControl is not a constructor`

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/26110476/132021344-fee44065-3679-4566-b343-7a6be57fbd44.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefox
 - Version 91.0.2 (64 bit)

**Comment by xeolabs** [comment]
Hi, this is not an extension point within the xeokit API - in other words, the DistanceMeasurementPlugin is designed to internally manage the lifecycle of its DistanceMeasurementsControl, ie. instantiating and destroying that internally.

So according to this design, unfortunately the API does not support you subclassing the DistanceMeasurementsControl (unless you rewrite parts of DistanceMeasurementPlugin, which would deviate too much architecturally, so we don't recommend).

I'd recommend making a new version of DistanceMeasurementPlugin with the custom behaviour you need, perhaps copied from the original DistanceMeasurementPlugin and modified as you need it.

**Comment by zhy1440** [comment]
Hi Lindsay,
So, I should copy the the three class for reference and it is the only way to change the styles of the wire, marker, label of the DistanceMeasurement, right?

**Comment by zhy1440** [comment]
@xeolabs I find that Dot and Wire are also unavailabe...

**Comment by xeolabs** [comment]
Hi, yes, modifying a copy of the DistanceMeasurementsPlugin is the way to go, including Dot and Wire. 

Since DistanceMeasurementPlugin not designed to be extended or subclassed, this is the only option this point.

Were we to extend DistanceMeasurementPlugin, we would also need to extend documentation and examples for that component. Much easier to make a new tool, if the behaviour is to be very different from the original.
