### ISSUE TITLE
Fix pickSurfacePrecision for ray-pick along vertical world axis

### ISSUE THREAD

**Issue by juho-ylikyla** [xeokit/xeokit-sdk#723]
**Describe the bug**
`viewer.scene.pick` does not return consistent results.
Picking towards `viewer.scene.camera.worldUp` or `viewer.camera.worldUp` never hits anything.

**To Reproduce**
1. Copy and paste the following code to the examples directory. Run it in chrome. https://gist.github.com/juho-ylikyla/bbe22c47a1bd640e04182538a23b08dd
2. Click around, for example, a door
3. See that sometimes the measurements go through objects

**Expected behavior**
Measurements should be consistent. We should see also measurements in the up-down direction.

**Screenshots**
https://user-images.githubusercontent.com/62982612/132332813-bf7b9685-ad47-4e7a-9f39-c9f28c74b8f6.mp4

**Desktop (please complete the following information):**
 - OS: ios or macOS
 - Browser Safari or chrome 92.0.4515.159 (Official Build) (x86_64)
 - Version 92.0.4515.159 (Official Build) (x86_64)
 - Xeokit version `2.0.0-beta.11`

**Additional context**
This seems to happen with `pickSurfacePrecision: true`
The up-down direction measurements work if we add a small offset to `worldUp` normal vector or use a slightly skewed vector such as [0.002, 1, 0]

**Comment by xeolabs** [comment]
Hi @juho-ylikyla I just published a fix in xeokit-sdk 2.0.0-beta.24.

**Comment by juho-ylikyla** [comment]
Hi,

Thank you for the quick fix! 

I pulled the latest master and used the code in the gist. The up-down direction now works but the other direction still results in inconsistent results. See attached video.

https://user-images.githubusercontent.com/62982612/133614632-10773c0d-8890-4c36-b2d5-ebd9cb5427ee.mp4

Do you want me to open a new issue?

**Comment by xeolabs** [comment]
Hmm yes, please open a new issue for this one. Does your measurement tool work by picking an object, then firing vertical and horizontal ray-picks to find the object/surface width and height?

FYI we can query geometry positions from the Entitys now, in case that's a more robust source of data for measurement.

**Comment by juho-ylikyla** [comment]
Our measurement tool is used for indeed determining the object dimensions in some cases but also the distance between objects. It is important for us that we can determine objects "next" to each other, with ray-picking or otherwise.

Thanks, I'll look into the geometry positions 👍

**Comment by pbbr** [comment]
@xeolabs We've identified an issue with precision ray picking when taking measurements on the backface of an object. In this case, `precisionRayPickSurface` does not return an intersection. On the frontface of the object, the ray picking works like expected. Do you have any idea how to extend the function with backface support like the other pick functions?

https://github.com/xeokit/xeokit-sdk/blob/a02bf9d4f31e7e7572457081d4d2296d06b1a4fe/src/viewer/scene/models/VBOSceneModel/lib/layers/trianglesBatching/TrianglesBatchingLayer.js#L1174

**Comment by pbbr** [comment]
> @xeolabs We've identified an issue with precision ray picking when taking measurements on the backface of an object. In this case, `precisionRayPickSurface` does not return an intersection. On the frontface of the object, the ray picking works like expected. Do you have any idea how to extend the function with backface support like the other pick functions?

@xeolabs Do you have an idea how to solve this issue? Thanks for your check.

**Comment by xeolabs** [comment]
Hi, not yet, because this is not a use case for which ray-picking was designed. This would be an "extra feature". However, it is possible to extend it to do this, but I'd need to do some thinking on it. Can we track this one via the Creoox Asana?
thanks

**Comment by pbbr** [comment]
@xeolabs Thx for your feedback. I don't have access to the Asana Board. But anyway, the precision surface picking could be comined with the normal surface picking to allow measurements even on backfaces (with lower accuracy). The advantage of this approach is also to don't have issues if the model is sliced (because ray picking doesn't take that into account. What do you think about this approach?
