### ISSUE TITLE
Markers (Annotation) - ver 2 beta xeokit

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#730]
Is there a way to show Annotations if only I can see them in the camera?
and if I can't see them in the camera they will be display none?

**Comment by xeolabs** [comment]
If I understand the description of this issue correctly, Annotations already work this way - they disappear when out of view - see example: https://xeokit.github.io/xeokit-sdk/examples/#annotations_clickShowLabels

If you can post a link to a live example that reproduces a bug, I'll take a look.
