### ISSUE TITLE
Error reporting: fs Module not found

### ISSUE THREAD

**Issue by dengzer1001** [xeokit/xeokit-sdk#745]
after updating xeosdk to version 2.0.6, error logs:
```
Module not found: Error: Can't resolve 'fs' in '/projectpath/node_modules/@xeokit/xeokit-sdk/dist'
```
and it seems to be related to code as below and lacking of a dependency in package.json:

https://github.com/xeokit/xeokit-sdk/blob/e863dddcac1ffd999234d724cfebdac04b5882c7/src/plugins/XKTLoaderPlugin/XKTDefaultDataSource.js#L46

**Comment by Amoki** [comment]
https://developer.mozilla.org/fr/docs/Web/API/URL/createObjectURL can be used for this purpose
