### ISSUE TITLE
Access properties of an element at onClick

### ISSUE THREAD

**Issue by fabriziopaolopetrelli** [xeokit/xeokit-sdk#747]
Hi guys, I'm trying to imitate the behavior of the [xeokit-sdk](http://xeokit.io/demo.html?projectId=OTCConferenceCenter&tab=storeys) example where you can access the properties of the selected element, how can I do it? 

`viewer.cameraControl.on('doublePicked', (pickResult) => {
      console.log(pickResult)
    });`

I've searched through the object above but haven't found anything

**Comment by jenbuzz** [comment]
Have you tried looking at this.viewer.metaScene.metaObjects and matching the IDs ?

**Comment by xeolabs** [comment]
Perhaps this will help: https://www.notion.so/xeokit/Scene-Representation-and-Metadata-in-xeokit-936fa040f4e9417bb83cc04136ca0b8d
