### ISSUE TITLE
GLTFLoader doesn't load embedded textures/ images

### ISSUE THREAD

**Issue by K01603779** [xeokit/xeokit-sdk#755]
**Describe the bug**
When using a gltf - File with embedded Textures the GLTFLoaderPlugin doesn't recognize these as embedded images and tries to load them from the webserver. 
e.g. 
```
"images": [
    {
      "mimeType": "image/png",
      "uri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB
                HSuDAAAAAXNSR0IArs4c6QAAIABJREFUeF7s3Qew5td93vdz ... 
  }
]
```
Resutls in 
![Request-Emedded](https://user-images.githubusercontent.com/73077750/139531735-bb5a54d4-f812-473d-9e92-b85f30efa155.PNG)

**Comment by satyajitghana** [comment]
same here :(

**Comment by satyajitghana** [comment]
One way to fix this would be to place the image file separately in `public` folder and map the location in the `gltf` file

**Comment by xeolabs** [comment]
Added in 2.3: https://xeokit.github.io/xeokit-sdk/examples/#loading_glb_BoxTextured
