### ISSUE TITLE
Issue with loading glTF file exported from Three JS Editor

### ISSUE THREAD

**Issue by rahulkhandepts** [xeokit/xeokit-sdk#757]
**Describe the bug**

We are evaluating XeoKit SDK for a project. Here we need to load glTF file. I could setup the project correctly and load glTF files from Khronos repository. Later I tried to load few glTF files exported from Three js editor but it failed. I tried both i.e. embedded gltf and gltf with bin but no luck. Can someone please guide. 
Attached is the sample glTF file.

Thank you.
[2dSingleDraw.zip](https://github.com/xeokit/xeokit-sdk/files/7453162/2dSingleDraw.zip)
.

**Comment by rahulkhandepts** [comment]
Hello Team,

Any suggestions on this issue. Thank you.

**Comment by satyajitghana** [comment]
use blender to export, works everytime.
