### ISSUE TITLE
Double precision support for GLTFLoaderPlugin performance mode

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#761]
Extends [GLTFLoaderPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/GLTFLoaderPlugin/GLTFLoaderPlugin.js~GLTFLoaderPlugin.html) to support models that contain double-precision coordinates, which is the case when those models are placed at real-world positions.

* [Run this example](https://xeokit.github.io/xeokit-sdk/examples/#loading_glTF_MAP)

````javascript
import {Viewer, GLTFLoaderPlugin} from "../dist/xeokit-sdk.es.js";

    const viewer = new Viewer({
        canvasId: "myCanvas",
        transparent: true
    });

    viewer.scene.camera.eye = [1841982.5187600704, 19.207790938410042, -5173303.042326414];
    viewer.scene.camera.look = [1842011.793756829, 9.913817421536704, -5173299.841616623];
    viewer.scene.camera.up = [0.2991762376746394, 0.9536370664170352, 0.0327096983532173];

    const gltfLoader = new GLTFLoaderPlugin(viewer);

    const model = gltfLoader.load({
        id: "myModel",
        src: "../assets/models/gltf/MAP/MAP.gltf",
        metaModelSrc: "../assets/models/gltf/MAP/MAP.json",
        edges: true
    });

    model.on("loaded", () => {
        viewer.cameraFlight.flyTo(model);
    });
````

**Comment by Amoki** [comment]
Is it a first step to support double precision with quality mode?

**Comment by xeolabs** [comment]
Yes, that is one of the next steps.

BTW, you can move Node and Mesh hierarchies around in double-precision space by centering the model (before loading) and dynamically updating the ````origin````, which is the new alias name for ````rtcCenter````. That effectively updates the origin recursively for the Nodes and Meshes in the hierarchy, and can be used to move the model around.

One user is already doing that with STL models, to position them on a Mapbox map.
