### ISSUE TITLE
Uncaught incorrect header check

### ISSUE THREAD

**Issue by fabriziopaolopetrelli** [xeokit/xeokit-sdk#762]
Hi everyone, I'm trying to fetch an XKT from an API

The API returns the XKT in base64 so the steps to reproduce are: 

```
const data = atob(fileXKT);
const test = new Blob([data], { type: 'application/*; charset=utf-8' });
const url = URL.createObjectURL(test);

model = xktloader.load({
  src: url,
});

```

Initially the components render the loading circle and then it stops leaving a blank component and an error in the console:
`Uncaught incorrect header check`

How to fix?

**Comment by xeolabs** [comment]
This is not a bug, so no fix to xeokit required for this. The ````src```` parameter for the ````XKTLoaderPlugin#load```` call is assumed to be a path to a file, not the Base64-encoded contents of the file. 

https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/XKTLoaderPlugin/XKTLoaderPlugin.js~XKTLoaderPlugin.html#instance-method-load

**Comment by fabriziopaolopetrelli** [comment]
The error persist even if we pass it to the `xkt` parameter as an arrayBuffer, how we can fix this?

**Comment by xeolabs** [comment]
The ````xkt```` parameter works OK for us so far, so it is difficult to guess what is wrong with your ArrayBuffer without the means to reproduce the error - could you please post a working example that reproduces the error.
