### ISSUE TITLE
firstPerson pan

### ISSUE THREAD

**Issue by NeluQi** [xeokit/xeokit-sdk#764]
how to change pan speed for first Person (which is on the right mouse button)?

and how to disable changing the pan speed for the first Person when pan for the model object and for the void?

Now when I paranomy from the PC (with the mouse - right click):
1) When I take a canvas (not an object), the movement occurs at normal speed
2) When I take an object, the movement is very slow (camera speed)

How to fix point 2?

**Comment by NeluQi** [comment]
@xeolabs pls help

**Comment by xeolabs** [comment]
By design, when moving in first-person mode, the rate of movement is in proportion to the distance to the object under the mouse cursor. So unfortunately there's nothing we can fix here, sorry.
