### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by NeluQi** [xeokit/xeokit-sdk#766]
VSC gives me a warning 

warning  in ./node_modules/@xeokit/xeokit-sdk/dist/xeokit-sdk.min.es.js

Critical dependency: the request of a dependency is an expression

 "@xeokit/xeokit-sdk": "^2.0.14",

**Comment by xeolabs** [comment]
Do you mean WebPack, like in this stackoverflow issue? 

https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

**Comment by NeluQi** [comment]
> Do you mean WebPack, like in this stackoverflow issue?
> 
> https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

My project on WebPack

I import like this
import {
  AnnotationsPlugin,
  AxisGizmoPlugin,
  buildGridGeometry,
  buildSphereGeometry,
  ContextMenu,
  DistanceMeasurementsPlugin,
  EmphasisMaterial,
  FastNavPlugin,
  Mesh,
  NavCubePlugin,
  ReadableGeometry,
  VBOGeometry,
  ViewCullPlugin,
  Viewer,
  XKTLoaderPlugin,
} from '@xeokit/xeokit-sdk/dist/xeokit-sdk.min.es.js';


It never happened before

**Comment by behuf** [comment]
i have the same warning with webpack
`WARNING in ./node_modules/@xeokit/xeokit-sdk/dist/xeokit-sdk.es.js 93422:11-21
Critical dependency: the request of a dependency is an expression`

**Comment by fabriziopaolopetrelli** [comment]
Same error with create-react-app

**Comment by amir-arad** [comment]
same error with next.js (webpack)
