### ISSUE TITLE
AngleMeasurementsPlugin and DistanceMeasurementsPlugin

### ISSUE THREAD

**Issue by NeluQi** [xeokit/xeokit-sdk#767]
AngleMeasurementsPlugin and DistanceMeasurementsPlugin

Creates lines and names in the DOM.

When you go beyond the canvas (turn away from the camera) - a scroll appears on the entire page

Add hiding as with Annotation when going out of screen

**Comment by Amoki** [comment]
I think this is similar to https://github.com/xeokit/xeokit-sdk/issues/662.

Annotations are appended to the body iirc, not the canvas of xeokit. There is no CSS property `overflow` (and we don't want them on the body anyway) so when an annotation goes outside of the canvas, it triggers a scrollbar.

@Kurtil Am I right?

**Comment by Kurtil** [comment]
Yes @Amoki, I think you are right. But it is possible to configure it.

In [the distance plugin documentation](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/DistanceMeasurementsPlugin/DistanceMeasurementsPlugin.js~DistanceMeasurementsPlugin.html), on the **Public Constructors** section, the second argument of the constructor is an optional `cfg` object. It accepts an `cfg.container` property : "Container DOM element for markers and labels. Defaults to document.body.". I think it may be what you need @NeluQi.
