### ISSUE TITLE
are touch events supported for input ?

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#768]
hello,

i was wondering, are touch events supported in input, for example i want to add an annotation using a touch event, i looked in the documentation, and i can only find mouse and keyboard events, if anyone has an idea on how to do that i would appreciate the help.

thank you all
@xeolabs

**Comment by Amoki** [comment]
No event seems to be emitted. Picking stuff happens [here](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/CameraControl/lib/handlers/TouchPickHandler.js) and [here](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/CameraControl/lib/handlers/TouchPanRotateAndDollyHandler.js), and you can find an event example [here](https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/CameraControl/lib/handlers/MousePickHandler.js#L218) if you want to open a PR

**Comment by assaad97** [comment]
@Amoki what i mean is, for example this is an example to create an annotation using a mouse event(mouseclicked), what im asking for is it possible to replicate the same feature, but instead of using a mouse events, we use touch events(like touchstart or touch end)

thank you.
@xeolabs
