### ISSUE TITLE
XKTLoaderPlugin optimization: selectively batch instanced geometries

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#769]
## A pathological case for geometry instancing

XKT reduces its file size by re-using geometries among objects, a technique called *[geometry instancing](https://webglfundamentals.org/webgl/lessons/webgl-instanced-drawing.html)*. Instead of having 100 identically-shaped objects each having their own geometry, we share the same chair geometry among the 100 objects. In addition to reducing file size and transfer time, instancing is also great for reducing memory footprint and bandwidth within the browser and GPU, which lets us load more models into the viewer at once.

 In terms of WebGL performance, instancing has a pathological case, however, when we have a large number of geometries, each of which have multiple instances. 
 
When we have a small set of geometries that each have a large set of instances, that's the **ideal case.** In that case, following the way instancing works in WebGL, we're doing a single draw call for each of those sets of instances (instead of having to draw each instance individually).

When we have large number of geometries, each of which have some number of instances (don't care how many), we're hitting the **pathological case**, simply because we need to do a large number of draw calls, one for each geometry, to render its set of instances.  Draw calls are always expensive, and are even more expensive when they each represent a set of instances. On my machine, I get a noticeable performance drop beyond 1K instanced geometries or so, which makes sense.
 
## Solution

For XKT v8 and v9, extend ````XKTLoaderPlugin```` to automatically "expand" certain instanced geometries, to convert their instances into *geometry batches*.   In other words, if we have a chair geometry that is instanced 100 times, convert that into a geometry batch that contains 100 duplicates of the chair geometry. 

The XKT file can continue to re-use geometry as much as it likes, which is great for reducing file size.

Whether xeokit uses instancing or batching for geometries is completely invisible to the user/developer, except that xeokit will consume more memory when batching ( but actually not as much as I thought - with xeokit's relative coordinates and vertex attributes compression, we can pack **a lot** of models into  1GB GPU RAM).

In experiments, I found that:

* Models like OTC Conference Center, Holter Tower seem much more responsive (from 30-40FPS increased to 60FPS)
* There is some extra overhead while XKTLoaderPlugin expands the instances into batches, while it performs a few transforms and array copies to "bake" each instance into a batch. OTCConferenceCenter took another 30% longer to load.
* XKT files don't need to be modified/reconverted - this is all handled in the XKTLoaderPlugin.

## Usage

Load the Duplex IFC model, forcing the conversion of all reused geometries into xeokit's batched geometry representation:
 
````javascript
const xktLoader = new XKTLoaderPlugin(viewer, {
      reuseGeometries: false
});

const model = xktLoader.load({
    id: "myModel",
    src: "../assets/models/xkt/v9/ifc/Duplex.xkt"
});
````

## Progress

I have a working implementation, which just converts **all** instances into batches, I'll push an expermental npm package soon.

It would be nice if we could still use instancing though, for the sweet-spot where we've got many instances of a small set of geometries.

My implementation is able to selectively expand whatever geometries it chooses to, but at the moment it just expands all instances.

Can we find a heuristic to guide that? 

Perhaps a "budget" of instanced geometries we're allowed, say 200, so that when we've got 200 instanced geometries in the Viewer, XKTLoaderPlugin starts expanding all instances.

Or a kind of threshold, like when a geometry has >N instances, don't expand it.

Or some kind of memory footprint tracking/packing algorithm, where XKTLoaderPlugin tries to find the optimal instancing/batching ratio to make everything fit in a desired memory limit, while avoiding too much instancing at the same time? 

The tricky thing is that a viewer cannot predict how many models a user may want to load; XKTLoaderPlugin doesn't know whether to be aggressive or conservative in selecting an instanced geometry for expansion.

**Comment by xeolabs** [comment]
@Amoki this one is up your alley - should mean that you can go ahead and do automatic geometry reuse in your pipeline, and xeokit will ensure that doesn't kill the Viewer FPS :)

**Comment by Amoki** [comment]
Let me see if I understand correctly:
By default :
20 unique geometries will be rendered in 1 batch draw
1 set of reused geometries will be rendered in 1 draw

So 1 model with 100 unique geometries and 20 similar windows and 20 similar walls will be rendered in 3 draw calls.

Enabling `reuseGeometries` will duplicate reused geometries in memory to make it all in 1 batch draw call.

If I'm right, then my problem comes from models with:
10,000 unique geometries (1 draw instead of 10,000) => OK
40 geometries reused 100 times (40 draws instead of 4,000) => OK
1,000 geometries reused only twice (1,000 draws) => NOT OK
 = 1,041 draws with 1140 objects in memory
 
The solution could be to set a threshold and if a geometry is reused less than the threshold (3, 4, or 5, let's benchmark it), duplicate it.

This way, the draw of my previous model would be:
10,000 + 2 x 1,000 geometries in 1 draw
40 geometries reused 100 times in 40 draws
= 41 draws with 1240 in memory.

If I'm wrong, I'd really like another explanation 😅
