### ISSUE TITLE
Integration with React

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#79]
Hi.

I'm trying to integrate this sdk into a React application. I've gone through the issues and documentation but haven't found a solution to my problem.

Actually I've not gotten too far because merely trying to import the Viewer gives me the following errors:

```
./src/xeokit-sdk/src/viewer/scene/math/math.js
  Line 44:    'vec4CacheLen' is not defined  no-undef
  Line 44:    'vec4CacheLen' is not defined  no-undef
  Line 2632:  'v' is not defined             no-undef
  Line 2633:  'v' is not defined             no-undef
```

Here's what I've done:

I downloaded the source code from this repo, extracted it to my React app's src folder, so this is kind of the folder structure I have right now:
{react app path}/src/xeokit-sdk

In my App.js, I try to import the Viewer module as such:

```js
import {Viewer} from './xeokit-sdk/src/viewer/Viewer.js'
```

And I'm presented with the error msg posted above.

Maybe it's a really trivial thing I'm missing here, I apologize if so, but could anyone please suggest a fix for this?

Cheers.

**Comment by xeolabs** [comment]
Thanks - I just patched math.js in master - try the master branch now - https://github.com/xeokit/xeokit-sdk/commit/703d348c1fa8eca4098e40a2c3b5b1b924e80204

**Comment by barnabasmolnar** [comment]
Hey, thanks for the quick response! That particular error went away, indeed. :+1: 

However, I'm now greeted by this:

```
./src/xeokit-sdk/src/viewer/scene/scene/Scene.js
  Line 982:  Your render method should have return statement  react/require-render-return
```

So my assumption here is that the method name "render" is tripping up React because it expects anything with a render method to return some JSX. When I change the method name in the Scene.js file to something else, this error indeed goes away, although of course now the rest of the xeokit stuff won't work because the render method is referenced throughout it all over I'd imagine.

Any ideas perhaps on how to get around this particular issue?

**Comment by chloesun** [comment]
@barnabasmolnar I'm super new to this library and  thanks for your instruction! I was trying to do the same - integrate this sdk with React app. I was able to fork, delete unnecessary folders and install with npm from GitHub, my question is how to use this properly in the React class component syntax. Here is the code that I tried to test to display a GLTF file:
```
import * as React from 'react';
import { Viewer } from 'xeokit-sdk/src/viewer/Viewer';
import { GLTFLoaderPlugin } from 'xeokit-sdk/src/plugins/GLTFLoaderPlugin/GLTFLoaderPlugin';

const viewer = new Viewer({
  canvasId: 'myCanvas'
});

const gltfLoader = new GLTFLoaderPlugin(viewer);

const model = gltfLoader.load({
  id: 'testModel',
  src: '../../../assets/gltf/test.gltf',
  edges: true
});

export default class GltfViewer extends React.Component {
  render() {
    return <div>{model}</div>;
  }
}
```
The error I got is `parser.ts:44 Uncaught Canvas not found: 'myCanvas'`
Can you share some insights how did you use this sdk? Thank you!

**Comment by barnabasmolnar** [comment]
@chloesun Sure thing. Head on over to https://github.com/bimspot/xeokit-react-demo to check out a couple of working examples. Have a look at the GLTFViewer component in the src directory.

We're working on integrating the sdk with React in a nice and reusable way. We're hoping to add more core features from the sdk as time goes on but what we already have here may be of help to you.

A quick recap of the key points:

- you want to render a canvas, not the model object itself
- you want to pass the canvas id to the Viewer
- in order to be able to do that, the DOM needs to be ready (=you need a canvas element to be in the DOM with the specified ID), so you should set up all this logic in the componentDidMount lifecycle method (see more on componentDidMount here: https://reactjs.org/docs/react-component.html#componentdidmount; note the following passage: ```Initialization that requires DOM nodes should go here```. This is exactly what we need.)
- and, as mentioned before, you want to render a canvas element with the appropriate id (the one you passed to the Viewer)

And that's the gist of it.

Another thing perhaps: you don't necessarily have to save your model to a variable if you're not planning to call some of the sdk's built-in methods/event on it. But don't quote me on that.

Hope this helps somewhat, and do let me know how you're getting along. :+1:

**Comment by chloesun** [comment]
@barnabasmolnar Thanks again for sharing this example! I downloaded your project and it works fine, and I almost copied your GltfViewer component and tried to implement within my app.  the `canvas` didn't render properly with `width` and `height` both being `0`, I even copied the same models from your example just to recreate the scenario, the only difference is I don't use bootstrap for style. Here is my code and some screenshots:

DetailViewer which builds on top of GltfViewer component exactly the same from your example:
```
import * as React from 'react';
import GltfViewer from '../GltfViewer';
import { Button } from 'antd';
import './DetailViewer.scss';
import { sampleModel1 } from './Models';

const sampleCameraProps = {
  eye: [-10, 0, 0],
  look: [-1, 0, 0],
  up: [0, 1, 0],
  zoom: -10
};

export default function DetailViewer({ handleClose, displayDetailViewer }) {
  const showHideClassName = displayDetailViewer
    ? 'detailViewer display-block'
    : 'detailViewer display-none';

  return (
    <div className={showHideClassName}>
      <Button style={{ marginLeft: 850, position: 'fixed' }} icon="close" onClick={handleClose} />
      <GltfViewer
        canvasID="canvas-1"
        width={900}
        height={1200}
        models={[sampleModel1]}
        camera={sampleCameraProps}
      />
    </div>
  );
}
```
`Models.tsx` saved under the same folder as DetailViewer component
```
export const sampleModel1 = {
  id: 'duplex',
  src: '../../../assets/models/duplex/scene.gltf',
  metaModelSrc: '../../../assets/metaModels/duplex/metaModel.json',
  edges: true
};

export const sampleModel2 = {
  id: 'conferenceCenter',
  src: '../../../assets/models/OTCConferenceCenter/scene.gltf',
  metaModelSrc: '../../../assets/metaModels/OTCConferenceCenter/metaModel.json',
  edges: true
};
```
![viewer](https://user-images.githubusercontent.com/13730281/59359565-8c991280-8cfc-11e9-83d3-b44b482a41fd.PNG)
As you can see the props of `width` and `height` are `0`, not the value I set up from the DetailViewer component, and there is no error messages from console.

I'm so confused about why this happens, can you take a look at the way I implement? Thank you!

**Comment by barnabasmolnar** [comment]
@chloesun 

- Is your assets directory inside the public directory? If not, can you please try moving all the model related assets in there? I seem to recall receiving a similar error when I didn't have all the model files in the public dir
- As for the canvas not rendering with the proper width & height: I see that you're doing some conditional css class application on the parent div and I assume that you're initially applying the display: none rule. If something is set to display: none, it won't have any width or height in the DOM so my guess would be that, irrespective of the values you're passing through as props, your canvas is always going to have 0 for both properties. And when you click a button or something and apply the display block class, that won't trigger a component rerender (you're only changing a css value), so you'll be left with the initial 0 values.

You might want to look into a solution where you do some conditional rendering... on the whole component, that is. So instead of always having it in the DOM and just hiding/showing it with css, you'll probably want to have some sort of state based on which you'll render the component conditionally.

This is a problem that we might have to tackle ourselves at some point and I'll certainly let you know if/once we have implemented it as a feature in our project.

**Comment by chloesun** [comment]
@barnabasmolnar Thanks for your speedy response!  I moved the files to `public` directory, and without conditional rendering, it works!
With `public` directory, with conditional rendering, here is the error look like:
![console](https://user-images.githubusercontent.com/13730281/59373560-e824c980-8d17-11e9-81f9-9d8ed9ca1a3c.PNG)
And do you know what is this <div> element which is `hidden`?
![error](https://user-images.githubusercontent.com/13730281/59373573-efe46e00-8d17-11e9-9b11-23e212ac17aa.PNG)

I will try to refactor my component to see if I can make conditional rendering working, and I will keep you posted. Thanks!

**Comment by barnabasmolnar** [comment]
@chloesun 

Nice, glad to hear you're making progress! I think that div is just the container for the loading spinner.

**Comment by chloesun** [comment]
@barnabasmolnar update on my refactor progress.
```
import * as React from 'react';
import GltfViewer from '../GltfViewer';
import { Button } from 'antd';
import './DetailViewer.scss';
import { sampleModel1 } from './Models';
import faker from 'faker';

const sampleCameraProps = {
  eye: [-10, 0, 0],
  look: [-1, 0, 0],
  up: [0, 1, 0],
  zoom: -10
};

export default function DetailViewer({ handleClose, displayDetailViewer }) {
  const view = (
    <React.Fragment>
      <Button
        style={{ marginLeft: 850, marginTop: 15, position: 'fixed' }}
        icon="close"
        onClick={handleClose}
      />
      <GltfViewer
        canvasID={faker.name.findName()}  // a hack to generate different id to rerender gltf model
        width={900}
        height={1200}
        models={[sampleModel1]}
        camera={sampleCameraProps}
      />
    </React.Fragment>
  );

  const conditionalView = displayDetailViewer ? view : null;

  return <div className="detailViewer">{conditionalView}</div>;
}
```
With a static `canvasID`, this renders at the first time, but when you close the view and reopen, it won't render. 
![view](https://user-images.githubusercontent.com/13730281/59448379-fe439000-8dd2-11e9-9022-59bb90af9812.gif)

So I used a hack like this `canvasID={faker.name.findName()}` to generate a random string and it reloads every time I click `check the model`, it's not an ideal solution, and I wonder if you have a better solution to reload the model.

**Comment by barnabasmolnar** [comment]
@chloesun 

I'll have to test it myself before I can give you a definitive answer but I might have an idea what's happening.

You're now conditionally mounting and unmounting the viewer onto/from the DOM.
When you initially mount it, stuff works fine as expected.
When you unmount it (=close the viewer), however, the viewer object (the one initialised with `new Viewer`) probably doesn't get destroyed and when you try to remount (=reopoen) it, everything in componentDidMount gets executed.
So it tries to create a new Viewer with the same static canvasID that was initially passed in. But since the viewer didn't get cleaned up, it probably all goes haywire there.

I believe the viewer object has a destroy method or something similar, and you probably want to add a componentWillUnmount lifecycle method to the GLTFViewer component in which you destroy/clean up the viewer.

In fact, this is something that I'll almost surely include in our package sometime soon. Keep an eye out for updates at our repo but I'll also try and let you know here once I've implemented this functionality.

Oh and btw, thank you for the progress updates, it's nice to see someone else is interested in this stuff! And as you can already see, just by experimenting with it and letting us know how it goes, we can get a better sense of the future issues & challenges ahead of us.

So yeah, cheers! :+1:

**Comment by chloesun** [comment]
@barnabasmolnar 
Thanks! I will follow your update and try to implement the `componentWillUnmount` lifecycle method in the meantime. Keep up the good work and look forward to collaborating more in the future!
