### ISSUE TITLE
Accelerate XKTLoaderPlugin using Web workers

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#790]
### Just an idea

* Move AJAX request and XKT parsing into a Worker.
* Within the worker, the parser builds an object similar to PerformanceModel, which we'll call WorkerPerformanceModel for discussion.
* Once built, the worker packs all the VBO data in the WorkerPerformanceModel into shared buffers, which are returned to XKTLoaderPlugin, running in the main process.
* In the main browser process, XKTLoaderPlugin then creates a PerformanceModel from the shared buffers. This would be super fast - little more than allocating a bunch of WebGL VBOs around the arrays in the shared buffers, and instantiating a whole lot of PerformanceNodes and Entities.
* The shared buffers would also contain some arrays that contain other bookkeeping data collected while parsing the XKT, which PerformanceModel also initializes itself from.

**Comment by Amoki** [comment]
Is this done or dropped?

**Comment by hamza-hajji** [comment]
@xeolabs Sorry for reviving this 2 years later, is there a plan to support it for GLB? Is there a way to use web workers on my side without official library support? Thanks
