### ISSUE TITLE
Better customization of the TreeView

### ISSUE THREAD

**Issue by pierluigi-iezzi** [xeokit/xeokit-sdk#806]
I'm working with an IFC file which has 4 storeys ("Piano" in picture below), inside of each of them every object is grouped by their type. EG: If i expand the category Doors ("Porte" in the picture below), I can see every door on that Storey.
![image](https://user-images.githubusercontent.com/73798010/152937192-ca279c51-e0ed-4843-95a0-06d4b706dac5.png)

I can't get it working like this with TreeViewPlugin. If I set `hierarchy:"storeys"` there isn't the possibility to expand it at all:
![image](https://user-images.githubusercontent.com/73798010/152937949-651e97bf-4f8d-42cc-829d-9290f0b5398e.png)

If I set  `hierarchy:"containment"` the storeys are shown properly, but the elements of the same kind are not grouped by (for example, the doors in the picture below)
![image](https://user-images.githubusercontent.com/73798010/152938051-67a2d620-4428-481e-ba03-39168967d110.png)

Here's the code:
![image](https://user-images.githubusercontent.com/73798010/152938346-c42d984d-2181-457c-8971-942e788b43c4.png)

Can I get some help with this? Thanks in advance!

**Comment by xeolabs** [comment]
I'm not quite sure why you're getting a single node with title "IfcBuilding" in storeys mode - sounds like a bug!
I can't reproduce anything on my end, but I'll reopen if you're still experiencing it and can reproduce on your end with sample IFC etc.
