### ISSUE TITLE
How to look up mesh triangle number

### ISSUE THREAD

**Issue by kingwangwang** [xeokit/xeokit-sdk#807]
i want to know my model's triangle number,
Can someone tell me how to fix it？
thanks

**Comment by Amoki** [comment]
`Object.values(viewer.scene.objects).map(obj => obj.meshes).flat().map(mesh => mesh.numTriangles).reduce((num, acc) => acc += num)`

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。
祝您生活愉快。
BY WJC

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。
祝您生活愉快。
BY WJC
