### ISSUE TITLE
Data texture based scene representation

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#811]
Couldn't avoid to make a bit of pre-noise here, and feel really excited about it 😄 

You @xeolabs already know what is it about 🥳

**Comment by simplylogicninjas** [comment]
@tmarti Can you provide some more information? We are curious about it :-)

**Comment by tmarti** [comment]
## Before

72 M non-instanced triangles

<img width="552" alt="image" src="https://user-images.githubusercontent.com/2405414/158989380-a6d79fba-8d82-4824-a01f-48bb0712fe70.png">

55.8M non-instanced triangles

<img width="533" alt="image" src="https://user-images.githubusercontent.com/2405414/158989439-e278afa3-0305-41bb-b423-63fb69d57e03.png">

## What is coming ⚙️🕺🏻

72M non-instanced triangles

<img width="549" alt="image" src="https://user-images.githubusercontent.com/2405414/158989556-1547608b-58dd-489d-b758-626d82111d6f.png">


55.8M non-instanced triangles

<img width="550" alt="image" src="https://user-images.githubusercontent.com/2405414/158989509-02a93e89-dae3-4ae6-963f-6bfed40a46b6.png">

**Comment by tmarti** [comment]
😉 https://github.com/xeokit/xeokit-sdk/pull/824

**Comment by xeolabs** [comment]
See also: https://github.com/xeokit/xeokit-bim-viewer/issues/137

**Comment by tmarti** [comment]
Took a while but super glad this is about to land! 🕺

**Comment by xeolabs** [comment]
* [DataTexure demo in BIMViewer](https://xeokit.github.io/xeokit-bim-viewer/app/index.html?projectId=OTCConferenceCenterDataTex&tab=storeys)

[Screencast from 12.05.2023 03:45:05.webm](https://github.com/xeokit/xeokit-sdk/assets/83100/58a21905-3890-4a62-be11-ab2ae1d445f0)
