### ISSUE TITLE
Possibility to show a map tiles on a Mesh/Image layer

### ISSUE THREAD

**Issue by simplylogicninjas** [xeokit/xeokit-sdk#815]
I have a question if the following is possible with Xeokit currently.

We want to load specific GeoJSON files and we want to position this objects on a "tiled" map, for example tiles from Mapbox.

Kind of this example: https://xeokit.github.io/xeokit-sdk/examples/#ImagePlane_groundPlane

But then dynamically with tiled images and with correct coordinates

**Comment by xeolabs** [comment]
Yes this is certainly possible, via custom application code on top of xeokit SDK - the SDK has all the extension points required AFAIK. 

Can't really offer much more info though, without embarking on analysis/design/development.
