### ISSUE TITLE
.xkt   Partial model offset   

### ISSUE THREAD

**Issue by cikke** [xeokit/xeokit-sdk#818]
![1](https://user-images.githubusercontent.com/25577460/157829819-3999926a-5b5f-4fe0-93b1-eeb1acb94a2b.png)
![2](https://user-images.githubusercontent.com/25577460/157829828-adbe8963-53cc-40be-a6f5-f1ac3d4768ff.png)

**Comment by cikke** [comment]
IFC normal

**Comment by xeolabs** [comment]
Is this with @xeokit/xeokit-sdk@2.2.5-performance-textures-beta?

This is an "internal R&D release" that's not ready for production yet.

We have however fixed that particular bug though - see @xeokit/xeokit-sdk@2.2.5-performance-textures-beta-2
