### ISSUE TITLE
Update BIMServerLoaderPlugin for BIMServer v1.5.147

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-sdk#83]
At the time that I developed [BIMServerLoaderPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/BIMServerLoaderPlugin/BIMServerLoaderPlugin.js~BIMServerLoaderPlugin.html), BIMServer 1.5.X was still in development, and so the BIMServer 1.5.x client-server protocol was also frequently changing.

Therefore, BIMServerLoaderPlugin currently only works with [BIMServer v1.5.120](https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.120).

However, with [BIMserver 1.5.147](https://github.com/opensourceBIM/BIMserver/releases/tag/v1.5.147) now released, as the stable release candidate, I can now update BIMServerLoaderPlugin for the latest protocol changes.

**Comment by david-San** [comment]
Has there been any progress on this ? There are some bugs on the BIMserver that have been corrected in latest versions but it completely breaks XeoKit.

**Comment by xeolabs** [comment]
Not yet, it's on the queue. Currently prioritizing licensee requirements. I will post an update here when this is done.

**Comment by xeolabs** [comment]
Duplicate of https://github.com/xeokit/xeokit-sdk/pull/270, which has now been fixed.
