### ISSUE TITLE
can't able to view the ifc 

### ISSUE THREAD

**Issue by Arunvishnu123** [xeokit/xeokit-sdk#840]
I am using the below code but I can't able to view the bim model

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>xeokit Example</title>
    <style>
        body {
            margin: 0;
            width: 100%;
            height: 100%;
            user-select: none;
        }

        #myCanvas {
            width: 100%;
            height: 100%;
            position: absolute;
            background: lightblue;
            background-image: linear-gradient(lightblue, white);
        }
    </style>
</head>

<body>
    <canvas id="myCanvas"></canvas>
</body>
<script id="source" type="module">

    import { Viewer, WebIFCLoaderPlugin } from
        "https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk/dist/xeokit-sdk.es.min.js";

    const viewer = new Viewer({
        canvasId: "myCanvas",
        transparent: true
    });

    viewer.camera.eye = [-3.933, 2.855, 27.018];
    viewer.camera.look = [4.400, 3.724, 8.899];
    viewer.camera.up = [-0.018, 0.999, 0.039];

    const webIFCLoader = new WebIFCLoaderPlugin(viewer, {
        // Path to web-ifc.wasm, which does the IFC parsing for us
        wasmPath: "https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk/dist/"
    });

    const model = webIFCLoader.load({ // Returns an Entity that represents the model
        src: "./Duplex.ifc",
        edges: true
    });

</script>

</html>

I am using vue for this project but it is not working in vue so i just tried to test without any framework but the result is same 
can anyone help to solve the issue

**Comment by Amoki** [comment]
`src: "./Duplex.ifc"`
Is the file `Duplex.ifc` hosted alongside your HTML page?

**Comment by Arunvishnu123** [comment]
Yes both are in the same folder
This is the error i got 

"Access to XMLHttpRequest at 'file:///C:/Users/ARUN/OneDrive/Desktop/ccc/Duplex.ifc' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.

**Comment by Arunvishnu123** [comment]
issue solved thank you

**Comment by Bartifle** [comment]
> issue solved thank you

Hi,

Can you explain how you solved it ? I have the same problem.
By the way I can't understand th custom data source thing is it linked with this problem ?
