### ISSUE TITLE
Unsupported .XKT file version: 1329865020 - this XKTLoaderPlugin supports versions 1,2,3,4,5,6,7,8,9

### ISSUE THREAD

**Issue by Arunvishnu123** [xeokit/xeokit-sdk#844]
I tried to integrate the xeokit to the vue.js application but I got this error could help to solve this issue

**Comment by Arunvishnu123** [comment]
Unsupported .XKT file version: 1329865020 - this XKTLoaderPlugin supports versions 1,2,3,4,5,6,7,8,9

**Comment by Amoki** [comment]
This means the file is not an XKT. Maybe an XKT but gzipped, maybe a glTF, maybe another file

**Comment by xeolabs** [comment]
Hi, what were the steps
