### ISSUE TITLE
Match mouse orbit / rotate rate to canvas dimensions

### ISSUE THREAD

**Issue by magnayn** [xeokit/xeokit-sdk#846]
**Describe the bug**
As described in https://github.com/xeokit/xeokit-sdk/issues/189

It looks like a fix was created in 2019, but then reverted.

When I have a canvas which is mostly full height but only ±40% width, I can set the dragRotationRate, but this is either unacceptably fast in the horizontal direction (at "360" it spins 20+ times over the width), or unacceptably slow in the vertical direction.

**Comment by xeolabs** [comment]
Fixed in 

* @xeokit/xeokit-sdk 2.3.0-beta-21
* @xeokit/xeokit-bim-viewer 2.4.7-beta-7
