### ISSUE TITLE
Load ifc model Viewer

### ISSUE THREAD

**Issue by KiraL91** [xeokit/xeokit-sdk#848]
**Load ifc model with a service**

Is it possible to load an IFC file without using a Viewer element? I'd like to load Ifc files with an Angular's service, which do not have visual interface so, i.e., all ifc's MetaObjects can be can be accessed from other app components.

As far as I can see, the Viewer is requiered since the IfcLoader is a plugin, and the Viewer needs to be loaded in a Html element.

Thanks in advanced

**Comment by xeolabs** [comment]
No, no possible, sorry - this is outside the scope of xeokit - IFCLoaderPlugin is only designed to populate a xeokit Viewer with its output.
