### ISSUE TITLE
is it possible to move objects in the .ifc file using the xeokit library

### ISSUE THREAD

**Issue by Arunvishnu123** [xeokit/xeokit-sdk#852]
In the BIM model , furniture are there. Is this possible to position the furnitures in the bim model

For example select one furniture and drag that furniture to new position using the xeokit

**Comment by Amoki** [comment]
You could move them in the viewer, but their new position won't be saved in the IFC file.

**Comment by Arunvishnu123** [comment]
model.scene.objects.geometry - is this the way to move the objects . 

After that can I store the new position in the database and each time when I call the model . then the new position of the particular object should updated

is this possible
