### ISSUE TITLE
how to disable sectionPlane's control rotation

### ISSUE THREAD

**Issue by hefujie1988** [xeokit/xeokit-sdk#858]
i only need to pull control on x, y, z directions

**Comment by xeolabs** [comment]
Sorry, this is not a feature of the ````SectionPlanesPlugin````.

However xeokit SDK is designed to be extensible, so you should be able to customize it with your own SectionPlane controls. 

We can't help with the implementation of that however, but you're welcome to contribute.

Note that [gemini-viewer](https://github.com/pattern-x/gemini-viewer), built on xeokit, has a "section box" which you find useful.
