### ISSUE TITLE
Documentation regarding input events

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#87]
Hello there!

Please consider updating/expanding the documentation regarding input events.

Let me give you an example of what I mean:

I was trying out the picking/highlighting feature and largely followed one of the examples from here: https://xeokit.github.io/xeokit-sdk/examples/#picking_canvas_mesh_colorize

In the source, there's this line:

```viewer.scene.input.on("mousemove", function (coords) {}```

So in this example the highlighting happens on basically a mouse hover. That's fine but what if I want it to happen on a click event for instance? I managed to figure out that I need to pass in the `mouseclicked` event but it wasn't actually documented anywhere as far as I can tell.

For reference and a bit of context, this was my flow of going through the docs:

- as per the example, the input method is on the scene object, so I looked for the Scene section in the docs and found the input subsection here: https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/scene/Scene.js~Scene.html#instance-member-input
- seeing that there's no list of input events here, I hit up the Input section in the docs: https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/input/Input.js~Input.html
- I scrolled down and found a couple of mouse events but neither `mousemouse` nor `mouseclicked` was among them

Now I did find these in the source file but I think it would be a good idea to explicitly list and document all possible input event types on the docs pages too.

**Comment by chloesun** [comment]
It would be nice to have a feature that you can trigger an event from another component to pick/highlight the model.

For example, I have a `table` component that is composed of the entity ids, and while clicking one of the table cell can trigger the highlight of the entity of Gltf model.
