### ISSUE TITLE
Unable to load models

### ISSUE THREAD

**Issue by yinonv** [xeokit/xeokit-sdk#877]
**Describe the bug**
Unable to load models

**To Reproduce**
1. Use xeokit version 2.3.0-beta-16
2. Load a model

**Expected behavior**
A model should be loaded and presented

**Desktop:**
 - OS: Windows 10
 - Browser: Opera 
 - Browser Version: 88.0.4412

**Additional context**

Error log:
```
TypeError: Cannot read properties of null (reading 'id')
  at stateSortCompare
```

**Comment by xeolabs** [comment]
Hi, which kind of model are you loading - could you provide a code snippet? 
Thanks

**Comment by yinonv** [comment]
i'm using the `XKTLoaderPlugin` to load a xkt model.

```
const viewer = new Viewer({
  canvasElement: canvas,
});
const loader = new XKTLoaderPlugin(viewer);
const model = loader.load({
  id: 'model',
  src: 'model.xkt',
  edges: true,
});

**Comment by xeolabs** [comment]
I can't reproduce this issue, all tests are working OK for me.
Can you provide a complete example that reproduces this issue?
Is there a live example that no longer works?

**Comment by yinonv** [comment]
Found some more information regarding the error.
This logs also appears:
![image (1)](https://user-images.githubusercontent.com/57749510/174760291-b4d555a8-28a8-4f40-853d-ab6b6bcd8a24.png)

**Comment by yinonv** [comment]
This was replicated also with edge and chrome.
Trying to figure out what other env differences created this behavior.

**Comment by yinonv** [comment]
not it doesn't:
![image](https://user-images.githubusercontent.com/57749510/175005369-21831e45-90cb-43cc-8f29-2a23ddc05ad3.png)

is there any way to get an indication of this before the viewer crashes ?

**Comment by yinonv** [comment]
xeokit use to work with this computer in previous versions (2.2.3).
is there a change of requirements in the new versions ?

**Comment by xeolabs** [comment]
Aha yes - we switched from WebGL1 to WebGL2, possibly that's why - hope you can get your machine to support it!

**Comment by yinonv** [comment]
ok,
from which version the switch was made?
is there a possibility of supporting also "WebGL1" in the newer versions? something like having the option to choose if to use "WebGL1" or "WebGL2".

**Comment by xeolabs** [comment]
Switch was made in 2.3 - it's currently not on our roadmap to fall back to WebGL1
