### ISSUE TITLE
Possible rendering bug

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#88]
Hi,

I've come across what I believe to be a bug. I've got a .gltf file that is not being rendered properly.

Please find the file here:

https://gist.githubusercontent.com/barnabasmolnar/848a36be58d7ab7d29e402a9de399fc2/raw/eb6e2bfb173da4841289b404bdec35d6fd6a451b/test.gltf

If you do a search for `1BBNvXyaj5$uVtIFUcr640`, that's the node/mesh (sorry, not quite sure about the proper terminology here) that's not being drawn on the canvas at all.

I've tried it with CesiumJS, three.js and even the xeogl library and they all render that wall just fine, so the issue appears to be limited to the xeokit-sdk.

Would appreciate if you could have a look. :+1:

**Comment by xeolabs** [comment]
Hi, looks like this is the same issue as one I just fixed: https://github.com/xeokit/xeokit-sdk/issues/89

If you could confirm, then I'll close this ticket.

Before the fix:

![Screenshot from 2019-06-13 13-27-34](https://user-images.githubusercontent.com/83100/59429054-3224b280-8ddf-11e9-8fc6-539e0b5edae0.png)

After the fix:

![Screenshot from 2019-06-13 13-28-06](https://user-images.githubusercontent.com/83100/59429067-36e96680-8ddf-11e9-8be3-2719d3113cbf.png)

**Comment by barnabasmolnar** [comment]
Yep, just tested it, appears to be fixed. Thank you! :+1:
