### ISSUE TITLE
Type properties missing

### ISSUE THREAD

**Issue by Gipfel** [xeokit/xeokit-sdk#896]
**Is this feature critical for your commercial enterprise?**
Yes, the properties of an metaObject are not enough. We would need the properties of a type (for example a IfcWall)

**Is your feature request related to a problem? Please describe.**
It is a important and missing feauture.

**Describe the solution you'd like**
Inside the metaobjects below metaObjectsByType properties for that Type.

**Comment by xeolabs** [comment]
Sounds like you need property sets - see here: https://www.notion.so/xeokit/Scene-Representation-and-Metadata-936fa040f4e9417bb83cc04136ca0b8d

**Comment by Gipfel** [comment]
> Sounds like you need property sets - see here: https://www.notion.so/xeokit/Scene-Representation-and-Metadata-936fa040f4e9417bb83cc04136ca0b8d

Thank you for your quick response. Sorry, but I couldn't find that there. I get there that my wall is a IfcWall, but I would like to get informations about what type of ifcWall that is (IfcWallType) and get it's properties.
