### ISSUE TITLE
Feature request: tool to find objects interesting a given 3D location

### ISSUE THREAD

**Issue by elyrank** [xeokit/xeokit-sdk#898]
I need to have a way to check if a specific point (or range) collides with an object in the model.

I want to be able to get the objects that collided with the location I provided.

something like this: 
`scene.getObjectsInRange([0,0,0], [1,1,1])`
and it would return a list of objects that are (partially) within that range

**Comment by xeolabs** [comment]
I just added a marquee selection tool to xeokit-bim-viewer - perhaps this can help: https://github.com/xeokit/xeokit-bim-viewer/issues/132
