### ISSUE TITLE
[question] : xktLoader vs webifcLoader

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#899]
hii, i have a question about the use of xktloader and webifcloader, i know that webifcloader is used for small to large ifc models, my question is when is an ifc file considered large, and is it based of file size or what criteria ?

**Comment by lanjoni** [comment]
By the amount of detail your model can contain. To minimize the impacts that a high detail rate can have, try using the template converter offered in the bimspot repository: https://github.com/bimspot/xeokit-converter
