### ISSUE TITLE
Reset BCF viewpoint

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#90]
Hello there!

According to the [documentation](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/BCFViewpointsPlugin/BCFViewpointsPlugin.js~BCFViewpointsPlugin.html#instance-method-setViewpoint), the setViewpoint method on the BCFViewpointsPlugin accepts a JSON viewpoints object or a `"reset"` string which `clears SectionPlanes, shows default visible entities and restores camera to initial default position`.

I've looked in the source however and sadly couldn't find this feature.

It would actually be really handy to have such a functionality available. Any plans to implement it?

Cheers!

**Comment by xeolabs** [comment]
Hi, yip, on the queue for this week or next week.
