### ISSUE TITLE
Add gamma correction to colorTexture rendering mode

### ISSUE THREAD

**Issue by kikunota** [xeokit/xeokit-sdk#900]
**Description:**
We exported the textured mesh model in GLB format and loaded the model using GLTF loader. We were able to view the model; however, the texture of the model looks too white/bright and I can't seem to adjust the gamma value. When I export the GLB format with texture image data as JPEG format using blender, the texture and gamma seems to work fine. My prediction is that the current GLTF loader doesn't seem to parse the texture image of photogrammetry model correctly when the texture image is formatted other than JPEG format.

**To Reproduce:**
Photogrammetry model exported directly from LiDAR app.
The model that doesn't show the color correctly.
[sample_directlyExported.zip](https://github.com/xeokit/xeokit-sdk/files/9185485/sample_directlyExported.zip)
(sample_directlyExported.glb)

Photogrammetry model exported with texture image as JPEG format.
When we modify the export setting with Blender, it shows the color correctly.
(https://drive.google.com/file/d/1ezPtWjYQmVU9z37PIfSz9enj8ddcfVEL/view?usp=sharing)
(sample_jpegTextureImage.glb)

Minimum viewer setting
[index.zip](https://github.com/xeokit/xeokit-sdk/files/9185509/index.zip)
(index.html)

**Expected behavior:**
The color of "sample_directlyExported.glb" should be same as "sample_jpegTextureImage.glb". The model should not look too bright or white on "sample_directlyExported.glb" model.

**Screenshots:**
Photogrammetry model exported directly from LiDAR app.
The model that doesn't show the color correctly.
![sample_directlyExported](https://user-images.githubusercontent.com/44632198/180894517-70c46073-6ed6-4fa5-b6f8-7fe76f942481.png)
(sample_directlyExported.png)

Photogrammetry model exported with texture image as JPEG format.
The model that shows the color correctly.
![sample_jpegTextureImage](https://user-images.githubusercontent.com/44632198/180895050-cae3c5f0-7d98-4d27-90e6-8a633e7e4200.png)
(sample_jpegTextureImage.png)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: npm Xeokit SDK (npm/@xeokit/xeokit-sdk@2.3.0-beta-22)

**Comment by kikunota** [comment]
@xeolabs  Could you take a look at this issue?

**Comment by xeolabs** [comment]
@kikunota gamma correction is currently only implemented for xeokit's physically-based (PBR) rendering mode.

To enabled gamma correction, we need ````pbrEnabled:true````, like below:

````javascript
const viewer = new Viewer({
        canvasId: "myCanvas",
        transparent: true,
        pbrEnabled: true,
        colorTextureEnabled: false
    });

    viewer.scene.gammaInput = true;
    viewer.scene.gammaOutput = true;
    viewer.scene.gammaFactor = 2.4;
````

PBR rendering is more expensive than basic color texture though, so I'm going to now see if it makes sense to support gamma correction for basic color texture mode. I need a day or two for that, because it does need a little documentation update/planning.

In the meantime, enabling PBR as shown above should be an OK workaround, since your models are not too big.

**Comment by xeolabs** [comment]
@kikunota I just added gamma correction for ````colorTextureEnabled```` mode in @xeokit/xeokit-sdk-2.3.0-beta-32

Note that ````colorTextureEnabled```` is more efficient than ````pbrEnabled````, which uses special physically-based rendering, which is overkill for photogrammetry. So, please continue using ````colorTextureEnabled```` instead of ````pbrEnabled````, for this type of model.
