### ISSUE TITLE
no control over model load request options

### ISSUE THREAD

**Issue by ohadgilboa888** [xeokit/xeokit-sdk#901]
**Describe the bug**
when loading a model with `xeokit.XKTloader.load()`, i don't have any control on the fetch request options.
for example i can't add/edit headers, credentials

**Expected behavior**
control over the model load request options

**Comment by xeolabs** [comment]
The ````load```` method allows you to provide a pre-loaded XKT array buffer as an ````xkt```` parameter, so you could manage the fetch yourself, which would give you that control. You can also configure the loader with your own data access strategy, like this one: https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/XKTLoaderPlugin/XKTDefaultDataSource.js
