### ISSUE TITLE
Problem converting

### ISSUE THREAD

**Issue by Drazing** [xeokit/xeokit-sdk#902]
Hello everyone, I have a problem converting a .ifc

I did installed xeokit-convert following the guide from over there : https://xeokit.github.io/xeokit-convert/docs/ .
The thing is that it doesnt seems to fetch something as you can see below:
![Problem](https://user-images.githubusercontent.com/110114285/181279854-94f65011-78b1-47ac-a188-b8b40bc53315.png)

If someone has a fix for it or know from where the problem is that would be really cool! 👍

**Comment by lanjoni** [comment]
Try using the converter offered by bimspot: https://github.com/bimspot/xeokit-converter

Use dockerfile to configure installation links on your machine. Requires: Ubuntu 18/20 and dotnet runtime 3.1.
