### ISSUE TITLE
IfcSpace Elements are not visible

### ISSUE THREAD

**Issue by turuncgil** [xeokit/xeokit-sdk#907]
Hello, 
Even though I created new object defaults and made defined IfcSpace as visible, IfcSpace Elements are not visible. I tried all the methods, and I am certain my model has space geometry inside. What is the solution to make it visible, further than the methods on XKTloader tutorial ?

**Comment by DB-EC-Hamburg-BIM** [comment]
I don't think thats an XKTloader problem. I think there is a problem in the xkt convertion. in xkt v8 IFC Space is visible. See my post at the xeokit-converter
https://github.com/xeokit/xeokit-convert/issues/33

**Comment by turuncgil** [comment]
Thank you so much, this is correct, but how can I convert it to V8 model ? I tried -v but it is giving me an output only.

**Comment by DB-EC-Hamburg-BIM** [comment]
I don't know how to convert in an old version. I hope this bug get fixed in xkt v10. Sorry
