### ISSUE TITLE
Fix BCF download button on BCF Loading examples

### ISSUE THREAD

**Issue by lanjoni** [xeokit/xeokit-sdk#909]
**The bug**
I'm having problems using the tool to save the BCF viewpoint. Basically, there is no change of viewpoint values when I walk through the model, select objects or make any kind of modification: it simply saves only the initial viewpoint.

**To Reproduce**
1. Go to BCF_LoadViewpoint_MultipleModels example;
2. Click on Download BCF Viewpoint after changing the view or performing some action;
3. Make another change, and try downloading again;
4. Note that there is no data change for viewpoint;

**Expected behavior**
It was expected that there would be a change to the current viewpoint, so that it is possible to save a viewpoint.

**Desktop:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 103.0.1 (64-bit)

**Comment by xeolabs** [comment]
It was only a broken button in some examples - fixed in master now
