### ISSUE TITLE
Typos in Guides

### ISSUE THREAD

**Issue by alabrazi** [xeokit/xeokit-sdk#91]
1. at "https://github.com/xeokit/xeokit-sdk/wiki/Viewing-Models-from-BIMServer"
BIMServerLoader is not defined anywhere: fix -> rename the variable(delete Plugin) as shown 
<img width="785" alt="Screenshot 2019-06-18 at 10 39 55" src="https://user-images.githubusercontent.com/7549404/59662577-ec3c6580-91b5-11e9-9898-432a09a1381a.png">
2. at "https://github.com/xeokit/xeokit-sdk/wiki/Viewing-BIM-Models-Offline"
this line may be wrong 
const metaObject = metaModel.metaObjects["3NI6Sp$yf87eKCx0T$FWj3"];
It worked when it is changed to
const metaObject = metaModel.metaScene.metaObjects["3lMSBJ1J9AUQZulZNJl9KP"];

Also the GUIDs numbers in the guide may not be correct.

**Comment by xeolabs** [comment]
Thanks very much! I've fixed those JS examples. Don't worry about the GUIDs in those examples - they're just randomly picked for that example.
