### ISSUE TITLE
Fix occlusion shader error when logarithmicDepthBufferEnabled is true

### ISSUE THREAD

**Issue by DB-EC-Hamburg-BIM** [xeokit/xeokit-sdk#915]
When I activate "logarithmicDepthBufferEnabled: true" in the viewer, I got an error while vertex shader compiling

ERROR:

`
index.js:1 Vertex shader failed to compile

ERROR: 0:29: 'assign' : l-value required (can't modify an input "vFragDepth")
ERROR: 0:30: 'assign' : l-value required (can't modify an input "isPerspective")

1: #version 300 es
2: // Instancing occlusion vertex shader
3: uniform int renderPass;
4: in vec3 position;
5: in vec3 offset;
6: in vec4 color;
7: in vec4 flags;
8: in vec4 flags2;
9: in vec4 modelMatrixCol0;
10: in vec4 modelMatrixCol1;
11: in vec4 modelMatrixCol2;
12: uniform mat4 worldMatrix;
13: uniform mat4 viewMatrix;
14: uniform mat4 projMatrix;
15: uniform mat4 positionsDecodeMatrix;
16: uniform float logDepthBufFC;
17: in float vFragDepth;
18: bool isPerspectiveMatrix(mat4 m) {
19:     return (m[2][3] == - 1.0);
20: }
21: in float isPerspective;
22: void main(void) {
23: if (int(flags.x) != renderPass) {
24:       gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
25: } else {
26:   vec4 worldPosition = positionsDecodeMatrix * vec4(position, 1.0); 
27:   worldPosition = worldMatrix * vec4(dot(worldPosition, modelMatrixCol0), dot(worldPosition, modelMatrixCol1), dot(worldPosition, modelMatrixCol2), 1.0);
28:       worldPosition.xyz = worldPosition.xyz + offset;
29:   vec4 viewPosition  = viewMatrix * worldPosition; 
30: vec4 clipPos = projMatrix * viewPosition;
31: vFragDepth = 1.0 + clipPos.w;
32: isPerspective = float (isPerspectiveMatrix(projMatrix));
33: gl_Position = clipPos;
34: }
35: }

xeokit-sdk.min.es.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'bindArrayBuffer')
    at e.value (xeokit-sdk.min.es.js:1:758421)
    at e.value (xeokit-sdk.min.es.js:1:856082)
    at r.value (xeokit-sdk.min.es.js:1:1068652)
    at ot.doOcclusionTest (xeokit-sdk.min.es.js:1:170055)
    at r.value (xeokit-sdk.min.es.js:1:242039)
    at xeokit-sdk.min.es.js:1:52701
    at e (xeokit-sdk.min.es.js:1:52455)
`

**Desktop:**
 - OS: Windos 10
 - Browser: chrome 104
 - Version: xeokit-sdk 2.3.0

**Comment by xeolabs** [comment]
Fixed in:
* xeokit/xeokit-sdk 2.3.1 
* xeokit-bim-viewer 2.4.8
