### ISSUE TITLE
CameraControl followPointer same zoom dist to entity and not

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#920]
Maybe Enhancement.
Can make same or similar zoom distance to entity and not to entity when mouse wheel?
https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/CameraControl/lib/CameraUpdater.js#L88
It is fixed value dollyDistFactor.

**Comment by xeolabs** [comment]
I'm not sure I understand, but it sounds intriguing - if it looks like a promising enhancement, could you make a PR? 
Thanks
