### ISSUE TITLE
TreeViewPluginUI

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#924]
i would like to know what are the limits for treeViewPlugin to replace or have some sort of custumisation for us, im talking about the ui, i wonder is ther a way i can custumise it with bootstrap or something like that

**Comment by mlankamp** [comment]
@xeolabs I had an idea to have a plugin-type model (just like datasource in plugins) for the treeview plugin, so in the constructor you can provide a class that is responsible for creating the treenodes. This allows for custom rendering of the treenodes.

Do you like the idea? If so, i'm willing to create a PR

**Comment by xeolabs** [comment]
A configurable strategy class sounds like an excellent idea - PR away!
