### ISSUE TITLE
NavCube is not working correct after zoom to BCF 

### ISSUE THREAD

**Issue by DB-EC-Hamburg-BIM** [xeokit/xeokit-sdk#927]
**Describe the bug**
After I zoom to a BCF viewpoint, the NavCube is not zooming back to the model

**To Reproduce**
1. zoom to a BCF viewpoint
2.  click on any face of the navcube

**Expected behavior**
zoom back to model

**Screenshots**
loaded model
![image](https://user-images.githubusercontent.com/46476466/190381751-e0571a80-60f4-4f9f-a9f7-cc79d21d8738.png)

zoomed to bcf viewpoint
![image](https://user-images.githubusercontent.com/46476466/190382066-802064c9-4bc9-4cbd-8e71-1a161d9bb14d.png)

after clicking on the navcube
![image](https://user-images.githubusercontent.com/46476466/190382261-9ad43899-9a34-4af2-8f88-37e629495033.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome 105
 - Version 3.2.1

**Additional context**
after clicking on the navcube, the viewer.scene._aabb gets MAX_SAFE_INTEGER as matrix values

**Comment by xeolabs** [comment]
I tried to reproduce this issue by adding the NavCubePlugin to the [BCF_LoadViewpoint](https://xeokit.github.io/xeokit-sdk/examples/#BCF_LoadViewpoint) and it seems to work OK.

Must be something special about the model placement?

Possibly a difference in coordinate systems, ie. direction of "up"?

Looks like we need a little more info - could you post an HTML page to reproduce? 

thanks
