### ISSUE TITLE
Section plane axis not displaying correctly for double precision model

### ISSUE THREAD

**Issue by kikunota** [xeokit/xeokit-sdk#928]
**Description**
When we are using a section plane for the double precision model, where the model is located far away from the center of the world coordinates, the axis plane of the section plane displays in low resolution. These axis are hardly visible and I was wondering if there is fix for this.

**To Reproduce**
1. Use the double precision demo file from the following URL.  [(https://xeokit.github.io/xeokit-model-conversion-tests/viewer.html?batchId=BIMData&modelId=MAP)]
2. Create section plane with this model and when you zoom into the model these axis displays in low resolution.

**Expected behavior**
The resolution of these axis should not change regardless of what kind of model that I'm using.

**Screenshots**
![sectionplane_low_resolution](https://user-images.githubusercontent.com/44632198/190415286-5d663494-c68d-40e6-985e-7e3a4b1e0d9c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version npm xeokit-sdk@1.9.0

**Comment by Amoki** [comment]
Hmm, MAP is our demo model, we use it intensively and we never had this bug. The blue shadow of the section plane is strange too. Are you able to try against a more recent version of xeokit?

**Comment by xeolabs** [comment]
Yes, xeokit-sdk 1.9.0 is *very* early version, so many fixes and features since then.

**Comment by xeolabs** [comment]
Closing for now, will reopen if this issue persists with the latest release.
