### ISSUE TITLE
Extract/expose functionality from NavCube

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#93]
Hello there, me again, sorry 😊 

I have another request/proposal for you to consider.

The NavCube plugin is a really nice and convenient way to control the scene's camera, just really good work all around! 👍 

I was wondering however if it would be possible to **extract** the core functionality somehow and **expose** it as simple methods.

The idea is that I would have a couple of UI elements, say buttons, like Front, Back, Top, etc and I would simply call the respective method on the btn click.

In this way, we could create a custom UI but still have this lovely feature available as it would now be decoupled from the plugin and exposed as methods on the viewer/scene.

(You should definitely keep the plugin too, of course, I'm not suggesting to replace it. My suggestion is to simply extract the core functionality as an additional feature.)

**Comment by xeolabs** [comment]
Hi Barnabas,

do you mean extracting out the fly-camera-to-axis/diagonal functionality into some methods on say, ````CameraFlightAnimation````? If so, then yeah I agree, that would be useful, and fairly easy.

**Comment by barnabasmolnar** [comment]
Hi Lindsay,

Yeah, something like that. I don't have the docs on hand at the moment but the `CameraFlightAnimation` thingy can do a jump, not just a fly animation, correct? If so, yes, that would be awesome! 👍

**Comment by xeolabs** [comment]
I'm going to extract these out into a function this week or next week

**Comment by barnabasmolnar** [comment]
Hey Lindsay,

Just an FYI:
I've taken this one up myself and tried to implement it in the xeokit-react project.

I think I've largely got it working, this is what I have now:

![presets](https://user-images.githubusercontent.com/38168628/64611933-e29c5580-d3d2-11e9-8713-e114f3872949.gif)

I was wondering if there was any way to contribute this back to you but I'm a bit unclear on a couple of things. So, I'd like to get your take on this if you're interested.

In essence, most of the code is copy pasted from you. 😄 

If you have a look at [this](https://github.com/bimspot/xeokit-react/blob/feature/camera-presets/src/useViewer.js#L74) and [this](https://github.com/bimspot/xeokit-react/blob/feature/camera-presets/src/utils.js#L63) link, you'll find that I basically grabbed the pieces of code that handle setting the camera to the desired angle and the predefined presets/angles from the NavCubePlugin, I believe.

What I've found however is that the `aabb` variable is `undefined` before a model is actually loaded. Which does make sense of course. So in our application, I tied this whole functionality to the condition that the model(s) have been loaded into the viewer. This works perfectly because we keep track of the model loaded state anyway for other reasons too.

What I'm not sure about is how I could achieve this in the xeokit package. If I recall correctly, you store the models on the `scene.models` object as key-value pairs, right? So perhaps, I could check if that object has any key value pairs at all? I'm open to suggestions here, though.

Another question is where I might actually implement this.
The way I imagine it is we would have a function/method that takes as parameter the desired angle or face (as I have called it) that we want to rotate the model to. But where should that method sit? On the `camera`, `scene` or `viewer` object? Or somewhere else entirely? I'm leaning towards the `viewer` as that is where you have the `cameraFly` method too.

Anyway, I'd be happy to have your thoughts on this. Even if only whether it's worth thinking about or maybe you want to tackle this in a different way.

Cheers.

**Comment by xeolabs** [comment]
@barnabasmolnar the only issue I have with this addition is that, for symmetry, it would be nice to also have methods to position the camera at the corners of the scene boundary, to obtain diagonal views. That would mean 14 methods in total, eg

* moveToLeft
* moveToRight
* moveToTop
* moveToBottom
* moveToFront
* moveToBack
* moveToTopLeftBack
* moveToTopRightBack
* moveToTopLeftFront
* moveToTopRightFront
* etc

So, this would be bit of a minor combinatorial explosion here, unless you can think of a way to reduce it..

**Comment by Bartosz-L** [comment]
Hi guys. I'm trying to figure out how to implement those camera presets: 

> * moveToTopLeftBack
> * moveToTopRightBack
> * moveToTopLeftFront
> * moveToTopRightFront

I was trying to use the [link ](https://github.com/bimspot/xeokit-react/blob/feature/camera-presets/src/utils.js#L63)provided by @barnabasmolnar . It's great and it works fine, but I have trouble implementing corner views. 
Can you provide any solution for this without using NavCube? I can't use navcube, 'couse my UI must look like this --->
![image](https://user-images.githubusercontent.com/20401418/111135534-11255e80-857d-11eb-9e26-cb7999c8b50f.png)

**Comment by Wesley-DST** [comment]
Hey @Bartosz-L ,

if you have a look at CubeTextureCanvas you will notice that all of the views are defined there: https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/NavCubePlugin/CubeTextureCanvas.js#L64

If I'm not mistaken the unlabeled ones are in the following order:
front-top
left-top
back-top
right-top
front-bottom
left-bottom
back-bottom
right-bottom
front-left
front-right
back-right
back-left
front-bottom-left
back-bottom-left
front-top-left
back-bottom-right
back-top-right
front-bottom-right
back-top-left
front-top-right

**Comment by Bartosz-L** [comment]
> Hey @Bartosz-L ,
> 
> if you have a look at CubeTextureCanvas you will notice that all of the views are defined there: https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/NavCubePlugin/CubeTextureCanvas.js#L64
> 
> If I'm not mistaken the unlabeled ones are in the following order:
> front-top
> left-top
> back-top
> right-top
> front-bottom
> left-bottom
> back-bottom
> right-bottom
> front-left
> front-right
> back-right
> back-left
> front-bottom-left
> back-bottom-left
> front-top-left
> back-bottom-right
> back-top-right
> front-bottom-right
> back-top-left
> front-top-right

Thank U! Works like a charm :)
