### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by salimcherifi** [xeokit/xeokit-sdk#939]
Hi,

I have just installed version 2.3.2 in a vue2 project and i have a warning when compiling: 

Critical dependency: the request of a dependency is an expression.

How do I resolve this ?

**Comment by mlankamp** [comment]
This has to do with the fact that some dependency of xeokit has a dependency on asciify-image, but this package is only needed when running in Node. Just ignore the warning.
