### ISSUE TITLE
question: support in native mobile envirement

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#940]
Hello,

The title might be a little confusing, but what I'm asking for (or about) is if I want to build a react-native app using xeokit-SDK, so it can be deployed on android or iOS, is this possible or not? If it is, what are the limits for it? And what can we do and can't do in such context.

I never tried to build a react-native app using xeokit, it's just a question that I had and wanted to know before engaging in anything.

Thank you in advance.

**Comment by divjakLab** [comment]
I also have a similar problem. We are using Xeokit in the web app already ( React ). But now our customer wants a mobile app made in Flutter - what would be the best way? I tried webview not an option at all. Has anyone had a similar problem? or did something like this?

**Comment by xeolabs** [comment]
See discussion on running apps offline: https://github.com/xeokit/xeokit-sdk/issues/958
