### ISSUE TITLE
XKT loading fails

### ISSUE THREAD

**Issue by intrida-dev** [xeokit/xeokit-sdk#945]
When I try to load some XKT files using XKTLoaderPlugin, it gives an error on console. I debugged a little and found, it is failing at line highlighted in following SS. edgeIndicesBuf is null, so it can't call edgeIndicesBuf.bind().
![image](https://user-images.githubusercontent.com/73640257/195082437-926fda89-0db5-4a5e-a39f-95b4ddc845fa.png)

I am getting following error:
![image](https://user-images.githubusercontent.com/73640257/195082520-a84bb727-df7d-4d4b-8e69-c4592b810654.png)

To reproduce the same error, I am sending you the XKT file.
[9623c9ad-2b8d-43f1-ad8c-e8aafbc8d40d.zip](https://github.com/xeokit/xeokit-sdk/files/9754824/9623c9ad-2b8d-43f1-ad8c-e8aafbc8d40d.zip)

Please check and let me know, if something is being wrong here.

**Comment by xeolabs** [comment]
Looks like it's loading OK now in the latest release.

 
![Screenshot from 2024-04-20 20-18-07](https://github.com/xeokit/xeokit-sdk/assets/83100/73800858-f2d3-458a-8868-89236649856b)


My test code:

````javascript

    import {Viewer, XKTLoaderPlugin} from "../../dist/xeokit-sdk.min.es.js";

    const viewer = new Viewer({
        canvasId: "myCanvas",
        dtxEnabled: true 
    });

    const xktLoader = new XKTLoaderPlugin(viewer);

    const sceneModel = xktLoader.load({
        id: "myModel",
        src: "../../assets/models/xkt/v10/model.xkt"
       
    });

    sceneModel.on("loaded", () => {
        viewer.cameraFlight.jumpTo(sceneModel);
    });
````

**Comment by intrida-dev** [comment]
> Looks like it's loading OK now in the latest release.
> 
> ![Screenshot from 2024-04-20 20-18-07](https://private-user-images.githubusercontent.com/83100/324197355-73800858-f2d3-458a-8868-89236649856b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjA2OTQsIm5iZiI6MTcxMzc2MDM5NCwicGF0aCI6Ii84MzEwMC8zMjQxOTczNTUtNzM4MDA4NTgtZjJkMy00NThhLTg4NjgtODkyMzY2NDk4NTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA0MzMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZWE2MTVhYjU3MmY0NTljNDk4OGM3M2RhYzFhZGExOWIxZTczNWE1ODU2MzcwZjU2Y2FlYmU2Yzk1ZTIzYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CBhdIIcjosN0WsPVyOQGEco8gv8r3Qj6HCtfCO9glpU)
> 
> My test code:
> 
> ```js
>     import {Viewer, XKTLoaderPlugin} from "../../dist/xeokit-sdk.min.es.js";
> 
>     const viewer = new Viewer({
>         canvasId: "myCanvas",
>         dtxEnabled: true 
>     });
> 
>     const xktLoader = new XKTLoaderPlugin(viewer);
> 
>     const sceneModel = xktLoader.load({
>         id: "myModel",
>         src: "../../assets/models/xkt/v10/model.xkt"
>        
>     });
> 
>     sceneModel.on("loaded", () => {
>         viewer.cameraFlight.jumpTo(sceneModel);
>     });
> ```

We will check this in latest version of Xeokit.
Thanks :-)
