### ISSUE TITLE
Model doesn't render on loading

### ISSUE THREAD

**Issue by intrida-dev** [xeokit/xeokit-sdk#946]
When we try to load any 3D XKT model into application, it doesn't get rendered immediately.  We have to resize our application to have model render inside canvas. It started happening after we updated xeokit sdk recently to 2.3.2.

I have attached the video of issue. 
[demo.zip](https://github.com/xeokit/xeokit-sdk/files/9754967/demo.zip)

Please check this and let us know how can it be corrected.

**Comment by Amoki** [comment]
Could it be related to https://github.com/xeokit/xeokit-sdk/issues/892#issuecomment-1188761876 ?

**Comment by intrida-dev** [comment]
> Could it be related to [#892 (comment)](https://github.com/xeokit/xeokit-sdk/issues/892#issuecomment-1188761876) ?

Amoki, we are using xeokit sdk  (2.3.2) from node modules. We don't have canvas.js installed. We have following files and folders in our node_modules.

![image](https://user-images.githubusercontent.com/73640257/195255248-6a8d2657-3202-43a7-ba03-1c372426504b.png)

What are we supposed to do here?

**Comment by Amoki** [comment]
You can try to `git clone https://github.com/xeokit/xeokit-sdk.git` (can take many minutes), revert the commit `git revert f66a01c88d5001c561cf9a00272ce03f8b282632` , run `npm install` and `npm run build` then copy the dist directory in your node_modules.
Then see if it fixes your problem

**Comment by intrida-dev** [comment]
Thanks, Amoki.
I will follow the steps you mentioned and will let you know how it goes.
