### ISSUE TITLE
The package.json fields main and module must not start with a slash

### ISSUE THREAD

**Issue by idibau** [xeokit/xeokit-sdk#948]
**Describe the bug**
Rollup cannot resolve the import {Viewer, XKTLoaderPlugin} from "@xeokit/xeokit-sdk" .

**To Reproduce**
Create a npm package and setup rollup with @rollup/plugin-node-resolve and build that dummy package which depends on xeokit-sdk.
In the resulting bundle js file xeokit-sdk is not included but there is still the import from "@xeokit/xeokit-sdk" statement.
(When modifying node_modules/@xeokit/xeokit-sdk/package.json by adding a dot to the field module it works as expected.)

**Expected behavior**
All dependencies from node_modules should be included in the resulting bundle.

**Comment by xeolabs** [comment]
Could you make a PR? Thanks

**Comment by idibau** [comment]
To my understanding I cannot link that [PR](https://github.com/xeokit/xeokit-sdk/pull/955) here.
