### ISSUE TITLE
Fix WebIFCLoaderPlugin property set loading 

### ISSUE THREAD

**Issue by deamondz** [xeokit/xeokit-sdk#950]
**Describe the bug**
https://github.com/xeokit/xeokit-sdk/blob/master/src/plugins/WebIFCLoaderPlugin/WebIFCLoaderPlugin.js#L844
i think that _if_ is wrong, i tried this:
```
if (!relatedObjects || relatedObjects.length === 0) {
    return;
}
```
and it works! propertySets array is filled

**To Reproduce**
1. load any model through WebIFCLoaderPlugin
2. inspect `viewer.metaScene.metaModels[modelId].metaScene.metaObjects[metaObjectId].propertySets` array
3. its always empty

**Expected behavior**
propertySets array is filled with _properties_

**Comment by xeolabs** [comment]
Oops I pushed a fix before I even realised you'd made a PR - thanks though!

**Comment by deamondz** [comment]
thank u for the great library! waiting for new release ;)
