### ISSUE TITLE
xrayed + (un)pickable, so that I can click on element inside model

### ISSUE THREAD

**Issue by stepanchvatik** [xeokit/xeokit-sdk#957]
Is is possible, to make whole model xrayed, but with some filtered entities fully visible, so that they are clickable "through the xrayed" model? 

Here is code what I do, when user filteres, toShow is array of filtered entities

```
 $("#btnSearch").on("click",function(e){
    e.preventDefault();
    var entities = scene.objects;
    if(toShow.length == 0){
      for (var key in entities) {
        entities[key].xrayed = false;
        entities[key].pickable = true;
        entities[key].highlighted = false;
      }
    }else{
      for (var key in entities) {
        if(toShow.indexOf(key)>-1){
          entities[key].xrayed = false;
          entities[key].pickable = true;
          entities[key].highlighted = true;
        }else{
          entities[key].xrayed = true;
          entities[key].pickable = false;
          entities[key].highlighted = false;

        }
      }
    }

  })
```

Screenshots:
1) entity that i want to click
![image](https://user-images.githubusercontent.com/34139286/201343297-11c85cd1-9b0b-480e-a7b6-393a37f52690.png)

2) entity that gets clicked (outer wall, bad behavior)
![image](https://user-images.githubusercontent.com/34139286/201343382-4199549c-e1b6-4d0c-b742-37ae57ea1bf1.png)

**Comment by Amoki** [comment]
It may be related to https://github.com/xeokit/xeokit-sdk/issues/879

**Comment by xeolabs** [comment]
Will reopen if still happening and not fixed by https://github.com/xeokit/xeokit-sdk/issues/879
