### ISSUE TITLE
SDK functions for bim-viewer and bim-server

### ISSUE THREAD

**Issue by lanjoni** [xeokit/xeokit-sdk#961]
Can I use SDK functions in bim-viewer + bim-server?

Also: can I modify specific functions, such as saving the set of object IDs that have been selected to a variable? Example: I select three objects and assemble a string with these three IDs in a single variable.

**Comment by xeolabs** [comment]
Hi, yes you should be able to use BIMViewer and xeokit functions alongside each other.

BIMViewer is designed to be a "white box" like that, and as such is designed to synchronize with any state changes you make directly on the xeokit API.

Should also be no problem modifying things as you described, if I understand correcty.
