### ISSUE TITLE
Fix stuck pan/rotate/dolly keypresses over annotations and measurements

### ISSUE THREAD

**Issue by elyrank** [xeokit/xeokit-sdk#965]
**Describe the bug**
when using the keys to zoom in or out (w,s) and while zooming out you now hover over an annotation, 
the zoom stops, and even though I let go of the key - the zoom out keeps going forever and there is no way to change it other than refresh the page.

**To Reproduce**
1. go to a page with annotations: i.e. https://xeokit.github.io/xeokit-sdk/examples/#annotations_occlusionDisabled
2. hover with the mouse close to an annotation
3. press 's' key to zoom out - until the mouse is over the annotation
4. let go of the key and move mouse - now zoom out is till continuing without pressing or clicking anything

**Expected behavior**
zoom out state should be reset

**Desktop (please complete the following information):**
OS: [macOS]
Browser [chrome]
Version [2.3.1]

**Comment by xeolabs** [comment]
Fixed in [xeokit-sdk 2.4.0-alpha-22](https://github.com/xeokit/xeokit-sdk/releases/tag/v2.4.0-alpha-22)
