### ISSUE TITLE
how to convert ifc and build metadata.json file

### ISSUE THREAD

**Issue by icefiresong24** [xeokit/xeokit-sdk#975]
I used the convert service to IFC and got a.xkt file, but I did not find the metadata.json file, is this json file necessary to load the model

**Comment by xeolabs** [comment]
Here's some info: https://xeokit.github.io/xeokit-model-conversion-tests/index.html

**Comment by icefiresong24** [comment]
Thank you for your answer, but the following error occurred when I executed the last step. May I ask what the problem is

![image](https://user-images.githubusercontent.com/67216778/208061671-ba732d54-9fc8-4616-99c1-9a7a6d977a76.png)
