### ISSUE TITLE
Release notes etc

### ISSUE THREAD

**Issue by mlankamp** [xeokit/xeokit-sdk#986]
According to github the latest release is 2.3.3 while on npmjs.org the release 2.3.5 exists.

Maybe it's an idea to use github actions to create a release on new tag-creation. This would also mean that the dist folder in not part of the source, but an output of the build in actions.

**Comment by xeolabs** [comment]
Agreed - good plan.

**Comment by mlankamp** [comment]
I will try to create a example workflow in my fork

**Comment by mlankamp** [comment]
See  #987
