### ISSUE TITLE
I don't  know how to get expressid from ifc model or a  xkt model.That's very important for me 

### ISSUE THREAD

**Issue by cugb-suerwei** [xeokit/xeokit-sdk#988]
**Is this feature critical for your commercial enterprise?**
If you need prioritized xeokit SDK fixes and features for your commercial enterprise, consider a Service Level Agreement (SLA) with xeolabs - [get in touch](http://xeokit.io/index.html?foo=3#contact) if you need one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xeolabs** [comment]
Hi, by design, express IDs are not retained within the XKT data - only the IFC element/product IDs are retained.
