### ISSUE TITLE
I need to find the centroid of an IFCSpace. Is there any method availble to find the centroid of a IFCSpace. I check to bounding box of ifcspace. but I couldn't found. kindly request for  a method

### ISSUE THREAD

**Issue by Arunvishnu123** [xeokit/xeokit-sdk#994]
**Is this feature critical for your commercial enterprise?**
If you need prioritized xeokit SDK fixes and features for your commercial enterprise, consider a Service Level Agreement (SLA) with xeolabs - [get in touch](http://xeokit.io/index.html?foo=3#contact) if you need one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xeolabs** [comment]
Hi, if the IfcSpace has an Entity with the same ID, then you can calculate the centroid from the Entity's boundary - see here for the boundary property: https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/Entity.js~Entity.html#instance-get-aabb

Note that this does depend on the IfcSpace having a geometric representation in the IFC model (not all do).
