### ISSUE TITLE
set object's texture given the object(s) id(s)

### ISSUE THREAD

**Issue by ohadgilboa888** [xeokit/xeokit-sdk#995]
can't find a way to set / update existing object's texture / pattern / material / image as it's surface,
how can i do this given the object(s) id(s)?

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by xeolabs** [comment]
It's not supported on the large models loaded into ````VBOSceneModels````, but it is supported by the scene graph representation, which is used for smaller models and gizmos like `NavCubePlugin`.

Start here: https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/scene/materials/Texture.js~Texture.html
